### ISSUE TITLE
bug: <switchNetwork>

### ISSUE THREAD

**Issue by GetWebHB** [wagmi-dev/wagmi#1002]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

^0.6.0

### Current Behavior

SwitchChainNotSupportedError: "WalletConnect" does not support programmatic chain switching.

### Expected Behavior

switching

**Comment by jxom** [comment]
Not all wallets support programmatic chain switching via WalletConnect. 
What wallet are you trying to switch chains with?
Closing for now until further information is provided.

**Comment by GetWebHB** [comment]
I want to switch chains through WalletConnect,But I don't know how to call.
