### ISSUE TITLE
No wagmi client found in Code Sandbox

### ISSUE THREAD

**Issue by FanManutd** [wagmi-dev/wagmi#1004]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.6.7

### Current Behavior

Hi! I wanted to create a minimally reproducible example in Code Sandbox for another issue, but encountered an error: `Error: No wagmi client found. Ensure you have set up a client: https://wagmi.sh/docs/client`. 

This happens if you try to connect MetaMask or WalletConnect

### Expected Behavior

Wagmi must connect wallet.

### Steps To Reproduce

1. Open Sandbox
2. Click on MetaMask or WalletConnect button.

### Link to Minimal Reproducible Example (CodeSandbox, StackBlitz, etc.)

https://codesandbox.io/s/wagmi-walletconnect-trustwallet-23wxfl?file=/src/App.tsx

**Comment by jxom** [comment]
#933 should eventually fix this.

**Comment by ackvf** [comment]
Is it possible to play with wagmi in codesandbox yet?
