### ISSUE TITLE
TrustWallet not connected with WalletConnect

### ISSUE THREAD

**Issue by FanManutd** [wagmi-dev/wagmi#1005]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.6.7

### Current Behavior

Hello! I'm using the latest version of wagmi and can't connect TrustWallet (mobile app) using WalletConnect via QR-code. At first I wanted to make a demo myself in the Code Sandbox, but encountered another error (#1004). 

I found another Code Sandbox demo that plays my issue. 

### Expected Behavior

WalletConnect must connect my TrustWallet mobile app.

### Steps To Reproduce

1. Open Sandbox
2. Click to WalletConnect button.
3. Try to scan the qr-code through TrustWallet mobile app

### Link to Minimal Reproducible Example (CodeSandbox, StackBlitz, etc.)

https://codesandbox.io/s/focused-rosalind-uznjkk?file=/package.json

### Anything else?

I found other examples in the Code Sandbox, where there was a different version of Wagmi and I could connect TrustWallet. Also, everything works correctly on the [examples](https://wagmi.sh/examples/connect-wallet) website.

I downgraded the Wagmi version to 0.6.0 at most, but the behavior did not change. I haven't tried lowering it lower, as I'm not sure about API compatibility.

**Comment by jxom** [comment]
I seem to connect to my Trust wallet fine via WalletConnect. What is the behaviour you are experiencing?

**Comment by FanManutd** [comment]
> I seem to connect to my Trust wallet fine via WalletConnect. What is the behaviour you are experiencing?

So, on the first video everything is ok. On the second, after scanning the qr-code, nothing happens. I am using the latest version of the TrustWallet, android 12. 

https://user-images.githubusercontent.com/90761929/192694869-f58801fc-26c2-46dd-abdf-9984535aee00.mp4

https://user-images.githubusercontent.com/90761929/192695395-7c81f916-39de-414b-81b5-0e78d3ac9dcf.mp4

**Comment by jxom** [comment]
Seems to work fine on iOS for me. I have a feeling this is more specific to TrustWallet's Android app.

**Comment by FanManutd** [comment]
The strange thing is that for some reason everything is fine on the wagmi page, but not in the CodeSandbox and in my project.

**Comment by jxom** [comment]
Going to close this for now as a reproducible example cannot be provided. Does this happen with other wallets via WalletConnect? If not, it could be an issue upstream with Trust Wallet's Android app, or WalletConnect.

**Comment by FanManutd** [comment]
> Going to close this for now as a reproducible example cannot be provided. Does this happen with other wallets via WalletConnect? If not, it could be an issue upstream with Trust Wallet's Android app, or WalletConnect.

We updated to 0.7.5 and the problem is gone.
