### ISSUE TITLE
BUG:  ERESOLVE unable to resolve dependency tree

### ISSUE THREAD

**Issue by MoAnsir** [wagmi-dev/wagmi#1015]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

^0.6.7

### Current Behavior

Can't install all the packages needed for the eth sign in example.

$ npm install siwe iron-session
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: wagmitest@0.1.0
npm ERR! Found: ethers@5.7.1
npm ERR! node_modules/ethers
npm ERR!   ethers@"^5.7.1" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer ethers@"5.5.1" from siwe@1.1.6
npm ERR! node_modules/siwe
npm ERR!   siwe@"*" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.

### Expected Behavior

Should be able to install all packages and be able to use the examples on the wagmi.sh website

### Steps To Reproduce

npx create-react-app wagmitest

npm i wagmi ethers

npm install siwe iron-session

**Comment by tmm** [comment]
Thanks for reporting. This issue is temporarily closed due to lack of information. Please provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) and reopen this issue.
