### ISSUE TITLE
How to get returnned value from useContractWrite hook ?

### ISSUE THREAD

**Issue by anteqkois** [wagmi-dev/wagmi#1019]
@nasa8x response returns hash transaction, not deployed address :/
Anyone have idea how to solve it ? I don't want to use useContractRead, It would be better if I can get data in one transaction. I have to connect data from form and returned contract address (from transaction) and save in database, so any delay will be disadvantegous.

_Originally posted by @anteqkois in https://github.com/wagmi-dev/wagmi/discussions/691#discussioncomment-3759883_

**Comment by jxom** [comment]
Hi. Let's leave this to the discussions as this is not technically an issue with the library itself.

`useContractWrite` only returns the hash of the transaction. If you would like to get the transaction details, consider using [`useTransaction`](https://wagmi.sh/docs/hooks/useTransaction).
