### ISSUE TITLE
Can't debug when using mobile device connect to local server.

### ISSUE THREAD

**Issue by Santiago0412** [wagmi-dev/wagmi#1020]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.5.9

### Current Behavior

can't debug on my mobile device when run the code on my local computer. always error when try to use wallet connect.

### Expected Behavior

no error and can debug normally

### Steps To Reproduce

1. using `yarn dev` on my own computer to start local server
2. open http://localhost:3000 on my browser on my computer, everything works fine
3. open http://_MY_COMPUTER_IP_:3000 on my iPhone(my iPhone and my computer are on same wifi)
4. click connect button to call wallet connect, there will be an error like: **_walletconnect_enviroment_WEBPACK_IMPORTANT_MODULE_0_.getSubtleCrypto().importKey')**

![431664444156_ pic](https://user-images.githubusercontent.com/10152008/192997061-98d78192-422a-4e65-b61f-05abb8a67a4a.jpg)

the point is if I distributed my web to some remote server like Vercel, everything works fine, but I can't debug on remote server like add some breakpoints or console some log.

**Comment by jxom** [comment]
Pretty sure you need to run your local server via HTTPS. You might want to take a look at using [`local-ssl-proxy`](https://github.com/cameronhunter/local-ssl-proxy).
