### ISSUE TITLE
bug: metamask connector saves connection even when shimDisconnect is true

### ISSUE THREAD

**Issue by ShravanSunder** [wagmi-dev/wagmi#1023]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.6.0

### Current Behavior

using rainbow and metamask
1. connect to metamask using rainbow when `shimDisconnect` is true
2. disconnect from rainbow
3. refresh the page

Rainbow wallet automatically connects to meta mask.  This behaviour is in rainbow's documentation website as well.  

### Expected Behavior

When `shimDisconnect` is true, it does not connect to metamask

### Link to Minimal Reproducible Example (CodeSandbox, StackBlitz, etc.)

https://www.rainbowkit.com/

**Comment by jxom** [comment]
This has already been addressed here: https://github.com/wagmi-dev/wagmi/issues/38#issuecomment-1006685000
