### ISSUE TITLE
bug: creating alchemyProvider with optimism-goerli throws unsupported network

### ISSUE THREAD

**Issue by c0rv0s** [wagmi-dev/wagmi#1024]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.6.7

### Current Behavior

when I call `configureChains` and try to use an `alchemyProvider` for Optimism Goerli it fails with the error:
```
Error: unsupported network (argument="network", value={"name":"optimism-goerli","chainId":420,"ensAddress":null,"_defaultProvider":null}, code=INVALID_ARGUMENT, version=providers/5.6.8)
```

### Expected Behavior

The alchemy provider should connect with the key I've provided. I was using this code with Optimism Kovan until recently and it worked fine there.

### Steps To Reproduce

My code:
```
const chainId = 420;

export const { chains, provider, webSocketProvider } = configureChains(
  [
    chainId === 10
      ? chain.optimism
      : chainId === 420
      ? chain.optimismGoerli
      : chain.hardhat,
  ],
  [alchemyProvider({ apiKey: alchemyKey })]
);
```

**Comment by jxom** [comment]
Seems to work fine for me in my dev environment. Are you on the latest version of ethers? If you are, can you please provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) via a CodeSandbox (feel free to use [this template](https://codesandbox.io/s/bitter-wind-pv0hwj))? I'll reopen this issue when one is provided! :)
