### ISSUE TITLE
bug: `Connectors` doesn't display all the available connectors

### ISSUE THREAD

**Issue by sumicet** [wagmi-dev/wagmi#1041]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.6.7

### Current Behavior

Only one of the 2 connectors available shows up in the list. I have both MetaMask and Coinbase installed and the list only displays Coinbase.

### Expected Behavior

`Connectors` should return all connectors available.

### Steps To Reproduce

Install MetaMask and Coinbase. Disable all other wallets.

### Link to Minimal Reproducible Example (CodeSandbox, StackBlitz, etc.)

https://codesandbox.io/s/connectors-bug-lrsh7x

**Comment by tmm** [comment]
Looks like you haven't configured any [`connectors`](https://wagmi.sh/docs/client#connectors-optional). By default, `Client` only includes the `InjectedConnector`.
