### ISSUE TITLE
bug: Coinbase connector's `ready` field is `true` when the wallet isn't available

### ISSUE THREAD

**Issue by sumicet** [wagmi-dev/wagmi#1042]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.6.7

### Current Behavior

When looking at the `connectors` list (from `useConnect`), the `ready` field inside `CoinbaseWalletConnector` seems to always be `true` even when the Coinbase Wallet extension is disabled.

### Expected Behavior

The `ready` field should be `false` when the Coinbase Wallet extension isn't available.

### Steps To Reproduce

Disable your Coinbase wallet extension if you have it installed.

### Link to Minimal Reproducible Example (CodeSandbox, StackBlitz, etc.)

https://codesandbox.io/s/ready-bug-vv6vy5?file=/src/App.tsx

**Comment by tmm** [comment]
`CoinbaseWalletConnector` works with the browser extension and mobile app so it is always ready. For example, if you don't have the browser extension installed, you see the following:

<img width="559" alt="image" src="https://user-images.githubusercontent.com/6759464/194091975-1ec320a0-c326-40cd-9e6c-95a54ab58383.png">
