### ISSUE TITLE
bug: ethereumjs-abi breaks deployment without ssh 

### ISSUE THREAD

**Issue by dcsan** [wagmi-dev/wagmi#1047]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.6.8

### Current Behavior

see https://github.com/ethereumjs/ethereumjs-abi/issues/67

crashes trying to install on any managed system that doesn't have .ssh keys available.
for me i found out on vercel, but assume its the same if you try to make a docker container, app engine, cloud func or similar.

 because of deep dependency on a coinbase SDK that uses a 
> "git+ssh"

link, but that will fail without any key present.

the solution might be to try and update the dependencies?

```
yarn why ethereumjs-abi
yarn why v1.22.19
[1/4] 🤔  Why do we have the module "ethereumjs-abi"...?
[2/4] 🚚  Initialising dependency graph...
[3/4] 🔍  Finding dependency...
[4/4] 🚡  Calculating file sizes...
=> Found "ethereumjs-abi@0.6.8"
info Reasons this module exists
   - "wagmi#@coinbase#wallet-sdk#eth-json-rpc-filters#eth-json-rpc-middleware#eth-sig-util" depends on it
   - Hoisted from "wagmi#@coinbase#wallet-sdk#eth-json-rpc-filters#eth-json-rpc-middleware#eth-sig-util#ethereumjs-abi"
info Disk size without dependencies: "456KB"
info Disk size with unique dependencies: "780KB"

```

### Expected Behavior

can install /deploy without fail

### Steps To Reproduce

try to deploy client on vercel / nextJS

### Link to Minimal Reproducible Example (CodeSandbox, StackBlitz, etc.)

no because

### Anything else?

deep dependency pain

**Comment by tmm** [comment]
Hey! Not sure about your specific set up, but we have no issue with Vercel for the wagmi docs site. This unfortunately seems like it needs to be solved upstream in either [ethereumjs-abi](https://github.com/ethereumjs/ethereumjs-abi) or [coinbase-wallet-sdk](https://github.com/coinbase/coinbase-wallet-sdk).
