### ISSUE TITLE
bug: Error: user rejected transaction (unhandled)

### ISSUE THREAD

**Issue by junhuang-ho** [wagmi-dev/wagmi#1058]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.6.8

### Current Behavior

Using wagmi with next js on chrome + **metamask chrome extension**.

When calling **any** contract call that uses gas (`sendTransaction`) via `useContractWrite`'s `writeAsync`, if we reject this transaction on metamask will cause this error to occur:

> Uncaught (in promise) Error: user rejected transaction (action="sendTransaction", transaction=....... code=ACTION_REJECTED

This error still occurs even if I have `onError` set in `useContractWrite`. 

Note: I have `usePrepareContractWrite` before and `useWaitForTransaction` after `useContractWrite`.

![Screenshot from 2022-10-10 12-03-10](https://user-images.githubusercontent.com/96459097/194797812-6d5bf896-fbd7-4c31-80ae-e18d2ec6092f.png)

### Expected Behavior

`onError` should handle this error so that it not show up, i.e error **handled**.

**Comment by MyNameIsTakenOMG** [comment]
same here, at first, I didn't set up `onError` and I got this unhandled error, and then after looking up the doc, I thought it would be working after setting up the `onError` handler, but turned out the error still remains.

**Comment by MyNameIsTakenOMG** [comment]
> same here, at first, I didn't set up `onError` and I got this unhandled error, and then after looking up the doc, I thought it would be working after setting up the `onError` handler, but turned out the error still remains.

okay, I got a workaround, so what I did is I wrapped the `write` or `writeAsync`  in a `trycatch` block which is in an outer function, and then you call that outer function instead of calling the `write` or `writeAsync` : 
```
const outerFunction = async()=>{
  try {
    await writeAsync()
  } catch (error) {
    console.log(error)
  }
}
```
Hopefully this could work out in your case

**Comment by tmm** [comment]
`writeAsync` throws so you need to catch the error like @MyNameIsTakenOMG mentioned.

`write` is safe so no need to catch errors there (sometimes browser extension wallets, like MetaMask, will throw there own errors that show up in the console).
