### ISSUE TITLE
Bug: WalletConnect - No error thrown when user rejects connection from wallet application

### ISSUE THREAD

**Issue by elizalucas** [wagmi-dev/wagmi#1066]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.6.5

### Current Behavior

If a user is connecting to WalletConnect, scans the QR code, and then rejects the request from their wallet application, the `isLoading` variable is not updated to false. I have tested this in [this connect wallet demo](https://wagmi.sh/examples/connect-wallet) and confirmed the behavior. If I reject the connection from my wallet application (I am using Zerion) the QR code will close out on the screen but the loading symbol next to the WalletConnect button remains. 

If I exit out of the QR code directly on the website it works as expected. 

### Expected Behavior

If you reject the connection from your wallet application, it should throw a rejected connection error and update the `isLoading` boolean.

### Steps To Reproduce

1. Select WalletConnect
2. Scan QR code in your wallet application
3. Reject the connection from your wallet application

### Link to Minimal Reproducible Example (CodeSandbox, StackBlitz, etc.)

https://wagmi.sh/examples/connect-wallet

**Comment by mlshv** [comment]
I've tried to debug this, but seems like it's an issue with WC itself and there is no external way to fix it.

**Comment by tmm** [comment]
Same there isn't an event to hook into for this nor does it throw an error we can bubble up through wagmi.

Going to close for now and follow up with the WalletConnect team.

**Comment by elizalucas** [comment]
Hello @tmm . Did you get a chance to followup with the WalletConnect team?

**Comment by tmm** [comment]
Yes, this will be added to the behavior as part of https://github.com/wagmi-dev/wagmi/pull/1208

**Comment by montanaflynn** [comment]
Having same issue using connectkit and metamask. If I reject the transaction the useContractWrite data resets but `isLoading` remains true.

**Comment by saitejas-cypherd** [comment]
Is this error solved? Because I'm still not able to catch it properly

**Comment by stackrev** [comment]
I am also having an same issue. Is the issue solved?
