### ISSUE TITLE
bug: can't listen to event using useContractEvent

### ISSUE THREAD

**Issue by izcoser** [wagmi-dev/wagmi#1075]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.6.8

### Current Behavior

I am trying to listen to a contract event, but it's throwing an error which I can't make sense of.

### Expected Behavior

I expected the event listener to be set normally.

### Steps To Reproduce

It's just a create-react-app with wagmi.

Here is a minimal reproducible example:

App.js

```js
import {
  WagmiConfig,
  createClient,
  defaultChains,
  configureChains,
  chain,
  useContractEvent,
} from 'wagmi'

import { infuraProvider } from 'wagmi/providers/infura'
import { publicProvider } from 'wagmi/providers/public'
import { MetaMaskConnector } from 'wagmi/connectors/metaMask'
import { MRE } from './profile/MRE';
import { MRE2 } from './profile/MRE2';

const { chains, provider, webSocketProvider } = configureChains([chain.sepolia, chain.goerli],
  [publicProvider()])


// Set up client
const client = createClient({
  autoConnect: true,
  connectors: [
    new MetaMaskConnector({ chains }),
  ],
  provider,
  webSocketProvider,
})

function App() {
  return (
    <WagmiConfig client={client}>
      <MRE />
    </WagmiConfig>
  )
}

export default App;

```

./profile/MRE.js

```js
import * as React from 'react';
import { useContractEvent } from 'wagmi'

const abi = [{
  "anonymous": false,
  "inputs": [
    {
      "indexed": true,
      "internalType": "address",
      "name": "sender",
      "type": "address"
    },
    {
      "indexed": false,
      "internalType": "uint256",
      "name": "amount",
      "type": "uint256"
    },
    {
      "indexed": false,
      "internalType": "uint256",
      "name": "nonce",
      "type": "uint256"
    },
    {
      "indexed": false,
      "internalType": "bytes",
      "name": "signature",
      "type": "bytes"
    }
  ],
  "name": "DepositSigned",
  "type": "event"
}
]

export function MRE() {
  useContractEvent({
    address: "0x03D3966ec2f5F058DC9f0D7bFfbc9b22426283C4", // sep bridge
    abi: abi,
    eventName: 'DepositSigned',
  });
}

```

When the page loads, an error is thrown immediately:

```
interface.ts:100 Uncaught TypeError: Cannot read properties of undefined (reading 'map')
    at new Interface (interface.ts:100:1)
    at getInterface (index.ts:820:1)
    at new BaseContract (index.ts:662:1)
    at new Contract (index.ts:1140:1)
    at getContract (wagmi-core.esm.js:462:1)
    at wagmi.esm.js:1205:1
    at mountMemo (react-dom.development.js:17225:1)
    at Object.useMemo (react-dom.development.js:17670:1)
    at Object.useMemo (react.development.js:1650:1)
    at useContract (wagmi.esm.js:1204:1)

react-dom.development.js:18687 The above error occurred in the <MRE> component:

    at MRE (http://localhost:3000/static/js/bundle.js:230:58)
    at QueryClientProvider (http://localhost:3000/static/js/bundle.js:77594:5)
    at WagmiConfig (http://localhost:3000/static/js/bundle.js:69028:5)
    at App

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://reactjs.org/link/error-boundaries to learn more about error boundaries.
```

### Anything else?

I'm sure it's something that I'm doing wrong, but I can't pin point it. I'd like to add that I am able to send transactions and use nearly all other hooks without any trouble. Also, the contract in question is in the Sepolia network.

**Comment by izcoser** [comment]
I found the solution.
The ```addressOrName``` and ```contractInterface``` contract hooks where renamed to ```address``` and ```abi``` in 0.7.x.
I am using 0.6.x, however the 0.6.x examples in the docs are wrongly using the new version's names.

Closing.

**Comment by cryptobeaver** [comment]
I can't get it to work in 0.7.8 using address and abi with nextjs setup

**Comment by tmm** [comment]
@cryptobeaver are you sure you are using `0.7.8`? Can you post a [minimal reproducible example](
https://stackoverflow.com/help/minimal-reproducible-example)?

**Comment by cryptobeaver** [comment]
To be able to test, i created a new nextjs project locally and used the examples as code

`import { WagmiConfig, createClient } from 'wagmi'
import { getDefaultProvider } from 'ethers'
import Home from '.'

const client = createClient({
  autoConnect: true,
  provider: getDefaultProvider(),
})

function App() {
  return (
    <WagmiConfig client={client}>
      <Home />
    </WagmiConfig>
  )
}

export default App`

and 
`import styles from '../styles/Home.module.css'
import {useContractEvent, } from 'wagmi';

export default function Home() {
  useContractEvent({
    address: CONTRACT_ADDRESS,
    
    eventName: 'Painted',
    listener(node, label, owner) {
      console.log(node, label, owner)
    },
  })
  
  return (
    <div className={styles.container}>
      test
    </div>
  )
}`

I'm using wagmi 0.7.8, i don't see any logging from the console.log

**Comment by tmm** [comment]
It looks like you are missing the [`abi`](https://wagmi.sh/docs/hooks/useContractEvent#abi-optional) config parameter.

**Comment by cryptobeaver** [comment]
It’s optional, well that is what the documentation says, but I had tested with ti. I’ll added it again to make sure.

**Comment by tmm** [comment]
Correct. It is optional, but the hook will not start listening to events unless you provide it.
