### ISSUE TITLE
bug: Types of property 'abi' are incompatible.

### ISSUE THREAD

**Issue by azf20** [wagmi-dev/wagmi#1090]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.7.3

### Current Behavior

I upgraded from 0.6.8 to 0.7.3. I followed the migration guide, principally `addressOrName and contractInterface renamed to address and abi`. My `config` from `usePrepareConfigWrite` now throws an error when passed into `useContractWrite`

```
      Types of property 'abi' are incompatible.
        Type 'readonly unknown[]' is not assignable to type 'readonly {}[]'.
          Type 'unknown' is not assignable to type '{}'.
```

### Expected Behavior

With the fields renamed, I expected the `config` to work as it did previously

### Steps To Reproduce

Before, with 0.6.8:

```
  const { config } = usePrepareContractWrite({
    addressOrName: contractAddresses(writeContractName),
    contractInterface: abis[writeContractName],
    functionName: 'safeClaimUBI',
    args: [outstandingCharacters]
  });

  const { writeAsync } = useContractWrite({ ...config, chainId: genesisChain.id });
```

After, with 0.7.3:

``` 
  const { config } = usePrepareContractWrite({
    address: contractAddresses(writeContractName),
    abi: abis[writeContractName],
    functionName: 'safeClaimUBI',
    args: [outstandingCharacters]
  });

  const { writeAsync } = useContractWrite({ ...config, chainId: genesisChain.id }); // this line throws the error:
```

Error:
```
TS2345: Argument of type '{ chainId: number; abi: readonly unknown[]; address: string; functionName: "safeClaimUBI"; mode: "prepared"; request: ethers.PopulatedTransaction & { to: `0x${string}`; gasLimit: ethers.BigNumber; }; }' is not assignable to parameter of type 'UseContractWriteConfig<readonly unknown[], "safeClaimUBI"> | undefined'.
  Type '{ chainId: number; abi: readonly unknown[]; address: string; functionName: "safeClaimUBI"; mode: "prepared"; request: ethers.PopulatedTransaction & { to: `0x${string}`; gasLimit: ethers.BigNumber; }; }' is not assignable to type 'MutationConfig<SendTransactionResult, Error, UseContractWriteArgs<Abi, string>> & Omit<ContractConfig<Omit<{ ...; }, OmitConfigProperties>, readonly unknown[], "safeClaimUBI", never, { ...; }>, "args"> & ... 5 more ... & Omit<...>'.
    Type '{ chainId: number; abi: readonly unknown[]; address: string; functionName: "safeClaimUBI"; mode: "prepared"; request: ethers.PopulatedTransaction & { to: `0x${string}`; gasLimit: ethers.BigNumber; }; }' is not assignable to type 'Omit<ContractConfig<Omit<{ abi: readonly unknown[]; functionName: "safeClaimUBI"; chainId?: number | undefined; }, OmitConfigProperties>, readonly unknown[], "safeClaimUBI", never, { isAbiOptional: true; isAddressOptional: true; isArgsOptional: true; isFunctionNameOptional: true; isRequestOptional: true; }>, "args">'.
      Types of property 'abi' are incompatible.
        Type 'readonly unknown[]' is not assignable to type 'readonly {}[]'.
          Type 'unknown' is not assignable to type '{}'.
    87 |   });
    88 |
  > 89 |   const { writeAsync } = useContractWrite({ ...config, chainId: genesisChain.id });
```

**Comment by tmm** [comment]
Thanks for reporting. This issue is temporarily closed due to lack of information. Please provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) and reopen this issue. Specifically, would be great to see what `abis` looks like.

**Comment by azf20** [comment]
thanks @tmm - I managed to resolve this, I needed to add `as const` to the `abi`. The upgrade also seems to have made the types are quite a bit stricter (e.g. previously I was passing an array of strings or numbers to a BigNumber argument, which ethers [Bignumberish was able to handle](https://docs.ethers.io/v5/api/utils/bignumber/#BigNumberish), but now I need to cast them explicitly).

I think it's worth mentioning both in the migration guide, particularly `as const`, as the error message wasn't that easy to diagnose. The type strictness feels less ergonomic than before given ethers flexibility here, but I appreciate that is just an opinion.

Happy to add a PR to the docs if you agree these are worth adding to the migration guide?

**Comment by tmm** [comment]
@azf20 great! Either a [const assertion or defining inline](https://wagmi.sh/docs/typescript#type-inference) is the way to go. The [wagmi TypeScript docs](https://wagmi.sh/docs/typescript) cover this and are linked in the migration guide.

You are correct the types are stricter — and that's a good thing! Previously, they were more permissive and ethers worked behind the scenes to convert them to the correct representation. This was unsafe as you could do things like pass in a `BigNumber` that would overflow a `number` parameter.

It shouldn't be too bad to convert most of these cases (and you likely don't need to add explicit casts). For example:

```diff
useContractRead({
  …,
- args: ['123'],
+ args: [BigNumber.from('123')],
})
```

I added a [note to the migration guide](https://wagmi.sh/docs/migration-guide#upgrade-to-typescript474) about this. Let me know if that makes sense.

**Comment by oveddan** [comment]
I have this same issue and it's tough to track down what is wrong or whats wrong with my ABI - given i generate it directly using hardhats generation functionality.

**Comment by tmm** [comment]
@oveddan can you link to your ABI? Happy to take a look.

**Comment by oveddan** [comment]
Sure, it is here:
https://github.com/landaxr/waypoint/blob/main/src/api/smartContract/contracts/Waypoint.json

**Comment by azf20** [comment]
@oveddan did you add a `const` assertion when you upgraded?

**Comment by oveddan** [comment]
Thanks for the tip @azf20 

It's not entirely clear how to do that from the docs when importing the abi from a json.

When I try something like:

```js
import ContractJson from './Contract.json';

const abi = [...ContractJson.abi] as const;

const { config, error, isError } = usePrepareContractWrite({
    address: getContractArgs.address,
    abi,
    functionName: 'safeMint',
    args,
  });

  const { data, isLoading, isSuccess, write } = useContractWrite(config);
```

I get the same error.

It would be nice if there was an end to end example showing how to do this when importing from a json.  

Write now the [example for contract write](https://wagmi.sh/examples/contract-write) just shows how to do it with an inline abi def.

**Comment by tmm** [comment]
@oveddan 

Unfortunately [TypeScript doesn't support importing JSON as const](https://github.com/microsoft/TypeScript/issues/32063). You either need to define the ABI inline or add a const assertion. Here's an example https://github.com/wagmi-dev/wagmi/discussions/1084#discussioncomment-3891592

I added a note to the [wagmi TypeScript docs](https://wagmi.sh/docs/typescript#type-inference) for future folks encountering this.

**Comment by oveddan** [comment]
Ok well I figured out a workaround.  I"m using [hardhat's sample deploy script](https://github.com/NomicFoundation/hardhat-boilerplate/blob/master/scripts/deploy.js) to generate the abi.

The current script has this function:

```js
function saveFrontendFiles(token) {
  const fs = require("fs");
  const contractsDir = path.join(__dirname, "..", "frontend", "src", "contracts");

  if (!fs.existsSync(contractsDir)) {
    fs.mkdirSync(contractsDir);
  }

  fs.writeFileSync(
    path.join(contractsDir, "contract-address.json"),
    JSON.stringify({ Token: token.address }, undefined, 2)
  );

  const TokenArtifact = artifacts.readArtifactSync("Token");

  fs.writeFileSync(
    path.join(contractsDir, "Token.json"),
    JSON.stringify(TokenArtifact, null, 2)
  );
}
```

I can generate a typescript friendly abi with the following code:

```js
 const abiTs = `export const abi = ${JSON.stringify(ContractArtifact.abi, null, 2)} as const`;
```

Altogether it looks like:

```js
function saveFrontendFiles(token) {
  const fs = require("fs");
  const contractsDir = path.join(__dirname, "..", "frontend", "src", "contracts");

  if (!fs.existsSync(contractsDir)) {
    fs.mkdirSync(contractsDir);
  }

  fs.writeFileSync(
    path.join(contractsDir, "contract-address.json"),
    JSON.stringify({ Token: token.address }, undefined, 2)
  );

  const TokenArtifact = artifacts.readArtifactSync("Token");

  const abiTs = `export const abi = ${JSON.stringify(ContractArtifact.abi, null, 2)} as const`;

  await writeFileAsync(path.join(contractsDir, 'abi.ts'), abiTs);

  fs.writeFileSync(
    path.join(contractsDir, "abi.ts"),
    abiTs
  );
}
```

Then in my code I can do:


```ts

import { abi } from '../contracts/abi';

```

and use that abi successfully.

Not sure if theres a better way to generate the `ts` abi file but open to suggestions.
