### ISSUE TITLE
bug: '...valid provider configuration...' error throwing, causing minified bundle in Next to break due to mixing quote style 

### ISSUE THREAD

**Issue by mirshko** [wagmi-dev/wagmi#1102]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.7.4

### Current Behavior

App logic breaks, but builds pass due to invalid minification of the wagmi/core bundle. This however could be a bug upstream with next's SWC minification when it comes to processing mixed quote styles. CC'ing @leerob 

### Expected Behavior

Throwing the error with mixed quote styles flowing correctly into a single string as the logic defines. 

### Steps To Reproduce

Next.js build with Wagmi ran in production

### Anything else?

<img width="785" alt="Screen Shot 2022-10-17 at 6 47 18 PM" src="https://user-images.githubusercontent.com/8116716/196236150-e2b7ee3c-c9f2-4afa-bd7f-b8dd12528eea.png">

**Comment by mirshko** [comment]
Attached is the patch-package diff. 

```patch
diff --git a/node_modules/@wagmi/core/dist/wagmi-core.cjs.dev.js b/node_modules/@wagmi/core/dist/wagmi-core.cjs.dev.js
index ea7f281..ac3ba3b 100644
--- a/node_modules/@wagmi/core/dist/wagmi-core.cjs.dev.js
+++ b/node_modules/@wagmi/core/dist/wagmi-core.cjs.dev.js
@@ -60,7 +60,7 @@ function configureChains(defaultChains, providers) {
 
 
     if (!configExists) {
-      throw new Error([`Could not find valid provider configuration for chain "${chain.name}".\n`, "You may need to add `jsonRpcProvider` to `configureChains` with the chain's RPC URLs.", 'Read more: https://wagmi.sh/docs/providers/jsonRpc'].join('\n'));
+      throw new Error([`Could not find valid provider configuration for chain "${chain.name}".`, `You may need to add "jsonRpcProvider" to "configureChains" with the chain's RPC URLs.`, `Read more: https://wagmi.sh/docs/providers/jsonRpc`].join('\n'));
     }
   }
 
diff --git a/node_modules/@wagmi/core/dist/wagmi-core.cjs.prod.js b/node_modules/@wagmi/core/dist/wagmi-core.cjs.prod.js
index f663fd0..fe763ca 100644
--- a/node_modules/@wagmi/core/dist/wagmi-core.cjs.prod.js
+++ b/node_modules/@wagmi/core/dist/wagmi-core.cjs.prod.js
@@ -60,7 +60,7 @@ function configureChains(defaultChains, providers) {
 
 
     if (!configExists) {
-      throw new Error([`Could not find valid provider configuration for chain "${chain.name}".\n`, "You may need to add `jsonRpcProvider` to `configureChains` with the chain's RPC URLs.", 'Read more: https://wagmi.sh/docs/providers/jsonRpc'].join('\n'));
+      throw new Error([`Could not find valid provider configuration for chain "${chain.name}".`, `You may need to add "jsonRpcProvider" to "configureChains" with the chain's RPC URLs.`, `Read more: https://wagmi.sh/docs/providers/jsonRpc`].join('\n'));
     }
   }
 
diff --git a/node_modules/@wagmi/core/dist/wagmi-core.esm.js b/node_modules/@wagmi/core/dist/wagmi-core.esm.js
index aa7f69d..0248a19 100644
--- a/node_modules/@wagmi/core/dist/wagmi-core.esm.js
+++ b/node_modules/@wagmi/core/dist/wagmi-core.esm.js
@@ -54,7 +54,7 @@ function configureChains(defaultChains, providers) {
 
 
     if (!configExists) {
-      throw new Error([`Could not find valid provider configuration for chain "${chain.name}".\n`, "You may need to add `jsonRpcProvider` to `configureChains` with the chain's RPC URLs.", 'Read more: https://wagmi.sh/docs/providers/jsonRpc'].join('\n'));
+      throw new Error([`Could not find valid provider configuration for chain "${chain.name}".`, `You may need to add "jsonRpcProvider" to "configureChains" with the chain's RPC URLs.`, `Read more: https://wagmi.sh/docs/providers/jsonRpc`].join('\n'));
     }
   }
 
```

**Comment by mirshko** [comment]
@tmm

**Comment by jxom** [comment]
I can seem to deploy a wagmi app to Vercel fine ([reference repository](https://github.com/jxom/wagmi-next-template) – [deployed site](https://wagmi-next-template.vercel.app/)). Do you mind sharing a minimal reproducible repository like mine so we can investigate further – are you passing custom chains/providers in? I can re-open the issue when provided!

**Comment by mirshko** [comment]
@jxom seems there's some issue with swcMinify with my setup, with it disabled this is not a problem. Can't seem to replicate with the same sort of setup with your reference repo, unsure of the reason. My guess is its an upstream issue. 

Something is causing the `"You may need to add `jsonRpcProvider` to `configureChains` w...` bit to not escape the ` properly when swcMinify is enabled. 

Sorry for the issue!

**Comment by tomoima525** [comment]
Hey @jxom @mirshko I had the same issue and created a reproducible repo and deployment website 👇 

https://wagmi-next-template-lymktdvd1-tomoima525.vercel.app/
https://github.com/tomoima525/wagmi-next-template/pull/1 (Reproducible branch)

This seems to happen in 12.1.x and below versions of Next.js in conjunction with `swcMinify` option. I think we can ignore the issue as it's specific to the older version of Next.js
