### ISSUE TITLE
bug: ABI not creating types when importing as JSON

### ISSUE THREAD

**Issue by samkingco** [wagmi-dev/wagmi#1106]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.7.5

### Current Behavior

Functions that rely on the ABI are currently not detecting the correct types when the ABI is imported as JSON. This happens specifically in `useContractRead` and `usePrepareContractWrite` but I haven't tested others.

### Expected Behavior

I would expect the JSON import to be correctly picked by the hooks so that function names and arguments are typed.

### Steps To Reproduce

**ERC721.abi.json** with other functions omitted for brevity. See CodeSandbox for full JSON.
```json
[
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "id",
        "type": "uint256"
      }
    ],
    "name": "ownerOf",
    "outputs": [
      {
        "internalType": "address",
        "name": "owner",
        "type": "address"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  }
]
```

Then in my component:
```tsx
import { useContractRead } from "wagmi";
import { BigNumber } from "ethers";
import { useIsMounted } from "../hooks/useIsMounted";
import ABI from "../ERC721.abi.json";

export default function IndexPage() {
  const isMounted = useIsMounted();

  // Return type of `data` is not defined correctly
  const { data: ownerOf } = useContractRead({
    // Deadfellaz as an example
    address: "0x2acAb3DEa77832C09420663b0E1cB386031bA17B",
    abi: ABI,
    // Should "fail" since `ownedOf` is not in the ABI, but `ownerOf` is.
    // Is typed as `string | undefined`.
    functionName: "ownedOf",
    // Also none of these args are typed
    args: [BigNumber.from(1)],
    watch: true
  });

  return (
    <div>
      <p>Owner of token ID 1: {(isMounted ? ownerOf : null) ?? "-"}</p>
    </div>
  );
}
```

### Link to Minimal Reproducible Example (CodeSandbox, StackBlitz, etc.)

https://codesandbox.io/s/cold-sound-f24lbx?file=/pages/index.tsx

### Anything else?

I'm not sure if I'm doing something wrong when importing JSON, but I can't add `as const` since it's imported and not a literal. I've checked and copy pasting the ABI as a literal and adding `as const` works as expected.

My use case is a monorepo with foundry. I'd like to be able to import the ABI directly from the foundry output folder using a pnpm monorepo e.g.

```tsx
import MyContractABI from "@sk-web3/contracts/out/MyContract.sol/MyContract.abi.json";
```

Here's my `tsconfig.json` if it helps:
```json
{
  "compilerOptions": {
    "target": "es5",
    "lib": ["dom", "dom.iterable", "esnext"],
    "allowJs": true,
    "skipLibCheck": true,
    "strict": true,
    "forceConsistentCasingInFileNames": true,
    "noEmit": true,
    "esModuleInterop": true,
    "module": "esnext",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "jsx": "preserve",
    "incremental": true
  },
  "include": ["next-env.d.ts", "**/*.ts", "**/*.tsx"],
  "exclude": ["node_modules"]
}
```

**Comment by tmm** [comment]
Appreciate you putting together a solid issue! Unfortunately [TypeScript doesn't support importing JSON as const](https://github.com/microsoft/TypeScript/issues/32063) right now so this doesn't work. Without giving too much away, watch out for a tighter integration between wagmi and Foundry/Hardhat in the future.

**Comment by samkingco** [comment]
Yeah I landed on the same issue in TypeScript 😞. Appreciate the response though, and looking forward to the tighter integration.

For anyone else that ended up here, I decided to write a temporary shell script to take the contents of a Foundry ABI JSON file and save them to a .ts file exported as a const. You can see it in my [template repo here](https://github.com/samkingco/sk-web3/blob/d7cd967383759300a9a96721aa49c592b8e4352f/packages/app/gen-abi.sh).

**Comment by anteqkois** [comment]
I also created my own function to prepare Type Script files with abi as constant using Hardhat. In deploy script is [function saveAbi](https://github.com/anteqkois/tipdapp/blob/72bcd6d3e2bc55c41b13e919298fe5782c0bc495/contracts/scripts/deploy.ts#L45-L64) to do it.
