### ISSUE TITLE
bug: useContractReads breaks typescript

### ISSUE THREAD

**Issue by cesargdm** [wagmi-dev/wagmi#1110]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.7.x

### Current Behavior

If I import the hook `useContractReads`, typescript fails, in VSCode extension and also using `tsc`.

### Steps To Reproduce

```
import {
	useContractReads,
} from 'wagmi'
```

**Comment by cesargdm** [comment]
Editing `useContractReads` declaration to  enables the build/typelinting
```ts
export declare function useContractReads<TAbi extends Abi | readonly unknown[], TFunctionName extends string, TContracts extends {
    abi: TAbi;
    functionName: TFunctionName;
}[]>(any): import("../utils/query/useQuery").UseQueryResult<
    any
>;
```

**Comment by tmm** [comment]
Thanks for reporting! Looking into it.

Related discussion https://github.com/wagmi-dev/wagmi/discussions/1107#discussioncomment-3906115

**Comment by k-xo** [comment]
Also experiencing the same issue

**Comment by VTAkbay** [comment]
Same issue here ✋🏻

**Comment by Eyon42** [comment]
This issue also affects useContractInfiniteReads and causes VSCode's autocompetion (for the entire project) to hang up and occupy 100% cpu power.
