### ISSUE TITLE
bug: useSwitchNetwork not detecting Wallet Connect

### ISSUE THREAD

**Issue by NBMSacha** [wagmi-dev/wagmi#1122]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.6.3

### Current Behavior

useSwitchNetwork returns switchNetwork undefined when connecting with Wallet Connect

### Expected Behavior

useSwitchNetwork returns switchNetwork functional when connecting with Wallet Connect as it is supported (i.e. 1Inch dApp)

### Steps To Reproduce

- Install Wagmi
- Connect a wallet with Wallet Connect
- console.log(switchNetwork)

### Link to Minimal Reproducible Example (CodeSandbox, StackBlitz, etc.)

https://mobula.fi

### Anything else?

(try to log in with bnb chain and navigate to an eth-only asset, i.e. The White Rabbit)

**Comment by jxom** [comment]
Not all wallets support network switching through wallet connect. Here are the [current wallets that do support it](https://github.com/wagmi-dev/wagmi/blob/main/packages/core/src/connectors/walletConnect.ts#L21). If the wallet you're using does support it, feel free to open a PR adding it.

**Comment by NBMSacha** [comment]
Trust wallet does and isn't supported - to update that, I just need to modify 

const switchChainAllowedRegex = /(imtoken|metamask|rainbow)/i


And to update it to 

const switchChainAllowedRegex = /(imtoken|metamask|rainbow|trustwallet)/i

?

Or do we need to include additional logic, or, trustwallet isn't the same of Trust Wallet?

**Comment by NBMSacha** [comment]
Up :)

**Comment by NBMSacha** [comment]
@jxom ?
