### ISSUE TITLE
bug: useContractRead method with watch affecting other call

### ISSUE THREAD

**Issue by yujiym** [wagmi-dev/wagmi#1127]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.7.5

### Current Behavior

`useContractRead` method with `watch: true` option affecting other calls.

1. `useContractRead` with `watch: false` -> called every new block (should be called once)
2. `useContractRead` with `watch: true` -> called every new block

![Screen Shot 2022-10-21 at 16 38 11](https://user-images.githubusercontent.com/1409395/197140304-4dd057cb-00c3-4be2-9214-94c07bf27717.png)

If both methods are set to `watch: false`, they will only be called once.

### Expected Behavior

1. `useContractRead` with `watch: false` -> called once
2. `useContractRead` with `watch: true` -> called every new block

### Steps To Reproduce

Open codesandbox link and watch browser's console.

### Link to Minimal Reproducible Example (CodeSandbox, StackBlitz, etc.)

https://codesandbox.io/p/sandbox/boring-pascal-w4jnlq

### Anything else?

Since `useBlockNumber` has the same behavior, `useBlockNumber`'s state called inside `useContractRead` may be the cause.

This cloud be due to the same cause. https://github.com/wagmi-dev/wagmi/issues/888

**Comment by jxom** [comment]
Can now use the `scopeKey` config option on `useContractRead` to scope the hook to a given key to isolate it from other instances!

**Comment by rsodre** [comment]
Does it mean that if we don't use the `scopeKey`, one single hook using `watch` wil trigger all other hooks to refetch?
And in a group of hooks with `scopeKey`, one update will trigger all the other hooks?

**Comment by rsodre** [comment]
> 

Does it mean that if we don't use the scopeKey, one single hook using watch wil trigger all other hooks to refetch?
And in a group of hooks with scopeKey, one update will trigger all the other hooks?

**Comment by tmm** [comment]
Correct, the fetching will be deduplicated across query keys though.
