### ISSUE TITLE
bug: Error: could not detect network (event="noNetwork", code=NETWORK_ERROR

### ISSUE THREAD

**Issue by soccerarenadev** [wagmi-dev/wagmi#1133]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.7.5

### Current Behavior

I'm constantly getting this error:

Error: could not detect network (event="noNetwork", code=NETWORK_ERROR, version=providers/5.7.1)

<img width="957" alt="image" src="https://user-images.githubusercontent.com/99416733/197272283-04a6d709-cf0e-4e39-ba59-7a89828ebd83.png">

I have alchemyProvider as my first provider.
Changing back to the default API doesn't change anything, but removing from providers does.

However, I have also infuraProvider. But unless I remove alchemyProvider, it doesn't fallback to infureProvider.

### Expected Behavior

Fallback to other providers if the first provider fails.

**Comment by jxom** [comment]
Thanks for reporting. This issue is temporarily closed due to lack of information. Please provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) via a CodeSandbox (feel free to use [this template](https://codesandbox.io/s/bitter-wind-pv0hwj)) and reopen this issue. It will help us reproduce your issue! 🙏

**Comment by soccerarenadev** [comment]
There you have the minimal reproducible example:
https://codesandbox.io/s/zen-browser-c5mh21?file=/pages/_app.tsx

However, it is just the rainbowkit example. Very basic stuff with little things.
Using the ethers.js API key.
However, with my own API key I have the same error.

**Comment by paulpopus** [comment]
We're also seeing this with the Alchemy provider

**Comment by wassienabe** [comment]
I have the same issue after copy/pasting the example shown here: 
https://wagmi.sh/examples/connect-wallet

Adding in the Infura provider and placing it before the Alchemy provider resolved it for now.

**Comment by adshodgson** [comment]
Also seeing this issue...
