### ISSUE TITLE
`usePrepareContractWrite` taken from examples is failing 

### ISSUE THREAD

**Issue by theodale** [wagmi-dev/wagmi#1138]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.6.8

### Current Behavior

I have copy-pasted the `usePrepareContractWrite` section of the contract write (dynamic args) example in the docs. The hook is failing when run, trying to `map` over its `abi` argument, which is undefined, despite using the example in the docs. 

### Expected Behavior

The hook should not fail and should return a usable write `config`

### Steps To Reproduce

Enter a number into the form and see the error message in the browser console.

Here is the repo https://github.com/theodale/wagmi-issue

Sandbox below - look at `MintNFTForm.js`

### Link to Minimal Reproducible Example (CodeSandbox, StackBlitz, etc.)

https://codesandbox.io/p/github/theodale/wagmi-issue/main?file=%2Fsrc%2FMintNFTForm.js&workspace=%257B%2522activeFileId%2522%253A%2522cl9jtkr0f0009lsh1a3cafyvu%2522%252C%2522openFiles%2522%253A%255B%255D%252C%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522gitSidebarPanel%2522%253A%2522COMMIT%2522%252C%2522sidekickItems%2522%253A%255B%257B%2522key%2522%253A%2522cl9jtn3wg00073b6jbzy9fey1%2522%252C%2522type%2522%253A%2522PROJECT_SETUP%2522%252C%2522isMinimized%2522%253Afalse%257D%252C%257B%2522type%2522%253A%2522PREVIEW%2522%252C%2522taskId%2522%253A%2522start%2522%252C%2522port%2522%253A3000%252C%2522key%2522%253A%2522cl9jtlmpq00533b6jlh2bn2o3%2522%252C%2522isMinimized%2522%253Afalse%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522start%2522%252C%2522key%2522%253A%2522cl9jtljtd003n3b6jy2aynub0%2522%252C%2522isMinimized%2522%253Afalse%257D%255D%257D

**Comment by owade** [comment]
If you are using version 0.6 preparecontract write should be 
```
usePrepareContractWrite({
    addressOrName: '0x050B31f15DCeE34529E5A4E5Cb9C159483729582',
    contractInterface: SimpleContractAbi,
    functionName: 'setCount',
    args: [ethers.utils.parseEther(count)],
    enabled: Boolean(count),
  })
```

**Comment by theodale** [comment]
Thanks. I think its a bit confusing that if you use `ConnectKit` as suggested in the docs (https://wagmi.sh/examples/connect-wallet) and follow their getting started instructions (i.e. the development flow I followed), you end up with an older version of `wagmi` installed cannot use the following methods in the same example docs.t

Furthermore, is there a workaround to use the latest versions of each package? If not, are there docs for the `wagmi` version (`^0.6.0`) used by `ConnectKit`?

**Comment by tmm** [comment]
0.6.x docs are [here](https://0.6.x.wagmi.sh). Will follow up with the ConnectKit team too.
