### ISSUE TITLE
bug: can't use custom wallet connect modal

### ISSUE THREAD

**Issue by xuzhanhh** [wagmi-dev/wagmi#1150]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.68

### Current Behavior

As https://docs.walletconnect.com/quick-start/dapps/web3-provider#disable-qr-code-modal said, I need on listen `display_uri` on walletConnectProvider, But when i trigger connect, it will forceUpdate the walletConnectProvider, so I can't get the latest provider and listen `display_uri`

### Expected Behavior

Provide a way to listen the origin walletConnectProvider

**Comment by jxom** [comment]
You might be looking for the provider on your WalletConnect connector.

```tsx
import { useConnect } from 'wagmi'

function Example() {
  const { connectors } = useConnect()
  
  useEffect(() => {
    async function displayUriHandler() {
      const connector = connectors.find(({ id }) => id === 'walletConnect')
      if (!connector) return

      const provider = await connector.getProvider()
      provider.connector.on('display_uri', (err, payload) => {
        // ...
      })
    }
    displayUriHandler()
  }, [connectors])

  // ...
}
```

**Comment by tmm** [comment]
Check out how [RainbowKit](https://github.com/rainbow-me/rainbowkit/blob/main/packages/rainbowkit/src/wallets/walletConnectors/metaMaskWallet/metaMaskWallet.ts#L73) and [ConnectKit](https://github.com/family/connectkit/blob/57b888fa87b0b3566dd48d1308b3b514b3442a39/packages/connectkit/src/wallets/connectors/metaMask.tsx#L86) get the WalletConnect session URI.
