### ISSUE TITLE
bug: `usePrepareContractWrite` resolver or addr is not configured for ENS name

### ISSUE THREAD

**Issue by marcustut** [wagmi-dev/wagmi#1171]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.7.6

### Current Behavior

Was using the hook as follows, however the `write` and `writeAsync` are both undefined. This is because the config returned by `usePrepareContractWrite` has an undefined request field. 

```tsx
  const { config: addInventoryConfig } = usePrepareContractWrite({
    address: config.app.contractAddresses.inventory,
    abi: InventoryABI,
    functionName: 'addInventory',
    args: convertFormikValuesToAddInventoryArgs(formik.values),
  });
  const { write, writeAsync, error, status } = useContractWrite(addInventoryConfig);
```

The error I can see from the logs are as follow:

<img width="804" alt="Screenshot 2022-10-26 at 9 21 12 PM" src="https://user-images.githubusercontent.com/59773847/198036888-827e6f47-9903-4b5b-be77-bbcc2a4ac997.png">

I think this is a bug because I'm not using any ENS name here, it is a valid contract address.

I later tried using it as follows, turns out write is now defined, but when I call it the same error appears. Does this has to do with ethers.js trying to create a new Contract with ENS name even though an address was passed in?

```tsx
  const { write } = useContractWrite({
    mode: 'recklesslyUnprepared',
    address: config.app.contractAddresses.inventory,
    abi: InventoryABI,
    functionName: 'addInventory',
    args: convertFormikValuesToAddInventoryArgs(formik.values),
  });
```

### Expected Behavior

Expecting `usePrepareContractWrite` to return a config with the `request` field populated.

**Comment by tmm** [comment]
Thanks for reporting. This issue is temporarily closed due to lack of information. Please provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) and reopen this issue.
