### ISSUE TITLE
bug: <useContractsRead caused vscode CPU 100%>

### ISSUE THREAD

**Issue by sunopar** [wagmi-dev/wagmi#1180]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.7.5

### Current Behavior

When vscode tsserver scan the `node_modules/wagmi/dist/declarations/src/hooks/contracts/useContractReads.d.ts` file, it will cause the CPU to 100% by vscode.

### Steps To Reproduce

open vscode, open node_modules/wagmi/dist/declarations/src/hooks/contracts/useContractReads.d.ts file. You can see the CPU status.

**Comment by sunopar** [comment]
Find new version fix this issue, ignore me.

**Comment by TikiCat7** [comment]
lol my nvim and vscode both died from just looking up the type definition 😅
