### ISSUE TITLE
bug: WallectConnect signature wrong address

### ISSUE THREAD

**Issue by kkatusic** [wagmi-dev/wagmi#1182]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.7.5

### Current Behavior

When you are connecting via WallectConnect on website using your mobile wallet, connection done wright. But if you want to make some signature using `useSignMessage`hook you get sign message, approved it, signature has been made but with wrong address. I tested on local computer, on my website and also one your example: https://wagmi.sh/examples/sign-message 

![walletconnect_290AFAF8](https://user-images.githubusercontent.com/1242145/198367069-5178241a-8cab-4ba6-8f27-dfa872599e32.png)

and when you try to check signature on etherscan with your wallet address signature isn't ok because it has been signed with some address: 0xd5289Bc91E2822A23A8A9BB38E26ffc1EFEa82AF , I don't know who is owner of this address.

### Expected Behavior

That recovered address is same that wallet address when using sign message.

### Steps To Reproduce

Go to link: https://wagmi.sh/examples/sign-message
Connect your mobile wallet via WalletConnect
Enter some sign message
Click "Sign Message"

### Anything else?

Sorry if I'm wrong :(

**Comment by tmm** [comment]
I wasn't able to reproduce using Rainbow or MetaMask via WalletConnect. Happy to look into further if you provide a [minimal reproducible example](
https://stackoverflow.com/help/minimal-reproducible-example), wallet you used, etc.

https://user-images.githubusercontent.com/6759464/198392051-c774a474-d35f-4d4c-ad37-42ba071c684d.mp4

**Comment by kkatusic** [comment]
Thx @tmm for fast response, I was using Argent wallet, maybe someone will have same issue I will leave this comment.

**Comment by vinliao** [comment]
This bug happens if message has `Date.now()`

```
const payload = canonicalize({
  method: "generateToken",
  params: {
    timestamp: Date.now()
  },
});

// wagmi
const { signMessage } = useSignMessage({
  message: payload, // results in mismatched address
)}
```

This issue doesn't happen if `Date.now()` is a hard-coded integer UNIX timestamp:
```
// this is OK
const payload = canonicalize({
  method: "generateToken",
  params: {
    timestamp: 1669097939021
  },
});
```

**Comment by neuxregime** [comment]
Running into a similar issue with Argent/WalletConnect. Our payload is a string akin to `We use this cryptographic signature to verify your ownership of this wallet - UID: 1677696932940`. 
Recovered signer address does not match the connected account.
