### ISSUE TITLE
bug: Add to cont erc20ABI func permit

### ISSUE THREAD

**Issue by StKostyantin** [wagmi-dev/wagmi#1205]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.6.8

### Current Behavior

In [eip-2612]( https://eips.ethereum.org/EIPS/eip-2612) a function has been added `permit`.
And in order not to create new files in the project, it would be good to update the existing const.

**Comment by tmm** [comment]
Can you please add some more additional info to this issue (e.g. Expected behavior, [minimal reproducible example](
https://stackoverflow.com/help/minimal-reproducible-example), etc.)?
