### ISSUE TITLE
call revert exception : when calling read contract before connecting wallet

### ISSUE THREAD

**Issue by adriadrop** [wagmi-dev/wagmi#1231]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.7.7

### Current Behavior

I have token counter that I want to display count of NFTs already minted before the wallet is connected but this doesn't happen until I connect the wallet.  From what I read WAGMI is using providers from config not from injected wallet and I did check provider object its present so I don't see a reason why this isn't possible.

### Expected Behavior

Read contract data before the wallet is connected

### Steps To Reproduce

I tried both the "useContract"  with the provider and  "useContractRead" and both failed with error
`(method="totalSupply()", data="0x", errorArgs=null, errorName=null, errorSignature=null, reason=null, code=CALL_EXCEPTION, version=abi/5.7.0)`

**Comment by tmm** [comment]
Thanks for reporting. This issue is temporarily closed due to lack of information. Please provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) and reopen this issue.

**Comment by adriadrop** [comment]
But this?
https://github.com/wagmi-dev/wagmi/issues/1004

how can I provide it in sandbox when it isnt working there?

**Comment by tmm** [comment]
Have you tried putting together a CodeSandbox? If it doesn't work, you can share a link to a GitHub repo with the minimal reproducible example instead.

**Comment by adriadrop** [comment]
Thnx for pushing. 
In the end I made it works as designed, there was a problem that I was using Matic chain and if It isnt specificed in function call it would not know it was refering to that chain. Which makes sense as how can it know if its not specified. So in the end works as designed with both functions as long as chainID is provided. So if someone stumbles on same issue here is example

For useContract add this 
`  const provider = useProvider({ chainId: 137,});`

for useContractRead add this

```
  const { data: totalSupplyData } = useContractRead({
    ...contractConfig,
    functionName: "totalSupply",
    chainId: 137,
  });
```
