### ISSUE TITLE
bug: Unpredictable disconnect Metamask

### ISSUE THREAD

**Issue by Nikitulb** [wagmi-dev/wagmi#1239]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.7.12

### Current Behavior

1. Connect with Metamask
2. Select another chain in extension (ex. BSC) - everything is ok
3. Select Arbitrum chain in extension -  you will be disconnected and wagmi store clean active connector

### Expected Behavior

1. Connect with Metamask
2. Select another chain in extension (ex. BSC) - everything is ok
3. Select Arbitrum chain in extension -  everything is ok

### Steps To Reproduce

1. Connect with Metamask
2. Select another chain in extension (ex. BSC)
3. Select Arbitrum (Optimism) chain in extension

### Link to Minimal Reproducible Example (CodeSandbox, StackBlitz, etc.)

https://wagmi.sh/examples/connect-wallet

### Anything else?
Params for Arbitrum Network 
- Network name
Arbitrum Mainnet
- RPC URL
https://arb1.arbitrum.io/rpc
- Chain ID
42161
- Currency symbol
ETH
 - Block explorer URL(Optional)
https://arbiscan.io

**Comment by tmm** [comment]
This is a [known issue](https://github.com/MetaMask/metamask-extension/issues/13375#issuecomment-1087023057) with MetaMask, where a `"disconnect"` event is emitted when you switch from MetaMask's default networks to custom networks.

wagmi patches this behavior with the [`shimChainChangedDisconnect`](https://wagmi.sh/docs/connectors/metaMask#shimchainchangeddisconnect) flag, but it unfortunately doesn't work when switching networks from the browser extension.
