### ISSUE TITLE
bug: Deprecated dependency, ethereumjs-abi, causes builds to fail on Netlify

### ISSUE THREAD

**Issue by tristangrace** [wagmi-dev/wagmi#1263]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.7.14

### Current Behavior

Explained very well here.
https://answers.netlify.com/t/builds-started-failing-after-build-image-update/77666

In summary, when Netlify updated their build image this caused this error to appear:

`YN0018: │ ethereumjs-abi@https://github.com/ethereumjs/ethereumjs-abi.git#commit=ee3994657fa7a427238e6ba92a84d0b529bbcde0: The remote archive doesn't match the expected checksum`

I traced back this dependency through yarn.lock and found it came from wagmi. 
This was the path:
wagmi@npm:^0.7.14
@coinbase/wallet-sdk@npm:^3.5.3
eth-json-rpc-filters@npm:4.2.2
eth-json-rpc-middleware@npm:^6.0.0
eth-sig-util@npm:^1.4.2
ethereumjs-abi@git+https://github.com/ethereumjs/ethereumjs-abi.git

Being that ethereumjs-abi is depreciated it might be worth looking at updating how this is handled. It looks like eth-json-rpc-middleware has updated away the depreciated package.

**Comment by helloLance** [comment]
I have same issue, you can fix it by change .lock  ethereumjs-abi:0.6.8

**Comment by TrisDotEth** [comment]
Oh thanks for the help helloLance, ironically enough I came back to this page to say I found an answer too!
By adding this to my package.json 
```
  "resolutions": {
    "eth-sig-util": "3.0.1"
  },
```

Now I am able to deploy my site again. Hopefully this can help someone else.

**Comment by helloLance** [comment]
thank you ,@TrisDotEth,
