### ISSUE TITLE
bug: Cannot Find Module Error in VSC using Next.JS

### ISSUE THREAD

**Issue by NuclearGeekETH** [wagmi-dev/wagmi#1278]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

^0.7.15

### Current Behavior

When using wagmi in Next.JS I am showing red underlined errors in VS Code. The error states cannot find Module. I have confirmed wagmi is installed and my site is functioning like it should. I am not sure if there is just a bug in VSC.

### Expected Behavior

I would expect VSC to find the module.

### Steps To Reproduce

npm install my repo and npm run dev to see that it is working. Open index.tsx in pages to see the red underlined error in VSC.

### Link to Minimal Reproducible Example (CodeSandbox, StackBlitz, etc.)

https://github.com/NuclearGeekETH/Developer-Portfolio

### Anything else?

![image](https://user-images.githubusercontent.com/47373292/200989232-8a67bb0b-cea1-489a-b816-708cfd6b20bb.png)

**Comment by tmm** [comment]
Cloned the repo, installed deps, and working fine for me.

https://user-images.githubusercontent.com/6759464/201226980-03c1b039-8753-4ff5-b43b-80e9de0c5418.mp4
