### ISSUE TITLE
bug: use useContractRead on a non-view function throws a sendTransaction error

### ISSUE THREAD

**Issue by Theo-** [wagmi-dev/wagmi#1280]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.7.0

### Current Behavior

```
Error: sending a transaction requires a signer (operation="sendTransaction", code=UNSUPPORTED_OPERATION, version=contracts/5.7.0)
```

### Expected Behavior

It should read the result of the non-view function

### Steps To Reproduce

use `useContractRead` on a non-view function such as UniswapV3 quoter

**Comment by tmm** [comment]
Thanks for reporting. This issue is temporarily closed due to lack of information. Please provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) and reopen this issue.
