### ISSUE TITLE
bug: abi

### ISSUE THREAD

**Issue by matthewlilley** [wagmi-dev/wagmi#1291]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

latest

### Current Behavior

Fails to infer return type for ABI function

### Expected Behavior

Infers return type for ABI function

### Anything else?

https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgVwM4FMDCEB2MoCGAxjAEroEAmqANHAIKWVTqqpwC+cAZlBCHADkAdwIBzEMEEBYAFByiuVPAIAjYHAC8cANpy4ifQbgEcuAJ4gIaAFw8CAGww0jB4DjDIYqO3tnHjBFcAuHdKdAAPdEo7fGR0F38Qtzx0KBxHABVzMHQ7QSpmVlRBROSDDJA8oQhhHDTS4ICYHOqCphY2RqSAjjKQoJ6QsMjo2Kh4-uT3GDSMh2zc-MLOkqmQyrbUXJxwqG7yuBaloRXig5C+psMhgJGomPsnBOuU2fSs1vzkGYAmAFYAGwXZKbfIAN0c8RBIWObR+eABwPWBiuQwAuuswUJ6GAwHxIQ4YXD8uhweg8Bc0QZBgFTBYrLYns5gu5PN5fNdaeV7mMjhMXrdjDM5p8Tu0il0UcZsYIMLsGtKDCTTh1ztLqQNXqEFQ87NxHCyhW9RQsvkIETAkTCArKCIy8AAGG3GFWCS3WjXS7nTXV8g3PJU697zRbwv5Al0Ve1te3WPAARijR3N7ojyOumoCPuGfsecUFhxFHzN4rOUu1spgEGTbvLa0z60xwVlACFkOliamyRSYFT+jn6ThLNYfMzC8KPF4x35kjm7nnxpNtcXQ6n68nZfK9rX12qK0Ks4EV4vx0HV2Lw4jI0G7Q6YM6g26PTfG1yT+E9WeTyHL9905uMbLPeSZPqmL4ZoeTZYkBQgALIzF24o9pS-SaoOZjDoyY4BkaC7sjO77Gjqn58gW56pCWYbLPuDbEVuFI7mBZa0S6R40h+oyPLhE6+r+pZXlar70bBBT3o6ACSOC7uKEFsd6nFfjxFH8dRFoAbeolxsgiZSTJgmem+QrzpOpHcYavG5qp4EaZWWniQA8l4+n-tekHJOxNxFqeyk-qaalpm5gFVMB8YwAmTl9sxBnCR5CnEby+YCip-l7pKdGHFWNbRTR6XycEzZDLKADKohgEhbQoVFRjocEQ4jkyvlDGy06csZin+hZKVUTZiYJr8wVtJ0aTko+2rPjMCb9fl7UJT5XV+T1smTdNmkhUIw1QOSoHjb14WrUZASFbaonFeYOBEBVpLkqhNUDnVmENThC3NVOHK6ER3lmUulkLtZLF5WtbS8PwLmqoDh1anN338suc3-bGrFA-k1ZgxKqwzXOHXmYGi1rstQXI0IhLQjl6mE5DBjHTKomZIQOCoNwirBG6VX9kYOaKAzMCmDAP3rC1706NT0brYIAAiDlwfQEkAHIAPrFQAogACvQpD0JkDmkDC1gwARbVY-DqXiqo5izKgADMA1E4IaNmxb1uY8YItwGABDmGoDjVE1ATKAQsxwV4ajAA4wAtBCwDoMIV1CNwOkkMAuDs0knNKDzeD86yb0zq7spwXLElwQAqnB8sADISQAisXEnixJmQAJq614BsfbN3kI65QnueUspo3JXoFes7ue6o3v6i9fs84HwfqGHEdCJ4LCx4I8cXTASfSWh91DFz-uZ7DlmC7nMFiyrSukAXmTy03F8ABL0MV98t-rrXt0bncm20DusE7tv23Nn-G2lM4Cu1Hl7H2U9jD+1njzee4dzD5GXugVe69E7Jx3hzYI+8M58yPgLHOhsoZfyWojCGIkxa1HqPsMm6N1SgI4sbMhuUMa222IxZmxE6xI1AXnLSDgHC1FMEQVB6w9Zt1nCQnklF8YxV7qCUSA9bJQWHsECB48oG4yGLA9AQd4Gh0QZHaOaCE6b0wXdbBe90680nto-C78pHZjxn+cGbC7Jiw4QqWhu0AbuNUR3GRXdyY90GhCKEYjfHyOdlTM+sY8QEkiUMCRjjPpBO-vkVQEAIBEgAXQrJOSYlgJHh7SBdi8IwJnnouehjF6CEwho72piN5bxTkwgIuDbEEOzpItJfEMluIYZQto1CuGHB4RQuKaiiqiVUI4ER6AHLcFfr0wJ-SWEhMMsM-IyiKYBKOiUseE9vw6KqfokOC8kHEyjjHdYbp0HmO3pY1OOCbGH19pOVZn90kbPoQeTKolUZ0I3EPDEcTMkdieck1uqS1lWQGYFUJtttJOl2UixhXkflyO7lsgFYsUXhTRbiy40F1GlM0eUyyujzkILqQ08lTS7mpgea0rBLzrHcy6eRHpjj+Fi3CEQUAhoVmwu+es7FISAAcYShBoulaCg5ZKjlaIqQYalNTLnII7Ek5ozKzGsuee04wnTD7ctepIvlwNiDVigOYEVQs+nwt+SCjxbQ0Yuv2S7Q5ZSTnTwDtUgxmrrkmKZeKFlFiki1Q5QffBZqHFC0tfkMQ6AyCsBGqwe1hE4V-QRZaKaIDtkbTTVtdAY1uF7XzUUo14rXGIsrbbTa200X1oxSZE0vzLT-1dZkoRRAADWmRQCsB5uAcuBBlBoq7Z62JSqfUfLVWcjVRjg23JZnqlpEbUS7w6W8-B86dRfOkTWgSrChl4rdcC3h07jzMIlX8jKfclGXsmSS6ZJ0xbuHDsARwwAABeOrjApITd6ilvrKn+ppbUq59TcCNIA8qddGCoVbqsTuzlprko8uAy2USfax0TvETCh12bJzBMRcSxRYsiWxVfWC2doH93qsDcuwQ4IbnNKQ20zFBgTV7ugSkQ9zjb21o9eelG2Uomnv+bRxVMyxaSFutCt+xGxVOrvYPbtQgw4AEcfiUEQdRhRxgjzgIZSqqli7mN0tg2ZjjjyuNp3Q7GzD5reXgqEJsTNxChOkLvcoKA7gxAyrtnQ-zgWimmeVZS9YTGLksZQXZg1kbt3Gt3VnVzKmj1qZE1esTNQ6hjPKBM-xUy6NybaJhURD6DBAazapnNHaVF5ZC5JzZNHeikqGHB6LwRYu0ug2xkNa6w36s3ZwFLPG0tgYE6KrLDW72icfVQgrPjy1+LPTJubpGEWLco1sHYTFWv3qrdx7LJ62tGffW0Em8HYR7Qo8Z+Kvna0acLYIcIVAw71EMydttwZc0zHlZp1jcrfsuPO4IX+VsC3NdW+M1MUOp2lfq9t35iOYdLa2IAx2GOOtvppmLXIUBJDVSUxakDxzGOWbi9ZjwtnQ3A1G8h8bqHUtOfS-G0+OHCcBdEY6TAyAQDIAcAHYA5J8Ok4CLV7zN7nsQ9e81n7CqvX0cp-xuAfWoPGNXUMe5TOHOvPZ90jLXPyvIN5+gBMAuhci83uL8dkvANEbq1t9t6mmuY52XQhXm2Z1dbMz105EGl11MGzr3VI2N3M6jWhmNgfOcy+rWdgKu2NiAok2t8hJXffFO51sPtoAvO6Ei3O9Xmug0wbp8qxLY2Y9s7j9Ng9s2fNYpex7vboUdIPkikr1t4OAo+476cECPfvft8e46+bOWX1D8EECo7qeUMkbd7WqHwXKABwINjjNyu-dXfyKgMqRfhYU-MzF6n-X8j0urwz-I4bo8TbgLxjnny3N54P5YLJuTgjS4-q7-7vyYWOAQWeSR2QBIBfCp+8e4GcCNO0GCWt+cc+ubKSez+jeJ8vgiaQgqA50l0hGympuAQ3Wje5eLG1+kCNeD+rOk2Rucar+2GZuQg1YfaFIZaUuzuiep2U+EOi+BOF6C+uWOeJeDGZeF+WuK6lBBu0aeCL+M2DB++TBEALBOAO0ZOzesurePBghs+7q2hE+ZWRBAeJBYhFeYekhKBp2aBdBchhBfB4mPMDgxUyAeIDgdq+BgmGhx6A+4+ChLWmeOK7W+hsmhhUWxhweVmA27GiBa8yBhqlhU2+6GBf+LeXhaU2es+8+-hgy0meOy+AB7ueyzWN2ve16WBc+9MjMhWNWHByRnhyeCO2S3+b29sjREWUBYRsBl+HmNmN+w2jOUeUhseMh6BRCtRSe3BKeehvhIMIAuhM+QR-+F4Wh8xvhmR8O62ORCxKR9RBM6Kb2xRY+hRQh7m5RpglRUAAAYnwLMe4eoeMajnegUk0Yrvkq0bvrnv7qEVTuEXAVfj0RQdEffinOiCYOwLgnIAoOnCYLRKwHYIwOlMLFoMXhCbILgogHABvjzJwEiWgFgLgPgNauQFQKgAABTcgAD05JAQAAegAPxGBcwEkkBjj1isAAB0IABAYAJJwQJJ9YAAlFoAAHzXBknahEAAAWBA7gEkjwCYQY9Y+QjoEQgAZATJghx2AhxBj36yyiTJqpoYAlrVYhAEBQBiC2G9CglP7pz8l0CUlwAAA8mgzp2gss6A0QcAAABuOtadzJ6TwNAF6RyVyf6Z0MLvAKgBAHAGGMVEQAFmAPAH2mYMIOwDABKegCmLkEYLaXIBwPySiZiQQHIPaYcHSXIEAA

**Comment by tmm** [comment]
Remove `args: []` and type inference works. (You don't need to pass `args` if `inputs: []`.)

```diff
import { useContractReads, type Address } from 'wagmi'

const abi = […]
const addresses: Address[] = […]

const { data } = useContractReads({
  contracts: addresses.map(
    (address) =>
      ({
        address,
        abi,
        chainId: 1,
        functionName: 'getReserves',
-       args: [],
      } as const),
  ),
})

data
// ^? const data: ({
//      reserve0: BigNumber;
//      reserve1: BigNumber;
//      blockTimestampLast: number;
//    } & readonly [BigNumber, BigNumber, number])[] | undefined
```

**Comment by matthewlilley** [comment]
@tmm TypeScript required an args array to be passed when preparing contracts config. Maybe the return type is wrong? It's not clear, but it's requiring args to be set...

![Screenshot_115](https://user-images.githubusercontent.com/6063350/201499261-30b7ef0f-e75d-490e-9790-d8e29b10b49e.png)
