### ISSUE TITLE
bug: App forces to connect to a different chain

### ISSUE THREAD

**Issue by 70nyIT** [wagmi-dev/wagmi#1302]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.7.14

### Current Behavior

I have integrated `wagmi` in my React app as follows

```typescript

import {chain, createClient, WagmiConfig} from "wagmi";

const chains = [chain.polygon, chain.goerli, chain.hardhat];
const client = createClient(
  getDefaultClient({
    appName: "app-name",
    autoConnect: false,
    chains
  }),
);

const container = document.getElementById('root');
const root = createRoot(container!);
root.render(
    <Provider store={store}>
      <WagmiConfig client={client}>
        <ConnectKitProvider>
          <StyledEngineProvider injectFirst>
              <CssBaseline />
              <App />
          </StyledEngineProvider>
        </ConnectKitProvider>
      </WagmiConfig>
    </Provider>
);
```

I have then inside `<App/>` a button component that, once clicked, shows the `connectKit` UI to connect a wallet

```typescript
import React from 'react';
import {ConnectKitButton} from "connectkit";

const Web3ModalWrapper: React.FC<IWeb3ModalWrapper> = (props) => {

  return (
      <ConnectKitButton.Custom>
        {({ isConnected, isConnecting, show, hide, address, ensName }) => {
          return (
            <div onClick={props.disabled ? ()=>{} : show}>
              {props.children}
            </div>
          );
        }}
      </ConnectKitButton.Custom>
  );
};
```

I use a wrapper so I can place anything in the body, but beside the layout of `props.children`, the usage is pretty straightforward.

When I open my dApp with my Metamask connected to Goerli, and I click the "connect" button, it works.

If I connect my Metamask to Polygon, refresh the page and try to connect the wallet, Metamask shows a *Switch Network* window, asking me to switch from Polygon to Goerli. If I refuse, the wallet does not connect. If I accept, and then change the network, without refreshing the page, the connection works.

I've tried to search among the knows issues, but nothing has been found. 

### Expected Behavior

When I connect the wallet (using Metamask), as long as I'm connected to a supported chain, I should be able to connect without being forced to switch to Goerli chain.

### Steps To Reproduce

* create a minimum React App
* install wagmi and connectkit
* recreate the above mentioned structure
* Launch the App and connect your wallet (make sure Metamask is connected to Goerli)
* refresh the page, connect Metamask to Polygon, then click the "connect wallet" button in the App

**Comment by jxom** [comment]
Hi! As long as your target chain (goerli) is configured, then wagmi will not prompt you to switch chains. 

This may be a behavior of ConnectKit, so I would recommend to post this issue there! 🙏

**Comment by 70nyIT** [comment]
Thanks for the quick reply @jxom . As for reference, I've opened a Bug on ConnectKit too.
https://github.com/family/connectkit/issues/44
