### ISSUE TITLE
bug: usePrepareContractWrite, Overrides not allowing me to pass in a variable as an argument for value

### ISSUE THREAD

**Issue by m3tamorphTECH** [wagmi-dev/wagmi#1326]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.7.9

### Current Behavior

Attempting to pass a variable as an value override in a function call based off user input. 

`overrides: {
            from: address,
            value: ethers.utils.parseUnits(paymentAmount.toString()),
          },`

paymentAmount is a variable populated when a user selects a payment method in the front end. It is stored as a number. I am trying various methods of converting the number to string, but she aint taking. 

The error is: "index.js?dd68:224 Uncaught Error: invalid decimal value (argument="value", value="", code=INVALID_ARGUMENT, version=bignumber/5.7.0)"

The weird thing, is if I put in a random number as a string as the argument, save, change it back to paymentAmount.toString(), save, and press the button in the front end to call the function- it works properly! But as soon as i refresh the page/disconnect wallet I get this error and I can't continue.

### Expected Behavior

Expect it to accept a <variable>.toString() as an valid argument

**Comment by tmm** [comment]
Thanks for reporting. This issue is temporarily closed due to lack of information. Please provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) and reopen this issue.

**Comment by m3tamorphTECH** [comment]
Was able to get her working. Issue appeared to be that the state(paymentAmount) I was passing as the argument for value was empty. Added the && operator and she took. 

`value: paymentAmount && ethers.utils.parseUnits(paymentAmount.toString())`

Cheers
