### ISSUE TITLE
bug: build with nextjs failed

### ISSUE THREAD

**Issue by callmejm** [wagmi-dev/wagmi#1329]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.8.5

### Current Behavior

there is a related issue https://github.com/wagmi-dev/wagmi/issues/1255 about lower typescript, however I using higher version

run `npm run build` failed
next@12.1.0
wagmi@0.8.5
node version v18.12.1
typescript version 5.0.0-dev.20221117

![image](https://user-images.githubusercontent.com/6957533/202659152-c3dc6fee-17d4-4c14-aec0-e31b35a48e65.png)

**Comment by tmm** [comment]
Thanks for reporting. This issue is temporarily closed due to lack of information. Please provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) and reopen this issue.

**Comment by callmejm** [comment]
@tmm Hi, can you check on https://github.com/callmejm/check_sample , I have uploaded a repo, when `npm run build` having the same issue

**Comment by tmm** [comment]
[`wagmi@>=0.7` requires `typescript@>=4.7.4`](https://wagmi.sh/docs/migration-guide#upgrade-to-typescript474)
