### ISSUE TITLE
bug: The `Address` type is unproductive

### ISSUE THREAD

**Issue by madsbuch** [wagmi-dev/wagmi#1330]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.8.5

### Current Behavior

accounts are typed as `0x${string}`

### Expected Behavior

accounts should be typed as `string`, regular strings.

Most accounts are passed around using regular strings. Therefore, on compile time it cannot be decided if the string starts with "0x".

### Steps To Reproduce

Use the library

### Link to Minimal Reproducible Example (CodeSandbox, StackBlitz, etc.)

account as Address

### Anything else?

It is not a good developer form to use coercion, though I see myself being forced to use `account as Address` more than necessary.

Therefore I suggest changing the Address type to `type Address = string`.

**Comment by tmm** [comment]
I would argue that it is productive — helps guard against accidentally passing in a non-address value. It also makes types more obvious for autocomplete, etc.

That said, you can [configure the underlying address type](https://wagmi.sh/docs/typescript#configuring-internal-types) to use whatever `AddressType` you want:

1. Add `abitype` to `devDependencies`
2. Set `AddressType` to `string`
```ts
declare module 'abitype' {
  export interface Config {
    AddressType: string
  }
}
```

**Comment by madsbuch** [comment]
Both the safety and IDE arguments are contingent on the rest of the code also using these typings, which is very unlikely as it looks into the structure of a string.

Regardless, I appreciate the functionality to alter the types. Very neat!
