### ISSUE TITLE
bug: Error when calling useContractWrite write method with Core Wallet

### ISSUE THREAD

**Issue by elizalucas** [wagmi-dev/wagmi#1334]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.7.15

### Current Behavior

When I connect to Core Wallet using the InjectedConnector, I get the following error when calling `useContractWrite`'s write method: `MetaMask - RPC Error: Resource unavailable. {code: -32002, message: 'Resource unavailable.'`

I am logging the connector before and after calling the write method. Before calling it I can see that the InjectedConnector is connected and ready, but after calling `write` the connected connector is `undefined`. But if I look at the Core Wallet extension it stil displays the wallet as connected.

When I use `InjectedConnector` to connect to metamask this does not happen. 

### Expected Behavior

It should call the `write` method and execute the transaction. 

### Steps To Reproduce

1. Use InjectedConnector to connect to Core Wallet
2. Use useContractWrite hook to get `write` method - using ERC20 transfer method
3. Call `write` while connected to core wallet

**Comment by jxom** [comment]
Thanks! Got a PR here to fix: https://github.com/wagmi-dev/wagmi/pull/1335.

**Comment by elizalucas** [comment]
Thank you @jxom ! This is great. What's the typical timeline for a new release after this fix is merged?

**Comment by jxom** [comment]
Just needs peer review first, then we can merge it in and release! Aiming early this week.

**Comment by jxom** [comment]
Released in `wagmi@0.8.6`.
