### ISSUE TITLE
bug: Docs Update SIWE useNetwork

### ISSUE THREAD

**Issue by codingwithmanny** [wagmi-dev/wagmi#1336]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.85

### Current Behavior

Update Sign-In With Ethereum example docs to reflect new behaviour for `useNetwork`.

https://wagmi.sh/examples/sign-in-with-ethereum#step-3-sign--verify-message

**File:** `./docs/pages/examples/sign-in-with-ethereum.en-US.mdx`

```diff
// ...

const { address } = useAccount()
- const { chain: activeChain } = useNetwork()
+ const { chain } = useNetwork()
const { signMessageAsync } = useSignMessage()

// ...

const signIn = async () => {
  try {
-    const chainId = activeChain?.id
+    const chainId = chain?.id
    if (!address || !chainId) return

// ...
```

**Comment by tmm** [comment]
Linking PR https://github.com/wagmi-dev/wagmi/pull/1337
