### ISSUE TITLE
WAGMI continually attempts to POST to the alchemy RPC endpoint, resulting in tens of 429 errors within seconds

### ISSUE THREAD

**Issue by ibrosen** [wagmi-dev/wagmi#1338]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.5.0

### Current Behavior

After configuring the chains to use the exported `alchemyProvider`, the console and network tabs are littered with tens of failed POST requests to the alchemy endpoint `https://eth-mainnet.alchemyapi.io/v2/_gg7wSSi0KMBsdKnGVfHDueq6xMB9EkC`

![image](https://user-images.githubusercontent.com/24663638/202924075-9146e3d0-5b6e-4300-872d-7fa404a01bb2.png)

![Uploading image.png…]()

### Expected Behavior

Fewer POST requests to this endpoint, possibly an increasing timeout to protect against these 429s.

If this is an issue caused by the user not providing an API key for the alchemyProvider, then wagmi could possibly just reduce the frequency of these POST requests

### Steps To Reproduce

I was able to reproduce in the `/examples/_dev` project in this codebase. Simply run `yarn`, then `yarn dev`, connect a wallet, and open the developer tools.

**Comment by jxom** [comment]
The "littering" of network requests is occurring due to ethers' retry strategy. Please ensure to provide your own API key as the public Alchemy API key is too vulnerable to rate-limiting.
