### ISSUE TITLE
bug: useContractReads failing to infer a simple dynamic return type

### ISSUE THREAD

**Issue by matthewlilley** [wagmi-dev/wagmi#1341]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.6.8

### Current Behavior

https://tsplay.dev/NdrlnW

Unsure if this is a bug, or expected. It's a simple case of a map with 2 potential return types so expected inference would work.

### Link to Minimal Reproducible Example (CodeSandbox, StackBlitz, etc.)

https://tsplay.dev/NdrlnW

**Comment by tmm** [comment]
This is a limitation of TypeScript at the moment. See https://github.com/microsoft/TypeScript/issues/29841

Starting with the following tuple:

```ts
const types = [RewarderType.Primary, RewarderType.Secondary] as const
//    ^? const types: readonly [RewarderType.Primary, RewarderType.Secondary]
```

Then mapping it:

```ts
const { data } = useContractReads({
  contracts: types.map((type, i) => { … })
  // ^? ({ functionName: 'pendingSushi', … } | { functionName: 'pendingTokens', … })[]
)}
```

Results in an array of union type instead of a fixed tuple so inference fails.

**Comment by matthewlilley** [comment]
@tmm in that case, I guess the only option is to cast it. 
e.g.
const _data = data as (BigNumber | { rewardAmounts: BigNumber[] })[]
