### ISSUE TITLE
bug: mock connector defaults to chainId one despite the RPC being for another network

### ISSUE THREAD

**Issue by matthewlilley** [wagmi-dev/wagmi#1343]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.6.8

### Current Behavior

Auto connecting with mock connector seems to default to chainId 1 despite the connected RPC being for 137, this seems to make the auto connect behavior different from the regular connectors.

### Expected Behavior

Mock connector to match behavior of regular connectors, which is to auto connect to the same chain id as the current RPC.

### Steps To Reproduce

Use mock connector with Polygon RPC

**Comment by BastionProvider** [comment]
Also experiencing the same with Aurora with the auto connect feature. The signer ends up defaulting to chainid 1 for some reason.

We use the following config for the Aurora chain for reference:
```
const AURORA_CHAIN: Chain = {
  id: 1313161554,
  name: 'Aurora Mainnet',
  network: 'aurora',
  nativeCurrency: {
    decimals: 18,
    name: 'Ethereum',
    symbol: 'ETH',
  },
  rpcUrls: {
    default: 'https://mainnet.aurora.dev',
  },
  blockExplorers: {
    default: { name: 'Aurorascan', url: 'https://aurorascan.dev/' },
  },

  testnet: false,
}
```
Here's also the config for the connector for reference: 
```
const { chains, provider, webSocketProvider } = configureChains(
  [chain.mainnet, AURORA_CHAIN],
  [
    jsonRpcProvider({
      rpc: (chain) => { return { http: chain.rpcUrls.default }},
    }),
  ]
)
const client = createClient({
  autoConnect: true,
  connectors: [new InjectedConnector({ chains })],
  provider,
  webSocketProvider
})
```

**Comment by BastionProvider** [comment]
This issue seems to be present on 0.8.8 but not on 0.8.4

**Comment by BastionProvider** [comment]
@tmm The issue occurs when you use custom chains like Aurora.

Steps to reproduce:
1. Create a new project using the wagmi-template
2. Add the following chain in the config
```
const AURORA_CHAIN: Chain = {
  id: 1313161554,
  name: 'Aurora Mainnet',
  network: 'aurora',
  nativeCurrency: {
    decimals: 18,
    name: 'Ethereum',
    symbol: 'ETH',
  },
  rpcUrls: {
    default: 'https://mainnet.aurora.dev',
  },
  blockExplorers: {
    default: { name: 'Aurorascan', url: 'https://aurorascan.dev/' },
  },

  testnet: false,
}
```
3. Connect your wallet and console log the signer that you get from useSigner. Make sure it's not connected to Ethereum mainnet, any chain would do.
4. Refresh the page and check the chain the signer is connected to. It would default to chainID 1 instead of the current selected chainID.

Note: The issue is still present in 0.8.10. Would really appreciate some response here.

**Comment by tmm** [comment]
Opened up a PR for this that follows the behavior of other connectors in wagmi.

Could also explore making an `eth_chainId` call to set the `chainId` for `MockConnector`'s underlying provider in the future, but this would deviate from the behavior of other connectors so holding on that for now.
