### ISSUE TITLE
bug: SyntaxError: Unexpected token '?' in NextJS mobile browser

### ISSUE THREAD

**Issue by lucaford** [wagmi-dev/wagmi#1356]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.8.6

### Current Behavior

Un error happens when you try to setup wagmi and use it in an mobile browser with NextJS. 
**SyntaxError: Unexpected token '?'.**

### Expected Behavior

Not throwing an error.

### Steps To Reproduce

You can reproduce it using the example application (`yarn create wagmi`) and opening it in chrome or any browser from a mobile phone.

### Link to Minimal Reproducible Example (CodeSandbox, StackBlitz, etc.)

It can be reproduced using the example application

### Anything else?

Can it be that wagmi is not compatible with mobile browsers and I am missing something?.

Thank you.

**Comment by jxom** [comment]
Seems to work fine for me. 

Would you be able to give more details on your environment (yarn version, what browser, etc), and even be able to upload the repository to GitHub?

Will close until more info is provided.

**Comment by lucaford** [comment]
@jxom It happened in my main project but I tried with the example project and got the same error. Desktop works fine.
I also created a vanilla NextJS project and setup wagmi configurations till I end up with an error.
https://github.com/lucaford/wagmi-test

I am using Android, Chrome version 77.0, yarn 1.22.

**Comment by AlwaysBuyCheap** [comment]
Hi, I get a similar error when running build with next.js. Here is the error code:
`Failed to compile.

./node_modules/@wagmi/core/dist/contracts-3c4d70a1.d.ts:144:91
Type error: '?' expected.

  142 | declare type GetArgs<TAbi extends Abi | readonly unknown[], TFunction extends AbiFunction & {
  143 |     type: 'function';
> 144 | }, TOptions extends Options = DefaultOptions> = TFunction['inputs'] extends infer TInputs extends readonly AbiParameter[] ? Or<IsNever<TInputs>, NotEqual<TAbi, Abi>> extends true ? {
      |                                                                                           ^
  145 |     /**
  146 |      * Arguments to pass contract method
  147 |      *`

**Comment by tmm** [comment]
@AlwaysBuyCheap This is a different error. What version of TypeScript are you using? You must use [4.7.4 or above](https://wagmi.sh/react/typescript).

**Comment by jxom** [comment]
Just coming back to this one again. Seems that you are using Chrome 77 in the screenshot above, which doesn't support (or minimal) ES2021. Currently, wagmi only supports the following suite of browsers/versions:

- Chrome 85+ (August 25, 2020)
- Edge 85+ (August 25, 2020)
- Firefox 79+ (July 28, 2020)
- Opera 71+ (September 15, 2020**)**
- Safari 14.1+ (April 26, 2021)
