### ISSUE TITLE
bug: useWaitForTransaction is not triggering any events when user speeds up the transaction on Metamask

### ISSUE THREAD

**Issue by IProdev211** [wagmi-dev/wagmi#1359]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

^0.8.6

### Current Behavior

If a user speeds up the transaction on metamask, onSuccess is not triggered even the txn is finished successfully.
In normal case, onSuccess is triggered as expected.

**Comment by tmm** [comment]
[EIP-2831](https://eips.ethereum.org/EIPS/eip-2831) is not currently supported. See https://github.com/wagmi-dev/wagmi/discussions/799

**Comment by tmm** [comment]
This will be released in https://github.com/wagmi-dev/wagmi/pull/1344
