### ISSUE TITLE
provider.getBalance is not a function

### ISSUE THREAD

**Issue by MichaelOdumosu57** [wagmi-dev/wagmi#1360]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

    "@wagmi/core": "^0.7.5",

### Current Behavior

when I provide the address to the fetchBalance promise and resolve it it rejects saing provider.getBalance is not a function, 

### Expected Behavior

I should get the API call as listed in the docs

### Steps To Reproduce

import { fetchBalance } from '@wagmi/core'

fetchBalance({
              address:
"0xe8eBBA988763A40d132A5C23aB7A35Ddaa5BbA2f"
            }).then(console.log).catch(console.error)

### Anything else?

![image](https://user-images.githubusercontent.com/21322737/203998290-326d25de-da4d-4f1b-8bc9-a31f6c41b43e.png)

**Comment by tmm** [comment]
Thanks for reporting. This issue is temporarily closed due to lack of information. Please provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) and reopen this issue.
