### ISSUE TITLE
bug: useWaitForTransaction stuck on isLoading/isFetching

### ISSUE THREAD

**Issue by danilo-89** [wagmi-dev/wagmi#1362]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.8.6

### Current Behavior

When running useContractWrite, editing priority in Metamask extension, and then canceling transaction, useWaitForTransaction gets stuck on "isLoading" and "isFetching" states after transaction is canceled.
(Video reproduction bellow)

### Expected Behavior

Transaction error should be shown when transaction is canceled.

### Steps To Reproduce

1. Log in metamask
2. Press "Execute Write" button
3. In metamask extension window "Edit" transaction, set it to "Low" and press "Save"
4. Confirm transaction
5. Quickly open metamask and cancel that transaction
6. Wait for transaction to be canceled

### Link to Minimal Reproducible Example (CodeSandbox, StackBlitz, etc.)

https://stackblitz.com/edit/nextjs-evccka

### Anything else?

Video: https://watch.screencastify.com/v/LDLPCv4JdXJZrybKP4nY

**Comment by jxom** [comment]
This has been fixed in `0.9.x`! :)
