### ISSUE TITLE
bug: Hang while trying to connect using WalletConnect

### ISSUE THREAD

**Issue by jjduhamel** [wagmi-dev/wagmi#1367]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

@wagmi/core 0.7.5

### Current Behavior

The await at [this line](https://github.com/wagmi-dev/wagmi/blob/main/packages/core/src/connectors/walletConnect.ts#L62) never returns.  I tried digging into why it might be hanging but I can't figure it out.  I found a few other places where the documentation was out of date so I'm not sure if there were some recent breaking changes.  Here is what my code looks like:

```
  const { chains, provider, webSocketProvider } = configureChains(
    [ chain.mainnet, chain.localhost ],
    [ publicProvider() ]
  );

  const client = createClient({
    provider,
    webSocketProvider
  });

 async function connectWalletConnect() {
    const walletconnect = new WalletConnectConnector({
      chains,
      options: {
        qrcode: false,
        rpc: {
          1: 'https://eth-mainnet.g.alchemy.com/v2/<api-key>',
          80001: 'https://polygon-mumbai.g.alchemy.com/v2/<api-key>'
        },
        client: {
          projectId: <client-id>
        }
      }
    });

    await connect({                            <<<< Hangs here
      chainId: 1,
      connector: walletconnect
    });
 }
```

### Expected Behavior

I should get a 'signer_uri' event or something.  The docs don't really say what should happen.

### Anything else?

You have to pass the chainId to `connect` or it will throw an error, which isn't covered in the documentation.  The documentation for both Wagmi and WalletConnect 2.0 is very sparse and needs some attention.

**Comment by tmm** [comment]
The reason the call never returns is because of `qrcode: false`. When `qrcode` is `false`, you need to provide your own interface for connecting to the WalletConnect session, like a QR code. If you switch `qrcode` to `true`, it displays the default WalletConnect modal, allowing you to connect to the session.
