### ISSUE TITLE
bug: Incorrect return format "useContractRead"

### ISSUE THREAD

**Issue by TwistedMinda** [wagmi-dev/wagmi#1373]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.8.6

### Current Behavior

Hi,
when trying to get read from a contract using "useContractRead", I get this type of result:

<img width="465" alt="Screenshot 2022-11-27 at 23 10 15" src="https://user-images.githubusercontent.com/11213609/204162302-634612ab-0f0b-4ca3-b223-64e5e549b492.png">

How do you parse such a thing?

### Expected Behavior

I should have a normal array like so,

`[ { betsCount: 1, maxBet: 1, name: "Team 1", dieResult: 0} ]`

(simple array of objects)

### Steps To Reproduce

Make a solidity smart contract with one function that returns an array

### Link to Minimal Reproducible Example (CodeSandbox, StackBlitz, etc.)

https://codesandbox.io/s/epic-rgb-72gyx7?file=/src/App.js

**Comment by jxom** [comment]
This is because contract functions in [Ethers](https://docs.ethers.io/v5/) return a [hybrid object/array type](https://github.com/ethers-io/ethers.js/blob/master/packages/abi/src.ts/coders/abstract-coder.ts#L11-L13). 

You should still be able to access values by named key still though (e.g. `teams[0].name`, `teams[1].betsCount`, etc).

**Comment by tmm** [comment]
Expanding on what Jake said, if you use TypeScript and convert the ABI to a const assertion, you can get the return type inferred automatically. More info [here](https://wagmi.sh/react/typescript#type-inference).

**Comment by TwistedMinda** [comment]
@tmm Thanks, incredible <3

@jxom Thanks! Good to know

But why are the "BigNumber" not automatically casted to "number" for me ?
Seems to be kind of a hustle to always have to map the numbers yourself like so : 
```
results.map((item: Team) => ({
  dieResult: Number(item.dieResult),
  maxBets: Number(item.maxBets),
  betsCount: Number(item.betsCount),
  name: item.name,
}))
```

With web3-react it is done internally.
Thanks again!
