### ISSUE TITLE
bug: MetaMask `connector.ready` evaluates to false in Chrome if you have coinbase wallet or core wallet installed

### ISSUE THREAD

**Issue by elizalucas** [wagmi-dev/wagmi#1390]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.7.15

### Current Behavior

The MetaMask `connector.ready` is evaluating to false in Chrome when coinbase wallet or core wallet is installed in the browser. The same issue is happening on mobile, where if you have those applications downloaded on your phone it will also evaluate to false, but once you delete them it evaluates to true. 

Is this the expected behavior that you cannot have other EVM wallets installed on your browser / mobile device and use the MetaMask connector?

### Expected Behavior

MetaMask `connector.ready` should evaluate to true

### Steps To Reproduce

On Chrome: Install metamask extension and core wallet or coinbase extension

On mobile: Install metamask application and core wallet or coinbase application

**Comment by jxom** [comment]
Does my [reply here](https://github.com/wagmi-dev/wagmi/issues/1134#issuecomment-1319371024) make sense to why this is happening for desktop? 

Note: the `MetaMaskConnector` inherits the `InjectedConnector`, which is only available on browsers that support `window.ethereum` (ie. desktop browsers), so it's expected that `connector.ready` is falsy on mobile browsers (no injected `window.ethereum`). Maybe the naming "InjectedMetaMaskConnector" would make more sense here.

**Comment by elizalucas** [comment]
> Does my [reply here](https://github.com/wagmi-dev/wagmi/issues/1134#issuecomment-1319371024) make sense to why this is happening for desktop?
> 
> Note: the `MetaMaskConnector` inherits the `InjectedConnector`, which is only available on browsers that support `window.ethereum` (ie. desktop browsers), so it's expected that `connector.ready` is falsy on mobile browsers (no injected `window.ethereum`). Maybe the naming "InjectedMetaMaskConnector" would make more sense here.

The reply makes sense, but just to confirm the behavior so I can plan how to handle it - the user an ONLY have metamask installed (not any other wallets that inject into `window.ethereum` for the metamask connector to work?

**Comment by jxom** [comment]
Yep, that's pretty much right. Unfortunately it is a drawback of the `window.ethereum` model at the moment.

**Comment by tmm** [comment]
Adding a bit of extra context: `MetaMaskConnector` attempts to work when other wallets are installed, but sometimes falls short due to `window.ethereum` and [other wallets trying to make themselves look like MetaMask](https://github.com/wagmi-dev/wagmi/blob/main/packages/core/src/connectors/metaMask.ts#L128-L133) (e.g. `window.ethereum.isMetaMask = true`).

**Comment by elizalucas** [comment]
Got it, thanks both for your clarification!
