### ISSUE TITLE
bug: Not to compare address strings with the 'address' returned by useAccount

### ISSUE THREAD

**Issue by McCoady** [wagmi-dev/wagmi#1441]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.8.10

### Current Behavior

I'm trying to iterate over an array of addresses to see if the connected address matches any of them. Simplified code:

```
const addresses = [
   ["0x{address}", int], [etc,etc]
]

const {address, isConnected } = useAccount()
const ownedTokens = addresses.find(el => el[0] === address)
```
The above always returns undefined, however if you switch `address` for a string '0x{address}' it works find.
console.log(address) and console.log(typeof address) both return the correct value & 'string' so I'm unsure what's causing the issue.

### Expected Behavior

"0x{address]" === address

### Steps To Reproduce

const addresses = [
    ["0x{address", integer],
    [etc,etc]
    ]
const { address, isConnected } = useAccount()

 const ownedTokens = addresses.find(el => el[0] === address)

**Comment by tmm** [comment]
You might need to make sure addresses in `addresses` are checksummed (can use `ethers.utils.getAddress` for this). Beyond that I'm not exactly sure what the goal is here. Can you attach a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) and re-open this issue?
