### ISSUE TITLE
Documentation for watchContractEvent is wrong?

### ISSUE THREAD

**Issue by cilphex** [wagmi-dev/wagmi#1453]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.9.0

### Current Behavior

In the [docs](https://wagmi.sh/core/actions/watchContractEvent), there is an example for `watchContractEvent`.

In this example, `watchContractEvent` is being passed 1 parameter which is an object with 4 properties:

```solidity
import { watchContractEvent } from '@wagmi/core'
 
const unwatch = watchContractEvent({
  address: '0x00000000000C2E074eC69A0dFb2997BA6C7d2e1e',
  abi: ensRegistryABI,
  eventName: 'NewOwner',
  listener(node, label, owner) {
    console.log(node, label, owner)
  },
})
```

### Expected Behavior

When I try this format in the actual code, my IDE (webstorm) gives a warning that the call is using an invalid number of arguments. It should be 2:

<img width="801" alt="Screenshot 2022-12-11 at 3 44 40 AM" src="https://user-images.githubusercontent.com/611803/206896923-33704d61-1691-40ce-94f5-4d4cc4144cf4.png">

The callback being a separate, final argument would seem to match other code patterns in the `wagmi/core` library. Is the documentation wrong?

### Steps To Reproduce

Try writing `watchContractEvent` with 1 argument rather than 2.

**Comment by jxom** [comment]
@justingreenberg is right – docs were wrong. Thanks for the call out!
