### ISSUE TITLE
bug: Chain not found in WAGMI

### ISSUE THREAD

**Issue by alexiskattan** [wagmi-dev/wagmi#1462]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.9.2

### Current Behavior

Error: after install and try and run

```
import { useProvider, chain as wagmiChains } from "wagmi";
                      ^^^^^
SyntaxError: The requested module 'wagmi' does not provide an export named 'chain'```

### Expected Behavior

Should run 

### Steps To Reproduce

"wagmi": "^0.9.2"
"ethers": "^5.7.1",


### Link to Minimal Reproducible Example (CodeSandbox, StackBlitz, etc.)

_No response_

### Anything else?

_No response_

**Comment by jxom** [comment]
`0.9.x` no longer exports `chain`. Read [here](https://wagmi.sh/react/migration-guide#chain-exports) for a migration guide. 😊
