### ISSUE TITLE
bug: Block Explorers route is broken but still appears on searching

### ISSUE THREAD

**Issue by ernestognw** [wagmi-dev/wagmi#1465]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

latest

### Current Behavior

When going to the [block-explorers](https://wagmi.sh/react/constants/block-explorers) docs, the link appears broken although I arrived via search.

<img width="632" alt="Captura de Pantalla 2022-12-12 a la(s) 12 38 08" src="https://user-images.githubusercontent.com/33379285/207115001-78119099-dca4-4145-bcc9-092647ed8aac.png">

### Expected Behavior

Not really sure what should we expect here. But I think the docs should either not show search results, or enable the page.

### Steps To Reproduce

Just go to the react [docs](https://wagmi.sh/react/getting-started) and try to search for _block explorer_. Enter to any of the results

**Comment by tmm** [comment]
Thanks for reporting! The search index is cached. This should resolve shortly.

**Comment by ernestognw** [comment]
Gotcha @tmm, feel free to close whenever it's solved 👍
