### ISSUE TITLE
Bug: provider after disconnect

### ISSUE THREAD

**Issue by essserrr** [wagmi-dev/wagmi#1477]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.9.2

### Current Behavior

Initials:
You have a connector (Metamask) with multiple supported chains (Mainnet, Goerli)
Chains are written like [Mainnet, Goerli]
You are connected to Metamask via useConnect().connect()
Active chain is Goerli

1. When you disconnect connector with useDiconnect().disconnect(), you are switched to the first chain in the list above (Mainnet). At this time library doesn't have connector and chain (they both are undefined), so it should generate JsonRPCProvider for the first chain in the list. Istead it generates Web3Provider Metamask provider for the first chain in the list. In this state it is impossible to reconnect connector, provider itself is also no use.
![image](https://user-images.githubusercontent.com/21965602/207272843-035bdd9e-53c7-4b02-baef-a3d03548850e.png)
2. If you do the same steps while being connected to mainnet, you will be switched to JsonRPC as it should be done

### Expected Behavior

1. Library should always generate JsonRPCProvider if there is no connector/connector was disconnected

### Steps To Reproduce

````
const { chains, provider, webSocketProvider } = configureChains(
  [mainnet, goerli],
  [publicProvider()],
);

const metaMask = new MetaMaskConnector({
  chains,
});

const client = createClient({
  autoConnect: true,
  provider,
  connectors: [metaMask],
});

render(
  <React.StrictMode>
            <WagmiConfig client={client}>
                     <App />
             </WagmiConfig>
  </React.StrictMode>,
  document.getElementById("root"),
);

function App(): React.ReactElement {
  const { connect } = useConnect();
  const { disconnect } = useDisconnect();
  const provider = useProvider();
  const { data: signer } = useSigner();
  const { connector } = useAccount();

  const { chain } = useNetwork();
  const { id: chainId } = chain || {};

  useEffect(() => {
    console.log("PROVIDER", provider);
  }, [provider]);
  useEffect(() => {
    console.log("SIGNER", signer);
  }, [signer]);
  useEffect(() => {
    console.log("CONNECTOR", connector);
  }, [connector]);
  useEffect(() => {
    console.log("CHAIN", chainId);
  }, [chainId]);

  return (
    <button onClick={() => connect({ connector: metaMask, chainId: goerli.id })}>CONNECT</ button>
    <button onClick={() => disconnect ()}>DISCONNECT</ button>
  );
}
````

**Comment by tmm** [comment]
Thanks for reporting. This issue is temporarily closed due to lack of information. Please provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) and reopen this issue.

Based on the incomplete code in "Steps to Reproduce" above, make sure `createClient` is either memoized or not run inside component body.
