### ISSUE TITLE
Bug: signer after disconnect

### ISSUE THREAD

**Issue by essserrr** [wagmi-dev/wagmi#1487]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.9.2

### Current Behavior

Initials:
You have a connector (Metamask) with multiple supported chains (Mainnet, Goerli)
Chains are written like [Mainnet, Goerli]
You are connected to Metamask via useConnect().connect()

1. Active chain is Goerli. When you disconnect connector with useDiconnect().disconnect(), you are switched to the first chain in the list above (Mainnet). At this time library doesn't have connector and chain (they both are undefined), but for some reason signer is nut nullified in this case

2. Active chain is Mainnet. If you do the same steps while being connected to mainnet, signer will be nullified properly

### Expected Behavior

1. The problem lies in the order of chains inside the chain list. Library should nullify signer on disconnect no matter if the previous chain has index 0 or not.

### Steps To Reproduce

1. Connect Goerli -> disconnect -> connector, chain === undefined, signer =/= null
![image](https://user-images.githubusercontent.com/21965602/207520511-5ac8564b-4f6d-4b9f-aa84-e81799e26966.png)
https://codesandbox.io/s/wagmi-disconnect-unproperly-023t2q

2. Connect Mainnet -> disconnect -> connector, chain === undefined, signer === null
![image](https://user-images.githubusercontent.com/21965602/207520600-2e5fdde4-4b66-467e-880c-5292755435e5.png)
https://codesandbox.io/s/wagmi-disconnect-properly-bim8vw

### Link to Minimal Reproducible Example (CodeSandbox, StackBlitz, etc.)

1. https://codesandbox.io/s/wagmi-disconnect-unproperly-023t2q
2. https://codesandbox.io/s/wagmi-disconnect-properly-bim8vw

### Anything else?

previous #1477

**Comment by jxom** [comment]
#1447 (unreleased) may have fixed this – will check tomorrow.

**Comment by jxom** [comment]
Can confirm, #1447 fixes this. Should be released soonish.

**Comment by jxom** [comment]
Fixed on `0.10.0`!
