### ISSUE TITLE
bug: Integration Binance Wallet Extension

### ISSUE THREAD

**Issue by Droppix** [wagmi-dev/wagmi#1498]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.8.2

### Current Behavior

I try to add Binance Wallet Extension to Web3Modal, I would have liked to avoid making a "custom-connector", which the Web3Modal team advised me. Is it possible to simplify on your side?

[(https://github.com/WalletConnect/web3modal/issues/771)]

**Comment by tmm** [comment]
You don't need a custom Connector. You can use the [`getProvider`](https://wagmi.sh/react/connectors/injected#getprovider) option:

```ts
import { InjectedConnector } from 'wagmi/connectors'

const connector = new InjectedConnector({
 options: {
 name: 'Binance Wallet',
 getProvider: () =>
   typeof window !== 'undefined' ? window.BinanceChain : undefined,
 },
})

```

**Comment by jeftarmascarenhas** [comment]
See the complete example for you implement Binance Wallet Connector:
https://gist.github.com/jeftarmascarenhas/3214feb7c6871253cf9486fd8ccacc40

**Comment by jeftarmascarenhas** [comment]
> You don't need a custom Connector. You can use the [`getProvider`](https://wagmi.sh/react/connectors/injected#getprovider) option:
> 
> ```ts
> import { InjectedConnector } from 'wagmi/connectors'
> 
> const connector = new InjectedConnector({
>  options: {
>  name: 'Binance Wallet',
>  getProvider: () =>
>    typeof window !== 'undefined' ? window.BinanceChain : undefined,
>  },
> })
> ```

add return in `getProvider`
```js
export const BinanceSmallConnector = new InjectedConnector({
  options: {
    name: "Binance",
    getProvider: () => {
      return typeof window !== "undefined" ? window.BinanceChain : undefined;
    },
  },
});
``
