### ISSUE TITLE
bug: Error thrown when user rejects request is not type UserRejectedRequestError

### ISSUE THREAD

**Issue by aalmada** [wagmi-dev/wagmi#1499]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.7.9

### Current Behavior

When using `useSignMessage()` and the user clicks on the _cancel_ button, the error thrown is not of type `UserRejectedRequestError`. 

### Expected Behavior

Expect to get an error of type `UserRejectedRequestError`.

### Steps To Reproduce

Executing the code:

```typescript
const { signMessageAsync } = useSignMessage();

let signature: string;
try {
  signature = await signMessageAsync({ message});
} catch (error) {
  console.log(error instanceof UserRejectedRequestError);
  console.log(error instanceof ProviderRpcError);
  console.log(isErrorWithCode(error));
  console.log(isErrorWithMessage(error));
  console.log(getErrorMessage(error));
}
```

I get the following when I click on the cancel button:

```
false
false
false
true
user rejected signing (action="signMessage", from="n0x2756f6D40ED4E4df0003CAE", messageData="localhost:3000 wants you to sign in with your Ethereum account:\n0x2756f6D40ED4E4df0003CAE\n\nSign in with Ethereum to the app.\n\nURI: http://localhost:3000\nVersion: 1\nChain ID: 5\nNonce: JIzUBnI6Cee1aUsXT\nIssued At: 2022-12-15T16:23:35.809Z", code=ACTION_REJECTED, version=providers/5.7.2)
```

It seems the error is not `UserRejectedRequestError` neither `ProviderRpcError`. It's a simple `Error` with a `message` property.

I used the following methods:

``` typescript
// eslint-disable-next-line @typescript-eslint/no-explicit-any
export const isErrorWithMessage = (error: any): error is { message: string } =>
	typeof error === "object" &&
	error !== null &&
	typeof error.message === "string";

// eslint-disable-next-line @typescript-eslint/no-explicit-any
export const isErrorWithCode = (error: any): error is { code: number } =>
	typeof error === "object" &&
	error !== null &&
	typeof error.code === "number";

export const getErrorMessage = (error: unknown): string | undefined => {
	if (isErrorWithMessage(error)) return error.message;
	return typeof error === "string" ? error : undefined;
};
```

### Anything else?

Tested using MetaMask 10.22.2 browser extension.

**Comment by tmm** [comment]
Unfortunately [`ethers@5.7.0`](https://github.com/ethers-io/ethers.js/commit/d9897e0fdb5f9ca34822929c95a478634cc2a460) started wrapping RPC errors with a custom error so that's why it's not bubbling up the same way. Can look into a workaround for this.

**Comment by aalmada** [comment]
Thank you @tmm for all the great work!
