### ISSUE TITLE
bug: sometimes can't connect/signMessage successfully for mobile app

### ISSUE THREAD

**Issue by SunnyCheung-cp** [wagmi-dev/wagmi#1513]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.9.3

### Current Behavior

I used https://wagmi.sh/examples/sign-message to build a mobile app page and tried connect and signMessage，
Unable to connect successfully and unable to sign successfully appeared, for this I added two videos

1. can be seen from the no-connect-video that after connecting metamask, the modal is not closed, and it is not connected

2. can be seen from no-signmessage-video, the connection can be successful, but the signature is always loading

https://user-images.githubusercontent.com/105030733/208060555-0b934928-bc1c-4c97-8944-2b44211d7901.MP4

https://user-images.githubusercontent.com/105030733/208060568-40c5be68-f674-40e3-9dd1-cc5e13060fe3.MP4

### Expected Behavior

1. Fix the problem that the connection cannot be successful in some time
2. Fix the problem of not being able to sign

### Steps To Reproduce

Use capacitor to build a mobile app, modify capacitor.config server to https://wagmi.sh/examples/sign-message

### Link to Minimal Reproducible Example (CodeSandbox, StackBlitz, etc.)

https://wagmi.sh/examples/sign-message

**Comment by tmm** [comment]
Works fine for me. My guess is it's related to WalletConnect connection issues.

https://user-images.githubusercontent.com/6759464/208156964-3b92e86f-8660-4d42-bb3e-ef6cafa43c5f.MP4

https://user-images.githubusercontent.com/6759464/208157275-65ee7ff0-19bd-4919-9917-371eef270f55.MP4

**Comment by SunnyCheung-cp** [comment]
@tmm  Because you are trying mobile browser, not mobile app

**Comment by tmm** [comment]
Not sure I understand what you are trying to say? Looks like both videos have wagmi.sh loaded up in a mobile browser and then switch to a mobile wallet app.

**Comment by SunnyCheung-cp** [comment]
@tmm  Yes, the difference is that you opened it through the mobile browser, I opened it through the build app, not the browser
