### ISSUE TITLE
bug: write loading on ios mobile Metamask always true if reject transaction

### ISSUE THREAD

**Issue by 0xuhe** [wagmi-dev/wagmi#1519]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.9.4

### Current Behavior

If I reject a transaction on ios Metamask, the status of write hook is always true, so the write button is always disabled.
It works fine on PC chrome. But on IOS Metamask, it fails

demo: https://sgt-farm-5v1k.vercel.app
steps to reproduce bug: On IOS mobile Metamask, click the Approve button, then reject on Metamask, the Approve Button is still loading, but it could reset on PC chrome. 

wagmi version: 0.9.4 
IOS Metamask version: 5.12.0

Code sample

```typescript
  const { config: approveArg } = usePrepareContractWrite({
    address: lpAddress as Address,
    abi: erc20ABI,
    functionName: "approve",
    args: [address as Address, parseEther("9999999999999999999999999999999")],
  });
  const {
    isLoading: approving,
    write: approve,
  } = useContractWrite(approveArg);
```

```typescript
<Button
            w="full"
            h={14}
            bg="orange.300"
            colorScheme={"orange"}
            isLoading={approving}
            onClick={() => {
              approve?.();
            }}
          >
            Approve
</Button>
```

**Comment by jxom** [comment]
I can't seem to reproduce this. Can you please provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) via a CodeSandbox (feel free to use [this template](https://codesandbox.io/s/bitter-wind-pv0hwj))? Will reopen once done.
