### ISSUE TITLE
bug: usePrepareContractWrite still runs with enabled: false

### ISSUE THREAD

**Issue by emmajane1313** [wagmi-dev/wagmi#1526]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

^0.8.5

### Current Behavior

The usePrepareContractWrite runs on component load even with setting `enabled: false` or `Boolean(enabled)`  where enabled = `const [enabled, setEnabled] = useState<boolean>(false);`

### Expected Behavior

usePrepareContractWrite should not prepare config/data until enabled is evoked to true.

**Comment by tmm** [comment]
Thanks for reporting. This issue is temporarily closed due to lack of information. Please provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) and reopen this issue.

Note: Data might be cached from a previous response so `usePrepareContractWrite` is returning that. Check out [`cacheTime`](https://wagmi.sh/react/prepare-hooks/usePrepareContractWrite#cachetime-optional) for more info.

**Comment by ppasta90** [comment]
Hi @emmajane1313 , I have exactly the same problem. Tried with the "enabled" state and with "cacheTime" but the problem persists. Have you figured it out eventually?

**Comment by emmajane1313** [comment]
hey, yes, it depends on how you are setting enabled, here is a code snippet that can hopefully help. Its best to set the enabled as a boolean for when the args exist, when i structure the code like this it works

```
const collectPost = async (): Promise<void> => {
    try {
      const collectPost = await collect({
        publicationId: pubId,
      });
      const typedData: any = collectPost.data.createCollectTypedData.typedData;
      const signature: any = await signTypedDataAsync({
        domain: omit(typedData?.domain, ["__typename"]),
        types: omit(typedData?.types, ["__typename"]) as any,
        value: omit(typedData?.value, ["__typename"]) as any,
      });
      
        const { v, r, s } = splitSignature(signature);
        const collectArgs = {
          collector: address,
          profileId: typedData.value.profileId,
          pubId: typedData.value.pubId,
          data: typedData.value.data,
          sig: {
            v,
            r,
            s,
            deadline: typedData.value.deadline,
          },
        };
        setCollectArgs(collectArgs);
      
    } catch (err: any) {
      console.error(err.message);
    }
  };

const { config } = usePrepareContractWrite({
    address: LENS_HUB_PROXY_ADDRESS_MUMBAI,
    abi: LensHubProxy,
    functionName: "collectWithSig",
    enabled: Boolean(collectArgs),
    args: [collectArgs],
  });

  const { writeAsync } = useContractWrite(config);
```

lmk if it doesnt work etc.

**Comment by vinerz** [comment]
This issue persists even if setting `enabled` to a hardcoded `false`. The request is dispatched no matter this flag is set to.

**Comment by Melancholism** [comment]
I can confirm the issue still persists. I tried setting the `cacheTime` to `0` and hard-coding the `enabled` flag to `false` but the query is enabled!

**Comment by tmm** [comment]
How have you confirmed the query is still enabled? Are you sure it is not cached data? If you believe an issue still exists, feel free to open a new issue with a minimal reproduction.
