### ISSUE TITLE
bug: trust wallet

### ISSUE THREAD

**Issue by essserrr** [wagmi-dev/wagmi#1532]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.9.2

### Current Behavior

I'am getting a error, when trying to connect Trust Wallet as injected provider.

### Expected Behavior

Trust Wallet injected provider should be connected without any errors
Or at least show account address and chain without any errors (as web3-react does)

### Steps To Reproduce

1. Install Trust Wallet extension https://trustwallet.com/download/
2. Go to https://wagmi.sh/examples/connect-wallet
3. Click Injected
![image](https://user-images.githubusercontent.com/21965602/208604045-931f5c82-e42e-4ee9-8345-dc8e93269055.png)

And another error
1. Install both Metamask and Trust Wallet
2. Go to trust wallet settings, click "Set As Default Wallet"
3. Click Injected, get error
4. Click Metamask, get connector error on metamask
![image](https://user-images.githubusercontent.com/21965602/208606550-3a2920d9-454d-4195-900a-2a275a5552e6.png)

### Link to Minimal Reproducible Example (CodeSandbox, StackBlitz, etc.)

https://wagmi.sh/examples/connect-wallet

**Comment by jxom** [comment]
Looks like the Trust Wallet browser extensions doesn't support `eth_chainId`, which isn't ideal. 😅

**Comment by jxom** [comment]
Seems to be working for me now. Can you confirm?
