### ISSUE TITLE
bug: awaiting switchNetwork before sendTransaction throws error

### ISSUE THREAD

**Issue by jmrossy** [wagmi-dev/wagmi#1565]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.9.5

### Current Behavior

The `@wagmi/core` `switchNetwork` function does successfully switch the network for most wallets, but subsequent calls to `sendTransaction` will still throw a `ChainMismatchError` even after the switch.

I guess there's stale data affecting `sendTransaction`.

### Expected Behavior

`SendTransaction` calls after awaiting `switchNetwork` succeed.

### Steps To Reproduce

```js
await switchNetwork({ chainId: 1 });
await sendTransaction({
    chainId: 1,
    request: myTxRequest,
    mode: 'recklesslyUnprepared',
});
```

**Comment by jmrossy** [comment]
Note, a workaround of `await sleep(1000);` to stall for a second or two seems to solve the issue, implying there's some kind of race condition involved.

**Comment by Nazeeh21** [comment]
Can I work on this issue?

**Comment by legendarykamal** [comment]
Hi , can I also contribute in solving this problem ?

**Comment by jxom** [comment]
PRs are welcome! Otherwise, I can pick this up when I get some spare time. Just reply to this thread so others know you are working on it.

**Comment by Nazeeh21** [comment]
Cool, I'll start working on it soon

**Comment by Nazeeh21** [comment]
> PRs are welcome! Otherwise, I can pick this up when I get some spare time. Just reply to this thread so others know you are working on it & so I can assign you to the issue.

I'd like to work on this, can you please assign it to me?

**Comment by DanInTheD4rk** [comment]
I'll take a crack at this if no one is working it

**Comment by tmm** [comment]
@DanInTheD4rk sweet! will assign it to you.

**Comment by jxom** [comment]
Fixed on latest `wagmi` & `@wagmi/core` versions! Thanks @DanInTheD4rk.
