### ISSUE TITLE
bug: "errorMessage":"Client network socket disconnected before secure TLS connection was established","code":"ECONNRESET"

### ISSUE THREAD

**Issue by nfts2me** [wagmi-dev/wagmi#1579]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.8.7

### Current Behavior

Since I updated from wagmi 0.7.x, I'm getting these errors (Error 500) even when loading parts of the website which doesn't use Wagmi at all, like api calls:

<img width="1260" alt="image" src="https://user-images.githubusercontent.com/109629895/209776445-dca0ae2c-c562-4006-ab65-bb241179f1dc.png">

```
2022-12-28T07:12:25.389Z	c8f501b6-f0d0-4abc-82d9-e3c61677baa3	ERROR	Uncaught Exception 	{"errorType":"Error","errorMessage":"Client network socket disconnected before secure TLS connection was established","code":"ECONNRESET","host":"eth-mainnet.ws.alchemyapi.io","port":443,"stack":["Error: Client network socket disconnected before secure TLS connection was established","    at connResetException (node:internal/errors:692:14)","    at TLSSocket.onConnectEnd (node:_tls_wrap:1587:19)","    at TLSSocket.emit (node:events:539:35)","    at endReadableNT (node:internal/streams/readable:1345:12)","    at processTicksAndRejections (node:internal/process/task_queues:83:21)"]}
Unknown application error occurred
Runtime.Unknown
```

I'm not sure about the root of the problem.
It seems that the server is connecting to the providers, and after a while the connections resets and affects to other page calls, which may be a node error.

However... it started happening after the Wagmi update and all of the errors include the alchemyapi endpoint.

Shouldn't wagmi avoid server calls to providers at all?
 

### Expected Behavior

Not crash.

### Steps To Reproduce

It is very randomly. 
Sometimes, it just gets the "Error 500", and a second call doesn't crash.

**Comment by jxom** [comment]
> Shouldn't wagmi avoid server calls to providers at all?

wagmi needs to utilize HTTP/WS (whether it be directly, or via a wallet) in order to interact with Ethereum.

Can you please provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) via a CodeSandbox (feel free to use [this template](https://codesandbox.io/s/bitter-wind-pv0hwj))?

**Comment by nfts2me** [comment]
> > Shouldn't wagmi avoid server calls to providers at all?
> 
> wagmi needs to utilize HTTP/WS (whether it be directly, or via a wallet) in order to interact with Ethereum.
> 
> Can you please provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) via a CodeSandbox (feel free to use [this template](https://codesandbox.io/s/bitter-wind-pv0hwj))? Will reopen when done!

There should be at least a way to forbid connecting on the server side.
When hydrating, the server connects to the provider and it raises these errors.

Is there a way to disable connections on the server side?

**Comment by yfs-2000** [comment]
> > Shouldn't wagmi avoid server calls to providers at all?
> 
> wagmi needs to utilize HTTP/WS (whether it be directly, or via a wallet) in order to interact with Ethereum.
> 
> Can you please provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) via a CodeSandbox (feel free to use [this template](https://codesandbox.io/s/bitter-wind-pv0hwj))? Will reopen when done!
This problem occurs with nextjs

**Comment by yfs-2000** [comment]
> > Shouldn't wagmi avoid server calls to providers at all?
> 
> wagmi needs to utilize HTTP/WS (whether it be directly, or via a wallet) in order to interact with Ethereum.
> 
> Can you please provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) via a CodeSandbox (feel free to use [this template](https://codesandbox.io/s/bitter-wind-pv0hwj))? Will reopen when done!

This problem occurs with nextjs

**Comment by DanielSinclair** [comment]
@jxom Noticed these occasional 500 errors in our Next.js example dApp. Seems to be a SSR race condition.
```bash
ERROR	Uncaught Exception 	{"errorType":"Error","errorMessage":"Client network socket disconnected before secure TLS connection was established","code":"ECONNRESET","host":"eth-mainnet.ws.alchemyapi.io","port":443,"stack":["Error: Client network socket disconnected before secure TLS connection was established","    at connResetException (internal/errors.js:639:14)","    at TLSSocket.onConnectEnd (_tls_wrap.js:1570:19)","    at TLSSocket.emit (events.js:412:35)","    at endReadableNT (internal/streams/readable.js:1333:12)","    at processTicksAndRejections (internal/process/task_queues.js:82:21)"]}
Error: Runtime exited with error: exit status 129
Runtime.ExitError
```
I'm not sure of the cleanest way to mitigate this, as `wagmiClient` can be initialized on the server-side and `WagmiConfig` doesn't like the client to be undefined if the dApp performs SSR context check. Because `WagmiConfig` is configured in `_app.tsx` there also isn't a clean strategy to utilize `next/dynamic` or other component-level import strategies that prevent SSR: 
```ts
import dynamic from 'next/dynamic'
const App = dynamic(() => import('../components/App'), { ssr: false })
```
