### ISSUE TITLE
Installing wagmi with pnpm give error ERR_PNPM_PREPARE_PKG_FAILURE

### ISSUE THREAD

**Issue by francesco-gaglione** [wagmi-dev/wagmi#1583]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

latest

### Current Behavior

I'm trying to install wagmi with this command into a turborepo project

```
pnpm i wagmi --filter web
```

but I have this error:
```
apps/web                                 |  WARN  deprecated safe-event-emitter@1.0.1
apps/web                                 |  WARN  deprecated @json-rpc-tools/provider@1.7.6
apps/web                                 |  WARN  deprecated eth-sig-util@1.4.2
apps/web                                 |  WARN  deprecated @walletconnect/mobile-registry@1.4.0
apps/web                                 |  WARN  deprecated @json-rpc-tools/utils@1.7.6
apps/web                                 |  WARN  deprecated @json-rpc-tools/types@1.7.6
.                                        | +288 +++++++++++++++++++++++++++++
 ERR_PNPM_PREPARE_PKG_FAILURE  Command failed with exit code 1: npm install
Progress: resolved 520, reused 507, downloaded 0, added 0
```

### Expected Behavior

A normal installation

### Steps To Reproduce

create a turborepo project and install wagmi with pnpm

**Comment by sebpalluel** [comment]
I also have a similar issue on a Dockerfile with `node:18-alpine` while doing `pnpm install`. I'm using `nx` but it's not related. I'm having the same problem with the `pnpm install` command on Github Action.

```bash
#11 184.8 Progress: resolved 3086, reused 0, downloaded 3084, added 0
#11 185.0  ENOENT  Command failed with ENOENT: git ls-remote https://github.com/ethereumjs/ethereumjs-abi.git HEAD
#11 185.0 spawn git ENOENT
#11 185.0
#11 185.0 This error happened while installing the dependencies of wagmi@0.10.0
#11 185.0  at @coinbase/wallet-sdk@3.6.3
#11 185.0  at eth-json-rpc-filters@4.2.2
#11 185.0  at eth-json-rpc-middleware@6.0.0
#11 185.0  at eth-sig-util@1.4.2
```
Looking at the log and my `pnpm-lock.yaml` it appears `@coinbase/wallet-sdk` is using deprecated packages, the one causing the issue is`eth-sig-util`:
```yaml
/eth-sig-util/1.4.2:
    resolution: {integrity: sha512-iNZ576iTOGcfllftB73cPB5AN+XUQAT/T8xzsILsghXC1o8gJUqe3RHlcDqagu+biFpYQ61KQrZZJza8eRSYqw==}
    deprecated: Deprecated in favor of '@metamask/eth-sig-util'
    dependencies:
      ethereumjs-abi: github.com/ethereumjs/ethereumjs-abi/ee3994657fa7a427238e6ba92a84d0b529bbcde0
      ethereumjs-util: 5.2.1
    dev: false
  ```

**Comment by francesco-gaglione** [comment]
@sebpalluel  have you found a solution?

**Comment by sebpalluel** [comment]
> @sebpalluel have you found a solution?

I just found a solution thanks to [this post](https://github.com/ethereumjs/ethereumjs-abi/issues/67#issuecomment-1102903197)
[The build is passing now on my project](https://github.com/sebpalluel/web3-monorepo/actions/runs/3795704784/jobs/6455085743) with [this commit](https://github.com/sebpalluel/web3-monorepo/commit/d9756f4d31c2632bc8d1c6f41c6b8de4eaa34a7a) so it should work for you also by adding this to your `package.json`:
```json
"pnpm": {
    "overrides": {
      "ethereumjs-abi": "https://registry.npmjs.org/ethereumjs-abi/-/ethereumjs-abi-0.6.8.tgz"
    }
  }
 ```

**Comment by jxom** [comment]
This was an [issue](https://github.com/pnpm/pnpm/issues/5845) with pnpm 7.20. Please upgrade to 7.21.

**Comment by sebpalluel** [comment]
> This was an [issue](https://github.com/pnpm/pnpm/issues/5845) with pnpm 7.20. Please upgrade to 7.21.

FYI I still have the same issue when removing the pnpm overrides with pnpm@7.21.0:

With normal reporter: https://app.warp.dev/block/r8w9gWV8MMFOfl8PukUlb6
With reporter ndjson: https://app.warp.dev/block/UMqI342kgOeUkSL4pGyIb1

And here's the Dockerfile:
```Dockerfile
FROM node:18-alpine as deps

RUN apk add --no-cache git
## set global npm path to node user to avoid permission error when installing global packages (pnpm)
ENV NPM_CONFIG_PREFIX=/home/node/.npm-global
ENV PATH=$PATH:/home/node/.npm-global/bin

USER node
WORKDIR /home/node

COPY --chown=node package.json pnpm-lock.yaml ./
RUN npm install -g pnpm@7.21.0 && pnpm install --ignore-scripts --reporter ndjson
```

**Comment by francesco-gaglione** [comment]
@jxom same error on 7.21

**Comment by francesco-gaglione** [comment]
Solution found upgrading to 7.22

**Comment by sebpalluel** [comment]
> Solution found upgrading to 7.22

Same here, build are now passing without the override because `ethereumjs-abi` is resolved correctly.
