### ISSUE TITLE
bug: invalid signature string with useSignMessage using Loopring Wallet via WalletConnect

### ISSUE THREAD

**Issue by agentx3** [wagmi-dev/wagmi#1586]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Package Version

0.10.1

### Current Behavior

Upon signing a message via WalletConnect using an activated Loopring Wallet, an error is returned. This happens on both local testing environment as well as on https://wagmi.sh/examples/sign-message. Example: 
![image](https://user-images.githubusercontent.com/104329992/209922481-4777ed33-5a84-4059-bca2-099e868d9499.png)

### Expected Behavior

Proper handling without errors.

### Steps To Reproduce

1. Connect with WC via web3modal using activated Loopring Smartwallet.
2. Invoke useMessage to sign a message

### Anything else?

With Loopring being on L2 it might be the case that this is out of your guys' control, I've done some digging but haven't come up with anything substantial myself. It might be that it's signing with EDDSA instead of ECDSA. Interestingly, using [this tool ](https://etherscan.io/verifiedSignatures) on Etherscan yields the exact same signature, yet when attempting to validate, Etherscan also says that the signature is invalid. Surely there must be some way to implement verification of a signed message with WalletConnect though? Amazing library btw.

**Comment by jxom** [comment]
I have a feeling this may be a downstream issue (perhaps Loopring's WalletConnect or JSON-RPC implementation) as all we do is utilize [ethers' `signMessage` method internally](https://github.com/wagmi-dev/wagmi/blob/main/packages/core/src/actions/accounts/signMessage.ts#L20-L22) (which internally uses `personal_sign`). Think you can get in touch with the Loopring team?
