### ISSUE TITLE
bug: signer is not updated on account change

### ISSUE THREAD

**Issue by essserrr** [wagmi-dev/wagmi#1622]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.10.3

### Current Behavior

After the recent update signer is never updated after account change. Account address however is updated correctly.

### Expected Behavior

Signer should be updated after account change

### Steps To Reproduce

1. Connect metamask with account A
2. Switch metamask account to B
3. Signer remains the same (account A)
4. Account address inside wagmi is correct - B
![image](https://user-images.githubusercontent.com/21965602/210916152-dce01b32-0459-4f25-8634-5db4e0533aef.png)

https://codesandbox.io/s/wagmi-no-signer-update-forked-cefnuu

### Link to Minimal Reproducible Example (CodeSandbox, StackBlitz, etc.)

https://codesandbox.io/s/wagmi-no-signer-update-forked-cefnuu

**Comment by jxom** [comment]
Good catch — fix at #1623.
