### ISSUE TITLE
error - Error: No QueryClient set, use QueryClientProvider to set one

### ISSUE THREAD

**Issue by TheGreatKAN** [wagmi-dev/wagmi#1625]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

10.5

### Current Behavior

![image](https://user-images.githubusercontent.com/95988106/211133318-71c5682b-2c20-4d12-82f8-6664196bd766.png)
![image](https://user-images.githubusercontent.com/95988106/211133344-6356693a-8851-4c72-8996-07763bdc9c2b.png)
![image](https://user-images.githubusercontent.com/95988106/211133359-9f12d3b5-8fb1-448d-b00d-6671e5e11434.png)
![image](https://user-images.githubusercontent.com/95988106/211133372-5c3cfad4-1e34-4542-9f4a-2b5775a2a1ef.png)
![image](https://user-images.githubusercontent.com/95988106/211133401-33958605-7854-410f-b0ba-7ed43fcb1279.png)
it seems like the actual function is using useQuery...
any help would be greatly appreciated!!

### Expected Behavior

copied the docs to a t...

### Steps To Reproduce

start nextjs project without typescript using eslint using npm

**Comment by tmm** [comment]
All hooks must be used inside `WagmiConfig` React Context Provider.
