### ISSUE TITLE
bug: send transaction example does not work with 1inch and trust wallet

### ISSUE THREAD

**Issue by qmzik** [wagmi-dev/wagmi#1642]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

latest

### Current Behavior

Trust wallet throws error when trying to send transaction. In 1inch wallet nothing happends

### Expected Behavior

It should open modal with transaction

### Steps To Reproduce

https://user-images.githubusercontent.com/26081016/211535602-849b51f0-b649-413f-8379-1e4f134887af.mp4

https://user-images.githubusercontent.com/26081016/211535823-cb85d009-8034-477e-ab3f-adbbd3113b35.mp4

**Comment by jxom** [comment]
As this functions properly for other wallets, I have a feeling this may be a downstream issue (perhaps Trust or 1inch's WalletConnect or JSON-RPC implementation) as all we do is utilize [ethers' `sendTransaction` method internally](https://github.com/wagmi-dev/wagmi/blob/main/packages/core/src/actions/transactions/sendTransaction.ts#L93-L95) (which internally uses `eth_sendTransaction`). Think you can get in touch with the Trust or 1inch team?

**Comment by aximas** [comment]
How I can catch Tx hash if I will use "trust wallet" 
I tried to use wagmi hook **usePrepareContractWrite** and @wagmi/core action **writeContract**. They could not help me ((

**Comment by arslancodes** [comment]
I have the same issue, any update guys?

**Comment by jxom** [comment]
This is an issue on the Wallet side. Best to get in touch with the wallet.

**Comment by shadowfaz16** [comment]
hello, having this issue as well. any luck getting in touch with trust wallet?

**Comment by Tura187** [comment]
This I'd my ex at her greatest hacking my account with the help of git hub

**Comment by Tura187** [comment]
Please fix my account she is stilling what dirsnt velong to her

**Comment by Tura187** [comment]
> hello, having this issue as well. any luck getting in touch with trust wallet?

Well sir it wasn't her trust account to begin with ...
Can you help me return my account back to normal please

**Comment by Tura187** [comment]
> As this functions properly for other wallets, I have a feeling this may be a downstream issue (perhaps Trust or 1inch's WalletConnect or JSON-RPC implementation) as all we do is utilize [ethers' `sendTransaction` method internally](https://github.com/wagmi-dev/wagmi/blob/main/packages/core/src/actions/transactions/sendTransaction.ts#L93-L95) (which internally uses `eth_sendTransaction`). Think you can get in touch with the Trust or 1inch team?

She hacked my trust account 
Amber wilber amber Stephen's amber Cole..
Help me recover my account .
.
