### ISSUE TITLE
bug: Wagmi-core raises TypeError on clean install

### ISSUE THREAD

**Issue by c0dejax** [wagmi-dev/wagmi#1643]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

latest

### Current Behavior

When building / installing wagmi latest (but also earlier versions). With the most basic setup followed here https://wagmi.sh/react/getting-started I get the following: 

![image](https://user-images.githubusercontent.com/110606352/211587232-70982272-842a-4266-936c-132bf66426f1.png)

I also now get this error when I rebuild an older project where I still use 0.8.9. 

### Expected Behavior

No errors. 

### Steps To Reproduce

Installing wagmi latest version and following the getting started here https://wagmi.sh/react/getting-started

**Comment by fanfarel** [comment]
It's probably zustand deprecated old style import, for right now you can add resolution in package.json with version 4.2.0

**Comment by c0dejax** [comment]
Fixed it, thank you
