### ISSUE TITLE
bug: Inaccurate documentation for param `reloadOnDisconnect` of `CoinbaseWalletConnector`

### ISSUE THREAD

**Issue by afmfe-iul** [wagmi-dev/wagmi#1651]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.10.10

### Current Behavior

When using `CoinbaseWalletConnector` the documentation says `reloadOnDisconnect` defaults to `true`, however it seems to [default to false](https://github.com/wagmi-dev/references/blob/main/packages/connectors/src/coinbaseWallet.ts#L50)

![image](https://user-images.githubusercontent.com/10389190/211938485-5e503d76-41d1-4e1c-b765-469377af5514.png)

The issue seems to come from the type [Options](https://github.com/wagmi-dev/references/blob/e7b150a320d5a119c69fa48d62a857f5fbb2eb02/packages/connectors/src/coinbaseWallet.ts#L21) that is a union with `CoinbaseWalletSDKOptions`, which do indeed default `reloadOnDisconnect` to true

### Expected Behavior

The documentation in question matches the implementation.

### Steps To Reproduce

- Start a new project with `wagmi`
- Instantiate a `CoinbaseWalletConnector` in a code editor that supports documentations

**Comment by jxom** [comment]
Thanks! Fixed at https://github.com/wagmi-dev/references/commit/e607ee27a27c826e998f9634a33a14cdeeca07c3
