### ISSUE TITLE
bug: `watchAccount` event activated when I change network in metamask

### ISSUE THREAD

**Issue by huumaa** [wagmi-dev/wagmi#1656]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

^0.8.8

### Current Behavior

When I change network in metamask, sometimes activated event `watchAccount`. This happens after a few (3-5) network changes. And it only happens in metamask.

### Expected Behavior

Event `watchAccount` must listen just change accounts.

### Steps To Reproduce

Start a new project with `wagmi`

Instantiate a `MetaMaskConnector` in a code editor that supports documentations

Connect your MetaMask wallet and try changing network (3-5 tries).

**Comment by huumaa** [comment]
Even on your site, if you connect a metamask and change the network several times, the wallet will turn off.

**Comment by jxom** [comment]
By default, `watchAccount` invokes when the `connector` instance changes (which is what is happening here). You can scope the behaviour to only change on `address` changes by doing:

```ts
watchAccount(
  () => { ... }, 
  { selector: ({ address }) => ({ address }) },
)
```

**Comment by tmm** [comment]
Also possible that this is related to a [longstanding MetaMask bug](https://github.com/MetaMask/metamask-extension/issues/13375#issuecomment-1087023057) (wagmi attempts to shim fix, but possible it is not successful all the time).
