### ISSUE TITLE
bug: Inaccurate documentation for @wagmi/core

### ISSUE THREAD

**Issue by danilo-89** [wagmi-dev/wagmi#1657]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.8.14

### Current Behavior

Issue No.1
https://wagmi.sh/core/getting-started
```
import {
  WagmiConfig,
  createClient,
  configureChains,
  mainnet,
} from '@wagmi/core'
```
Description: Module '"@wagmi/core"' has no exported member 'WagmiConfig'.

Issue No.2
https://wagmi.sh/core/getting-started
```
const { address } = await connect({
  connector: new InjectedConnector(),
})
const ensName = await fetchEnsName({ address })
```
Description: Property 'address' does not exist on type 'ConnectResult<Provider>'.

**Comment by jxom** [comment]
Thanks! Fixed it.
