### ISSUE TITLE
webpack编译启动就报这个错

### ISSUE THREAD

**Issue by Bubble2** [wagmi-dev/wagmi#1660]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Package Version

0.10.10

### Current Behavior

WARNING in ./node_modules/@walletconnect/sign-client/dist/index.es.js 1:20237-20238
export 'getInternalError' (imported as 'c') was not found in '@walletconnect/utils' (possible exports: addHexPrefix, appendToQueryString, concatArrayBuffers, concatBuffers, convertArrayBufferToBuffer, convertArrayBufferToHex, convertArrayBufferToNumber, convertArrayBufferToUtf8, convertBufferToArrayBuffer, convertBufferToHex, convertBufferToNumber, convertBufferToUtf8, convertHexToArrayBuffer, convertHexToBuffer, convertHexToNumber, convertHexToUtf8, convertNumberToArrayBuffer, convertNumberToBuffer, convertNumberToHex, convertNumberToUtf8, convertUtf8ToArrayBuffer, convertUtf8ToBuffer, convertUtf8ToHex, convertUtf8ToNumber, detectEnv, detectOS, formatIOSMobile, formatMobileRegistry, formatMobileRegistryEntry, formatQueryString, formatRpcError, getClientMeta, getCrypto, getCryptoOrThrow, getDappRegistryUrl, getDocument, getDocumentOrThrow, getEncoding, getFromWindow, getFromWindowOrThrow, getInfuraRpcUrl, getLocal, getLocalStorage, getLocalStorageOrThrow, getLocation, getLocationOrThrow, getMobileLinkRegistry, getMobileRegistryEntry, getNavigator, getNavigatorOrThrow, getQueryString, getRpcUrl, getType, getWalletRegistryUrl, infuraNetworks, isAndroid, isArrayBuffer, isBrowser, isBuffer, isEmptyArray, isEmptyString, isHexString, isIOS, isInternalEvent, isJsonRpcRequest, isJsonRpcResponseError, isJsonRpcResponseSuccess, isJsonRpcSubscription, isMobile, isNode, isReservedEvent, isSilentPayload, isTypedArray, isValidAddress, isWalletConnectSession, logDeprecationWarning, mobileLinkChoiceKey, parsePersonalSign, parseQueryString, parseTransactionData, parseWalletConnectUri, payloadId, promisify, removeHexLeadingZeros,
removeHexPrefix, removeLocal, reservedEvents, safeJsonParse, safeJsonStringify, sanitizeHex, saveMobileLinkInfo, setLocal, signingMethods, stateMethods, toChecksumAddress, uuid)
@ ./node_modules/@walletconnect/universal-provider/dist/index.es.js 1:20-62 1:6641-6647
@ ./node_modules/@wagmi/connectors/dist/walletConne

### Expected Behavior

不报错，正常启动

### Steps To Reproduce

0.9.x版本不报错

**Comment by tmm** [comment]
Thanks for reporting. This issue is temporarily closed due to lack of information. Please provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) and reopen this issue.
