### ISSUE TITLE
bug: switchNetwork exposes infura/alchemy API keys when adding a new network

### ISSUE THREAD

**Issue by nfts2me** [wagmi-dev/wagmi#1664]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.10.10

### Current Behavior

When using switchNetwork and the user doesn't have the network created, instead of adding the network with a public RPC, it uses the RPC with the API. This is highly undesirable, as not only it exposes our private API key, but also stores it on the user chain even for actions unrelated to our website.

With Polygon network not created, and providers created with API keys (Infura or Alchemy), something as easy as this:
     const network = await switchNetwork({
      chainId: 137,
    })

Tries to add the new network but with the internal RPC with our API key instead of the public RPC.

### Expected Behavior

Create the network with the public RPCs.

### Steps To Reproduce

With Polygon network not created, and providers created with API keys (Infura or Alchemy), use this code:
     const network = await switchNetwork({
      chainId: 137,
    })

**Comment by tmm** [comment]
In case anyone is interested in picking this up, seems like you just need to remove the code overriding `Chain.rpcUrls.default` for the following providers: [`infuraProvider`](https://github.com/wagmi-dev/wagmi/blob/main/packages/core/src/providers/infura.ts#L26), [`alchemyProvider`](https://github.com/wagmi-dev/wagmi/blob/main/packages/core/src/providers/alchemy.ts#L26), and [`jsonRpcProvider`](https://github.com/wagmi-dev/wagmi/blob/main/packages/core/src/providers/jsonRpc.ts#L29).

**Comment by nfts2me** [comment]
> In case anyone is interested in picking this up, seems like you just need to remove the code overriding `Chain.rpcUrls.default` for the following providers: [`infuraProvider`](https://github.com/wagmi-dev/wagmi/blob/main/packages/core/src/providers/infura.ts#L26), [`alchemyProvider`](https://github.com/wagmi-dev/wagmi/blob/main/packages/core/src/providers/alchemy.ts#L26), and [`jsonRpcProvider`](https://github.com/wagmi-dev/wagmi/blob/main/packages/core/src/providers/jsonRpc.ts#L29).

Pull request created.
