### ISSUE TITLE
Inconsistent pre-wallet connection network state

### ISSUE THREAD

**Issue by jtlacci** [wagmi-dev/wagmi#1671]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.8.1

### Current Behavior

```js
const { chains, provider, webSocketProvider } = configureChains(
  [mainnet, goerli],
  [infuraProvider({ apiKey: process.env.INFURA_KEY }), publicProvider()],
);
```
```js
// unconnected wallet
const Demo = () => {
  const { chain } = useNetwork()
  const web3Provider = useProvider()
  
  console.log(chain) // undefined
  console.log(await web3Provider.getNetwork()) // { ... , chainId: 1}
}
```
```js
// connected wallet
const Demo = () => {
  const { chain } = useNetwork()
  const web3Provider = useProvider()
  
  console.log(chain) // { ... , id: 1}
  console.log(await web3Provider.getNetwork()) // { ... , chainId: 1}
}
```

### Expected Behavior

```js
const { chains, provider, webSocketProvider } = configureChains(
  [mainnet, goerli],
  [infuraProvider({ apiKey: process.env.INFURA_KEY }), publicProvider()],
);
```
```js
// unconnected wallet
const Demo = () => {
  const { chain } = useNetwork()
  const web3Provider = useProvider()
  
  console.log(chain)  // { ... , id: 1}
  console.log(await web3Provider.getNetwork()) // { ... , chainId: 1}
}
```
```js
// connected wallet
const Demo = () => {
  const { chain } = useNetwork()
  const web3Provider = useProvider()
  
  console.log(chain) // { ... , id: 1}
  console.log(await web3Provider.getNetwork()) // { ... , chainId: 1}
}
```

Apps should be able to rely on the provider and network to fetch data regardless of wallet connection state. It's a common pattern to render pages pre-wallet connect so would be nice be able to keep the logic consistent regardless of wallet status. 

Additionally it seems like the provider defaults to the first chain array element passed to `configureChains` would be nice to have an explicit default

**Comment by tmm** [comment]
`useNetwork` tracks network information for connected wallets and is not always in sync with the Client's provider (e.g. when disconnected or Client provider not set up as a chain-aware function).

> Apps should be able to rely on the provider and network to fetch data regardless of wallet connection state. It's a common pattern to render pages pre-wallet connect so would be nice be able to keep the logic consistent regardless of wallet status.

If you want to allow users to change the chain id without being connected, I suggest keeping track of this using some type of global store (e.g. React Context, Redux, Zustand). You can then pass that chain id to various hooks that support the chainId prop and sync it when there is a connected wallet using `useNetwork`.

> Additionally it seems like the provider defaults to the first chain array element passed to configureChains would be nice to have an explicit default

Correct, when using `configureChains` the first chain in the array is the default. Can add a note to the docs.

**Comment by jtlacci** [comment]
> If you want to allow users to change the chain id without being connected,

i don't need the users to be able to change the network, just to be able to manage a default network to prefetch before wallet connect. This is a pretty common usecase and seems like an anti-pattern to have manage another piece of state to make components chain aware pre-wallet connection.

**Comment by jtlacci** [comment]
That was bad phrasing, what I meant is that I want to be able to be able to use the same fetching patterns in the default network state and the wallet connected state.  If the pattern is you can use `useProvider` to make calls pre and post wallet connection, many components also need to be network aware. 

For example had an component that showed some onchain state I can rely on `useProvider` to make the calls regardless of connection status. (great)

However if the component also need to get elements that are network dependant (opensea link, contract addresses, etc) then I can't rely on `useNetwork` because it's only available on wallet connect. 

I will instead have manage separate network state that has a consistent lifecycle to `useProvider`. Which isn't a huge deal but it seems silly to have to create my own abstraction for `useNetwork` for what I consider a base case.

**Comment by tmm** [comment]
You aren't the first to bring this up so the core team can spend some time thinking about if we want to prioritize this. 

There are some tricky pieces around keeping the "wallet connected state" id in sync with the "default network state." For example, what happens when the "default network state" is set to Chain A, then a wallet is connected and doesn't support Chain A, but does support Chain B? Does the state update to match Chain A or B?

Previous discussion: https://github.com/wagmi-dev/wagmi/discussions/461

**Comment by jtlacci** [comment]
can repost over there is helpful but IMO wagmi should always prioritize the wallet when possible. 

Case 1: Wallet connects with a app supported network different than default. 
- wagmi prioritizes wallet network. (valid signer so, app is read and write)

Case 2: Wallet connects with an app unsupported network different than default.
- wagmi prioritizes default network (no valid signer so, app is read only)

Case3: Wallet doesn't support any app supported networks.
- wagmi prioritizes default network (no valid signer so, app is read only)

Case4: Wallet disconnects after connected with a app supported network different than default. 
- wagmi prioritizes the last wallet network (no valid signer so, app is read only)
- potentially add a config option here as I could see a case for also reverting to default network

I think this would be a good MVP around this pattern with the potential to include the `switchNetwork` hook in the future. 

I do think this is an important pattern because not forcing wallet connect to use an app initially is critical UX.

**Comment by tmm** [comment]
Thanks for jotting that down. It's important to note that wagmi is a lower-level library so we try to avoid baking opinions into the core when possible so others aren't locked into specific behavior. Like I said before, the core team will chat about it and prioritize against existing and planned work. In the meantime, it's not too difficult to achieve what you are looking for with some code on your end and the abstractions wagmi already provides.
