### ISSUE TITLE
Perform method is implemented to always throw an error

### ISSUE THREAD

**Issue by its-me-ilia** [wagmi-dev/wagmi#1684]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.9.4

### Current Behavior

I am trying to use `provider.perform` function and no matter what method i use i always receive method not implemented, after  checking the actual code i came across this 

![image](https://user-images.githubusercontent.com/54749663/213009737-d330f0cb-a37c-4a9e-b368-246a6a9e87ec.png)

Maybe i am missing the point but why declare a function to just throw error on any parameter.

### Expected Behavior

Expected Behaviour would be for `perform` method to be implemented.

### Steps To Reproduce

Steps to reproduce:

declare provider with

`const provider = useProvider()`

and use any valid method for example `eth_chainId`

`provider.perform('eth_chainId', [])`

and check the thrown error.

**Comment by jxom** [comment]
This seems more like an Ethers implementation detail, rather than wagmi.

But, I think you might be looking for `.send` instead of `.perform`.
