### ISSUE TITLE
Perform method not implemented

### ISSUE THREAD

**Issue by its-me-ilia** [wagmi-dev/wagmi#1693]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.9.4

### Current Behavior

Perform is not implemented. issue explained here and there is no alternative to perform requests.

[https://github.com/wagmi-dev/wagmi/issues/1684](url)

### Expected Behavior

Perform should be implemented or there should be alternative like ethers providers with `prepareRequest`.

### Anything else?

@jxom Do not close this issue again without proper explanation and a response just to have one more closed issue. and regarding your comments what i screenshotted was Wagmi implementation, not ethers. ethers provides perform method that works well and is implemented properly, and wagmi provider has no `send` method either.

**Comment by its-me-ilia** [comment]
> ### Is there an existing issue for this?
> * [x]  I have searched the existing issues
> 
> ### Package Version
> 0.9.4
> 
> ### Current Behavior
> Perform is not implemented. issue explained here and there is no alternative to perform requests.
> 
> [https://github.com/wagmi-dev/wagmi/issues/1684](url)
> 
> ### Expected Behavior
> Perform should be implemented or there should be alternative like ethers providers with `prepareRequest`.
> 
> ### Steps To Reproduce
> _No response_
> 
> ### Link to Minimal Reproducible Example (CodeSandbox, StackBlitz, etc.)
> _No response_
> 
> ### Anything else?
> @jxom Do not close this issue again without proper explanation and a response just to have one more closed issue. and regarding your comments what i screenshotted was Wagmi implementation, not ethers. ethers provides perform method that works well and is implemented properly, and wagmi provider has no `send` method either.

**Comment by jxom** [comment]
A proper explanation was given in the previous issue (#1684) – being that this is an Ethers implementation detail. The screenshot of your code is not wagmi implementation, it is on the Ethers `BaseProvider` ([see here](https://github.com/ethers-io/ethers.js/blob/master/packages/providers/src.ts/base-provider.ts#L2098-L2100)).

`perform` is overridden by the `JsonRpcProvider` (ethers), which is only compatible for certain RPC methods (e.g. `call`, `estimateGas`, `getBlockNumber`, etc). The reproducible example you provided used `eth_chainId`, which would [cause this error to be thrown](https://github.com/ethers-io/ethers.js/blob/master/packages/providers/src.ts/json-rpc-provider.ts#L636-L638).

Here is a minimal example of how you can call a raw RPC request:

```tsx
import { useEffect } from 'react'
import { useProvider } from 'wagmi'

function Example() {
  const provider = useProvider()

  useEffect(() => {
    const getChainId = async () =>
      console.log(await provider.send('eth_chainId'))
    getChainId()
  }, [provider])

  return null
}
```



Does this make sense?

**Comment by its-me-ilia** [comment]
Looks like typescript declarations need to be updated then.

![image](https://user-images.githubusercontent.com/54749663/213291915-d550cf25-b3d0-4c3b-8a6d-a30138e8ab30.png)

Thank you for example.

**Comment by jxom** [comment]
Yeah, we can look into fixing that. Might just need to explicitly cast to a `JsonRpcProvider` from ethers for now.

**Comment by its-me-ilia** [comment]
FYI, any idea why eth_signTypedData_v3 is not available with provider.send? `the method eth_signTypedData_v3 does not exist/is not available`?

**Comment by jxom** [comment]
Depends if the RPC provider/node supports the method. What RPC provider are you using? Can you use v4 instead via wagmi's `useSignTypedData`/`signTypedData`?

**Comment by its-me-ilia** [comment]
Ah Thanks for the directions, i am using quicknode's rpc provider which does not seem to support the method. i could go for v4, that would be great but i am using v3 because i am implementing meta transactions, and EIP712 Domain requires salt

`    struct EIP712Domain {
        string name;
        string version;
        address verifyingContract;
        bytes32 salt;
    }`

if you can suggest any alternative w or w/o wagmi i would appreciate very much.
