### ISSUE TITLE
Next js ver. 13.0.2 build error

### ISSUE THREAD

**Issue by champseo2017** [wagmi-dev/wagmi#1695]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.10.11

### Steps To Reproduce
yarn build

_No response_

### Anything else?

<img width="1183" alt="Screen Shot 2566-01-19 at 10 50 43" src="https://user-images.githubusercontent.com/32265715/213351108-3aefc4c2-0dd1-411d-bfed-570484f28f35.png">

**Comment by tmm** [comment]
wagmi requires TypeScript 4.7.4 or later. More info [here](https://wagmi.sh/react/typescript).

**Comment by champseo2017** [comment]
thank you very much i will follow doc

**Comment by champseo2017** [comment]
it works successfully
