### ISSUE TITLE
bug: export 'filecoin' (reexported as 'filecoin') was not found in '@wagmi/chains'

### ISSUE THREAD

**Issue by razorbohan** [wagmi-dev/wagmi#1707]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.10.13

### Current Behavior

Was trying to follow https://wagmi.sh/core/getting-started for testing wagmi, but receiving an error while building the project. Have added the following code snippet:

```typescript
import { configureChains, createClient, mainnet } from '@wagmi/core'
import { publicProvider } from '@wagmi/core/providers/public'

const { chains, provider, webSocketProvider } = configureChains(
  [mainnet],
  [publicProvider()],
);

const client = createClient({
  autoConnect: true,
  provider,
  webSocketProvider,
});

console.log(chains, client);
```

Received this error:

<img width="423" alt="Снимок экрана 2023-01-23 в 15 37 18" src="https://user-images.githubusercontent.com/31306103/213996414-dc4992ba-90d8-4deb-8483-e42d7ad35e75.png">

Using "typescript": "4.7.4"

**Comment by jxom** [comment]
Published a fix on `0.10.14` – can you try again?
