### ISSUE TITLE
bug: type `Address` is not correctly picked even after configuring underlying `AddressType`

### ISSUE THREAD

**Issue by technophile-04** [wagmi-dev/wagmi#1712]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.10.10

### Current Behavior

As mentioned in this comment https://github.com/wagmi-dev/wagmi/issues/1330#issuecomment-1320317099 if you try to configure the underlying `AddressType` it works but things such as type `ConnectorData` (specifically stuff from `wagmi/connectors`)  still have types as `0x{string}`. 

### Expected Behavior

Once configured the underlying `AddressType` to `string`  as mentioned in https://github.com/wagmi-dev/wagmi/issues/1330#issuecomment-1320317099  it should be reflected everywhere. 

### Steps To Reproduce

Example repo link: https://github.com/technophile-04/se-2/tree/issue/wagmi

if you clone the repo checkout to `issue/wagmi` branch and go to `BurnerConnector.ts` you will find some typescript errors because in some places AdressType still refers to 0x{string} even after adding the declaration file.

### Link to Minimal Reproducible Example (CodeSandbox, StackBlitz, etc.)

https://github.com/technophile-04/se-2/tree/issue/wagmi

### Anything else?

I think the reason for this is how wagmi is handling dependency of 'abitype'(I may be wrong here though) , checkout below SS : 
![Screenshot 2023-01-23 at 12 38 10 PM](https://user-images.githubusercontent.com/80153681/213962270-b2e8e37d-9a97-4d56-9b43-be325aac513e.jpg)
The above SS is of `node_modules` of `nexjs`directory. As we can see the `core` does not have `abitype` in its `node_modules` and thus using the `abitype` from our repo and using anything from `core` is inferring correct type for `AddressType : string` but if we look at `connectors` directory in above SS there is `abitype` in its `node_modules` because of which its taking `abitype` from its directory instead of targeting `abitype` of our repo. Since importing stuff from `connectors` in `BurnerConnector.ts` the types for `AddressTypes` there are `0x{string}`. 

can this line be causing issue in wagmi ? https://github.com/wagmi-dev/wagmi/blob/b846be6b1a3c0a6c967dc22c3fde7d3acdbf0607/tsconfig.json#L27 

For more description checkout https://github.com/scaffold-eth/se-2/pull/96#issuecomment-1399269480

**Comment by tmm** [comment]
Thanks for reporting! Seems like there is a version mismatch between packages. Created https://github.com/wagmi-dev/references/pull/74 that should fix this once rolled out downstream.

Aside: Noticed the TypeScript version in the project you shared does not meet minimum required for wagmi. Should be [at least 4.7.4](https://wagmi.sh/react/typescript) (currently 4.7.2).

**Comment by tmm** [comment]
Fixed https://github.com/technophile-04/se-2/pull/1

**Comment by technophile-04** [comment]
Thanks so much @tmm 🙌

**Comment by meltingice** [comment]
This bug has returned. `wagmi` depends on `abitype@^0.7.1` whereas `@wagmi/connectors` and `@wagmi/core` depend on `abitype@^0.3.0`.

**Comment by tmm** [comment]
@meltingice will have a fix shortly. in the future, feel free to create a new issue. going to eliminate this issue from creeping up in the future with some upcoming changes.
