### ISSUE TITLE
bug: "The method eth_sendTransaction does not exist is not available"

### ISSUE THREAD

**Issue by Admirated** [wagmi-dev/wagmi#1714]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

^0.8.15

### Current Behavior

When I try to call a contract method that requires a user signature, an error is returned to me:
On bsc(id:56) - code: -32000, message: "unknown account", No transaction comes to the wallet.
On mainnet(id:1) - code: -32601, message: "The method eth_sendTransaction does not exist is not available", The transaction does not come to the wallet.

![image_2023-01-24_14-41-28](https://user-images.githubusercontent.com/70275437/214294269-79f83697-1023-4813-a111-86bcaca62ae1.png)
![image_2023-01-24_14-38-43](https://user-images.githubusercontent.com/70275437/214293731-3ec90c7b-4741-4c90-af5c-13d558710ab6.png)
{"jsonrpc":"2.0","id":43,"error":{"code":-32000,"message":"unknown account"}}

### Expected Behavior

I expect that the transaction will come for confirmation in the connected wallet, after confirmation and payment of the fee, the transaction will be successful

### Steps To Reproduce

async function approveRouter(address) {
	const tokenAddress = "0xbb4cdb9cbd36b01bd1cbaebf2de08d9173bc095c"; // WBNB
	const approveAddress = "0x10ed43c718714eb63d5aa57b78b54704e256024e"; // PCRouter v2

	const tokenContract = new ethers.Contract(
		tokenAddress,
		erc20ABI,
		provider(56).getSigner(address) // address - connected user address
	);
	const maxApproval = ethers.constants.MaxUint256;

	const txRes = await tokenContract.approve(approveAddress, maxApproval, {
		gasLimit: 310000,
	});
	console.log(txRes);
}

### Anything else?

Browser: Google Chrome desktop

**Comment by Admirated** [comment]
> Виходячи з попереднього досвіду, **помилка «Метод eth_sendTransaction не існує, недоступний»** виникає, коли ви намагаєтеся підписати транзакцію неправильним підписувачем (приклад: спробуйте використовувати віддаленого підписувача замість підписувача плагіна).
> 
> Чому ви не використовуєте реакційні хуки замість змішування з використанням бібліотеки ефірів?
> 
> Це повинно працювати: https://wagmi.sh/react/hooks/useContractWrite
> 
> Насправді це те, що я маю у своїй програмі dapp і працює з v0.10.10 (typescript):
> 
> ```ts
> // Prepare the spender approval
> const {
>     write: approveSpender,
>     isLoading: isTxSending,
>     data: approveResult,
>   } = useContractWrite({
>     address: `${configuration?.TOKEN_CONTRACT}` as `0x${string}`,
>     abi: config.tokenAbi,
>     functionName: 'approve',
>     mode: 'recklesslyUnprepared',
>   });
> 
> // Handle the click on the approve button
> const handleApproveBtn = () => {
>     if (approveSpender) {
>       approveSpender({
>         recklesslySetUnpreparedArgs: [configuration?.STAKING_CONTRACT as string, amountToApprove],
>       });
>     }
>   };
> ```
I'm use Vue3, and it hasn't native support web3modal & wagmi hooks

**Comment by tmm** [comment]
@Admirated from your screenshot and code you provided, looks like you are using raw ethers. You should open up an issue over there instead.

**Comment by Admirated** [comment]
> @Admirated from your screenshot and code you provided, looks like you are using raw ethers. You should open up an issue over there instead.

Problem not in ethers.js, wagmi return fallback providers from configureChains, and i use it with web3modal connection (walletconnect 2.0)
i use walletConnect rpc connection, and this error occured.
When i use window.ethereum (metamask rpc) all working with ethers.js.

**Comment by tmm** [comment]
Please post a minimal reproducible example using wagmi. All the code in your original post from ethers, not wagmi.

**Comment by Admirated** [comment]
![image_2023-01-24_19-50-48](https://user-images.githubusercontent.com/70275437/214369938-c14c1ca5-2ab6-46b8-90d9-dcb41e804ba8.png)
![image_2023-01-24_19-50-23](https://user-images.githubusercontent.com/70275437/214369945-19ad170d-e2f7-41dd-8f48-3498077b5800.png)

i'm use configureChains provider with rpc.walletconnect

**Comment by tmm** [comment]
Can you post a link to a CodeSandbox or a GitHub repo that is [minimal and runnable with instructions](https://stackoverflow.com/help/minimal-reproducible-example)? Screenshots or code snippets aren't helpful because it's not a reproduction.

**Comment by Admirated** [comment]
@tmm, https://codesandbox.io/s/goofy-booth-e7hoz0?file=/src/assets/api.js
paste your projectID and click "connect", after click "approve"

**Comment by Admirated** [comment]
@tmm, Hi, you check my codesandbox link? I need to resolve that issue :)
