### ISSUE TITLE
bug: useNetwork's chain?.name returns "Chain 137" instead of "Polygon"

### ISSUE THREAD

**Issue by junhuang-ho** [wagmi-dev/wagmi#1723]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

^0.10.14

### Current Behavior

```
const { chain } = useNetwork();
console.log(chain?.name) // Chain 137
```

### Expected Behavior

```
const { chain } = useNetwork();
console.log(chain?.name) // Polygon
```

### Steps To Reproduce

```
import { useNetwork } from "wagmi";
const { chain } = useNetwork();
console.log(chain?.name) 
```

### Anything else?

only Eth mainnet seems to return "Ethereum", other chains all return "Chain XXX" instead of the chain's actual name.

**Comment by tmm** [comment]
Make sure you add any Chains you are using in your app to [`configureChains`](https://wagmi.sh/react/providers/configuring-chains) otherwise wagmi will fall back to this format (since it doesn't know about the chain).

**Comment by hskang9** [comment]
That does not solve the issue, I configured chains using `configureChains` and it still does not work.

**Comment by hskang9** [comment]
```
import { arbitrum, mainnet, optimism, evmos, polygon, hardhat} from "wagmi/chains";

const chains = [mainnet, optimism, arbitrum, evmos, polygon, hardhat];
const { provider, webSocketProvider } = configureChains(chains, [
  walletConnectProvider({ projectId }),
]);
```
I definitely included the chains from official package and still does not work.

**Comment by tmm** [comment]
Please comment here with a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) and I will re-open the issue.

**Comment by smakosh** [comment]
I'm running into the same issue as @hskang9, in order to reproduce @tmm, you can do so by running your wagmi-testing repository and try switching networks, the isTest you're doing before providing the `configureChains` is the reason for that happening.
