### ISSUE TITLE
bug: Potential risks for projects relying on CloudFlare's public node?

### ISSUE THREAD

**Issue by liarco** [wagmi-dev/wagmi#1730]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.10.15

### Current Behavior

The lib is currently using CloudFlare's public node as `default` and `public` options for `mainnet` :

https://github.com/wagmi-dev/references/blob/7cd37f23970fe5ae5c3d655fa7b7b34048fc9534/packages/chains/src/mainnet.ts#L17-L22

Starting yesterday my team noticed some changes on CloudFlare's end: some requests that run perfectly in the past started failing due to `call retuned result on length 328640 exceeding limit 100000`. Ignoring the spelling errors, I never got anything like that in the past but it looks like they may be lowering some limits on calls.

While doing some research I also bumped into this docs page: https://developers.cloudflare.com/web3/reference/migration-guide/

They refer to the public `cloudflare-eth.com` endpoint as deprecated and encourage users to move away from it.

### Expected Behavior

Here are my questions/considerations:
1. **should we be concerned about this?**
    Public nodes can always be unreliable, but using private nodes like Infura/Alchemy requires exposing keys that can always be used to run DDoS attacks on a project (e.g. even if I restrict the usage to specific contracts, an attacker can still grab the key and make a huge amount of calls to a whitelisted contract just to drain project requests).
    Having other options would be key to guarantee user access to a front end dapp
2. **would it be possible to add an option to run `read` calls using the same provider as for the `write` ones?**
    I understand why it's super convenient to be able to run read calls without a connected wallet (or with multiple providers at once), but allowing [useContractRead](https://wagmi.sh/react/hooks/useContractRead) to use the connected wallet as RPC provider would allow to have a strong fallback option which doesn't rely on a node provided by the dapp authors. (This would also improve decentralization IMHO)

Is this a bad idea? Does anyone have suggestions about this topic?

Thank you for your time.

**Comment by jxom** [comment]
I don't think `cloudflare-eth.com` itself has been deprecated, but rather, "hostnames that point to cloudflare-eth.com`.

> Starting yesterday my team noticed some changes on CloudFlare's end: some requests that run perfectly in the past started failing due to call retuned result on length 328640 exceeding limit 100000

Can you provide a minimal reproducible example via a CodeSandbox or something for this so we can have a look into it? From first glance, it looks like the RPC node doesn't support returning contract calls that return data exceeding 100000 bytes (0.1MB). 

To answer your questions:

> "Public nodes can always be unreliable, but using private nodes like Infura/Alchemy requires exposing keys that can always be used to run DDoS attacks on a project"

You can mitigate "DDoS attacks" by adding a domain whitelist to your Alchemy/Infura project.

> "allowing [useContractRead](https://wagmi.sh/react/hooks/useContractRead) to use the connected wallet as RPC provider would allow to have a strong fallback option"

Unfortunately, some injected wallets do not support _all_ public RPC methods, including the one that `useContractRead` uses (eth_call). Injected wallet RPCs are also prone to rate-limiting, and other attacks. I'm not sure if falling back to a wallet RPC is ideal.

**Comment by liarco** [comment]
Thank you very much @jxom for your kind reply.

> I don't think `cloudflare-eth.com` itself has been deprecated, but rather, "hostnames that point to cloudflare-eth.com`.

I get what you mean, I probably misunderstood what they mean with the deprecation notice.

---
 
> Can you provide a minimal reproducible example via a CodeSandbox or something for this so we can have a look into it? From first glance, it looks like the RPC node doesn't support returning contract calls that return data exceeding 100000 bytes (0.1MB).

I confirm your are right, we were concerned because those exact calls (with the same payload size) worked just fine until a few days ago and we couldn't find any news about the change.

Here is a very rough snippet that produces a big result:
```
(new ethers.Contract('0x06214FC62B4478a829Ac585EF780b09098fC0557', ['function getGenesisTokensData(uint256 _startId, uint256 _endId) public view returns (tuple(uint256 tokenId,address owner,bool hasClaimed)[] memory)'], new ethers.providers.StaticJsonRpcProvider('https://cloudflare-eth.com/'))).getGenesisTokensData(1, 5800).then(console.log);
```
It can be pasted and run on https://playground.ethers.org/

At the time of writing this is producing a pretty big output (but it works) and it's the same call that started failing the other day (we were requesting a smaller subset by passing `1, 4444` as params). Maybe CF is adapting limits based on workload?

Of course making such heavy calls is far from ideal, so we moved to a better solution, but this is just to explain what triggered our concerns.

---

> You can mitigate "DDoS attacks" by adding a domain whitelist to your Alchemy/Infura project.

If I get what you mean, that doesn't solve the problem... For instance, I just got the endpoint from LooksRare, here is what happens if I send a request using CURL:

```bash
$ curl https://eth-mainnet.alchemyapi.io/v2/PJg1rgLNmb76t_zt1uFirpS-1TXoYKMZ -H "Content-Type: application/json" --data '{"jsonrpc":"2.0","method":"eth_blockNumber","params":[],"id":1}'

{"jsonrpc":"2.0","id":1,"error":{"code":-32000,"message":"Unspecified origin not on whitelist."}}%
```

This means we can't use that RPC on any dapp with a custom domain, but if I can still add an `origin` header to make it work with a back end script:

```bash
$ curl https://eth-mainnet.alchemyapi.io/v2/PJg1rgLNmb76t_zt1uFirpS-1TXoYKMZ -H "Content-Type: application/json" -H "Origin: https://looksrare.org" --data '{"jsonrpc":"2.0","method":"eth_blockNumber","params":[],"id":1}'

{"jsonrpc":"2.0","id":1,"result":"0xfbe8e8"}%
```

This means I would be able to attack a brand by getting their endpoint and making a lot of requests so that:
1. their dapp stops working once reached to the billing/request limit
2. the brand would end up having a huge bill to pay for the requests that have been made

This might not be a problem for a big company, but might be much more impactful for a smaller business... Am I wrong?

---

> Unfortunately, some injected wallets do not support _all_ public RPC methods, including the one that `useContractRead` uses (eth_call). Injected wallet RPCs are also prone to rate-limiting, and other attacks. I'm not sure if falling back to a wallet RPC is ideal.

Thank you for the info, didn't know that some wallets could lack those features. That's a pity since being able to bring your own RPC node from the wallet would make dapps much more decentralized IMHO...

**Comment by montanaflynn** [comment]
> Unfortunately, some injected wallets do not support all public RPC methods, including the one that useContractRead uses (eth_call). Injected wallet RPCs are also prone to rate-limiting, and other attacks. I'm not sure if falling back to a wallet RPC is ideal.

Is there any public resource regarding what rpc methods common wallets do or do not support? We would also love to offload calls to the wallet RPC if possible, this could also greatly reduce costs.
