### ISSUE TITLE
bug: Hydration errors on Next.js

### ISSUE THREAD

**Issue by JDansercoer** [wagmi-dev/wagmi#1739]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.11.0

### Current Behavior

Error pops up stating that there is a mismatch between the server HTML and the client-renderend HTML

### Expected Behavior

Hydration should work perfectly fine

### Steps To Reproduce

Open up the repo, run it locally and you'll be instantly greeted with the error.

All code was taken from the wagmi docs.

### Link to Minimal Reproducible Example (CodeSandbox, StackBlitz, etc.)

https://github.com/JDansercoer/wagmi-test-next

**Comment by Raiden1411** [comment]
Check the issue #542 for potential solutions and reasons why this is happening
