### ISSUE TITLE
bug: wagmi generate gives out errors

### ISSUE THREAD

**Issue by ngmisl** [wagmi-dev/wagmi#1759]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.1.2

### Current Behavior

`yarn wagmi generate`

require() of ES Module /home/c/dev/solidity/en/node_modules/@wagmi/cli/dist/index.js from /home/c/dev/solidity/en/wagmi.config.bundled_4wbftmawep3.cjs not supported.
Instead change the require of index.js in /home/c/dev/solidity/en/wagmi.config.bundled_4wbftmawep3.cjs to a dynamic import() which is available in all CommonJS modules.
error Command failed with exit code 1.

config:

```
import { defineConfig } from "@wagmi/cli";
import { hardhat } from "@wagmi/cli/plugins";

export default defineConfig({
  plugins: [
    hardhat({
      project: "../en",
    }),
  ],
});

```

### Expected Behavior

work

### Steps To Reproduce

see current behavior

### Link to Minimal Reproducible Example (CodeSandbox, StackBlitz, etc.)

https://wagmi.sh/cli/plugins/hardhat

**Comment by tmm** [comment]
Can you put together a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) and reopen this issue?

Here's a basic Hardhat wagmi CLI project that works fine: https://github.com/tmm/wagmi-hardhat

**Comment by paOol** [comment]
getting this as well after upgrading WAGMI to latest (v11), and using NextJS

**Comment by jummy123** [comment]
I also get this when I try to instantiate the `hardhat` plugin.

Contents of _wagmi.config.js_
```
import { hardhat } from '@wagmi/cli/plugins'

export default {
  out: 'src/generated.ts',
  contracts: [],
  plugins: [hardhat({
	project: '../../rbd-game',
  })],
}
```

When I try to run ` yarn run wagmi generate` I get the following error

> require() of ES Module node_modules/@wagmi/cli/dist/plugins/index.js from /wagmi.config.bundled_scm0x8b940k.cjs not supported.
Instead change the require of index.js in wagmi.config.bundled_scm0x8b940k.cjs to a dynamic import() which is available in all CommonJS modules.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

I'm using node v18.15.0 and @wagmi/cli 0.1.14

**Comment by jummy123** [comment]
As additional context, if I remove the hardhat plugin import and the related config the generate command succeeds for me.

**Comment by jummy123** [comment]
If anyone stumbles across this I fixed the issue by adding `"type": "module"` to my package.json, I'm not experienced enough with js to know why this worked.
