### ISSUE TITLE
bug: Building a hooks package that uses wagmi as a dependency, does not find provider

### ISSUE THREAD

**Issue by rafinskipg** [wagmi-dev/wagmi#1781]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

latest

### Current Behavior

We have developed a hooks package that uses wagmi : https://github.com/makerdao-dux/metadao-frontend (see packages /hooks folder), this package works well in development mode, (the app has the wagmi provider and the hooks package uses wagmi correctly). But when we build the application, for some reason the bundled code will not find the wagmi provider and will always complain about "No wagmi client found. Ensure you have set up a client"

Do you have any recomendation on how to bundle a package that uses wagmi as a dependency? 

### Expected Behavior

The hooks library can find the wagmi provider. 

### Link to Minimal Reproducible Example (CodeSandbox, StackBlitz, etc.)

https://github.com/makerdao-dux/metadao-frontend

**Comment by rafinskipg** [comment]
Similar issues: https://github.com/wagmi-dev/wagmi/issues/1491

**Comment by jxom** [comment]
You'll want to make `wagmi` a `peerDependency` instead of a `dependency`.

**Comment by rafinskipg** [comment]
@jxom  You are the master of the universe. Thanks for helping. Would be nice to have that documented somewhere as an example. (Pnpm setup with wagmi). 

Unless another exist and i didn't see it because i was lazy to search
