### ISSUE TITLE
bug: missing revert data for useContractWrite

### ISSUE THREAD

**Issue by dataexcess** [wagmi-dev/wagmi#1783]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

^0.11.0

### Current Behavior

I am using the useContractPrepareWrite & useContractWrite hook to call a write method on my contract. I am (deliberately) passing faulty arguments and a require() statement is triggered in my contract. In my frontend code the isSuccess isError values are not changed... and the error (or prepareError) are not populated. In the console the following is printed:

`query.mjs?b367:293 Error: missing revert data in call exception; Transaction reverted without a reason string [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (data="0x", transaction={"from":"xxxxx","to":"xxxxx","type":2,"accessList":null}, error={"reason":"processing response error","code":"SERVER_ERROR","body":"{\"jsonrpc\":\"2.0\",\"id\":65,\"error\":{\"code\":-32000,\"message\":\"execution reverted\"}}\n","error":{"code":-32000},"requestBody":"{\"method\":\"eth_call\",\"params\":[{\"type\":\"0x2\",\"from\":\"xxxxx\",\"to\":\"xxxxx\"},\"0x2b1c82\"],\"id\":65,\"jsonrpc\":\"2.0\"}","requestMethod":"POST","url":"https://rpc.sepolia.org"}, code=CALL_EXCEPTION, version=providers/5.7.2)`

### Expected Behavior

I would expect wagmi to somehow catch the smart-contract error and display it in the frontend. The error catching is working perfectly with a useContractRead. With a useContractWrite() however it does not seem to do anything.

It seems that it is maybe not possible at all to catch these errors?
https://github.com/ethers-io/ethers.js/discussions/3300
https://github.com/ethers-io/ethers.js/issues/446

However, if this is truly the case that this is not possible, then might I ask what is the function of the isError and error variables of the useContractWrite? What is it actually used for? Is it possible to catch these contract-write require errors in the frontend with a meaningful message or not? 

Thank you!

**Comment by tmm** [comment]
Thanks for reporting. This issue is temporarily closed due to lack of information. Please provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) and reopen this issue.
