### ISSUE TITLE
bug: Module not found: Package path ./lib/utils.js is not exported from package with ethers 6

### ISSUE THREAD

**Issue by olivierlesnicki** [wagmi-dev/wagmi#1785]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.11.3

### Current Behavior

An error is thrown when using wagmi and connectkit with NextJS13.

```
./node_modules/@wagmi/connectors/dist/chunk-LNIFBRWC.js:21:0
Module not found: Package path ./lib/utils.js is not exported from package /node_modules/ethers (see exports field in /node_modules/ethers/package.json)

Import trace for requested module:
./node_modules/@wagmi/connectors/dist/metaMask.js
./node_modules/@wagmi/core/dist/connectors/metaMask.js
./node_modules/wagmi/dist/connectors/metaMask.js
./node_modules/connectkit/build/index.es.js

https://nextjs.org/docs/messages/module-not-found
```

### Expected Behavior

No errors.

**Comment by will-holley** [comment]
Appears to be related to the release of Ethers 6.0.0 about 12 hours ago. Downgrading to ethers@5.7.2 fixed the issue for me.

**Comment by tmm** [comment]
wagmi supports ethers >=5.5.1 <6. updating the version to reflect that in https://github.com/wagmi-dev/wagmi/pull/1786

**Comment by lekevicius** [comment]
Had same bug. Downgraded to ethers v5 for now, but would like better communication of intentions rather than npm i wagmi ethers@"<6". Is there a plan to support ethers v6? Or perhaps to encode ethers v5 as a dependency, not a peer?

(sorry for duplicating my comment, not sure which is the canonical issue to discuss ethers v6)

**Comment by will-holley** [comment]
+1 on Dependency instead of Peer.

**Comment by kecerud** [comment]
Same problem here and would prefer a plan for solution rather than "just downgrade" and closing the issue..

**Comment by tmm** [comment]
See https://github.com/wagmi-dev/wagmi/discussions/1782#discussioncomment-4865750. ethers v6 was released recently and is not stable enough for us to use in wagmi yet.
