### ISSUE TITLE
bug: vite 4 wagmi/ethers error

### ISSUE THREAD

**Issue by danilo-89** [wagmi-dev/wagmi#1790]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.11.4

### Current Behavior

Vite v4.1.1 (React + Typescript) with Wagmi throws the following error:

```
✘ [ERROR] [plugin vite:dep-pre-bundle] Missing "./lib/utils.js" specifier in "ethers" package

    node_modules/@wagmi/connectors/dist/metaMask.js:18:27:
      18 │ import { getAddress } from "ethers/lib/utils.js";
         ╵                            ~~~~~~~~~~~~~~~~~~~~~

  This error came from the "onResolve" callback registered here:

    node_modules/esbuild/lib/main.js:1287:20:
      1287 │       let promise = setup({
...
```

**App.tsx:**
```
import { configureChains, createClient, WagmiConfig } from 'wagmi';
import { publicProvider } from 'wagmi/providers/public';
import { MetaMaskConnector } from 'wagmi/connectors/metaMask';
import { polygonMumbai } from 'wagmi/chains';

const { chains, provider, webSocketProvider } = configureChains(
	[polygonMumbai],
	[publicProvider({ priority: 0 })]
);

const client = createClient({
	autoConnect: true,
	connectors: [new MetaMaskConnector({ chains })],
	provider,
	webSocketProvider,
});

function App() {
	return (
		<WagmiConfig client={client}>
			<div className='App'>test</div>
		</WagmiConfig>
	);
}

export default App;
```

### Expected Behavior

No error should occur.

### Steps To Reproduce

Create vite 4 (React + TS) project, add wagmi and ethers, and replace provided App.tsx code.

**Comment by tmm** [comment]
Check your ethers version. wagmi does not support `ethers@6`. See https://github.com/wagmi-dev/wagmi/issues/1785 for more info.

**Comment by danilo-timacum** [comment]
@tmm , thank you.

Maybe it should be added to the documentation (Manual setup > [Installation](https://wagmi.sh/react/getting-started#installation)):
`npm i wagmi ethers@"<6"`

**Comment by lekevicius** [comment]
Had same bug. Downgraded to ethers v5 for now, but would like better communication of intentions rather than `npm i wagmi ethers@"<6"`. Is there a plan to support ethers v6? Or perhaps to encode ethers v5 as a dependency, not a peer?

**Comment by AndreaBarghigiani** [comment]
mmm strange, I have the `^5.7.2` so it should not be a version issue. Does not matter what chain I try to use I always get: 
`ambiguous indirect export: <chain>`

**Comment by tmm** [comment]
That seems like a different potential error. Please open an issue with a minimal reproducible example if so.

**Comment by TetianaMolchanova** [comment]
I have this error with the last ethers version: "ethers": "^6.7.0",
import { utils, FixedNumber } from "/node_modules/.vite/deps/ethers.js?v=56c81247";

Uncaught SyntaxError: The requested module '/node_modules/.vite/deps/ethers.js?v=56c81247' does not provide an export named 'utils' (at Erc20.js:6:10)
