### ISSUE TITLE
bug: Ethers 6 breaks wagmi's imports

### ISSUE THREAD

**Issue by miguelangelrm** [wagmi-dev/wagmi#1796]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.11.4

### Current Behavior

Ever since ethers' new release (^6.0.0) wagmi's imports no longer work as expected.

```
Module not found: Package path ./lib/utils.js is not exported from package /Users/kinsyu/Documents/repos/dapp-tester/node_modules/.pnpm/@wagmi+connectors@0.2.4_q4u6clpx23gazeqfv5gq2oysei/node_modules/ethers (see exports field in /Users/kinsyu/Documents/repos/dapp-tester/node_modules/.pnpm/@wagmi+connectors@0.2.4_q4u6clpx23gazeqfv5gq2oysei/node_modules/ethers/package.json)

Import trace for requested module:
./node_modules/.pnpm/@wagmi+connectors@0.2.4_q4u6clpx23gazeqfv5gq2oysei/node_modules/@wagmi/connectors/dist/injected.js
./node_modules/.pnpm/@wagmi+core@0.9.4_ujjxpo3ngpb4gvccdlzmzf5ac4/node_modules/@wagmi/core/dist/chunk-BVC4KGLQ.js
./node_modules/.pnpm/@wagmi+core@0.9.4_ujjxpo3ngpb4gvccdlzmzf5ac4/node_modules/@wagmi/core/dist/index.js
./node_modules/.pnpm/wagmi@0.11.4_kbvu5rndqizvb7gvhcw64ioaam/node_modules/wagmi/dist/index.js
```

### Expected Behavior

Expected it to work.

### Steps To Reproduce

Follow the steps outlined on the [getting started](https://wagmi.sh/react/getting-started) page.

### Anything else?

This issue can be easily fixed by installing ethers@5.7.2, the last stable release before ethers 6

**Comment by miguelangelrm** [comment]
Didn't check closed issue 😵‍💫

**Comment by rafinskipg** [comment]
so what's the answer? @miguelangelrm
