### ISSUE TITLE
bug: Wallet connector on mobile error

### ISSUE THREAD

**Issue by hoangman1108** [wagmi-dev/wagmi#1810]
### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Package Version

0.11.4

### Current Behavior

step 1: import wallet connect 
step 2: using metamask or trust wallet enter to walletconnector
now i get error with message: Unhandled Runtime Error
TypeError: undefined is not an object (envaluating '_walletconnect_enviroment_WEBPACK_IMPORTED_MODULE_0....)

**Comment by jxom** [comment]
Thanks for reporting. Can you please provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) via a CodeSandbox or repository. Will reopen when done!

**Comment by hoangman1108** [comment]
https://codesandbox.io/s/divine-dew-z95twt?file=/src/App.tsx:0-1000

i clone from my nextjs. but on react it work fine

**Comment by hoangman1108** [comment]
https://github.com/WalletConnect/walletconnect-monorepo/issues/1908

i check your lib using in package. and got 1 problem with nextjs on wallet connector

**Comment by hoangman1108** [comment]
thanks. i can reslove it.

it problem happen when using http. 
walletconnector just working on https.

**Comment by amzfcy** [comment]
> 

Will this warning persist in the local environment?
