### ISSUE TITLE
Connect to Fortmatic Wallet

### ISSUE THREAD

**Issue by nuCode-Z** [wagmi-dev/wagmi#1811]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.1.5

### Current Behavior

Cannot find a reference to connect a Fortmatic or a Magic wallet.

### Expected Behavior

Being able to connect to Fortmatic or Magic wallet

**Comment by jxom** [comment]
Check out https://github.com/EveripediaNetwork/wagmi-magic-connector
