### ISSUE TITLE
After npm i wagmi i get bunch of weird errors

### ISSUE THREAD

**Issue by nalnir** [wagmi-dev/wagmi#1814]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.11.5

### Current Behavior

I use wagmi in connection with @rainbow-me/rainbowkit package, but anytime I npm i wagmi, my app just spews out like over 100 errors that are similar to each other. They look something like this:

```
WARNING in ../../node_modules/@metamask/safe-event-emitter/index.js
Module Warning (from ../../node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '../node_modules/@metamask/safe-event-emitter/index.ts' file: Error: ENOENT: no such file or directory, open '../node_modules/@metamask/safe-event-emitter/index.ts'

WARNING in ../../node_modules/@walletconnect/browser-utils/dist/esm/browser.js
Module Warning (from ../../node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '../node_modules/@walletconnect/browser-utils/src/browser.ts' file: Error: ENOENT: no such file or directory, open '../node_modules/@walletconnect/browser-utils/src/browser.ts'

WARNING in ../../node_modules/@walletconnect/browser-utils/dist/esm/index.js
Module Warning (from ../../node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '../node_modules/@walletconnect/browser-utils/src/index.ts' file: Error: ENOENT: no such file or directory, open '../node_modules/@walletconnect/browser-utils/src/index.ts'

...

```

I saw a similar thread here. Supposedly it has to with webpack. I use nx monorepo with react app. I tried the suggested way to circumvent this issue which was to use the command in package.json like so:

```
"scripts": {
    "start": "GENERATE_SOURCEMAP=false && nx run crypies:serve",
```

But that did not solve it. Now the app works well even with the issue, but it would definitely be nice, not to have these error.

**Comment by tmm** [comment]
These come from upstream packages and not wagmi directly.
