### ISSUE TITLE
bug: Wagmi CLI doesn't work with version 6.x of ethers

### ISSUE THREAD

**Issue by roninjin10** [wagmi-dev/wagmi#1835]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.1.6

### Current Behavior

On version 6 of ethers I get this error.  Downgrading to version 5.x fixes it

![image](https://user-images.githubusercontent.com/35039927/218287651-8ededf2a-f3af-42ca-97f1-a2dd3c04c2eb.png)

When we look in ethers.js we see it's a pretty easy fix of just changing `/lib/utils` to `/utils`

https://github.com/ethers-io/ethers.js/blob/main/package.json#L81

### Expected Behavior

Should be able to import ethers

### Steps To Reproduce

Install ethers v6 as a peer dep to wagmi cli

### Link to Minimal Reproducible Example (CodeSandbox, StackBlitz, etc.)

https://github.com/roninjin10/stax/tree/6496188567c976a1729276d5d01c51ea39512600/packages/contracts

**Comment by roninjin10** [comment]
This is a pretty annoying error btw because changing fixing this for v6 is a breaking change to wagmi.   Not sure the best way to handle it actually

**Comment by roninjin10** [comment]
Perhaps just import from `ethers`  and take the bundle hit now for compatibility?   Or just close this ticket and list ethers v6 as not compatibile with wagmi to wagmi 1.0?

**Comment by jxom** [comment]
Yeah, wagmi is only compatible with v5 right now. Would like to wait until v6 is stable enough for us.

**Comment by rafinskipg** [comment]
> Yeah, wagmi is only compatible with v5 right now. Would like to wait until v6 is stable enough for us.

do you have any ETA when this will happen? We are building some products on top of wagmi + ethers and a bit worried by the impact of a later migration

**Comment by tmm** [comment]
@rafinskipg no timeline. `ethers@6` is not considered stable yet.
