### ISSUE TITLE
bug: overrides value doesn't work when a contract function expects arguments but wasn't provided.

### ISSUE THREAD

**Issue by yassinrahim** [wagmi-dev/wagmi#1837]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.11.4

### Current Behavior

Say that we have a payable contract function called mint, and it expects an argument, if it's not provided, upon executing the write function, you'll notice that in wallet and in committed transaction that value passed is 0 despite value defined in the overrides config.

```js
const feeValue = ethers.utils.parseEther('0.01')

const { config: mintConfig } = usePrepareContractWrite({
		address: contractAddresses[chain ? chain.id.toString() : "1337"][0],
		abi,
		functionName: "mint",
		// args: ["XX"],
		overrides: {
			value: feeValue,
		},
	});

const { write } = useContractWrite(mintConfig);

write();
```

### Expected Behavior

Value to be passed but arguments to be empty.

**Comment by jxom** [comment]
What is the address of the contract you are using?

**Comment by yassinrahim** [comment]
> What is the address of the contract you are using?

I forgot to mention that I tested on a hardhat local network. So, unfortunately, giving the address here would be irrelevant. But I believe the issue should be reproducible in any contacts with a payable function that accepts an argument.

**Comment by jxom** [comment]
I can't seem to reproduce this. Seems to be working for me. 
Can you please provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) via a CodeSandbox or a separate repo? That would help a lot.

Will reopen when done!
