### ISSUE TITLE
TypeError when calling useSigner then useContract

### ISSUE THREAD

**Issue by muskScent** [wagmi-dev/wagmi#1840]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.11.5

### Current Behavior

I created the following custom hook (inspired by this: https://wagmi.sh/react/hooks/useSigner): 

```js
export const useSignedContract = () => {
  const { data: signer, isError, isLoading } = useSigner();

  const contract = useContract({
    address: "ADDRESS",
    abi: myABI,
    signerOrProvider: signer,
  });

  return contract;
};
```

This throws the following error: 
```
TypeError: Cannot read properties of null (reading 'call')
    at Contract.eval (index.js?b70c:291:1)
    at Generator.next (<anonymous>)
    at fulfilled (index.js?b70c:5:43)
```

As far as I understood, this is because signer is initially null.

I don't see any trivial solution to this due to the rule specifying that hooks should run in the same order.

### Expected Behavior

No thrown error by useContract

### Steps To Reproduce

Copy my custom hook code and use it.

**Comment by jxom** [comment]
I can't seem to reproduce the error with the snippet you provided above. Can you please provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) via a CodeSandbox or a separate repository?

Will reopen when done!
