### ISSUE TITLE
Wagmi CLI creates hooks that have unknown return types for typescript

### ISSUE THREAD

**Issue by Amirjab21** [wagmi-dev/wagmi#1842]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.8.6

### Current Behavior

The hooks work fine but there are no typescript types defined on the read results which is very annoying.

### Expected Behavior

It should use the ABIs to infer the return types.

**Comment by tmm** [comment]
`@wagmi/cli` React Plugin only works with `wagmi@>=0.11`

**Comment by Amirjab21** [comment]
> `@wagmi/cli` React Plugin only works with `wagmi@>=0.11`

Thanks for that prompt response which fixes the issue.

We're currently using wagmi with Rainbowkit which requires wagmi 0.9.x

Does this mean wagmi/CLI hooks are currently incompatible with Rainbowkit?

**Comment by tmm** [comment]
As long as `wagmi@>=0.11` is used, it is compatible.
