### ISSUE TITLE
docs: 404 link for connectors

### ISSUE THREAD

**Issue by MananTank** [wagmi-dev/wagmi#1850]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.11.5

### Current Behavior

<img width="701" alt="image" src="https://user-images.githubusercontent.com/22043396/218661152-72edf334-8c50-4e68-8bc7-87c957b4ca66.png">

https://wagmi.sh/react/connectors/walletconnect#options

<img width="830" alt="image" src="https://user-images.githubusercontent.com/22043396/218661203-765442cb-3bd9-4928-891f-9c7bedfeb166.png">

**Comment by byteHulk** [comment]
hi @tmm  can I take on this issue?

**Comment by tmm** [comment]
Go for it!

**Comment by tmm** [comment]
Completed in #1870
