### ISSUE TITLE
Remove external references from package meta data - codeload.github.com 

### ISSUE THREAD

**Issue by VamshikrishDanam** [wagmi-dev/wagmi#1854]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.11.5 

### Current Behavior

Hey Team, we are trying to include wagmi package in our application. While installing this package in our network we are getting network timed out error as it is trying to access one of it's transient dependency from codeload.github.com which is restricted in our network.

Error:
npm ERR! code ETIMEDOUT
npm ERR! network request to https://codeload.github.com/ethereumjs/ethereumjs-abi/tar.gz/ee3994657fa7a427238e6ba92a84d0b529bbcde0 failed, reason: connect ETIMEDOUT 140.82.114.10:443
npm ERR! network This is a problem related to network connectivity.

### Expected Behavior

We want to install wagmi and enable wallet connect in our application. 

As we analyzed, it is because of this following line: https://github.com/MetaMask/eth-sig-util/blob/1.x/package.json#L24 that codeload.github.com reference is hardcoded into the package meta data.

We believe, one possible solution for this issue is, if we can upgrade wagmi to have all external dependencies within the package instead of using external github references.

### Steps To Reproduce

If we try to install wagmi with common command, npm i wagmi within our ecosystem we are getting this error. 

Error:
npm ERR! code ETIMEDOUT
npm ERR! network request to https://codeload.github.com/ethereumjs/ethereumjs-abi/tar.gz/ee3994657fa7a427238e6ba92a84d0b529bbcde0 failed, reason: connect ETIMEDOUT 140.82.114.10:443
npm ERR! network This is a problem related to network connectivity.

**Comment by tmm** [comment]
Looks like this is from an upstream dependency we don't control. Best to raise an issue over there.
