### ISSUE TITLE
bug: Website Crash when connecting Wallet with Wagmi + Thirdweb + RainbowKit

### ISSUE THREAD

**Issue by theArtechnology** [wagmi-dev/wagmi#1858]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.11.5

### Current Behavior

When connecting a wallet, the website freezes until it crashes.

This is due to that ?

<img width="939" alt="Screenshot 2023-02-15 at 12 53 24" src="https://user-images.githubusercontent.com/26553194/218998944-dec15fa5-16fb-4bdf-9c1c-cd29a199d339.png">

When finding the main cause, it is because of `useAccount()`. I don't know why. But here some more screenshots:

<img width="610" alt="Screenshot 2023-02-15 at 12 33 25" src="https://user-images.githubusercontent.com/26553194/218999199-27d707de-f25d-4c3f-b07a-4b85b25f5b8c.png">
<img width="937" alt="Screenshot 2023-02-15 at 12 43 09" src="https://user-images.githubusercontent.com/26553194/218999266-60c05562-0c2f-48b0-acea-c954eda3ccbe.png">
<img width="945" alt="Screenshot 2023-02-15 at 12 42 46" src="https://user-images.githubusercontent.com/26553194/218999283-3c0f54a6-e550-41b9-8ae6-eea336273b5a.png">

### Expected Behavior

When connecting to the website, nothing should happen. It should connect without issue and no crash.

### Steps To Reproduce

Use wagmi, ethers, thirdweb sdk and react packages.

(using the example below)

Connect your wallet to rainbow kit, wait for few seconds, the website crashes.

On stackblitz, the page should be open outside of the iframe.

### Link to Minimal Reproducible Example (CodeSandbox, StackBlitz, etc.)

https://stackblitz.com/edit/nextjs-jfx8b2?file=pages/index.js

**Comment by MananTank** [comment]
@theArtechnology 
You are trying to save a huge string (5.1MB+) in local storage
![image](https://user-images.githubusercontent.com/22043396/219099932-d6be33fb-457d-4836-98db-542913365b4a.png)

this is probably because either the value itself is a huge object or the fact that it contains a recursive structure which is havings issues with serialization : 

![image](https://user-images.githubusercontent.com/22043396/219100010-05cecc71-56b3-42b4-91a0-e894e66fcf50.png)

**Comment by tmm** [comment]
`@thirdweb-dev/react` is [not compatible](https://github.com/thirdweb-dev/js/blob/main/packages/react/package.json#L123) with more recent versions of wagmi
