### ISSUE TITLE
bug: chain is undefined if no wallet connected

### ISSUE THREAD

**Issue by aalmada** [wagmi-dev/wagmi#1859]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.11.5

### Current Behavior

Using `const { chain } = useNetwork()`, `chain` is undefined when no wallet is connected.

But, using `const provider = useProvider();`, `provider.network.chainId` contains the ID of the active chain and `provider.chains` contains the list of chains. It's then possible to get the `chain`.

### Expected Behavior

Shouldn't `useNetwork()` return the active network even when no wallet is connected? The network has all the required information.

### Steps To Reproduce

To get the block explorer, I developed this hook to work around this issue:

``` typescript
import { useMemo } from "react";
import { useProvider } from "wagmi";

const useBlockExplorers = () => {
	const provider = useProvider();

	return useMemo(() => {
		const chains = provider.chains;
		const chainId = provider.network.chainId;
		const chain = chains?.filter(item => item.id === chainId);

		if (chain && chain.length !== 0) return chain[0].blockExplorers;

		return undefined;
	}, [provider]);
};

export default useBlockExplorers;
```

**Comment by tmm** [comment]
> Shouldn't `useNetwork()` return the active network even when no wallet is connected? The network has all the required information.

`useNetwork` only returns info if a connector is connected.

**Comment by duanescarlett** [comment]
I noticed this exact problem, useNetwork() has no attribute called chain, but this was working lastnight, so it seems to me that something has changed in one of the core dependencies and it has been breaking a lot of applications.

**Comment by aalmada** [comment]
Basically I want to have a button that takes the user to the Etherscan page of a given smart contract and trying to use the URL provided by wagmi. This should not require a connected wallet. This should also work when retrieving public data from a smart contract.

To my best understanding, wagmi will default to the first chain in the first array passed to `configureChains`. It will also try to use one of the providers passed on the second array. I'm adding both Infura and Alchemy providers.

@tmm If by design `useNetwork` should not work, should I keep using `useProvider`?

@duanescarlett  `useNetwork` has a `chain` attribute: https://wagmi.sh/react/hooks/useNetwork

Thanks!

**Comment by duanescarlett** [comment]
@aalmada I know this that is why there is an issue

**Comment by tmm** [comment]
You can keep using `useProvider` or you can create some global state in your app to keep track of the "activeChain" and keep it synced up with `useNetwork().chain`.

**Comment by aalmada** [comment]
I was now creating a custom `useChainId` to encapsulate my logic when I found that wagmi already provides one but that is now listed at https://wagmi.sh/react/hooks/useAccount
It works as I expected, not needing a connect wallet.
