### ISSUE TITLE
bug: allowFailure typesafety

### ISSUE THREAD

**Issue by matthewlilley** [wagmi-dev/wagmi#1866]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.8.1

### Current Behavior

I'm unsure if this has been resolved in subsequent versions of wagmi, but I have come across a few examples where the illusion of type safety is quite dangerous...

A simple example is to turn on allowFailure, the type remains the same. Most often it seems that when a call fails it introduces null into the list of results, but I've even come across undefined in some cases. Though the expected type is still for example BigNumber[]. This is quite dangerous.

### Expected Behavior

Turning on allowFailure doesn't change the type, though it should be known at this point that the type has to change.

### Steps To Reproduce

Turn on allowFailure

**Comment by tmm** [comment]
> Turning on allowFailure doesn't change the type, though it should be known at this point that the type has to change.

Good point. Seems like we should change the result to be a `Type | null` for each output in the array.

**Comment by tmm** [comment]
[TypeScript Playground](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgVwM4FMDCEB2MoCGAxjAEroEAmqANHOlEQEwAMAggEICScAvnADMoEEHADkAdwIBzEMDEBYAFDKiuVPCSUCMAnzgBeFBmx5CJclVQAKBMrhwCAGycQJAMQLAnyKOgBccPjI6DT2cGpmxDCogQDa4Q52Sg6pjgBGwIEMzOzcYSlpgsg4JMC4AHIEIAHi6c4EpegA8gJiBUWOUNKxcHFiLAAegGQEYgC6Ham8k0mJqQSZ2YysnFwzqQIlZZXVtWIwELpOAMrIYGBOAJ7tc9PhE8q8AJTKAPSvcBIAFug4cAAGzlcHi8Pj8gWC6H+AO0umhqC+EGQTkocHSATeH3+kQ0cFhBHimWkwDwcAAPnAcMinHQiST4BSqS4xuSUDhKOgBCT0JR-pi4CSNBRURABP5lPj+QA9AD8yiAA) with expected result if anyone wants to pick this up:

```ts
import { useContractReads, erc20ABI } from 'wagmi'

const { data } = useContractReads({
  allowFailure: true,
  contracts: [
    {
      abi: erc20ABI,
      functionName: 'balanceOf',
      args: ['0x…'],
    },
    {
      abi: erc20ABI,
      functionName: 'totalSupply',
    },
  ],
})
// when `allowFailure: true` `data` should be:
// `const data: [bigint | null, bigint | null] | undefined`
// instead of:
data
// ^? const data: [bigint, bigint] | undefined
```

**Comment by matthewlilley** [comment]
I have to find an example of undefined getting into the results too, this does happen but unsure why and is rarer than the expected case of null. We must guard against null and undefined when allowFailure is true to avoid unexpected behaviour.

**Comment by tmm** [comment]
Sure thing! If you do find it, can you create a separate issue? (Since it deals with the runtime behavior.)

**Comment by roninjin10** [comment]
I've seen undefined too before many many months ago and it when it happened to me the underlying thing happening was an Infura bug causing unexpected failures

**Comment by ameya-deshmukh** [comment]
@tmm can I take this up? :)

**Comment by tmm** [comment]
@ameya-deshmukh go for it! will assign you.

**Comment by oxcened** [comment]
Hey @tmm I took the time to work on this, hope that's ok!

**Comment by tmm** [comment]
Awesome! Will take a look.

**Comment by jxom** [comment]
Fixed in v1.
