### ISSUE TITLE
bug: metamask not valid when I have tokenpocket in my browser.

### ISSUE THREAD

**Issue by Santiago0412** [wagmi-dev/wagmi#1869]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.10.15

### Current Behavior

I have two plugin in my chrome browser:
1. metamask
2. tokenpocket

when I try to use meta mask with wagmi, it looks like this:
<img width="870" alt="image" src="https://user-images.githubusercontent.com/10152008/219554889-0992ba32-8f3c-405d-9134-b3398055dff3.png">

### Expected Behavior

if I remove the tokenpocket plugin in my chrome, it works fine like this:
<img width="1114" alt="image" src="https://user-images.githubusercontent.com/10152008/219554973-bc61e499-1859-4621-872b-55d55665d28d.png">

### Steps To Reproduce

1. install metamask in your chrome
2. install tokenpocket in your chrome
3. open https://wagmi.sh/examples/connect-wallet
4. try to sign in with metamask

### Anything else?

No

**Comment by tmm** [comment]
Unfortunately this is an issue with the state of `window.ethereum` and providers overriding each other. e.g. TokenPocket binds to `window.ethereum` so MetaMask is unable.

**Comment by TheJuze** [comment]
How can i fix this behaviour?

**Comment by TheJuze** [comment]
ф
