### ISSUE TITLE
Docs are of very less information : Please improve docs

### ISSUE THREAD

**Issue by ashishsurya** [wagmi-dev/wagmi#1876]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.11.5

### Current Behavior

For example,

for each and every hook, there is no information about parameters 

### Expected Behavior

Add information about every parameter of the hook

**Comment by jxom** [comment]
Parameters for Hooks are listed under the "Configuration" title.
https://wagmi.sh/react/hooks/useContractRead#configuration

If you mean something else – can you please elaborate?

**Comment by ashishsurya** [comment]
resolver or addr is not configured for ENS name (argument="name", value="0x[object Object],[object Object]", code=INVALID_ARGUMENT, version=contracts/5.7.0)

I am getting this error while writing to a contract.
How to resolve this?
