### ISSUE TITLE
bug: get 404 page when look at docs

### ISSUE THREAD

**Issue by TroubleSeven** [wagmi-dev/wagmi#1909]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.11.6

### Current Behavior

When i click the docs on [httsp://wagmi.sh](url),  it's auto redirect to the url : [https://wagmi.sh/zh-CN/core/getting-started](url), which is 404 page.   I think it's has some misjudgments when i18n figure out the browser language.

**Comment by tmm** [comment]
Thanks for reporting! Since we just use [Nextra](https://github.com/shuding/nextra) mostly as-is, I'm going to close this issue. If Nextra, adds a feature to make this easier/automatic, happy to adopt it.
