### ISSUE TITLE
bug: ContractMethodDoesNotExist is less than helpful

### ISSUE THREAD

**Issue by roninjin10** [wagmi-dev/wagmi#1917]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

latest

### Current Behavior

If ethers fails to populateTransaction on a populateTransaction a ContractMethodDoesNotExist error gets thrown.   There are a lot of ways for this to fail than just the method not existing however.

### Expected Behavior

Should only throw this specific of an error message when it has a low chance of being a false positive

### Steps To Reproduce

Pass in the wrong arguments or something similar to a prepare hook

### Anything else?

Might fix itself in ethers v6

**Comment by roninjin10** [comment]
I can update this to actually check to see if the contract exists before throwing the error but I think it might make sense until ethers v6 since the issue might fix itself

**Comment by jxom** [comment]
This error occurs when the contract method does not exist on the contract, or the method signature does not exist (overloads).

Will have better error messaging around this in v1.
