### ISSUE TITLE
bug: Multicall fails when a contract in call does not exist

### ISSUE THREAD

**Issue by nonseodion** [wagmi-dev/wagmi#1926]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.11.5

### Current Behavior

When I use multicall on a list of contracts, with one of them non-existing, the call fails even with `allowFailure` set to false. I am using it specifically to call `getReserves` on possible Uniswap pairs.

### Expected Behavior

I expected the call to pass and the return value for that particular contract to be null|undefined.

### Steps To Reproduce

1. Setup wagmi and call muticall with "getReserve" on these address on the Binance Smart Chain ["0x58F876857a02D6762E0101bb5C46A8c1ED44Dc16", "0x14A09BA063Ff914BeB90732e076da90613454dBD"]. You'll get this error below.
<img width="1012" alt="Screenshot 2023-02-28 at 16 42 54" src="https://user-images.githubusercontent.com/38128301/221903699-1be5b918-ef38-4069-974a-eb398f443b0c.png">

**Comment by matthewlilley** [comment]
@nonseodion you want allowFailure to be TRUE
