### ISSUE TITLE
bug: wallet involuntarily disconnects when the user switches to certain chains from inside the metamask browser extension

### ISSUE THREAD

**Issue by ryanberckmans** [wagmi-dev/wagmi#1941]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.11.3

### Current Behavior

As indicated in this thread and in https://github.com/MetaMask/metamask-extension/issues/13375, despite passing `{ shimDisconnect: true, shimChainChangedDisconnect: true }`, the wallet can still _sometimes_ involuntarily disconnect when the user switches the chain from inside the metamask browser extension.

For context,, when testing this on a mature non-wagmi app such as [Uniswap](https://app.uniswap.org/#/swap), we're able to switch (to, from) any chain in the metamask browser extension without the Uniswap UI involuntarily disconnecting.

### Expected Behavior

After connecting in the app, never spontaneously disconnect, regardless of which network a user switches to in their wallet, even if that network is unsuppoted/unconfigured in the current wagmi client instance.

### Steps To Reproduce

Non-deterministic reproduction (sometimes it disconnects, sometimes it doesn't):

1. load the link below (the only change from new.wagmi.sh is the addition of `shim/shimDisconnect: true` in Metamask connector
2. connect wallet
3. switch network between goerli and zkSyncTestnet in metamask browser extension. Sometimes it'll disconnect in the app.

### Link to Minimal Reproducible Example (StackBlitz, CodeSandbox, GitHub repo etc.)

https://stackblitz.com/edit/new-wagmi-utduc3?file=src%2Fwagmi.ts

**Comment by thebuidler** [comment]
We are also having this issue. Any progress?
