### ISSUE TITLE
bug: switchNetwork erroneously emits onSuccess instead of onError after rejecting auto network switch following auto network add

### ISSUE THREAD

**Issue by ryanberckmans** [wagmi-dev/wagmi#1942]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.11.0

### Current Behavior

When using switchNetwork to a network that's not yet in the wallet, wagmi auto pops up a network add, then:

After accepting wagmi's auto network add, but rejecting subsequent auto network switch to the added network, wagmi erroneously emits switchNetwork.onSuccess(newChain) instead of the expected switchNetwork.onError(user rejected request).

### Expected Behavior

switchNetwork.onError(user rejected request)

### Steps To Reproduce

1. switch browser metamask extension to goerli network
2. load https://stackblitz.com/edit/new-wagmi-jm7xac?file=src%2Fcomponents%2FNetworkSwitcher.tsx,src%2Fwagmi.ts
3. connect wallet
4. delete optimism goerli from your metamask's list of networks
5. click "optimism goerli" to switch to goerli -> wagmi auto pops up network add -> accept it -> wagmi auto pops up network switch -> reject it
6. search console for "switched" -> wagmi emitted switchNetwork.onSuccess instead of switchNetwork.onError(user rejected switch network request).

### Link to Minimal Reproducible Example (StackBlitz, CodeSandbox, GitHub repo etc.)

https://stackblitz.com/edit/new-wagmi-jm7xac

**Comment by tmm** [comment]
Thanks for reporting! This should take care of that: https://github.com/wagmi-dev/references/pull/180
