### ISSUE TITLE
bug: generated.ts file from adding wagmi actions is broken on wagmi-core

### ISSUE THREAD

**Issue by d1onys1us** [wagmi-dev/wagmi#1945]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

^0.9.7 (wagmi-core)

### Current Behavior

I added actions to wagmi.config.ts and the generated output file imports:
- GetContractArgs
- ReadContractConfig
- WriteContractMode
- WriteContractArgs
- WriteContractPreparedArgs
- WriteContractUnpreparedArgs
- PrepareWriteContractConfig

with errors.

### Expected Behavior

i should be able to use wagmi actions in my wagmi-core project generated from wagmi-cli

### Steps To Reproduce

after adding actions here it broke: https://github.com/d1onys1us/dapp-slaps/blob/main/packages/app/wagmi.config.ts (commented here, but if uncommented and try to use the actions it won't work)

### Link to Minimal Reproducible Example (StackBlitz, CodeSandbox, GitHub repo etc.)

https://github.com/d1onys1us/dapp-slaps/blob/main/packages/app/wagmi.config.ts 

### Anything else?

<img width="1445" alt="image" src="https://user-images.githubusercontent.com/13951458/222868912-ded52ce4-a173-4876-8711-330b707c0bff.png">

**Comment by wslyvh** [comment]
I had the same with wagmi version 0.10.0. 
I was trying to create a reproducible example, but the latest version (currently 0.12.1) solved it for me.

Hope that helps! 

Here's the repo I was preparing
https://github.com/wslyvh/wagmi-cli-test

**Comment by jxom** [comment]
Can you check if this is resolved on 0.12?

If not, can you please provide a more minimal reproducible repository w/ `pnpm create wagmi` or alike?

Will reopen when done!

**Comment by d1onys1us** [comment]
confirming this is still an issue on wagmi

**Comment by tmm** [comment]
@d1onys1us please open a new issue with reproduction if this is still a problem. It's hard to track people replying to old issues.
