### ISSUE TITLE
bug: WebSocket connection failed for URL: wss://relay.walletconnect.com

### ISSUE THREAD

**Issue by nfts2me** [wagmi-dev/wagmi#1964]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.12

### Current Behavior

Latest wagmi update (0.12.0 - https://github.com/wagmi-dev/wagmi/releases/tag/wagmi%400.12.0) breaks WS on WalletConnect.

On 0.11 we have no problems.

When using any of the connectors of the wallets with WalletConnect () we are having these issues:
![image](https://user-images.githubusercontent.com/109629895/223374073-29c3898c-50b3-4f3b-ae01-516210dde33c.png)

![image](https://user-images.githubusercontent.com/109629895/223374121-ab213a35-c21a-4919-9495-b230b127a55c.png)

No issues on wagmi@0.11

We're not using wallet connect v1, as you might imagine. 

### Expected Behavior

Don't raise the error

**Comment by marsidorowicz** [comment]
same here after update to latest

**Comment by maxaleks** [comment]
After upgrade I had the same error with WalletConnect v1 because of using the `WalletConnectConnector`. I fixed it and now both versions work correctly. My code:
```
import { WalletConnectConnector } from 'wagmi/connectors/walletConnect';
import { WalletConnectLegacyConnector } from 'wagmi/connectors/walletConnectLegacy';

const walletConnectV1 = new WalletConnectLegacyConnector({
  chains,
  options: {
    qrcode: true,
  },
});

const walletConnectV2 = new WalletConnectConnector({
  chains,
  options: {
    qrcode: true,
    projectId: process.env.REACT_APP_WALLETCONNECT_PROJECT_ID,
    name: 'My app',
    relayUrl: 'wss://relay.walletconnect.org'
  },
});

const client = createClient({
  autoConnect: true,
  provider,
  webSocketProvider,
  connectors: [walletConnectV1, walletConnectV2],
});
```

Hope this helps!

**Comment by jxom** [comment]
Yep, have a look at the migration guide for 0.12: https://wagmi.sh/react/migration-guide#012x-breaking-changes

If the error still occurs, please open a minimal reproducible example via https://new.wagmi.sh!

**Comment by hiromaily** [comment]
I started using wagmi from v0.12 and WalletConnectConnector() causes this issue.
