### ISSUE TITLE
bug: supportedChains

### ISSUE THREAD

**Issue by coovxrp** [wagmi-dev/wagmi#1973]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

latest

### Current Behavior

some of the supported chains in the wagmi documentation i've not been able to import with the 'import { mainnet } from 'wagmi/chains';' tag. 

specifically, the list says flare and flareTestnet are supported, and they will be if I build my own, but it appeared these chainsw were able to be imported directly from wagmi/chains when i read the docs. 

Thanks!

**Comment by coovxrp** [comment]
docs could explain better, i was able to figure it out after looking at the code sandbox, needed to add chain to my import from wagmi and change flare and flareTestnet to chain.flare chain.flareTestnet in the configureChains. https://codesandbox.io/s/rainbowkit-create-react-app-1vwx1r?file=/src/App.js

**Comment by coovxrp** [comment]
lol nvm that just caused more issues, my bad. now it says export chain not avail in wagmi, i dont understand tho, my imporr line matches the one in the codesandbox

**Comment by jxom** [comment]
Make sure you are on `wagmi@0.12.1` and try again. It works in the below StackBlitz. :)

https://stackblitz.com/edit/new-wagmi-hchsp9?file=src%2Fwagmi.ts
