### ISSUE TITLE
bug: typescript error when using useQuery imported from wagmi

### ISSUE THREAD

**Issue by danilo-89** [wagmi-dev/wagmi#1979]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.12.1

### Current Behavior

When importing useQuery from wagmi 

```
import { useInfiniteQuery, useQuery } from 'wagmi';
import axios from 'axios';

export async function getPosts() {
  return axios.get('http://localhost:3000/test').then((res) => res.data);
}

const Home: NextPage = () => {
  const { status, data, error, isFetching, isRefetching } = useQuery({
    queryKey: ['test'],
    queryFn: () => getPosts(),
    keepPreviousData: true,
    staleTime: 5000,
  }); 
...
```

I get following ts error:
```
No overload matches this call.
  Overload 1 of 4, '(queryKey: QueryKey, options?: (Omit<UseQueryOptions<unknown, unknown, unknown, QueryKey>, "queryKey" | "initialData"> & { initialData?: (() => undefined) | undefined; }) | undefined): UseQueryResult<...>', gave the following error.
    Argument of type '{ queryKey: string[]; queryFn: () => Promise<any>; keepPreviousData: boolean; staleTime: number; }' is not assignable to parameter of type 'QueryKey'.
      Object literal may only specify known properties, and 'queryKey' does not exist in type 'readonly unknown[]'.
  Overload 2 of 4, '(queryKey: QueryKey, options?: (Omit<UseQueryOptions<unknown, unknown, unknown, QueryKey>, "queryKey" | "initialData"> & { initialData: unknown; }) | undefined): DefinedUseQueryResult<...>', gave the following error.
    Argument of type '{ queryKey: string[]; queryFn: () => Promise<any>; keepPreviousData: boolean; staleTime: number; }' is not assignable to parameter of type 'QueryKey'.
      Object literal may only specify known properties, and 'queryKey' does not exist in type 'readonly unknown[]'.(2769)
```

when using useInfiniteQuery from wagmi, there are no errors.

### Expected Behavior

There should be no typescript errors when using useQuery imported from wagmi.

### Link to Minimal Reproducible Example (StackBlitz, CodeSandbox, GitHub repo etc.)

https://stackblitz.com/edit/next-typescript-s1l6e9?file=pages/index.tsx

**Comment by tmm** [comment]
wagmi's internal [`useQuery` API](https://github.com/wagmi-dev/wagmi/blob/main/packages/react/src/hooks/utils/query/useQuery.ts) is a bit behind the times right now so that's why it looks a bit different than what is in React Query. We'll update this soon, but for now closing as this is the expected behavior.

**Comment by sshmaxime** [comment]
@tmm But what is the expected behavior ? I cannot find anything in the docs about `useQuery`, why is that ?
