### ISSUE TITLE
bug: <Some hooks occured error>

### ISSUE THREAD

**Issue by mr-new-0509** [wagmi-dev/wagmi#1980]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.12.1

### Current Behavior

`usePrepareSendTransaction()`, `useWaitForTransaction()`, `usePrepareContractWrite()` and `useWaitForTransaction()` occured errors like this.

![image](https://user-images.githubusercontent.com/86947718/224227425-835338ca-e683-43b3-98d3-f94758701398.png)
![image](https://user-images.githubusercontent.com/86947718/224227585-4dfb4de5-061d-4386-92d8-b2b16267b640.png)

This hooks were worked when I used wagmi v0.11.7. **However, i faced this problem after upgrading wagmi version to 0.12.1.**
The language I am using is TypeScript.

### Expected Behavior

What can I do to let these hooks are worked without error like in v0.11.7?

### Steps To Reproduce

![image](https://user-images.githubusercontent.com/86947718/224227425-835338ca-e683-43b3-98d3-f94758701398.png)
![image](https://user-images.githubusercontent.com/86947718/224227585-4dfb4de5-061d-4386-92d8-b2b16267b640.png)

**Comment by jxom** [comment]
Thanks for reporting. Can you please provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) in a GitHub repository? It is a bit hard to see what is going on here from screenshots.

Will re-open when provided.

**Comment by mr-new-0509** [comment]
You fixed the error in version 0.12.2.
Thank you.
