### ISSUE TITLE
bug: onSuccess callback doesn't run when tx succeeds 

### ISSUE THREAD

**Issue by reasonmethis** [wagmi-dev/wagmi#1982]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.11.0

### Current Behavior

When tx succeeds, onSuccess doesn't run and isSuccess variable never becomes true.

### Expected Behavior

onSuccess should run on success.

### Steps To Reproduce

Create a wagmi next.js app with web3modal using create-wagmi (https://wagmi.sh/react/getting-started). Then follow the example here: https://wagmi.sh/examples/contract-write-dynamic

**Comment by reasonmethis** [comment]
Also, I'm using a local node provided by Hardhat.

**Comment by jxom** [comment]
Can you please provide a minimal reproducible example via a separate repository, with the steps to spin up your Hardhat node (is it a fork, fork block number, etc)?

Will re-open when done.
