### ISSUE TITLE
Package.json says 0.12.1-cjs but npm i doesent install cjs version

### ISSUE THREAD

**Issue by Borming** [wagmi-dev/wagmi#1986]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.12.1

### Current Behavior

Package.json says wagmi : 0.12.1-cjs but npm i doesent install cjs version

### Expected Behavior

npm i should install 0.12.2@cjs

### Steps To Reproduce

1. install wagmi with npm i wagmi@cjs 
2. remove node_modules
3. run npm i

**Comment by jxom** [comment]
Seems to work for me, and it [exists](https://www.runpkg.com/?wagmi@0.12.1-cjs).

Can you please add a minimal reproducible example via a repo if this continues to persist?
