### ISSUE TITLE
bug: Namegen conflict

### ISSUE THREAD

**Issue by norswap** [wagmi-dev/wagmi#1999]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.11.7

### Current Behavior

There are conflicts in the function name generation in the CLI-generated hooks, in particular, the following patterns can clash:

- use<Contract><Function>
- use <Contract> pattern

In particular, I ran into this with a contract called `Inventory` who had a `cardsCollection` public field, and a contract called `InventoryCardsCollection`.

### Expected Behavior

Possible fix: `use<Contract>_<function>`. If that's too ugly, `use<Contract>Call<Function>` is another possible pattern. In general, adding anything between the contract and the function (or even before/after in any of the two cases) will solve the issue.

### Steps To Reproduce

Create a contract `AB` and a contract `A` with a function `b`, generate hooks via the CLI, then use `useAB` and you'll get a Typescript compilation because of multiple definitions for the same function.

**Comment by norswap** [comment]
Yes, renaming is what I ended up doing. Didn't know about the config thing, nice workaround!

**Comment by norswap** [comment]
Could I suggest adding a reference to the array config trick in your #2000 error message? That probably will help someone to who this happens fix the issue really fast :)

**Comment by tmm** [comment]
Good idea. PR welcome if you want the credit :)

**Comment by norswap** [comment]
No need ;)
