### ISSUE TITLE
bug: Wagmi CLI generated code has type issues

### ISSUE THREAD

**Issue by akshatmittal** [wagmi-dev/wagmi#2006]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.12.1

### Current Behavior

Running `yarn wagmi generate` creates the ouput file correctly, but the file can not be compiled or have types emitted because typescript throws the following errors:

```
Return type of exported function has or is using name 'PayableOverrides' from external module "./node_modules/@wagmi/core/dist/contracts-b112c24e" but cannot be named. ts(4058)
```
```
Return type of exported function has or is using name 'CallOverrides' from external module "./node_modules/@wagmi/core/dist/contracts-b112c24e" but cannot be named. ts(4058)
```

### Expected Behavior

The generated file has non conflicting types and compiles correctly.

### Steps To Reproduce

1. Create a new project and add wagmi cli
2. Add config file with actions and react plugins (I also have the hardhat plugin enabled)
3. Run generate

### Link to Minimal Reproducible Example (StackBlitz, CodeSandbox, GitHub repo etc.)

See comment: https://github.com/wagmi-dev/wagmi/issues/2006#issuecomment-1472193395

**Comment by tmm** [comment]
Thanks for reporting. This issue is temporarily closed due to lack of information. Please provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) and reopen this issue.

**Comment by akshatmittal** [comment]
Repo: https://github.com/0xMetacrypt/metacrypt-deployer

1. `yarn install`
2. Build contracts
    - cd `apps/contracts`
    - `yarn build`
3. Switch to `deployer-sdk` package
    - cd `packages/deployer-sdk`
    - `yarn wagmi generate` (config already exists and reads hardhat project)
4. See file `packages/deployer-sdk/src/wagmi.ts` with errors.

I've also pushed an already built `wagmi.ts` file to see errors without doing all of this, if you'd prefer that. 

@tmm

**Comment by h0tw4t3r** [comment]
Raised the discussion with a repro over here: https://github.com/wagmi-dev/wagmi/discussions/2028
