### ISSUE TITLE
bug: WalletConnect Module Not Found Error

### ISSUE THREAD

**Issue by frankfka** [wagmi-dev/wagmi#2015]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.12.1

### Current Behavior

I'm currently getting the following behavior when trying to initialize `WalletConnectConnector` in a `Next.js` app:

```
../../node_modules/@walletconnect/ethereum-provider/dist/index.es.js:278:31
Module not found: Can't resolve '@web3modal/standalone'
```

### Expected Behavior

No errors

### Steps To Reproduce

Install `wagmi` and `ethers` on a Next.js app and attempt to initialize a `WalletConnectConnector`

**Comment by ShiyuCheng2018** [comment]
`npm install @web3modal/standalone` or `yarn add @web3modal/standalone`

**Comment by jxom** [comment]
Should be fixed now.

**Comment by Dalcor** [comment]
What if I use showQrModal: false, I still have to add this package to bundle?

**Comment by tmm** [comment]
Now that it's fixed, you don't need to either way.
