### ISSUE TITLE
Head tags doesn't work with Next.Js while conditionally rendering WagmiConfig

### ISSUE THREAD

**Issue by anthonyjacquelin** [wagmi-dev/wagmi#2022]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.12.1

### Link to minimal reproducible example

https://github.com/WalletConnect/web3modal/tree/V2/examples/nextjs

### Summary

When i try to add Head tags to the index.tsx file like this:
![Capture d’écran 2023-03-17 à 09 38 07](https://user-images.githubusercontent.com/39488794/225854569-3424d276-1bd5-4315-8cc0-edec9facaaf8.png)

and executes this command `curl -XGET http://localhost:3000` to check if my tags are well rendered in the dom, i get:
```
<!DOCTYPE html>
<html>
  <head>
    <style data-next-hide-fouc="true">
      body {
        display: none;
      }
    </style>
    <noscript data-next-hide-fouc="true"
      ><style>
        body {
          display: block;
        }
      </style></noscript
    >
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <meta name="next-head-count" content="2" />
    <noscript data-n-css=""></noscript>
    <script
      defer=""
      nomodule=""
      src="/_next/static/chunks/polyfills.js?ts=1679042062981"
    ></script>
    <script
      src="/_next/static/chunks/webpack.js?ts=1679042062981"
      defer=""
    ></script>
    <script
      src="/_next/static/chunks/main.js?ts=1679042062981"
      defer=""
    ></script>
    <script
      src="/_next/static/chunks/pages/_app.js?ts=1679042062981"
      defer=""
    ></script>
    <script
      src="/_next/static/chunks/pages/index.js?ts=1679042062981"
      defer=""
    ></script>
    <script
      src="/_next/static/development/_buildManifest.js?ts=1679042062981"
      defer=""
    ></script>
    <script
      src="/_next/static/development/_ssgManifest.js?ts=1679042062981"
      defer=""
    ></script>
    <noscript id="__next_css__DO_NOT_USE__"></noscript>
  </head>
  <body>
    <div id="__next"><w3m-modal></w3m-modal></div>
    <script src="/_next/static/chunks/react-refresh.js?ts=1679042062981"></script>
    <script id="__NEXT_DATA__" type="application/json">
      {
        "props": { "pageProps": {} },
        "page": "/",
        "query": {},
        "buildId": "development",
        "nextExport": true,
        "autoExport": true,
        "isFallback": false,
        "scriptLoader": []
      }
    </script>
  </body>
</html>
```
As you can see we don't get the tags under `<head>...`. After investigation i saw that it is because the whole application is conditionally rendered with the use of 
```
  {ready ? (
        <WagmiConfig client={wagmiClient}>
          <Component {...pageProps} />
        </WagmiConfig>
      ) : null}
```
in `app.tsx`

When i remove the condition, Seo work, but building the project craches like this:
![Capture d’écran 2023-03-14 à 18 36 18](https://user-images.githubusercontent.com/39488794/225855749-d6615c23-5173-49a6-97da-b8a9ed6c3110.png)

How can i handle SEO with Head tags with your NextJs code example ?

### List of related npm package versions

```
{
  "name": "nextjs-example",
  "version": "2.2.1",
  "private": true,
  "scripts": {
    "dev": "next dev"
  },
  "dependencies": {
    "@web3modal/ethereum": "2.2.1",
    "@web3modal/react": "2.2.1",
    "ethers": "5.7.2",
    "next": "13.2.4",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "wagmi": "0.12.1"
  },
  "devDependencies": {
    "@types/react": "18.0.28",
    "@types/react-dom": "18.0.11",
    "typescript": "5.0.2"
  }
}

```

### Expected Behavior

I'd like to use Wagmi with WalletConnect and Next 13 and also have the <head> tags working as i tried to check above.

### Link to minimal reproducible example

https://github.com/WalletConnect/web3modal/tree/V2/examples/nextjs

Clone this and add the Head tags in index.tsx as described

**Comment by tmm** [comment]
wagmi doesn't do anything related to html head tags. seems related to next.js. make sure you are following hydration best practices.
