### ISSUE TITLE
bug: useNetwork does not return the actual name of the chain

### ISSUE THREAD

**Issue by Mehdi-Verfaillie** [wagmi-dev/wagmi#2025]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.12.1

### Current Behavior

Currently, the `name` property returned by `useNetwork` hook provide a combinaison of "Chain" + id.
```
chain: { 
  id: 137
  name: "Chain 137"
  network: "137"
}
```

### Expected Behavior

Name should contain the actual name of the chain

### Steps To Reproduce

1. Connect with MetaMask
2. Switch from Ethereum mainnet to Polygon, Avavanche...
3. Log `chain.name` from `useNetwork`

### Link to Minimal Reproducible Example (StackBlitz, CodeSandbox, GitHub repo etc.)

https://stackblitz.com/edit/new-wagmi-tlege4?file=src/App.tsx

**Comment by tmm** [comment]
This is because the Chain is not known by the Connector. If you add it to the `configureChains` set up, it will return the actual name, etc.

**Comment by Melancholism** [comment]
> This is because the Chain is not known by the Connector. If you add it to the `configureChains` set up, it will return the actual name, etc.

@tmm I need to display the **actual name** of the current **unsupported** network(chain) that user is connected to. I also need to know the `nativeCurrency` field details to fetch the _network icon_ by its _symbol_. But none of the is possible without adding the chain to `configureChains`. How can I achieve it. Is it possible at all?

**Comment by tmm** [comment]
You could import all or a subset of chains and look it up.

```ts
import * as chains from 'wagmi/chains'

const { chainId } = useNetwork()
const unsupportedChain = chainId ? chains.find(x => x.id === chainId) : undefined
```
