### ISSUE TITLE
error trying to call smart contract functions that has onlyOwner modifier, even when the address is passed as an override

### ISSUE THREAD

**Issue by akorede12** [wagmi-dev/wagmi#2033]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

"^0.9.6"

### Current Behavior

I am trying to call a smart contract function 

`
    function addAllowedVoter(address newVoter) internal onlyOwnerOrSecondary{
        allowedVoters.push(newVoter);
    }

    function registerVoter(address [] memory newVoter) public onlyOwnerOrSecondary{
        // the person registering voters should be election creator not owner 
        for(uint i = 0; i < newVoter.length; i++ ){
            if(!voters[newVoter[i]]){
            voters[newVoter[i]] = true;
            // add new voters to the array 
            addAllowedVoter(newVoter[i]);               
            }
        }
` 

The smart contract function has a modifier 
`
        modifier onlyOwnerOrSecondary() {
        require(msg.sender == owner || msg.sender == electionCreator, "Caller is not authorized.");
        _;
    }
`

 frontend code for calling the function;

`
    const [voters, setVoters] = useState([]);
        const { config } = usePrepareContractWrite({
        address: votingContractAddress,
        abi: Votingabi.abi,
        functionName: "registerVoter",
        args: [voters],
        overrides: { from: newElectionCreator },
    });

  const { write: upload2 } = useContractWrite(config);

  async function uploadVoter2(e) {
    e.preventDefault();
    console.log(voters);

    try {
       const Add = await upload2?.();
       const tx = Add?.wait();
    }  catch (error) {
       console.error(error);
    }
  }

`

I get this error

> > next-dev.js?3515:20 
        
       Error: address is required
    at Object.mutationFn6 [as mutationFn] (index.js?d944:1453:1)
    at Object.fn (mutation.mjs?3849:85:1)
    at run (retryer.mjs?7e04:97:1)
    at createRetryer (retryer.mjs?7e04:145:1)
    at executeMutation (mutation.mjs?3849:79:35)
    at Mutation.execute (mutation.mjs?3849:136:1)

Why I am getting the error when the address is passed as an override when the function is called 
>        overrides: { from: newElectionCreator },

Am I missing something or is this a bug?

### Expected Behavior

It should call the function pasing in the override and arguments

### Steps To Reproduce

**smart contract code;** 
`    
        
   address[] public allowedVoters;

        modifier onlyOwnerOrSecondary() {
        require(msg.sender == owner || msg.sender == electionCreator, "Caller is not authorized.");
        _;
    }

    function addAllowedVoter(address newVoter) internal onlyOwnerOrSecondary{
        allowedVoters.push(newVoter);
    }
    function registerVoter(address [] memory newVoter) public onlyOwnerOrSecondary{
        // the person registering voters should be election creator not owner 
        for(uint i = 0; i < newVoter.length; i++ ){
            if(!voters[newVoter[i]]){
            voters[newVoter[i]] = true;
            // add new voters to the array 
            addAllowedVoter(newVoter[i]);               
            }
        }
`

**frontend code;** 
`
    const [voters, setVoters] = useState([]);
        const { config } = usePrepareContractWrite({
        address: votingContractAddress,
        abi: Votingabi.abi,
        functionName: "registerVoter",
        args: [voters],
        overrides: { from: newElectionCreator },
    });

  const { write: upload2 } = useContractWrite(config);

  async function uploadVoter2(e) {
    e.preventDefault();
    console.log(voters);

    try {
       const Add = await upload2?.();
       const tx = Add?.wait();
    }  catch (error) {
       console.error(error);
    }
  }

 return (

<form onSubmit={uploadVoter2}>
              
              <label>
                Voters:
                <input
                  type="text"
                  value={voters.join(",")}
                  onChange={(event) =>
                    setVoters(
                      event.target.value
                        .split(",")
                        .map((v) => ethers.utils.getAddress(v.trim()))
                    )
                  }
                />
              </label>
              <button type="submit">Register Voters</button>
            </form>
)
`

The error message; 

> next-dev.js?3515:20 
        
       Error: address is required
    at Object.mutationFn6 [as mutationFn] (index.js?d944:1453:1)
    at Object.fn (mutation.mjs?3849:85:1)
    at run (retryer.mjs?7e04:97:1)
    at createRetryer (retryer.mjs?7e04:145:1)
    at executeMutation (mutation.mjs?3849:79:35)
    at Mutation.execute (mutation.mjs?3849:136:1)

As you can see I pass the address as an override to the function but yet I still get the error.

### Anything else?

Contract is current deployed to hardhat for testing and development

**Comment by jxom** [comment]
The `address is required` error arises when you have not provided an `address` to `usePrepareContractWrite`. Please make sure this is populated. If the issue continues to persist, can you please open a Minimal Reproducible Example via https://new.wagmi.sh? Thanks.

**Comment by cosmicknox** [comment]
const { config: transfer, error } = usePrepareContractWrite({
    chainId: 137,
    address: "0x6B9a5BcaD8133bd08484103C8007fa105FE8460b", // test market address
    abi: [
      {
        inputs: [
          {
            internalType: "address",
            name: "from",
            type: "address",
          },
          {
            internalType: "address",
            name: "to",
            type: "address",
          },
          {
            internalType: "uint256",
            name: "tokenId",
            type: "uint256",
          },
        ],
        name: "safeTransferFrom",
        outputs: [],
        stateMutability: "nonpayable",
        type: "function",
      },
    ],
    functionName: "safeTransferFrom",
    args: [
      "0xC29576653f746f89dd2cCf77d432329623C83626",
      "0x14db5E1ce67D8Df5E4334AfE9FbA2587aC87afAF",
      parseInt(889),
    ],
  });


same error : 
address is required 
even after hardcoding the address in  usePrepareContractWrite

**Comment by sonukuldeep** [comment]
you have to use recklesslyUnprepared mode for this to work. Check [overload](https://wagmi.sh/react/hooks/useContractWrite#overrides-optional). I had this issue too which got solved by using overload
