### ISSUE TITLE
Trust Wallet Mobile : Method is not supported Error or Toast

### ISSUE THREAD

**Issue by IndigoSoftwares21** [wagmi-dev/wagmi#2034]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.11.7

### Current Behavior

When i send a transaction, it works well on other wallets including Trust Wallet on PC, but on Trust Mobile app, when I send a transaction it says Method is not supported.

### Expected Behavior

It should send the Ethereum.

**Comment by jxom** [comment]
My guess is that the Trust mobile app doesn't support an RPC method you are trying to use (either `eth_sendTransaction` or a prerequisite method). This doesn't seem to be a direct issue of wagmi, but rather Trust Wallet, so it might be worth contacting Trust Wallet to try resolve the issue.
