### ISSUE TITLE
bug: BSC Testnet RPC - Blocked by CORS

### ISSUE THREAD

**Issue by 0xhohenheim** [wagmi-dev/wagmi#2035]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.12.2

### Current Behavior

Using `@web3modal/ethereum` + `@web3modal/react` + `wagmi` to build a Dapp on BSC Testnet. Metamask connection and contract interactions work as expected but once a mobile wallet is connected via the WalletConnect QR code, it stops working with the following error:
```
Access to XMLHttpRequest at 'https://bsc-testnet.public.blastapi.io/' from origin 'http://localhost:3000' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
```

### Expected Behavior

To work on mobile wallets just as it does on Metamask browser wallet

### Steps To Reproduce

Here are my dependencies:
```json
{
...
    "@web3modal/ethereum": "^2.2.1",
    "@web3modal/react": "^2.2.1",
    "wagmi": "^0.12.2",
...
}
```

Here is my config:
```js
import { Chain, EthereumClient, w3mConnectors, w3mProvider } from '@web3modal/ethereum'
import { Web3Modal } from '@web3modal/react'
import { configureChains, createClient, WagmiConfig } from 'wagmi'
import { bscTestnet, bsc } from 'wagmi/chains'


const chains = process.env.REACT_APP_DEPLOYMENT === 'development' ? [bscTestnet] : [bsc];
const projectId = process.env.REACT_APP_WALLETCONNECT_ID as string;

const { provider } = configureChains(chains as Chain[], [w3mProvider({ projectId })])
const wagmiClient = createClient({
  autoConnect: true,
  connectors: w3mConnectors({ projectId, version: 1, chains }),
  provider
})
const ethereumClient = new EthereumClient(wagmiClient, chains);
```

### Anything else?

Solved by updating the RPCs, not a satisfactory approach:
```js
var _bscTestnet = JSON.parse(JSON.stringify(bscTestnet));
_bscTestnet.rpcUrls.default.http = ['https://data-seed-prebsc-2-s2.binance.org:8545'];
_bscTestnet.rpcUrls.public.http = ['https://data-seed-prebsc-2-s2.binance.org:8545'];
```

**Comment by jxom** [comment]
Looks like `https://bsc-testnet.public.blastapi.io/` do not allow localhost addresses. Might be worth getting in contact with the RPC Provider.

**Comment by 0xhohenheim** [comment]
@jxom I should add that I tested it on an HTTPS domain as well and it continued to fail, wouldn't it be good to have fallback RPCs in each chain config?
