### ISSUE TITLE
bug: wagmi cli "actions" plugin doesn't respect overridePackageName

### ISSUE THREAD

**Issue by darthmeme** [wagmi-dev/wagmi#2036]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

`@wagmi/core` - `0.10.2`
`@wagmi/cli` - `0.1.13`

### Current Behavior

The generated file from `yarn wagmi generate` will import everything from `wagmi/actions`

### Expected Behavior

Imports should come from `@wagmi/core`

### Steps To Reproduce

Install `@wagmi/core ethers@^5 @wagmi/cli`

Use the following config:
```ts
import { defineConfig } from '@wagmi/cli'
import { actions, erc } from '@wagmi/cli/plugins'
 
export default defineConfig({
  out: 'src/generated.ts',
  contracts: [],
  plugins: [
    erc({
      721: true
    }),
    actions({
      overridePackageName: '@wagmi/core'
    })
  ],
})
```

Run `wagmi generate`

### Anything else?

<img width="446" alt="image" src="https://user-images.githubusercontent.com/42481527/226250696-a3354aef-717d-4404-8bb5-d4e4c40c3121.png">

**Comment by tmm** [comment]
Thanks for reporting! This should take care of that: https://github.com/wagmi-dev/wagmi/pull/2039

**Comment by darthmeme** [comment]
Thanks for the quick fix 👍
