### ISSUE TITLE
bug: Scan the Wallect Connect QR with mobile wallet, nothing response 

### ISSUE THREAD

**Issue by kale5195** [wagmi-dev/wagmi#2051]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.12.4

### Current Behavior

Go to https://wagmi.sh/examples/connect-wallet

click wallet connect, scan with rainbow wallet, nothing response 

### Expected Behavior

The connect dialog should popup in rainbow wallet

### Link to Minimal Reproducible Example (StackBlitz, CodeSandbox, GitHub repo etc.)

https://wagmi.sh/examples/connect-wallet

**Comment by tmm** [comment]
Thanks for reporting. This issue is temporarily closed due to lack of information. Please provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) and reopen this issue.

What wallet are you using? Is it WalletConnect v2 enabled?

**Comment by jxom** [comment]
The example uses WalletConnect v2 (`WalletConnectConnector`) which I don't believe Rainbow has migrated to yet. For now, consumers will need to use WalletConnect v1 (`WalletConnectLegacyConnector`) for wallets that have not yet migrated to WalletConnect v2. 

FYI: Wallets will need to migrate to WalletConnect v2 by June 28, whereby WalletConnect v1 will be shut down and discontinued.

**Comment by kale5195** [comment]
@tmm @jxom  thanks for quick response. However, I tried the wallet connect  in https://cloud.walletconnect.com/sign-in

it works fine for rainbow wallet and it also use wallet connect v2

**Comment by jxom** [comment]
https://cloud.walletconnect.com/sign-in still uses WalletConnect v1.
