### ISSUE TITLE
bug: Make Sign-In with Ethereum (SIWE) example complete

### ISSUE THREAD

**Issue by MidnightLightning** [wagmi-dev/wagmi#2052]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.12.4

### Current Behavior

The current example at https://wagmi.sh/examples/sign-in-with-ethereum of the recommended way to do a "Sign-In with Ethereum" (SIWE) interaction is recommending a some bad practices in exchange for simplicity. Namely, they key purpose of a nonce in the signed message is to prevent replay attacks, and the provided example doesn't support that (the "logout" method doesn't invalidate the nonce used, so anyone who duplicated the session payload prior to issuing the logout command could still re-use that payload to get an active session.

### Expected Behavior

Best practices from the Sign-In with Ethereum (SIWE; ERC-4361 standard) should be adhered to, to show a server implementation that uses the properties of the SIWE payload in the manner they're supposed to.

For nonces, the back-end service will need to keep a stored cache of which nonces are valid. This can be a file cache (to avoid another dependency) or something simple like levelDB.

**Comment by MidnightLightning** [comment]
This issue came about from the discussion at https://github.com/wagmi-dev/wagmi/discussions/1989

**Comment by tmm** [comment]
Thanks for opening up the discussion! We are going to move the docs examples to a different format soon so probably not worth spending too much time updating. Added a note though:

<img width="850" alt="Before going to production, you likely want to invalidate nonces on logout to prevent replay attacks through session duplication (e.g. store expired nonce and make sure they can't be used again)." src="https://user-images.githubusercontent.com/6759464/227629032-36ca4eed-e4da-4e6f-984a-42a0581083f1.png">
