### ISSUE TITLE
useSendTransaction does not work via WalletConnect 2.0

### ISSUE THREAD

**Issue by swkim109** [wagmi-dev/wagmi#2061]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.12.6

### Current Behavior

I'm testing wagmi `usePrepareSendTransaction` and `useSendTransaction` at [wagmi example](https://wagmi.sh/examples/send-transaction). But I encountered some error when trying to send a transaction via WalletConnect.
When I clicked the Approve in the wallet side, it shows the following error:
``` 
Error: invalid transaction key: gas (argument="transaction", value={"gas":"0x5208","value":"0x0","from":"0xb120ed3dbb61644a7d8865a9fb7adf1800f5d3ce","to":"0xad36301e8c66bb2af80c63da5a99bdf2c202c9a1"}, code=INVALID_ARGUMENT, version=abstract-signer/5.7.0)
```
![wagmi](https://user-images.githubusercontent.com/46621605/226855714-187a159e-be2c-4e43-a3e4-45caf664ed8b.png)

### Expected Behavior

As it says in the above error message, **gas** should be changed to **gasLimit**. I have looked into WalletConnect side, it does not seem to be responsible for this error, or I could not find something wrong.

I tested sending a simple transaction using another way such as `SignClient` which is provided by WalletConnect, and it works fine. 

### Steps To Reproduce

Just connect a wallet via WalletConnect in the example page and click Approve button in the wallet.
You can use the sample wallet in [react-wallet](https://react-wallet.walletconnect.com/walletconnect) provided by WalletConnect 2.0

**Comment by jxom** [comment]
`gas` is a valid transaction request parameter. Ethers.js converts `gasLimit` to `gas` internally.
My guess is that the wallet isn’t parsing the `gas` param to `gasLimit` before handing it off to Ethers.

**Comment by 0xAsimetriq** [comment]
@swkim109 This is likely an issue in our example wallet, since it's been a while we tested it against on-chain transactions, it's mostly meant to test connecting the dapp and sending quick sign message request that doesn't require rpc.

I'd suggest to use any other v2 compatible wallet beyond this i.e. rainbow

**Comment by jxom** [comment]
@m4kgsjd what is the issue you are having? And which wallet?

This OP issue is not a wagmi issue, but rather, an issue in how the wallet is parsing the transaction request.

**Comment by JackLicc** [comment]
Same here, I'm using wagmi 0.12.12, wagmi seems can't catch errors from RPC calls.

**Comment by leejw51** [comment]
i had the same issue.
gas -> gas
gasLimit -> gas

so gas should be ok
