### ISSUE TITLE
WalletConnectConnector (V2) issue

### ISSUE THREAD

**Issue by KarthickSakthi** [wagmi-dev/wagmi#2073]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.12.4

### Current Behavior

WalletConnectConnector(V2) is not working stable

I am developing dapp in Nextjs:

here is my code:

My wagmi Client code in _app.js:

```
const { chains, provider , webSocketProvider} = configureChains(
  [mainnet, polygon, polygonMumbai],
  [alchemyProvider({ apiKey: '' }), publicProvider()],
)
 

const wagmiClient = createClient({
  autoConnect: true,
  connectors: [
    new InjectedConnector({
    chains,
    options: {
    shimChainChangedDisconnect: true, 
  }}), 
   new WalletConnectConnector({
    chains,
    options: {
      projectId: "..."  
    }
  })],
  provider,
  webSocketProvider
})
```

The connect call for WalletConnect:

  ```
const handleWalletConnect = async () => {

    if (isConnected) {
      await disconnectAsync();
    }

    const connector = new WalletConnectConnector({
      chains: [mainnet, polygonMumbai, polygon],
      options: {
        projectId:"...", // same Id I used in above app.js which got from https://cloud.walletconnect.com
      },
    });

    const { account, chain } = await connectAsync({ connector });

  }
```

Some times It shows that, walletConnectV2 modal, but someTimes Nothing happens, when I trigger the above function

### Expected Behavior

Need to Open the QR modal of WalletConnect(v2)

**Comment by tmm** [comment]
Thanks for reporting. This issue is temporarily closed due to lack of information. Please provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) and reopen this issue.

**Comment by DramaCrypto** [comment]
![image](https://github.com/wagmi-dev/wagmi/assets/51626000/2a65f5f7-2d2c-4fc3-bf34-7dff287c553d)
It causes `ReferenceError: exports is not defined` when trying to wallet connect
