### ISSUE TITLE
[bug] Cannot find module @walletconnect/ethereum-provider when in node context

### ISSUE THREAD

**Issue by iprotoni** [wagmi-dev/wagmi#2075]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.12.5

### Current Behavior

In order to build a page with next.js with getStaticProps, it try to use the commonjs module version of wagmi and breaks like it looks like wagmi-core doesnt export or include the required module.

**Comment by jxom** [comment]
Thanks for reporting. Can you please provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) via a separate GitHub repository? Will re-open this issue when provided.
