### ISSUE TITLE
bug: New metamask "Set a spending cap" feature causes transaction to fail

### ISSUE THREAD

**Issue by danilo-timacum** [wagmi-dev/wagmi#2078]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.12.6

### Current Behavior

Metamask (v.10.26.2) added new feature for approving amount.
Now, when calling approve function on contract, additional metamask dialog appears where amount for approve needs to be confirmed.
When setting amount in addition metamask dialog larger (for example: 20) than initially approved (for example: 1) in most cases following error will appear:
```
next-dev.js?3515:20 Error: missing revert data in call exception; Transaction reverted without a reason string [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (data="0x", transaction={"from":"0xdEB2746e8f40397056Dbf39F30f99217D81C399E","to":"0x501dF51feDd7fA301eca905184F5FDd0737395a8","type":2,"accessList":null}, error={"reason":"processing response error","code":"SERVER_ERROR","body":"{\"jsonrpc\":\"2.0\",\"id\":80,\"error\":{\"code\":-32000,\"message\":\"execution reverted\"}}","error":{"code":-32000},"requestBody":"{\"method\":\"eth_call\",\"params\":[{\"type\":\"0x2\",\"from\":\"0xdeb2746e8f40397056dbf39f30f99217d81c399e\",\"to\":\"0x501df51fedd7fa301eca905184f5fdd0737395a8\"},\"0x852b54\"],\"id\":80,\"jsonrpc\":\"2.0\"}","requestMethod":"POST","url":"https://rpc.ankr.com/eth_goerli"}, code=CALL_EXCEPTION, version=providers/5.7.2)
at Logger.makeError (index.js?dd68:224:1)
at Logger.throwError (index.js?dd68:233:1)
at checkError (json-rpc-provider.js?8679:64:1)
at StaticJsonRpcProvider.eval (json-rpc-provider.js?8679:575:1)
at Generator.throw (<anonymous>)
at rejected (json-rpc-provider.js?8679:6:42)
```

When I try to do this directly on contract (example: https://goerli.etherscan.io/address/0x501df51fedd7fa301eca905184f5fdd0737395a8#code ), there is no error and transaction passes.

### Expected Behavior

Transaction should complete without error.

### Steps To Reproduce

1. Open Minimal Reproducible Example.
2. Connect to metamask wallet
3. Click on Approve button
4. Set amount to 20 in additional "Set a spending cap" metamask dialog
5. Confirm transaction
6. Check console

### Link to Minimal Reproducible Example (StackBlitz, CodeSandbox, GitHub repo etc.)

https://stackblitz.com/edit/next-typescript-9p9q8e?file=pages%2F_app.tsx,pages%2Findex.tsx

**Comment by jxom** [comment]
For me, it seems like I get this error when the contract reverts, which is expected. My guess is that something is happening in the contract, because the calldata I sent between a successful call and a reverted call was identical.
