### ISSUE TITLE
bug: arbitrum watch: true and block time

### ISSUE THREAD

**Issue by agsola** [wagmi-dev/wagmi#2079]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

wagmi@0.12.6

### Current Behavior

I've tried using watch: true on arbitrum, which kills the API rate limits, as the current block time on Arbitrum is less than a second (https://arbiscan.io/blocks).

Since it queries for every new block, it makes quite a lot of queries, which kills the APIs rate limit.

I've tried with "`cacheTime`" and "`staleTime`", both separately and together, and with and without `watch` `true` and `false`.
And the only thing that seems to be relevant is "`watch`".

It either refreshes more than once a second, of never refreshes. 

### Expected Behavior

Allow to refresh every x milliseconds.

**Comment by tmm** [comment]
> Do you really need the "minimal reproducible example"?

Yes, this helps us jump right into fixing an issue without needing to set up anything. See [Why Reproductions are Required](https://antfu.me/posts/why-reproductions-are-required) for more info. You can pop in a dummy API key and use [new.wagmi.sh](https://new.wagmi.sh) as a baseline for the example.

> Regarding the "cacheTime" and "staleTime", ...

See the [React Query docs](https://tanstack.com/query/v4/docs/react/guides/important-defaults) for more info on `"cacheTime"` and `"staleTime"`. We are planning on improving wagmi's docs around this for the first major release.

**Comment by tmm** [comment]
You could switch to polling instead of using websockets. This is a limitation of ethers and since wagmi uses ethers for the time-being, unfortunately there's not much that can be done.
