### ISSUE TITLE
bug: Peer dependencies console errors & warnings

### ISSUE THREAD

**Issue by lefuncq** [wagmi-dev/wagmi#2089]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

10.0.7

### Current Behavior

I've tried updating my `@wagmi/core` version to the latest, but when doing that, some errors prompt on my browser's console.
I've tried updating to every version between the one I'm currently using, the `0.9.7`, and the latest, but every attempt resulted in those errors.
<img width="559" alt="Capture d’écran 2023-03-29 à 03 25 36" src="https://user-images.githubusercontent.com/15050175/228402829-bd490384-02b5-485e-bf1b-8c3fd59bebe5.png">

### Expected Behavior

Being able to update to the newest @wagmi/core version without having errors.

### Steps To Reproduce

- Create a NextJS App
- Create a `wagmi.js` file with the following content
```
import { configureChains, createClient } from '@wagmi/core';
import {
  avalancheFuji,
  bscTestnet,
  goerli,
  polygonMumbai,
} from '@wagmi/core/chains';
import { LedgerConnector } from '@wagmi/core/connectors/ledger';
import { MetaMaskConnector } from '@wagmi/core/connectors/metaMask';
import { CoinbaseWalletConnector } from '@wagmi/core/connectors/coinbaseWallet';
import { WalletConnectConnector } from '@wagmi/core/connectors/walletConnect';
import { jsonRpcProvider } from '@wagmi/core/providers/jsonRpc';
import { chainIdToChainName, chainsData } from '@/constants';

const chains = [goerli, polygonMumbai, bscTestnet, avalancheFuji];

export const initWagmiClient = () => {
  const { provider, webSocketProvider } = configureChains(chains, [
    jsonRpcProvider({
      rpc: (chain) => ({
        http: chainsData[chainIdToChainName[chain.id]].rpcUrl,
      }),
    }),
  ]);

  const connectors = [
    new LedgerConnector({
      chains,
    }),
    new CoinbaseWalletConnector({
      chains,
      options: {
        appName: 'Trustblock',
      },
    }),
    new MetaMaskConnector({ chains }),
    new WalletConnectConnector({
      chains,
      options: {
        qrcode: true,
      },
    }),
  ];

  return createClient({
    autoConnect: true,
    provider,
    webSocketProvider,
    connectors,
  });
};
```
- Call the function within your _app.js file as follows:
```
import '@/styles/globals.scss';
import PropTypes from 'prop-types';
import { SessionProvider } from 'next-auth/react';
import Navbar from '@/components/_global/Navbar/Navbar';
import Footer from '@/components/_global/Footer/Footer';
import { Analytics } from '@vercel/analytics/react';
import { Manrope } from 'next/font/google';
import { initWagmiClient } from '@/helpers/wagmi';
import { useEffect } from 'react';

const manrope = Manrope({ subsets: ['latin'] });

const propTypes = {
  Component: PropTypes.func,
  pageProps: PropTypes.shape({
    session: PropTypes.shape(),
  }),
};

const wagmiClient = initWagmiClient();

function App({ Component, pageProps }) {
  useEffect(() => {
    window.wagmiClient = wagmiClient;
  }, []);

  return (
    <>
      <style jsx global>{`
        html {
          font-family: ${manrope.style.fontFamily};
        }
      `}</style>
      <SessionProvider
        session={pageProps.session}
        refetchInterval={0}
        refetchOnWindowFocus={false}
      >
        <Navbar />
        <Component {...pageProps} />
        <Footer />
      </SessionProvider>
      <Analytics />
    </>
  );
}

App.propTypes = propTypes;
export default App;
```

### Anything else?

Are you planning on making dedicated default exports with tree shaking?
`@wagmi/core` is not a light package and being able to directly import functions would be much better performance-wise.

**Comment by jxom** [comment]
There was a breaking change in `0.10.0` where `WalletConnectConnector` uses WalletConnect v2 by default (instead of v1).  The errors that you are seeing here is because you have not set a `projectId` in `WalletConnectConnector`. Check out the migration guide here: https://wagmi.sh/core/migration-guide#010x-breaking-changes.

> Are you planning on making dedicated default exports with tree shaking?

`@wagmi/core` is already tree-shakable, however, Ethers.js does add a heavy size to the tree-shakable modules. In wagmi v1, we will be migrating from Ethers.js to [viem](https://viem.sh) which will resolve the bundle size & tree-shaking concerns.

**Comment by lefuncq** [comment]
It fixed it! Thanks for your guidance and the fantastic work you and the rest of wagmi's team are doing!
Though I still have a warning prompting, does `lit` being run in development mode drive the performance of the website down, or is it just a false positive?
<img width="555" alt="Capture d’écran 2023-03-29 à 15 24 40" src="https://user-images.githubusercontent.com/15050175/228552763-fd425a8c-bd23-4d87-b084-1788d46cf1bf.png">
Regarding tree-shaking, it is available for chains, connectors, and providers, but it doesn't seem available for `createClient` & `configureChains`, and all of the other methods like `getAccount`, `connect`, etc... Do you plan to enable it for these as well?
Last but not least, when do you plan on releasing v1? Looking forward to it!

**Comment by dmatora** [comment]
Anyone found a way to get rid of lit warning?
