### ISSUE TITLE
bug: `isFetched` prop returned by `usePrepareContractWrite` is not updating on production build

### ISSUE THREAD

**Issue by lykalabrada** [wagmi-dev/wagmi#2100]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.12.7

### Current Behavior

We are using the `usePrepareContractWrite` hook along with `useContractWrite` for a transaction.
 We didn't want to run the hook `usePrepareContractWrite` immediately on page load so we're setting the `enabled` property to `false`, and instead using the `refetch` function to get the config, this way we can control whenever we want to run the `usePrepareContractWrite` hook.

This is **working on development** and `isFetched` prop is updated accordingly. But weirdly enough it's **failing on production build**. Failing means `isFetched` prop is always false, it never refetches the config.

### Expected Behavior

`isFetched` prop should be updated accordingly in production build.

### Steps To Reproduce

```
const { config, refetch, isFetched } = usePrepareContractWrite({
    address: _address,
    abi: _abi,
    functionName: "func",
    args: [....],
    enabled: false
  });
```

then inside a useEffect, once needed data is ready we can refetch the config:
```
useEffect(() => {
    if (isReady) {
      refetch();
    }
  }, [isReady]);
```

`console.log(isFetched) // -> this is where issue is seen, always false on production build even after refetch.`

### Anything else?

Our current workaround is back to setting `enabled` to true when the data is ready. This is just not ideal for us since we want to explicitly control when to fetch the `usePrepareContractWrite` config.

Note: Data that we're waiting for is also from a contract and is using `useContractRead`.

Note: Although our "workaround" still looks fine, we just really find it strange that the behaviour is different between development and production build, hence raising this issue.

**Comment by jxom** [comment]
What if you try do:

```diff
const { config } = usePrepareContractWrite({
  address: _address,
  abi: _abi,
  functionName: "func",
  args: [....],
- enabled: false
+ enabled: isReady 
});

- useEffect(() => {
-  if (isReady) {
-    refetch();
-  }
-}, [isReady]);
```

**Comment by lykalabrada** [comment]
> What if you try do:
> 
> ```diff
> const { config } = usePrepareContractWrite({
>   address: _address,
>   abi: _abi,
>   functionName: "func",
>   args: [....],
> - enabled: false
> + enabled: isReady 
> });
> 
> - useEffect(() => {
> -  if (isReady) {
> -    refetch();
> -  }
> -}, [isReady]);
> ```

Yes that is exactly our 'workaround', as I mentioned in the last part we just find it really strange that the initial implementation is working on development but not on production build 😞

**Comment by jxom** [comment]
Can you please provide us with a reproducible example? can be a separate repo generated with `npm init wagmi`.
