### ISSUE TITLE
Docs - Bug: Injected Provider is having maximum call exceed error when MetaMask is being selected when there is Trust Wallet, MetaMask and CoinBase browser extensions together installed

### ISSUE THREAD

**Issue by linkb15** [wagmi-dev/wagmi#2104]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

latest

### Current Behavior

https://wagmi.sh/examples/sign-in-with-ethereum

In this documentation page, when user click connect with Injected provider, Coinbase will ask user to select which wallet you want to use, and when user click MetaMask the error shows up "Maximum call stack size exceeded"

Below is the recording it happened.

https://www.loom.com/share/f7ee83eaab1c444ca2c76d8a7ff65f97

### Expected Behavior

There is no error happening and it prompts MetaMask wallet connection request.

### Steps To Reproduce

In this documentation page, when user click connect with Injected provider, Coinbase will ask user to select which wallet you want to use, and when user click MetaMask the error shows up "Maximum call stack size exceeded"

https://www.loom.com/share/f7ee83eaab1c444ca2c76d8a7ff65f97

**Comment by tmm** [comment]
Unfortunately I'm not able to reproduce. If you lock down the reproduction criteria so it's easy to reproduce, happy to take a look. My guess is something funky is happening outside of wagmi's scope since it involves another external interaction with Coinbase Wallet.

https://user-images.githubusercontent.com/6759464/229583920-94c76a76-fd8a-4e9e-9327-4a3c1ddce1f8.mp4

**Comment by oanamun** [comment]
Hello! @tmm I get the same error when having multiple wallet extensions installed and enabled. You can see it reproducing on the wagmi example when having Metamask, Coinbase and Phantom wallets installed.

https://github.com/wagmi-dev/wagmi/assets/17378978/2276f2e4-6227-460f-872d-abd1a801b39f

**Comment by tmm** [comment]
This seems like a wallet issue outside of wagmi's control. Unfortunately using multiple injected wallets doesn't work very well because they fight over `window.ethereum`.
