### ISSUE TITLE
bug: can't use cli to generate hardhat code

### ISSUE THREAD

**Issue by Eyon42** [wagmi-dev/wagmi#2110]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.1.14

### Current Behavior

Running `npm run wagmi generate` throws:

```

> frontend@0.1.0 wagmi
> wagmi

✔ Validating plugins
⠸ Resolving contracts
Command failed with exit code 1: npm hardhat compile
Unknown command: "hardhat"
```
 `npm hardhat compile` is invalid

### Expected Behavior

It should call `npx hardhat generate` or something else.

### Steps To Reproduce

Install the cli with npm, use the hardhat plugin and try to use the cli to generate.

### Anything else?

The issue is [here](https://github.com/wagmi-dev/wagmi/blob/main/packages/cli/src/plugins/hardhat.ts#L145):

```
      if (clean) {
        const packageManager = await getPackageManager();
        const [command, ...options] = (typeof clean === "boolean" ? `${packageManager} hardhat clean` : clean).split(" ");
        await execa2(command, options, { cwd: project });
      }
      if (build) {
        const packageManager = await getPackageManager();
        const [command, ...options] = (typeof build === "boolean" ? `${packageManager} hardhat compile` : build).split(" ");
        await execa2(command, options, { cwd: project });
      }
```

The `{packageManager} hardhat compile` patter does not work for npm, as it does for pnpm and yarn

Proposed solution: add a special case.
I might do it tomorrow, now I'm sleppy.

Also, `npm run wagmi init` does not work by default, I had to do something hacky and add `"wagmi": "wagmi"` to package.json

**Comment by tomas-dukynas** [comment]
having the same issue

**Comment by Eyon42** [comment]
Created a couple of PRs to address the issues
