### ISSUE TITLE
bug: updata version0.12.8，error

### ISSUE THREAD

**Issue by gengbingbing** [wagmi-dev/wagmi#2112]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.12.8

### Current Behavior

Error: No wagmi client found. Ensure you have set up a client:

use：
`import { createClient, configureChains, mainnet } from 'wagmi'
import { publicProvider } from 'wagmi/providers/public'
import { WagmiConfig } from 'wagmi'

const { provider, webSocketProvider } = configureChains([mainnet], [publicProvider()])

const client = createClient({
    autoConnect: true,
    provider,
    webSocketProvider
})`

`<WagmiConfig client={client}>
        <ConfigProvider locale={enUS}>
            <HashRouter>
                <AliveScope>
                    <Root />
                </AliveScope>
            </HashRouter>
        </ConfigProvider>
    </WagmiConfig>`

this has a error
`
import { getNetwork } from '@wagmi/core'
const chain = getNetwork().chain
`

### Expected Behavior

get a net / chainid

### Anything else?

![image](https://user-images.githubusercontent.com/15809531/229332275-108ef69a-b601-4eca-8aa5-cb7d528fe061.png)

**Comment by jxom** [comment]
Thanks for reporting. This issue is temporarily closed due to lack of information. Please provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) via https://new.wagmi.sh or a separate repository.

Will re-open when provided.

**Comment by gaufranc** [comment]
@gengbingbing did you find a fix? i am also facing the exact same issue.
