### ISSUE TITLE
bug: constant erc20ABI cannot be used in backend

### ISSUE THREAD

**Issue by pgrandne** [wagmi-dev/wagmi#2113]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.12.8

### Current Behavior

Hi, I used the constant erc20ABI to execute some transactions with my backend :
   import { erc20ABI } from 'wagmi'
and then
   const contract = new ethers.Contract(process.env.USDC_CONTRACT, ERC20, wallet);

I know that it was not provided for that but it was an easy way to get ERC20 ABI without create a specific JSON.
Since the new version (before version 0.12.8 but I didn't find which one) I cannot use this constant as previously, I have this error message :
"Attempted import error: 'createContext' is not exported from 'react' (imported as 'React')"

### Expected Behavior

Use the constant erc20ABI from backend

### Steps To Reproduce

It is new route.ts API file from NextJS13 called by my front end:
"
import { NextResponse } from 'next/server';
import { ethers } from 'ethers'
import { ERC20 } from '@/lib/erc20'

export async function POST(request: Request) {
    try {
        const { address } = await request.json()
        const provider = new ethers.providers.AlchemyProvider("optimism-goerli", process.env.ALCHEMY_ID)
        if (typeof process.env.PRIVATE_KEY !== "undefined" && typeof process.env.USDC_CONTRACT !== "undefined") {
            const wallet = new ethers.Wallet(process.env.PRIVATE_KEY, provider)
            const contract = new ethers.Contract(process.env.USDC_CONTRACT, ERC20, wallet);
            const amount = ethers.utils.parseUnits('1000', 6)
            const balance = (await contract.balanceOf(address) / 10 ** 6).toString()
            console.log(`balance : ${balance}`)
            if (parseInt(balance) >= 1000) {
                const error = new Error('Cannot use faucet because already have USDC')
                error.name = 'balance'
                throw error

            }
            else {
                const result = (await contract.transfer(address, amount))
                const receipt = await result.wait()
                console.log(receipt)
                console.log(`Sent ${ethers.utils.formatUnits(amount, 6)} USDC to address ${address}`)
            }
        }
        else {
            const error = new Error('No env variable')
            error.name = 'env'
            throw error
        }
        return NextResponse.json({ status: 200 })
    } catch (_error) {
        console.error(_error)
        switch (_error.name) {
            case 'env':
                return NextResponse.json({
                    message: _error.message
                }, {
                    status: 422,
                })
            case 'balance':
                return NextResponse.json({
                    message: _error.message
                }, {
                    status: 423,
                })
            default:
                return NextResponse.json({
                    message: "Unknown error"
                }, {
                    status: 500,
                })
        }
    }
}
"

The files are in app/api/faucet and app/api/gas

### Link to Minimal Reproducible Example (StackBlitz, CodeSandbox, GitHub repo etc.)

https://github.com/pgrandne/revolte/tree/ae4f13daeb409190db4458acfebe198de55d15fb

**Comment by tmm** [comment]
Thanks for reporting. This issue is temporarily closed due to lack of information.

Please update or create a new example that is minimal (only the code required to reproduce the bug) and re-open this issue.
