### ISSUE TITLE
bug: hook useSendTransaction doesnt work into mobile wallets(trust wallet, metamask) 

### ISSUE THREAD

**Issue by deantek** [wagmi-dev/wagmi#2124]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.12.3

### Current Behavior

i want to transfer eth from one wallet to another

### Expected Behavior

on success, a modal window should open in the trust wallet confirming the transaction

### Steps To Reproduce

i use the standard rainbowkit + wagmi + ethers example, in mobile wallets confirmation does not work anywhere, only the metamask extension works

````
const { config } = usePrepareSendTransaction({
    request: {
      to: toAddress,
      value: incomeVal ? utils.parseEther(incomeVal).toString() : undefined,
    }
  })

  const { data, sendTransaction } = useSendTransaction(config)
````

![trusterror](https://user-images.githubusercontent.com/37242034/229501619-8f2c4f72-8d4e-4f0f-bf84-ffde80b76c46.png)

try to send transaction into trust wallet
https://codesandbox.io/s/peaceful-panna-ckel4p?file=/src/Home.js

### Link to Minimal Reproducible Example (StackBlitz, CodeSandbox, GitHub repo etc.)

https://codesandbox.io/s/peaceful-panna-ckel4p?file=/src/Home.js

### Anything else?

reopen this issue with example

**Comment by IndigoSoftwares21** [comment]
I have the same issue and I need a solution I hope they help, when you send it says Method is not supported
and gives the below error
{code: -32000, message: "User canceled"}
code: -32000
message: "User canceled"

**Comment by jxom** [comment]
Looks like this was fixed in latest version of RainbowKit: https://github.com/rainbow-me/rainbowkit/issues/1137#issuecomment-1496797438.
