### ISSUE TITLE
bug: UserRejectedRequestError: User rejected request error when user cancels

### ISSUE THREAD

**Issue by basememara** [wagmi-dev/wagmi#2129]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.12.9

### Current Behavior

When a user cancels or rejects the connect, the error occurs: UserRejectedRequestError: User rejected request

### Expected Behavior

No error should occur.

### Steps To Reproduce

Connect > MetaMask > Press cancel in MM

### Link to Minimal Reproducible Example (StackBlitz, CodeSandbox, GitHub repo etc.)

https://stackblitz.com/edit/new-wagmi

### Anything else?

I tried this with a vanilla `yarn create wagmi` but issue remains. This does not occur on [your home page](https://wagmi.sh/examples/connect-wallet) so I'm wondering what you're doing differently there. Is there any way to get this signal when user rejects wallet actions, or where should I handle this error?

There was a [previous issue](https://github.com/wagmi-dev/wagmi/issues/515) that was unanswered and closed so re-opening here. The related comment mentioned in the issue did not resolve it since happening on the latest version.

https://user-images.githubusercontent.com/892152/229927994-7a2247de-e70e-468f-b03f-a6ead94d1fb3.mov

![image](https://user-images.githubusercontent.com/892152/229928444-50d3bc21-dbe8-465e-b868-fb0ab9d2b79d.png)

**Comment by jxom** [comment]
Pretty sure [React Query](https://tanstack.com/query/latest/) logs mutation errors in development (and not production) – which is what you are seeing here with your example (dev env) vs. wagmi.sh (production env). That said, the error is caught within the `useSwitchNetwork` Hook, and you can handle the error there (with `isError`, `error`, etc).
