### ISSUE TITLE
bug: passing chainId in `connect` function doesn't work on mobile

### ISSUE THREAD

**Issue by darthmeme** [wagmi-dev/wagmi#2153]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

`@wagmi/core` - `0.10.2`

### Current Behavior

Not sure if this is a wagmi or MetaMask related bug (wallet I'm using).

When using the `connect` method and passing `chainId`. MetaMask on mobile never prompts the user.

### Expected Behavior

It should prompt the user to switch networks

### Steps To Reproduce

```ts
connect({
  connector, // some connector
  chainId: 80001
})
```

**Comment by tmm** [comment]
Thanks for reporting. This issue is temporarily closed due to lack of information. Please provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) and reopen this issue.
