### ISSUE TITLE
bug: trust wallet an unknown error occurred

### ISSUE THREAD

**Issue by ugurcanomur** [wagmi-dev/wagmi#2161]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Package Version

0.12.10

### Current Behavior

```
const { config } = usePrepareSendTransaction({
 request: {
    to: "my_wallet",
     value: amount ? utils.parseEther(amount) : undefined,
  },
});

const { data, sendTransaction } = useSendTransaction(config);

const { isLoading, isSuccess } = useWaitForTransaction({
  hash: data?.hash,
});
```

I'am trying to send transaction confirm to Trust Wallet on mobile. But when i trigger sendTransaction method Trust Wallet returns "An Unknown Error Occurred". It's work with metamask wallet but Trust Wallet return undefined error. 

I am using default example code it didn't work with Trust Wallet.

Network change request works successfully but transaction can't send to mobile.

**Comment by ugurcanomur** [comment]
i found the fix;
i added data property in request object

 ```
request: {
     to: "my_wallet",
     value: amount ? utils.parseEther(amount) : undefined,
     data: "0x",
  },

```

now it's works.

fyi everyone.

**Comment by profesor5150** [comment]
Have an issue. Been trying to connect a wallet from surgebit to trust wallet but keep getting Undefined Error/Contract Support. I have contacted both supports and both can't give me an answer. One support says I need eth in account to connect wallets. The other one from trust wallet says No eth needed in balance only for any other transactions? Going crazy and need to move my coin. If anyone can help will pass along a couple of coins for there help.
