### ISSUE TITLE
bug:  Wagmi disconnect issue

### ISSUE THREAD

**Issue by goodlucky0630** [wagmi-dev/wagmi#2163]
### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Package Version

0.9.5

### Current Behavior

when I switch and change the network, my metamask wallet is disconnected.
How can I fix this issue?

**Comment by tmm** [comment]
Thanks for reporting. This issue is temporarily closed due to lack of information. Please provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) and reopen this issue.
