### ISSUE TITLE
bug: switchNetwork not working for BSC mainnet

### ISSUE THREAD

**Issue by arindammojumder** [wagmi-dev/wagmi#2168]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

 "@wagmi/core": "^0.8.19",

### Current Behavior

Suddenly switchNetwork function is not working when a user changing the network from Ethereum Mainnet to BSC mainnet. It was working fine earlier (5 days ago). It is working fine if a user change the network manually via metamask browser extension.
It is also working fine if a user change his network from BSC mainnet to Ethereum Mainnet.

It is not a coading issue because I am facing the same issue on all my live projects ( approx 5 projects). 
Below I am pasting the issue:
`Error switching chain
    at chunk-YUNHZJBB.js:275:13
    at Generator.throw (<anonymous>)
    at asyncGeneratorStep (asyncToGenerator.js:3:1)
    at _throw (asyncToGenerator.js:29:1)
    at _ZoneDelegate.invoke (zone.js:372:26)
    at Object.onInvoke (core.mjs:26274:33)
    at _ZoneDelegate.invoke (zone.js:371:52)
    at Zone.run (zone.js:134:43)
    at zone.js:1275:36
    at _ZoneDelegate.invokeTask (zone.js:406:31)`

### Expected Behavior

It should change the network smoothly.

### Steps To Reproduce

1. Open link https://lovehateinu.com/en
2. Click on **BUY NOW** button.
3. Select MEtamask from the opened modal.
4. Now click on the **Buy with BNB** button at the bottom of the  center block.
5. You can check the status on console panel too of inspect element mode.

**Comment by nfts2me** [comment]
We have the same problem, the network switch does not work properly. Before, everything worked correctly

**Comment by jxom** [comment]
This is a [MetaMask issue](https://github.com/MetaMask/metamask-extension/issues/18509). The newest version of MetaMask has the fix. Doesn't seem to be published yet, but hopefully soon.

https://github.com/MetaMask/metamask-extension/releases/tag/v10.28.3
