### ISSUE TITLE
bug:the website of wagmi  ,https://wagmi.sh/examples/connect-wallet  Metamask connect throw an error

### ISSUE THREAD

**Issue by Clickcheng110** [wagmi-dev/wagmi#2176]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.12.10

### Current Behavior

when i click the metamask button ,it throw an error

### Expected Behavior

I wish when i click metamask button, then he will show modal of metakmask extension

### Steps To Reproduce

Steps:
1. open https://wagmi.sh/examples/connect-wallet
2. click metamask connect or inject connect
3. then you will find this error
<img width="981" alt="image" src="https://user-images.githubusercontent.com/128121971/231680960-117a6aeb-f197-4c77-a48b-cb11f647cd17.png">

**Comment by jxom** [comment]
Works for me. Try clear cache, or re-install metamask?

<img width="901" alt="Screenshot 2023-04-13 at 5 12 28 pm" src="https://user-images.githubusercontent.com/7336481/231682158-322498b7-e9d5-4ec8-9624-c1e12f050694.png">

**Comment by tmm** [comment]
`Resource unavailable` usually shows up when the MetaMask extension popup is already open. I'd check around to see that it's not hidden behind another window on your computer.
