### ISSUE TITLE
MetaMask: Received invalid isUnlocked parameter. Please report this bug

### ISSUE THREAD

**Issue by qieman** [wagmi-dev/wagmi#2181]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.11.5

### Current Behavior

A bug tracked by trackjs, I didn't use Metamask's API directly but Wagmi's hook. I can't find the reason for this error. It seems to only appear on mobile web pages occasionally.

![image](https://user-images.githubusercontent.com/9875305/231930623-e1c7dcbe-a885-4bcd-b98e-3f46df671f47.png)

here is my wagmi configuration：

```
import { mainnet, moonbeam } from 'wagmi/chains'
import { InjectedConnector } from 'wagmi/connectors/injected'
import { WalletConnectConnector } from 'wagmi/connectors/walletConnect'
import { publicProvider } from 'wagmi/providers/public'

const walletconnect = new WalletConnectConnector({
    chains: [mainnet, moonbeam],
    options: {},
})

const inject = new InjectedConnector({
    chains: [mainnet, moonbeam],
})

const { chains, provider } = configureChains(
    [mainnet, moonbeam],
    [publicProvider()],
)

const wagmiClient = createClient({
    autoConnect: true,
    connectors: [inject, walletconnect],
    provider,
})
```

**Comment by jxom** [comment]
Probably a bug in MetaMask. Might be worth opening an issue on MetaMasks repo.
