### ISSUE TITLE
bug: web "send transaction" tutorial have a mistake

### ISSUE THREAD

**Issue by MaximRugal** [wagmi-dev/wagmi#2184]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

bug

### Current Behavior

[LINK](https://wagmi.sh/examples/send-transaction)

In this example, the library import is lost as it progresses

at first : 
import { utils } from 'ethers'
value: debouncedAmount ? **utils.parseEther**(debouncedAmount) : undefined

then: 
**no import**
value: debouncedAmount ? parseEther(debouncedAmount) : undefined,

### Link to Minimal Reproducible Example (StackBlitz, CodeSandbox, GitHub repo etc.)

https://wagmi.sh/examples/send-transaction

**Comment by jxom** [comment]
Fixed!
