### ISSUE TITLE
bug: ContractMethodDoesNotExistError

### ISSUE THREAD

**Issue by bahoss** [wagmi-dev/wagmi#2195]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.6.8

### Current Behavior

When I use  hook usePrepareContractWrite, get this error nction "depositByNativeToken" on contract "0x7dbfdc0a2d18f690d35f38e66dfab795c0175dac" does not exist.

But in contract has transactions with this method https://ftmscan.com/address/0x7dbfdc0a2d18f690d35f38e66dfab795c0175dac

How can i fix that?

**Comment by tmm** [comment]
Thanks for reporting. This issue is temporarily closed due to lack of information. Please provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) and reopen this issue.

**Comment by Joshuajee** [comment]
I am still having the same issues, my contract is verified on etherscan, I can use it there but some functions don't work with wagmi
