### ISSUE TITLE
watchAccount doesn't fire when user switches accounts in metamask 

### ISSUE THREAD

**Issue by ArinCantCode** [wagmi-dev/wagmi#2199]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.12.10

### Current Behavior

My code: 

```

import React, { ReactNode } from 'react';
import { EthereumClient, w3mConnectors, w3mProvider } from '@web3modal/ethereum';
import {
  configureChains, createClient, WagmiConfig, useSignMessage,
} from 'wagmi';
import { mainnet } from 'wagmi/chains';
import { watchAccount } from '@wagmi/core';

const chains = [mainnet];
const projectId = '<projectID>';

const { provider } = configureChains(chains, [w3mProvider({ projectId })]);
const wagmiClient = createClient({
  connectors: w3mConnectors({ projectId, version: 2, chains }),
  provider,
});
const ethereumClient = new EthereumClient(wagmiClient, chains);

const AccountWatch = () => {
  const { isError, signMessageAsync } = useSignMessage({ message });
  watchAccount(({ isConnected, isConnecting, address }) => {
    console.debug('AccountWatch SWTICH', { isConnected, isConnecting, address });
  });

  return null;
};

export const withWeb3Modal = (component: () => ReactNode) => () => (
  <>
    <WagmiConfig client={wagmiClient}>
      <AccountWatch />
      {component()}
    </WagmiConfig>

    <Web3Modal projectId={projectId} ethereumClient={ethereumClient} />
  </>
);

```

Hook gets fired on app load as well as when i connect my account but when i try to switch account inside my metamask the hook isn't fired

### Expected Behavior

Hook fires when account is changed inside metamask

### Steps To Reproduce

1. Load app
2. Connect using web3modal
3. Refresh page
4. Switch account inside metamask

**Comment by tmm** [comment]
Thanks for reporting. This issue is temporarily closed due to lack of information. Please provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) and reopen this issue.

The way you are using `watchAccount` looks incorrect. You want to set it up in a `React.useEffect` instead of calling it in the component body like that.

**Comment by SashaDesigN** [comment]
I have the same issue, Metamast + Chrome on MAC
