### ISSUE TITLE
bug: Improper import of not-compiled ethers package

### ISSUE THREAD

**Issue by brunocangs** [wagmi-dev/wagmi#2205]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

@wagmi/core 0.10.9

### Current Behavior

When dynamic `import()`ing `@wagmi/core` and `@wagmi/core/providers/public` on a Nextjs app, it tries to resolve the development version of the `ethers/lib/utils.js` file. 

Since that file is not exported by `ethers/package.json`, the import fails and so does the build

<img width="655" alt="image" src="https://user-images.githubusercontent.com/30100875/233186134-f6f47786-3204-421b-9423-66c6f49e914d.png">

### Expected Behavior

The package should not reference files that are not correctly exported by the package and should work when `import()`ed dynamically

### Steps To Reproduce

Create a new Next app with `yarn create next-app`
`yarn install @wagmi/core ethers` as per the docs instruction. This behaviour is consistent on both `ethers` v5 and v6
`import("@wagmi/core")` on any file and try to load `localhost:3000` 

### Link to Minimal Reproducible Example (StackBlitz, CodeSandbox, GitHub repo etc.)

https://github.com/brunocangs/wagmi-import-issue

**Comment by roninjin10** [comment]
Are you using ethers v6 or v5?   Wagmi only works with v5.

**Comment by roninjin10** [comment]
Wagmi only supports ethers v5.   Run “yarn add ethers@5” and your issue will be fixed

**Comment by brunocangs** [comment]
> Wagmi only supports ethers v5. Run “yarn add ethers@5” and your issue will be fixed

I see! It actually did work, thank you

Would be nice to update the docs on the setup part
<img width="502" alt="image" src="https://user-images.githubusercontent.com/30100875/234593338-4ac8697b-06c9-4ec1-86d7-a3c838b071d9.png">

**Comment by roninjin10** [comment]
@brunocangs try using viem instead of wagmi/core.   Viem is the latest version of wagmi core in a wag

**Comment by roninjin10** [comment]
@brunocangs try using viem instead of wagmi/core. Viem is the latest version of wagmi core in a way
