### ISSUE TITLE
bug: Cannot switch chain with wagmi useSwitchNetwork

### ISSUE THREAD

**Issue by GabCh15** [wagmi-dev/wagmi#2206]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.10.15

### Current Behavior

When I try to use useSwitchNetwork with metamask throught web3auth I get this error:

![image](https://user-images.githubusercontent.com/64225598/233206651-5f2c9bb1-0bc3-432f-8e7f-3c8fb3344e8d.png)

 This is how I'm using the switchNetwork function
 
 `    if (switchNetwork)
      switchNetwork(1)
    return () => {
      if (switchNetwork)
        switchNetwork(137)
      return
    }
    `

### Expected Behavior

What I was expecting was the chain to switch

### Steps To Reproduce

This a simple app using web3auth + wagmi + useSwitchNetwork, I don't really know what the problem is

**Comment by tmm** [comment]
Thanks for reporting. This issue is temporarily closed due to lack of information. Please provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) and reopen this issue.
