### ISSUE TITLE
bug: Approve pop-up not autofilling value field anymore

### ISSUE THREAD

**Issue by daburuu** [wagmi-dev/wagmi#2212]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.12.12

### Current Behavior

When i call the approve function with a given value, the metamask pop-up appears but the "Amount" field is blank. I then have to click on either "Max." or "Use default." for the field to be filled. It only happened since the new metamask approval window UX/UI.

### Expected Behavior

When i call the approve function, the value is correctly set as soon as the pop-up opens.

### Steps To Reproduce

Call the approve config like this:

```
const { config: approveConfig }: { config: any } = usePrepareContractWrite({ 
    address: contractAddress, 
    functionName: "approve", 
    abi: [ { 
        "name": "approve", 
        "inputs": [{ 
            "internalType": "address", 
            "name": "spender", 
            "type": "address" 
        }, 
        { 
            "internalType": "uint256", 
            "name": "amount", 
            "type": "uint256" 
        }],
        "outputs": [
             { 
                "internalType": "bool", 
                "name": "", 
                "type": "bool" 
            }
        ],
        "stateMutability": "nonpayable", 
        "type": "function" 
    } ], 
  args: [spender, BigNumber.from(MAX_UINT256_VALUE)]
});
```

**Comment by tmm** [comment]
Thanks for reporting. This issue is temporarily closed due to lack of information. Please provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) and reopen this issue.

What contract address are you using? Having a complete example will help us help you.

**Comment by snorkypie** [comment]
This is because of an update to metamask (expected behaviour now) and not related to wagmi
