### ISSUE TITLE
SyntaxError Unexpected token .

### ISSUE THREAD

**Issue by gaokaikai** [wagmi-dev/wagmi#2222]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.12.12

### Current Behavior

部分android手机浏览器报错页面崩溃 白屏
引入wagmi的库的项目就会出现这样的问题

### Anything else?

<img width="1263" alt="image" src="https://user-images.githubusercontent.com/29045512/233936405-0127dd42-61c5-4f47-bd0d-e01578ff2641.png">
<img width="1185" alt="image" src="https://user-images.githubusercontent.com/29045512/233936456-1d2b93e3-9a9a-4fca-a39e-9a6ff168bc73.png">
<img width="482" alt="image" src="https://user-images.githubusercontent.com/29045512/233936862-1270209c-297e-42b1-b349-bfdce9730962.png">
node 本地版本 v16.20.0

**Comment by jxom** [comment]
Thanks for reporting. This issue is temporarily closed due to lack of information. Please provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) via https://new.wagmi.sh and then we will re-open the issue.

**Comment by gaokaikai** [comment]
> 感谢您的报告。由于缺乏信息，这个问题暂时关闭。请通过https://new.wagmi.sh提供一个[最小的可重现示例](https://stackoverflow.com/help/minimal-reproducible-example)，然后我们将重新打开该问题。[](https://new.wagmi.sh)

https://new.wagmi.sh/这个就是最小的例子 这个代码在部分android手机浏览器上就会崩溃

**Comment by gaokaikai** [comment]
> Thanks for reporting. This issue is temporarily closed due to lack of information. Please provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) via https://new.wagmi.sh and then we will re-open the issue.

意思就是引入了咱们的库在部分android浏览器上就会报错 崩溃
