### ISSUE TITLE
bug: Vite build error

### ISSUE THREAD

**Issue by RexHung0302** [wagmi-dev/wagmi#2228]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.4.9

### Current Behavior

I'm use wagmi on my project, here is my project basic setting:
- "vite": "^2.9.9"
- "react": "^18.0.0"
- "wagmi": "^0.5.9"

I got error like `'EventEmitter' is not exported by __vite-browser-external, imported by node_modules/@walletconnect/jsonrpc-provider/dist/esm/provider.js
file:  xxxx/xxxx/xxxx/xxxx`, I don't use walletconnect on my project, so I think this is wagmi dependency, why I got this error?

<img width="493" alt="截圖 2023-04-25 下午2 28 28" src="https://user-images.githubusercontent.com/45451039/234192349-eb0d1b07-8bdc-4ba5-abc4-2ba9cb6f5037.png">

### Expected Behavior

I expected build success.

### Steps To Reproduce

1. yarn install
2. yarn build
3. got error

**Comment by jxom** [comment]
Thanks for reporting. This issue is temporarily closed due to lack of information. Please provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) via a https://new.wagmi.sh fork and I'll reopen this issue.

https://new.wagmi.sh is a Vite project that successfully compiles a wagmi application. Might be worth cross-referencing your app with that one.

**Comment by RexHung0302** [comment]
Sorry, I found the problem.

https://github.com/vitejs/vite/issues/7821

I don't use any EventEmitter on my project, so I search dose anyone happended this problem too.

I install vite-plugin-node-polyfills for my vite project, and add `nodePolyfills` setting on vite.config.ts then resolve this problem.

```
import { defineConfig } from 'vite';
import { resolve } from 'path';
import { nodePolyfills } from 'vite-plugin-node-polyfills';
import react from '@vitejs/plugin-react';

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [
    react(),
    // I add this on my project
    nodePolyfills({
      protocolImports: true,
    }),
  ],
  // server: {
  //   host: '0.0.0.0',
  // },
  base: '/',
  esbuild: {
    drop: process.env.NODE_ENV === 'production' ? ['console', 'debugger'] : [],
  },
  resolve: {
    alias: [
      {
        find: '@',
        replacement: resolve(__dirname, 'src'),
      },
      {
        find: '@utils',
        replacement: resolve(__dirname, 'src/utils'),
      },
      {
        find: '@constants',
        replacement: resolve(__dirname, 'src/constants'),
      },
      {
        find: '@store',
        replacement: resolve(__dirname, 'src/store'),
      },
      {
        find: '@components',
        replacement: resolve(__dirname, 'src/components'),
      },
      {
        find: '@assets',
        replacement: resolve(__dirname, 'src/assets'),
      },
    ],
  },
});
```

I don't know why always build failed on jenkins, but sometime build success on local.
Hope this can help someone got this promble.
