### ISSUE TITLE
bug: Error in WalletconnectConnector in 0.12.12

### ISSUE THREAD

**Issue by frankfka** [wagmi-dev/wagmi#2236]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.12.12

### Current Behavior

In a `Next.js` app with `WalletConnectConnector`, I'm seeing:

```
TypeError: class heritage _walletconnect_types__WEBPACK_IMPORTED_MODULE_4__.IVerify is not an object or null
```

This does **not** occur with 0.12.11

### Expected Behavior

No error

### Steps To Reproduce

Install wagmi 0.12.12 on a Next.js app (haven't tried with other frameworks)

**Comment by jxom** [comment]
I cannot seem to reproduce this. Can you please link us to a minimal reproducible example (can use https://new.wagmi.sh). Will re-open when one is provided.

**Comment by aiiiden** [comment]
This issue also reproduce in version: `1.3.9`.

**Comment by aiiiden** [comment]
In console
```
Attempted import error: 'IVerify' is not exported from '@walletconnect/types' (imported as 'Zt').
```

In browser console,
```
9578.fda3393d854767ca.js:1 Uncaught (in promise) TypeError: Class extends value undefined is not a constructor or null
    at 49578 (9578.fda3393d854767ca.js:1:94449)
    at Function.s (webpack-e889ff643096189c.js:1:167)
    at async k.u (1236.b867ac4e24d92a7e.js:36:33433)
49578 @ 9578.fda3393d854767ca.js:1
s @ webpack-e889ff643096189c.js:1

```

**Comment by aiiiden** [comment]
I cannot reproduce in another env. but, I cannot track the error. no clue for this issue... @jxom
