### ISSUE TITLE
useContractReads don't use multicall if one call network is not support

### ISSUE THREAD

**Issue by 15077693d** [wagmi-dev/wagmi#2238]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.12.6

### Current Behavior

1. contract call contain METIS_ANDROMEDA_MAINNET and METIS_GOERLI_TESTNET which are multicall not supported.
2. All call use sigle call then

### Expected Behavior

All call use multi call except non supported network.

### Steps To Reproduce

-

### Link to Minimal Reproducible Example (StackBlitz, CodeSandbox, GitHub repo etc.)

https://codesandbox.io/s/try-wagmi-usecontractreads-xzbcv2?file=/src/App.tsx

**Comment by jxom** [comment]
Metis does not have a multicall contract, so it will not use a multicall and use single calls instead.

**Comment by ChrisChan888** [comment]
> Metis does not have a multicall contract, so it will not use a multicall and use single calls instead. 

Yes, Metis does not have multi call contract. But avax and avax fuji have why the call from avax and avax Fuji used single call?
