### ISSUE TITLE
useContractReads don't use multicall if one call network is not support

### ISSUE THREAD

**Issue by 15077693d** [wagmi-dev/wagmi#2241]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.12.6

### Current Behavior

-> contracts in avax and avax testnet ( multicall available)
<img width="465" alt="Screenshot 2023-04-28 at 9 38 18 AM" src="https://user-images.githubusercontent.com/51513183/235033948-2c516352-dc5b-4e17-be70-4493d5bbb72e.png">

-> contracts in avax, avax testnet ( multicall available), metis(multicall available)
<img width="465" alt="Screenshot 2023-04-28 at 9 37 56 AM" src="https://user-images.githubusercontent.com/51513183/235033944-6ebf851f-af20-4fbb-8351-433b53347749.png">

### Expected Behavior

-> contracts in avax and avax testnet ( multicall available)
Total Two call (avax multicall and avax testnet multicall)

-> contracts in avax, avax testnet ( multicall available), metis(multicall available)
Total Two call (avax multicall and avax testnet multicall) + some metis signle calls

### Link to Minimal Reproducible Example (StackBlitz, CodeSandbox, GitHub repo etc.)

https://codesandbox.io/s/try-wagmi-usecontractreads-xzbcv2?file=/src/App.tsx:631-1073

**Comment by jxom** [comment]
That's expected as you can only perform multicall on one chain at a time – meaning 1 call for `avax` + 1 call for `avaxTestnet` = 2 in total.

Metis also doesn't have a multicall contract, so the single calls are expected there.

**Comment by 15077693d** [comment]
> That's expected as you can only perform multicall on one chain at a time – meaning 1 call for `avax` + 1 call for `avaxTestnet` = 2 in total.
> 
> Metis also doesn't have a multicall contract, so the single calls are expected there.

when contracts. = [avaxContract,avaxContract,avaxTestContract,avaxTestContract,metisContract,metisContract]
I expect 1 call for avax + 1 call for avaxTestnet + 2 call for metis= 4 in total.

But actual = 2 call for avax + 2 call for avaxTestnet + 2 call for metis= 6 in total.

**Comment by jxom** [comment]
I seem to be getting one call for each in this example: https://stackblitz.com/edit/new-wagmi-v32cjb?file=src%2FApp.tsx,src%2Fwagmi.ts

Can you please provide a reproducible example via that sandbox?

**Comment by 15077693d** [comment]
> I seem to be getting one call for each in this example: https://stackblitz.com/edit/new-wagmi-v32cjb?file=src%2FApp.tsx,src%2Fwagmi.ts
> 
> Can you please provide a reproducible example via that sandbox?

Yes, your example is two multicall supported network.
The following example which have two multicall supported network and one multicall unsupported network:
I expect 1 call for avax + 1 call for avaxTestnet + 2 call for metis= 4 in total.
But actual = 2 call for avax + 2 call for avaxTestnet + 2 call for metis= 6 in total.
https://codesandbox.io/s/try-wagmi-usecontractreads-xzbcv2?file=/src/App.tsx
