### ISSUE TITLE
Can't use wagmi walletconnectconnector v2 in production

### ISSUE THREAD

**Issue by devsalman247** [wagmi-dev/wagmi#2253]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.12.12

### Current Behavior

We're having issues using wagmi walletconnectconnector v2.When the page loads i see error on console:
 "To use QR modal, please install @web3modal/standalone package"
 You can also check here : [NFT Promo](http://54.152.2.123/)
 
![Error](https://user-images.githubusercontent.com/112937676/235649585-95fa2a62-eddf-441a-b02d-f302ed87103f.png)

### Expected Behavior

Open a qrmodal on connect

### Steps To Reproduce

Here is my config (I'm following same guide from [Wagmi Wallet Connect](https://wagmi.sh/examples/connect-wallet) ) :

**Config:**
```
import { createClient, configureChains, mainnet } from "wagmi";
import { publicProvider } from "wagmi/providers/public";
import { MetaMaskConnector } from "wagmi/connectors/metaMask";
import { CoinbaseWalletConnector } from "wagmi/connectors/coinbaseWallet";
import { WalletConnectConnector } from "wagmi/connectors/walletConnect";
import { bsc } from "wagmi/chains";

export const walletConnectProjectId = ".........";

const { chains, provider, webSocketProvider } = configureChains([mainnet, bsc], [publicProvider()]);

export const client = createClient({
	autoConnect: true,
	connectors: [
		new MetaMaskConnector({ chains }),
		new CoinbaseWalletConnector({
			chains,
			options: {
				appName: "App Name",
			},
		}),
		new WalletConnectConnector({
			chains,
			options: {
				showQrModal: true,
				projectId: walletConnectProjectId,
			},
		}),
	],
	provider,
	webSocketProvider,
})
```

Use wagmi useConnect() Hook

**Comment by tmm** [comment]
Thanks for reporting. This issue is temporarily closed due to lack of information. Please provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) and reopen this issue.

**Comment by kristiegiles** [comment]
I was also having this issue but got a different error after upgrading to wagmi v1.2.1

**Comment by tmm** [comment]
@kristiegiles if you are having an issue, please add a minimal reproducible example so we can take a look.
