### ISSUE TITLE
bug @wagmi/cli: generate fails because esbuild version is <=16

### ISSUE THREAD

**Issue by Valentin-Seehausen** [wagmi-dev/wagmi#2254]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.1.15

### Current Behavior

When you use wagmi/cli in a svelte project, the command `npx wagmi generate` will fail with:

```
Build failed with 1 error:
project/node_modules/esbuild/lib/main.js:255:12: ERROR: Invalid option in build() call: "watch"
```

### Expected Behavior

When you lock the esbuild version in your project like this:

`		"esbuild": "0.16.5",`

It works.

More content: https://stackoverflow.com/questions/10972176/find-the-version-of-an-installed-npm-package

### Anything else?

I think upgrading the esbuild version (currently set to 0.15.13) would easily mitigate this error.

Thanks for the awesome library!

**Comment by j5h46bd** [comment]
same issue exactly. thanks for posting this!

**Comment by hiromaily** [comment]
I found same error by esbuild 0.18

**Comment by Valentin-Seehausen** [comment]
Well done!

**Comment by garlic-brewlabs** [comment]
I get the same issue using Vite version 5.0.8 

`Invalid option in build() call: "watch"`
'node_modules\esbuild\lib\main.js:255:12:`
`throw new Error(`Invalid option ${where}: ${quote(key)}`);`
