### ISSUE TITLE
bug: No redirect back to the platform when triggering signMessage

### ISSUE THREAD

**Issue by Cristi6** [wagmi-dev/wagmi#2257]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.12.12

### Current Behavior

I am using WalletConnect v2 with wagmi and some wallets open a new tab in your browser to approve a session proposal, sign a message, etc. An example of a wallet like this would be Venly but the issue is that when I trigger `signMessage` from `useSignMessage`, my app gets replaced in the same tab with the Venly wallet and after I sign the message, there is no redirect back.

### Expected Behavior

Ideally would be to open the sign in another tab, just as WalletConnect does for the session proposal. 

### Steps To Reproduce

1. Connect with Venly inside WalletConnect v2
2. Trigger a `signMessage` from `useSignMessage`

### Link to Minimal Reproducible Example (StackBlitz, CodeSandbox, GitHub repo etc.)

https://codesandbox.io/s/relaxed-varahamihira-xh5vv9

### Anything else?

When I get redirected to Venly to sign the message, the route looks like this `https://walletconnect.venly.io/wc?requestId=undefined&sessionTopic=b3ec26e4d59767dee5b4b6010fbd6cf863a99eb0cc620c84fd5b149bb26253e3`
Maybe requiestId might be the issue? I don't see any params on useSignMessage that could help me with this behavior. 

The codesandbox that I attached does redirect to Venly but doesn't show the sign action, maybe it's just because of the sandbox but I got the same code on my repo and I encounter the issue.

**Comment by jxom** [comment]
Seems like this issue stems in either the WalletConnect implementation or Venly's implementation of WalletConnect v2. Would you mind opening this issue on the [WalletConnect repository](https://github.com/WalletConnect/walletconnect-monorepo)? 

Will close this here for now.
