### ISSUE TITLE
Unexpected token .

### ISSUE THREAD

**Issue by gaokaikai** [wagmi-dev/wagmi#2259]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.12.10

### Current Behavior

wagmi库在部分android浏览器下报错导致页面崩溃

### Expected Behavior

期望页面不崩溃 可以显示

### Steps To Reproduce

[[new.wagmi.sh](https://new.wagmi.sh/)](https://new.wagmi.sh)
这个就是例子部分android浏览器页面崩溃

### Link to Minimal Reproducible Example (StackBlitz, CodeSandbox, GitHub repo etc.)

https://new.wagmi.sh

### Anything else?

<img width="1229" alt="image" src="https://user-images.githubusercontent.com/29045512/236098008-9d5f81aa-0bfb-49ad-baad-64f33e6bca6c.png">
<img width="676" alt="image" src="https://user-images.githubusercontent.com/29045512/236098042-e0f7ef54-b74a-4e56-9aa0-6c1a355b4d74.png">

**Comment by jxom** [comment]
Thanks for reporting. This issue is temporarily closed due to lack of information. Please provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example). Other information is also helpful, like framework (e.g. Next.js), browser, etc.

**Comment by gaokaikai** [comment]
> 感谢您的报告。由于缺乏信息，这个问题暂时关闭。请提供一个[最小的可重现示例](https://stackoverflow.com/help/minimal-reproducible-example)。其他信息也很有帮助，例如框架（例如 Next.js）、浏览器等。

你怎么看的 我不是提供了最小可重现示例了 天天就知道关闭

**Comment by jxom** [comment]
Could be because the browser is MiuiBrowser which I have not heard of. wagmi is supported on all modern browsers such as Chrome, Safari, Firefox, etc.

**Comment by gaokaikai** [comment]
> 可能是因为浏览器是我没听说过的MiuiBrowser。所有现代浏览器都支持 wagmi，例如 Chrome、Safari、Firefox 等。
部分android手机自带的浏览器不支持吗  咱们库不能说只支持Chrome、Safari、Firefox这几个吧  而且请不要把我的问题关闭  我需要解决这个问题

**Comment by gaokaikai** [comment]
> 可能是因为浏览器是我没听说过的MiuiBrowser。所有现代浏览器都支持 wagmi，例如 Chrome、Safari、Firefox 等。

请把我的问题打开 谢谢🙏

**Comment by gaokaikai** [comment]
> 
是android小米手机自带的 那我这边有没有什么办法来解决页面崩溃的问题呢 现在想实现wagmi报错 页面依然可以正常显示的功能

**Comment by gaokaikai** [comment]
> Is MiuiBrowser a built-in android browser? I thought it was one that you download separately. Unfortunately, wagmi doesn't support browsers that do not support modern JavaScript.

大哥 咱们支持一下android这种浏览器呗

**Comment by gaokaikai** [comment]
> Is MiuiBrowser a built-in android browser? I thought it was one that you download separately. Unfortunately, wagmi doesn't support browsers that do not support modern JavaScript.

我发现这是一个js版本的问题 wagmi/dist/index.js 依然采用的是es6的语法 所以某些浏览器会报错 您能帮忙改进一下这个问题吗

**Comment by gaokaikai** [comment]
> Is MiuiBrowser a built-in android browser? I thought it was one that you download separately. Unfortunately, wagmi doesn't support browsers that do not support modern JavaScript.

解决了 因为咱们库用的es6语法 需要编译的时候把咱们库的代码编译成es5

**Comment by yfs-2000** [comment]
> > Is MiuiBrowser a built-in android browser? I thought it was one that you download separately. Unfortunately, wagmi doesn't support browsers that do not support modern JavaScript.
> 
> 解决了 因为咱们库用的es6语法 需要编译的时候把咱们库的代码编译成es5

怎么解决的  我也有这个问题  我服了
