### ISSUE TITLE
bug: Cannot signMessageAsync with Zengo wallet through WalletConnectLegacy (v1)

### ISSUE THREAD

**Issue by tomtomdu73** [wagmi-dev/wagmi#2268]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.12.12

### Current Behavior

I cannot sign a message (using signMessageAsync() ) with Zengo wallet using WalletConnectLegacyConnector. 

I scan the Qr code provided by WalletConnectLegacyConnector from my Zengo app wallet to first connect and it works. 
Then I need to sign a message: I receive the message to sign on the Zengo app, I sign it in the app but I do not receive any response from the await signMessageAsync() on the frontend.

<img width="400" alt="Screenshot 2023-05-04 at 5 02 06 PM" src="https://user-images.githubusercontent.com/10169612/236317229-6387b71e-b5eb-46af-a504-60211335ddb2.jpg">

I have checked the WebSocket messages and I see the response coming from Zengo containing the signed message in data, however the signed message is not returned by wagmi signMessageAsync function. 

<img width="1113" alt="Screenshot 2023-05-04 at 5 02 06 PM" src="https://user-images.githubusercontent.com/10169612/236316600-3d0f694b-f0f2-4bc9-be05-b3ef84f3f12a.png">

I have tried logging in scanning the QR code with another mobile wallet like Trustwallet and the whole process goes smoothly.

### Expected Behavior

I should be able to connect and sign a message using Zengo wallet. 

### Steps To Reproduce

You should download the latest version of Zengo app wallet and try to connect with Zengo wallet on http://app.thesmurfssociety.com

### Link to Minimal Reproducible Example (StackBlitz, CodeSandbox, GitHub repo etc.)

https://app.thesmurfssociety.com

**Comment by Mulander-J** [comment]
I also encountered this problem. Would it still reproduce without wagmi?

**Comment by tmm** [comment]
> I have tried logging in scanning the QR code with another mobile wallet like Trustwallet and the whole process goes smoothly.

Seems like an issue with Zengo Wallet if other wallets work. Recommend following up with that team.
