### ISSUE TITLE
bug: usePrepareContractWrite returns empty error when enabled is false

### ISSUE THREAD

**Issue by BramMathijssen** [wagmi-dev/wagmi#2282]
### Is there an existing issue for this?

- [X] I have searched the existing issues
I found someone with a similar issue here: https://github.com/wagmi-dev/wagmi/issues/1526 

### Package Version

0.12.12

### Current Behavior

When I call the usePrepareContractWrite() hook with enabled false, isError will return true, which will return an empty error message. This will ONLY happen when all three of my args are empty strings. In my example below the initial state of my memberAddress, memberName and memberRole are all empty strings "". And the error message will trigger because isError is true. Which gives the output: ERROR. 

When I change **one or more** of my state variables initial value to something else, for example a single character the error will disappear. 

```
const AddMemberForm = () => {
    const { chain } = useNetwork();
    const { address, isConnected } = useAccount();
	
    const [memberAddress, setMemberAddress] = useState("");
    const [memberName, setMemberName] = useState("");
    const [memberRole, setMemberRole] = useState("");

    const {
        config,
        error: prepareError,
        isError: isPrepareError,
    } = usePrepareContractWrite({
        address: getContractAddressByChain(chain, CONTRACTS.DAO_CONTRACT),
        abi: daoContractAbi,
        functionName: "addMember",
        args: [memberAddress, memberName, memberRole],
        enabled: false,
    });

    const { data, error, isError, write } = useContractWrite(config);

    const { isLoading, isSuccess } = useWaitForTransaction({
        hash: data?.hash,
    });

    return (
        <form
            onSubmit={(e) => {
                e.preventDefault();
                write?.();
            }}
        >
            <label>Address</label>
            <input id="address" onChange={(e) => setMemberAddress(e.target.value)} placeholder="0x70997970C51812dc3A010C7d01b50e0d17dc79C8" value={memberAddress} />
            <label>Name</label>
            <input id="name" onChange={(e) => setMemberName(e.target.value)} placeholder="bert" value={memberName} />
            <label>Role</label>
            <input id="role" onChange={(e) => setMemberRole(e.target.value)} placeholder="0" value={memberRole} />
            <button disabled={!write || isLoading}>{isLoading ? "Minting..." : "Mint"}</button>

            {((isPrepareError || isError)) && <div>Error: {(prepareError || error)?.message}</div>}
        </form>
    );
};

export default AddMemberForm;
```

The above code will give the following output

![image](https://user-images.githubusercontent.com/15011053/236835298-2056df25-5cc5-42db-bf37-f3bc68356ea6.png)

The error only happens on this specific function which I'm trying to call, the signature of the function I'm trying to call is: 

```
function addMember(address _address, bytes32 _name, Role _role) external hasRole(ADMIN) {
 }
```

The error does not appear when if try to call the following function

```
function createProposal(string memory _description, Duration _duration) external hasRole(USER) {
 } 
```

### Expected Behavior

I'd expect no error message to appear when enabled is set to false

**Comment by scyllacz** [comment]
Hi, this error happens to me too. I made a reproducible example. Here is the link.
https://stackblitz.com/edit/new-wagmi-vowkg9?file=src%2FApp.tsx

You need to do the following steps to make it happen. 
Press Toggle Enable twice. Then reload react app page in stackblitz.
Then even if the hook is set to enable = false, I get isError true and error is an empty object for args null;
If I change the name of the function, I get to the correct state before I do the first enable. 
There is another strange behavior related to this, that if I don't enable the hook and switch the argument (null <=> 5), I don't get any error. BUT if I turn the hook on at least once and then off. For args null I start getting the error "Cannot convert null to a BigInt". 

I hope this helps.

**Comment by tmm** [comment]
@scyllacz please open a new issue if you want this to be looked into. in general, commenting on old issues is a great way for things to get lost.
