### ISSUE TITLE
bug: Issue with TrustWallet (WalletConnect) "Method Not Supported"

### ISSUE THREAD

**Issue by arslancodes** [wagmi-dev/wagmi#2283]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.10.11

### Current Behavior

If you connect to the TrustWallet App using the WalletConnect on this [Send Transaction - wagmi](https://wagmi.sh/examples/send-transaction) page and send a transaction, on the TrustWallet Application you get "Method Not Supported". I have seen the same behaviour on the local deployment of wagmi.

### Expected Behavior

It is expected after connection on the app to show that transaction confirmation page, instead it shows and error message "Method Not Supported" on the demo on wagmi's documentation as well as the local deployment of wagmi.

### Steps To Reproduce

1. Connect to your TrustWallet App using WalletConnect on [this](https://wagmi.sh/examples/send-transaction) page
2. Add the Recipient wallet address and the Amount
3. Click the "Send" Button
4. On the App, it will show an error message instead of showing the transaction page.

### Link to Minimal Reproducible Example (StackBlitz, CodeSandbox, GitHub repo etc.)

https://wagmi.sh/examples/send-transaction

**Comment by lassejaco** [comment]
I'm seeing this with Safe and Argent too

**Comment by jxom** [comment]
This issue is because these wallets don’t fully support WalletConnect v2 or they have not upgraded to the latest WalletConnect v2 SDKs 😅

Not sure if there is much we can do apart from bugging the wallets to fix it.

**Comment by lassejaco** [comment]
@jxom do you know if this would also apply when setting "version: 1" in the WalletConnect config? I'm seeing these errors even when doing that

**Comment by jxom** [comment]
`version` is no longer a config option on `WalletConnectConnector`. To use WalletConnect v1, you can use `WalletConnectLegacyConnector`.

**Comment by lassejaco** [comment]
May have been the case before, but following the latest docs setting version: 1 falls back to that connector afaik

**Comment by jxom** [comment]
Can you point me to those docs?

**Comment by lassejaco** [comment]
https://docs.walletconnect.com/2.0/web3modal/html-js/installation

they in fact default to 1 in their docs (I assume because 2 is still giving issues with too many wallets)
