### ISSUE TITLE
bug: WalletConnect Attestation Error

### ISSUE THREAD

**Issue by frankfka** [wagmi-dev/wagmi#2285]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.12.13

### Current Behavior

Developer console shows 422 errors from walletconnect:
<img width="1168" alt="image" src="https://user-images.githubusercontent.com/31530056/236958210-c6b4abb0-2254-4135-b66f-fd64b39754fc.png">

You can repro here: https://wagmi.sh/examples/connect-wallet

**Comment by jxom** [comment]
This seems to be coming from the MetaMask browser extension, not wagmi. Might be worth opening an issue on the MetaMask repo?
