### ISSUE TITLE
bug: auto connecting wallet doesnot work

### ISSUE THREAD

**Issue by mintdart** [wagmi-dev/wagmi#2287]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

1.0.0

### Current Behavior

Connecting your wallet and refreshing the page disconnects it

### Expected Behavior

Reconnect with wallet on refreshing the page

### Steps To Reproduce

1. Connect Wallet
2. Refresh Page
3. Check `isConnected` in `useAccount` hook

### Link to Minimal Reproducible Example (StackBlitz, CodeSandbox, GitHub repo etc.)

https://codesandbox.io/p/sandbox/shy-sea-2yc1ni

**Comment by jxom** [comment]
Interesting. I can't seem to reproduce this with a project bootstrapped with `create-wagmi (`pnpm create wagmi`).

**Comment by mintdart** [comment]
it seems if we use `connector` in `useConnect` hook, auto connect does not work
```
  const { connect } = useConnect({
    connector: new InjectedConnector(),
  });
```

**Comment by tmm** [comment]
Correct, since that connector is not "registered" in the global wagmi config during the auto connect phase.

**Comment by mintdart** [comment]
got it, thanks.
