### ISSUE TITLE
bug: < Incorrect type inference in prepareWriteContract  > 

### ISSUE THREAD

**Issue by siosio34** [wagmi-dev/wagmi#2289]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

1.0.0

### Current Behavior

I tried to issue setApprovalForAll transaction with code like below.
However, after updating wagmi to 1.0.0, an error occurs in that type inference.
I am attaching a picture below.

![image](https://user-images.githubusercontent.com/7166022/237017375-b3e0aa21-f47f-478b-979f-c4acc227c686.png)

**Comment by jxom** [comment]
What's the error?

**Comment by jxom** [comment]
Seems to work for me: https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgUygYwOwCYCMBBAIQEkAaOMKZMAQ0oHUpgZkBhCAOximrRgF84AMygQQcAOQABAO7UA5iGAB6NNGTiAsAChtFKrWQMmrDlx4wAFAm1w41ACb3KAZ2cAuCQAYAHuJI27ACNgD1RMXEJSAMEAV3ZeYA4AOWoQZA9xZ2QYPDAKCAA3agAbADFoPGLivwDaOXc4AG1xHz84LhjkAF1-LT4ASiA

**Comment by jxom** [comment]
Published `1.0.1` which fixed `abitype` dependency resolution. Could be related. Closing for now, but if this is still occurring, I’ll reopen!

**Comment by siosio34** [comment]
please repopen this issue @jxom 

![image](https://user-images.githubusercontent.com/7166022/237049875-576abfe3-2c89-4fab-8c7a-17364b299de4.png)
![image](https://user-images.githubusercontent.com/7166022/237049948-dd8d7305-9f6b-4b98-bc28-eaddce2724a4.png)

**Comment by jxom** [comment]
What is the type error in the screenshot? I cannot see it.

**Comment by siosio34** [comment]
@jxom  is this what you want?
![image](https://github.com/wagmi-dev/wagmi/assets/7166022/c63feb8d-e9e7-4733-a924-950845cdf067)

**Comment by siosio34** [comment]
![image](https://github.com/wagmi-dev/wagmi/assets/7166022/3f7be86b-be80-4d0a-aed5-1de80ff50231)

We will send you additional photos. The meaning of that error is that the type any' cannot be assigned to the type 'never'. ts(2322)

**Comment by The18thWarrior** [comment]
> ![image](https://user-images.githubusercontent.com/7166022/237131216-3f7be86b-be80-4d0a-aed5-1de80ff50231.png)
> 
> We will send you additional photos. The meaning of that error is that the type any' cannot be assigned to the type 'never'. ts(2322)

I also am seeing this issue

**Comment by siosio34** [comment]
@jxom 
Could you please reopen this issue?

**Comment by siosio34** [comment]
hmm this code save me ! https://github.com/wagmi-dev/viem/commit/9ae5eaa1465240d07577d380e7387f1a065707e3
