### ISSUE TITLE
bug: Incorrect dependency in @walletconnect/universal-provider package

### ISSUE THREAD

**Issue by t0rbik** [wagmi-dev/wagmi#2290]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

1.0.0

### Current Behavior

When next.js compiles app it throws:
```
warn  - ./node_modules/@walletconnect/universal-provider/dist/index.es.js
Module not found: Can't resolve 'react-native' in '.../node_modules/@walletconnect/universal-provider/dist'
```

### Expected Behavior

No warning in console

### Steps To Reproduce

1. Create next.js + wagmi v1 project.
2. Add WalletConnect connector
3. Try to run dev or build.

### Anything else?

Wallet connect package with bug dependency is defined [here](https://github.com/wagmi-dev/references/blob/66471aca846b2760a4a4e37f4574b5169e0939c4/packages/connectors/package.json#L26).
Issue in WalletConnect/walletconnect-monorepo is [here](https://github.com/WalletConnect/walletconnect-monorepo/issues/2304).

Possible solution: change package version to 2.7.0

**Comment by jxom** [comment]
Let’s track this in the WalletConnect issue as this is a downstream issue.
