### ISSUE TITLE
bug: BSC testnet blastapi doesn't work

### ISSUE THREAD

**Issue by kouraf** [wagmi-dev/wagmi#2303]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.10.6

### Current Behavior

The blast api is stuck in block `0x1c3e1ef`

### Expected Behavior

To not be stuck

### Steps To Reproduce

Create a new BEP-20 token and try to get  its total_supply.

### Anything else?

changing the default api for bsc testnet is a quick fix. (I am using [ankr](https://rpc.ankr.com/bsc_testnet_chapel))

**Comment by tmm** [comment]
Thanks for reporting. This issue is temporarily closed due to lack of information. Please provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) and reopen this issue.
