### ISSUE TITLE
bug: <title>Using wgmi to build walletconnect, mobile phone scanning will crash back? How to define the displayed wallet, such as metamask, coinbase, etc.

### ISSUE THREAD

**Issue by youthinn** [wagmi-dev/wagmi#2309]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

1.0.2

### Current Behavior

I used wagmi to build walletconnet's wallet connection method, and I have built a code scanning page, but the mobile phone scan code will crash back regardless of the wallet, how to solve this problem? Also How to configure a custom wallet list?

### Expected Behavior

I hope to realize scanning the code login without flashback, and realize the deployment of your own wallet list

### Steps To Reproduce

1

### Link to Minimal Reproducible Example (StackBlitz, CodeSandbox, GitHub repo etc.)

https://www.baidu.com

### Anything else?

1

**Comment by jxom** [comment]
I'm not sure what you mean by "crash back". Can you elaborate?

Seems to work all fine for me. Can you please provide a minimal reproducible example via https://new.wagmi.sh? Will re-open when done.
