### ISSUE TITLE
build error: Can't resolve 'viem/chains' in @wagmi\connectors\dist

### ISSUE THREAD

**Issue by cxss** [wagmi-dev/wagmi#2310]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

1.0.2

### Current Behavior

./node_modules/@wagmi/connectors/dist/chunk-QYMCVNHT.js
Module not found: Can't resolve 'viem/chains' in ${work_dir}\node_modules\@wagmi\connectors\dist'

my dependency:
"viem": "^0.3.21",
 "wagmi": "^1.0.2",

**Comment by jxom** [comment]
Can you please provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) via https://new.wagmi.sh? Will re-open when done!

**Comment by iandjx** [comment]
@jxom  ive created a React app using react 17.0.2 and craco 6.3.0 . This is the current stack we are using in our app's codebase

starting the app would automatically display the above error

**Comment by cxss** [comment]
> @jxom ive created a React app using react 17.0.2 and craco 6.3.0 . This is the current stack we are using in our app's codebase
> 
> starting the app would automatically display the above error

yes, I'm using react 17.0.2 too

**Comment by jxom** [comment]
What version of react-scripts are you running? Webpack 4 doesn't support `package.json#exports`, so it could be worth upgrading?

**Comment by cxss** [comment]
I'm using "react-scripts": "4.0.1"

**Comment by jxom** [comment]
Should work if you upgrade to `^5` which comes with Webpack 5!

**Comment by cxss** [comment]
> Should work if you upgrade to `^5` which comes with Webpack 5!

OK, thanks. I'll try it soon!

**Comment by iandjx** [comment]
https://github.com/iandjx/cra-17-wagmi
sorry forgot to post the repo earlier

**Comment by iandjx** [comment]
Confirmed working with react-scripts ^5.0.1 . thanks @jxom

**Comment by cxss** [comment]
react-scripts ^5.0.1 works, thanks a lot!
