### ISSUE TITLE
bug: usePrepareContractWrite not usable for payable functions

### ISSUE THREAD

**Issue by kdembler** [wagmi-dev/wagmi#2311]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

1.0.2

### Current Behavior

When I prepare a write config for payable function with `usePrepareContractWrite` and pass it to `useContractWrite`, I get TS error:

<details>
<summary>Details</summary>

Argument of type 'PrepareWriteContractResult<readonly [{ readonly constant: true; readonly inputs: readonly []; readonly name: "name"; readonly outputs: readonly [{ readonly name: ""; readonly type: "string"; }]; readonly payable: false; readonly stateMutability: "view"; readonly type: "function"; }, ... 14 more ..., { ...; }], "depo...' is not assignable to parameter of type 'UseContractWriteConfig<readonly [{ readonly constant: true; readonly inputs: readonly []; readonly name: "name"; readonly outputs: readonly [{ readonly name: ""; readonly type: "string"; }]; readonly payable: false; readonly stateMutability: "view"; readonly type: "function"; }, ... 14 more ..., { ...; }], "approve"...'.
  Type 'PrepareWriteContractResult<readonly [{ readonly constant: true; readonly inputs: readonly []; readonly name: "name"; readonly outputs: readonly [{ readonly name: ""; readonly type: "string"; }]; readonly payable: false; readonly stateMutability: "view"; readonly type: "function"; }, ... 14 more ..., { ...; }], "depo...' is not assignable to type 'Partial<Pick<PrepareWriteContractResult<readonly [{ readonly constant: true; readonly inputs: readonly []; readonly name: "name"; readonly outputs: readonly [{ readonly name: ""; readonly type: "string"; }]; readonly payable: false; readonly stateMutability: "view"; readonly type: "function"; }, ... 14 more ..., { ....'.
    Types of property 'request' are incompatible.
      Type 'Omit<WriteContractParameters<readonly [{ readonly constant: true; readonly inputs: readonly []; readonly name: "name"; readonly outputs: readonly [{ readonly name: ""; readonly type: "string"; }]; readonly payable: false; readonly stateMutability: "view"; readonly type: "function"; }, ... 14 more ..., { ...; }], "de...' is not assignable to type '(Omit<WriteContractParameters<readonly [{ readonly constant: true; readonly inputs: readonly []; readonly name: "name"; readonly outputs: readonly [{ readonly name: ""; readonly type: "string"; }]; readonly payable: false; readonly stateMutability: "view"; readonly type: "function"; }, ... 14 more ..., { ...; }], "a...'.
        Type 'Omit<WriteContractParameters<readonly [{ readonly constant: true; readonly inputs: readonly []; readonly name: "name"; readonly outputs: readonly [{ readonly name: ""; readonly type: "string"; }]; readonly payable: false; readonly stateMutability: "view"; readonly type: "function"; }, ... 14 more ..., { ...; }], "de...' is not assignable to type 'Omit<WriteContractParameters<readonly [{ readonly constant: true; readonly inputs: readonly []; readonly name: "name"; readonly outputs: readonly [{ readonly name: ""; readonly type: "string"; }]; readonly payable: false; readonly stateMutability: "view"; readonly type: "function"; }, ... 14 more ..., { ...; }], "ap...'.
          Type 'Omit<WriteContractParameters<readonly [{ readonly constant: true; readonly inputs: readonly []; readonly name: "name"; readonly outputs: readonly [{ readonly name: ""; readonly type: "string"; }]; readonly payable: false; readonly stateMutability: "view"; readonly type: "function"; }, ... 14 more ..., { ...; }], "de...' is not assignable to type 'Omit<WriteContractParameters<readonly [{ readonly constant: true; readonly inputs: readonly []; readonly name: "name"; readonly outputs: readonly [{ readonly name: ""; readonly type: "string"; }]; readonly payable: false; readonly stateMutability: "view"; readonly type: "function"; }, ... 14 more ..., { ...; }], "ap...'.
            Types of property 'value' are incompatible.
              Type 'bigint' is not assignable to type 'undefined'.ts(2345)

</details>

### Expected Behavior

No TS error

### Steps To Reproduce

You can see the following code in the StackBlitz link below. To see the error, wait till deps are installed and run `pnpm run check` in terminal (this will run `tsc`)

```ts
import { useContractWrite, usePrepareContractWrite } from 'wagmi';

// prettier-ignore
const WETH9_ABI = [{"constant":true,"inputs":[],"name":"name","outputs":[{"name":"","type":"string"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":false,"inputs":[{"name":"guy","type":"address"},{"name":"wad","type":"uint256"}],"name":"approve","outputs":[{"name":"","type":"bool"}],"payable":false,"stateMutability":"nonpayable","type":"function"},{"constant":true,"inputs":[],"name":"totalSupply","outputs":[{"name":"","type":"uint256"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":false,"inputs":[{"name":"src","type":"address"},{"name":"dst","type":"address"},{"name":"wad","type":"uint256"}],"name":"transferFrom","outputs":[{"name":"","type":"bool"}],"payable":false,"stateMutability":"nonpayable","type":"function"},{"constant":false,"inputs":[{"name":"wad","type":"uint256"}],"name":"withdraw","outputs":[],"payable":false,"stateMutability":"nonpayable","type":"function"},{"constant":true,"inputs":[],"name":"decimals","outputs":[{"name":"","type":"uint8"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":true,"inputs":[{"name":"","type":"address"}],"name":"balanceOf","outputs":[{"name":"","type":"uint256"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":true,"inputs":[],"name":"symbol","outputs":[{"name":"","type":"string"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":false,"inputs":[{"name":"dst","type":"address"},{"name":"wad","type":"uint256"}],"name":"transfer","outputs":[{"name":"","type":"bool"}],"payable":false,"stateMutability":"nonpayable","type":"function"},{"constant":false,"inputs":[],"name":"deposit","outputs":[],"payable":true,"stateMutability":"payable","type":"function"},{"constant":true,"inputs":[{"name":"","type":"address"},{"name":"","type":"address"}],"name":"allowance","outputs":[{"name":"","type":"uint256"}],"payable":false,"stateMutability":"view","type":"function"},{"payable":true,"stateMutability":"payable","type":"fallback"},{"anonymous":false,"inputs":[{"indexed":true,"name":"src","type":"address"},{"indexed":true,"name":"guy","type":"address"},{"indexed":false,"name":"wad","type":"uint256"}],"name":"Approval","type":"event"},{"anonymous":false,"inputs":[{"indexed":true,"name":"src","type":"address"},{"indexed":true,"name":"dst","type":"address"},{"indexed":false,"name":"wad","type":"uint256"}],"name":"Transfer","type":"event"},{"anonymous":false,"inputs":[{"indexed":true,"name":"dst","type":"address"},{"indexed":false,"name":"wad","type":"uint256"}],"name":"Deposit","type":"event"},{"anonymous":false,"inputs":[{"indexed":true,"name":"src","type":"address"},{"indexed":false,"name":"wad","type":"uint256"}],"name":"Withdrawal","type":"event"}] as const

function useDeposit() {
  const writePrepare = usePrepareContractWrite({
    address: '0x0',
    abi: WETH9_ABI,
    functionName: 'deposit',
    value: 1n,
  });

  const write = useContractWrite(writePrepare.config);
  // TS error:                   ^^^^^^^^^^^^^^^^^^
  return write.write;
}
```

### Link to Minimal Reproducible Example (StackBlitz, CodeSandbox, GitHub repo etc.)

https://stackblitz.com/edit/new-wagmi-9knwoh?file=src/App.tsx

**Comment by t0rbik** [comment]
`function useDeposit() {
  const {config} = usePrepareContractWrite({
    address: '0x0',
    abi: WETH9_ABI,
    functionName: 'deposit',
    overrides: {
      value: ur value
    }
  });

  return useContractWrite(config);
}`

**Comment by kdembler** [comment]
Thanks!

**Comment by thomasvalera** [comment]
@kdembler Is it fixed for you with the latest viem as suggested?

I still encounter the issue using:

`next: 13.1.6`
`viem: 0.3.33`
`wagmi: 1.0.5`

**Comment by kdembler** [comment]
@thomasvalera It was fixed for me, are you sure your function is marked as `payable`? Only then you will be able to provide `value`

**Comment by kdembler** [comment]
I'm not sure what the issue is. Keep in mind that if you define ABI in a variable, you need to add `as const` const assertion: https://wagmi.sh/react/typescript#type-inference

**Comment by thomasvalera** [comment]
Yep that was the issue, I realized it when looking at your code!
Thanks for the help @kdembler!

**Comment by alexboisseau** [comment]
> I'm not sure what the issue is. Keep in mind that if you define ABI in a variable, you need to add `as const` const assertion: https://wagmi.sh/react/typescript#type-inference

It works for me haha, thanks a lot :)
