### ISSUE TITLE
使用fetchBalnace获取余额报错

### ISSUE THREAD

**Issue by youthinn** [wagmi-dev/wagmi#2314]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

1.0.2

### Current Behavior

![image](https://github.com/wagmi-dev/wagmi/assets/96770326/1d363966-899f-4651-8f9e-dec2f042f45a)
Use fetchBalnace to get the balance error with the following code:
![image](https://github.com/wagmi-dev/wagmi/assets/96770326/d82aaa1e-1966-4eb3-b384-c73ff09ae8c3)

What's the problem? How to solve it

### Expected Behavior

Get accurate access to balances on a chain

### Steps To Reproduce

1

### Link to Minimal Reproducible Example (StackBlitz, CodeSandbox, GitHub repo etc.)

https://www.baidu.com

### Anything else?

1

**Comment by jxom** [comment]
You'll need to pass in an Alchemy API Key to `alchemyProvider`. The error you are seeing is because you have not provided an API Key.
