### ISSUE TITLE
bug: hooks loaders and enabled, ex: {isLoading} aren't working properly for some hooks

### ISSUE THREAD

**Issue by guillermoriv** [wagmi-dev/wagmi#2315]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

1.0.2

### Current Behavior

If I want to use the loaders for `useBalance` and `useContractRead`, but they aren't working properly, what I am trying to use right now is: `isFetching` but this is not a good approach.

`const { data, isLoading } = useBalance`, this is what I am doing and isLoading is always false, even when the data is loaded after X time, also `{ enabled: Bool }` is not working for `useBalance` hook. 

### Expected Behavior

`const { data, isLoading } = useBalance`, this is what I am doing and isLoading should be `true` when loading the information and `false` when the information is loaded.

### Steps To Reproduce

1. Install wagmi library
2. Export `useBalance` hook.
4. Use the hook and try to use the `const { isLoading } = useBalance`, and the value is always false

**Comment by guillermoriv** [comment]
Even when you put the `{ enabled: false }` it keeps fetching the balance of nothing, the query should be disabled even then

**Comment by guillermoriv** [comment]
I don't know if this could be related that's fetching too fast, then it doesn't even trigger the loading state, but that shouldn't make any sense tho

**Comment by guillermoriv** [comment]
`{ isFetching }` is hitting the correct state, being `true` at the beginning then `false` when I have the information

**Comment by jxom** [comment]
`isLoading` is only truthy when no data is in the cache, and the data is being fetched. It is falsy when there is data in the cache (you have fetched it before). 

To opt-out of this behaviour, you can indeed use `isFetching`, or set `cacheTime` to zero on the Hook to disable caching.
