### ISSUE TITLE
bug: Module '"wagmi"' has no exported member 'useContract'.ts(2305)

### ISSUE THREAD

**Issue by alanrsoares** [wagmi-dev/wagmi#2321]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

1.0.2

### Current Behavior

although `useContract` is present in the updated docs, It's not being exported from the `wagmi` package

### Expected Behavior

useContract hook should be exported from `wagmi`

**Comment by weber77** [comment]
Having same issue with _`useSigner`_
