### ISSUE TITLE
Using Wagmi to build walletConnect mobile phone scan code will crash back, what is the problem?

### ISSUE THREAD

**Issue by youthinn** [wagmi-dev/wagmi#2322]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

1.0.2

### Current Behavior

Using Wagmi to build walletConnect mobile phone scan code will crash back, what is the problem?

**Comment by jxom** [comment]
What do you mean by "crash back"? Can you please provide a minimal reproducible example via https://new.wagmi.sh, so we can help you?

**Comment by youthinn** [comment]
> “崩溃”是什么意思？您能否通过https://new.wagmi.sh提供一个最小的可重现示例，以便我们为您提供帮助？

It is the provided walletconnect example and I built it myself, the mobile wallet scan code will directly exit the wallet, and the desktop does not show that the login is successful.

This is the case both with the official example and with my own build, how to fix it, please?

Here's an example of walletconnect I built:
![image](https://github.com/wagmi-dev/wagmi/assets/96770326/2d0dba45-993a-4935-900e-f7ce59bb231c)

**Comment by jxom** [comment]
Can you upload your code please?

**Comment by youthinn** [comment]
> 
---------------------wagmiConfig.js:
import {
  createConfig,
  configureChains,
} from '@wagmi/core'
import { mainnet, optimism, polygon, arbitrumGoerli } from '@wagmi/core/chains'

import { publicProvider } from '@wagmi/core/providers/public'
import { alchemyProvider } from '@wagmi/core/providers/alchemy'

import { MetaMaskConnector } from '@wagmi/core/connectors/metaMask'
import { CoinbaseWalletConnector } from '@wagmi/core/connectors/coinbaseWallet'
import { WalletConnectConnector } from '@wagmi/core/connectors/walletConnect'
import { InjectedConnector } from '@wagmi/core'

const projectId = "624944ddf69f52071b35b4c4aa7f602f";
const alchemyId = 'oKMNBGBp_hvmPNKm1uNcDbqb32FxOGYP';

const { chains, publicClient, webSocketPublicClient } = configureChains(
  [mainnet, optimism, polygon, arbitrumGoerli],
  [alchemyProvider({ apiKey: alchemyId })],
)

export const wagmiConfig = createConfig({
  autoConnect: true,
  connectors: [
    new MetaMaskConnector({ chains }),
    new CoinbaseWalletConnector({
      chains,
      options: {
        appName: 'owlto',
        jsonRpcUrl:
          'https://eth-mainnet.alchemyapi.io/v2/oKMNBGBp_hvmPNKm1uNcDbqb32FxOGYP',
      },
    }),
    new WalletConnectConnector({
      chains,
      options: {
        projectId: projectId,
        showQrModal: true,
        metadata: {
          name: 'Owtlo',
          description: 'Owlto Finance',
          url: 'https://wagmi.sh',
          icons: ['https://wagmi.sh/icon.png'],
        },
      },
    }),
    new InjectedConnector({
      chains,
      options: {
        name: 'Injected',
        shimDisconnect: true,
      },
      explorerRecommendedWalletIds: 'NONE'
    }),
  ],
  publicClient,
  webSocketPublicClient,
})

-----Wagmi.vue
<template>
  <div>
    <div style="color: red">User ID：{{ userId }}</div>

    <div>User Balance{{ balance }}</div>
    <hr />
    <button
      v-for="item in vagmiConfig.connectors"
      @click="test(item)"
      style="margin: 0 20px"
    >
      {{ item.id }}
    </button>
    <div class="centern_bth">
      <button @click="getBalance">getBalance</button>
      <button @click="sengValue">send</button>
      <button @click="changeNetWork">switchNetwork</button>
    </div>

    <div style="margin-top: 50px">
      <button @click="dis">disconnect</button>
    </div>
  </div>
</template>

<script setup>
import { ref, reactive } from "vue";
import { vagmiConfig } from "./vagmi";
import { wagmiConfig } from "./wagmi";
import {
  connect,
  disconnect,
  getAccount,
  fetchBalance,
  switchNetwork,
  sendTransaction,
  prepareSendTransaction,
  getWalletClient,
} from "@wagmi/core";
import { parseEther } from "viem";
import { useConnect } from "vagmi";

const userId = ref("");
const balance = ref(0);
const test = async (item) => {
  const userid = await connect({
    connector: item,
  });
  const account = getAccount();
  console.log("account", account);
  userId.value = await userid.account;
};

const getBalance = async () => {
  const res = await fetchBalance({
    address: userId.value,
    chainId: 1,
  });
  balance.value = res.formatted;
};

const changeNetWork = async () => {
  const network = await switchNetwork({
    chainId: 1,
  });
  console.log("newtork", network);
};

const newConnectors = async (provider) => {
  const connector = await useConnect({
    connector: provider,
  });

  console.log(connector);
};
const setWalletClient = async () => {
  const account = await getAccount();
  console.log(account.connector);

  await newConnectors(account.connector);
};

const sengValue = async () => {
  const walletClient = await getWalletClient();
  console.log("walletClient", walletClient);
  console.log(window.ethereum);
  // await setWalletClient();
  const config = await prepareSendTransaction({
    to: "0x926022F5862DE2D41D01B8b4e956158F75AebC9C",
    value: parseEther("0.01"),
  });

  console.log(config);
  const { hash } = await sendTransaction(config);
  console.log(hash);
};

const dis = async () => {
  await disconnect();
  userId.value = "";
  balance.value = "";
  const account = getAccount();
  console.log("account", account);
};
console.log(vagmiConfig);
</script>

<style scoped>
.centern_bth button {
  margin: 40px 20px;
}
</style>


This is my code, and I am using Vue3

**Comment by youthinn** [comment]
This is my configuration file:

`import {
  createConfig,
  configureChains,
} from '@wagmi/core'
import { mainnet, optimism, polygon, arbitrumGoerli } from '@wagmi/core/chains'

import { publicProvider } from '@wagmi/core/providers/public'
import { alchemyProvider } from '@wagmi/core/providers/alchemy'

import { MetaMaskConnector } from '@wagmi/core/connectors/metaMask'
import { CoinbaseWalletConnector } from '@wagmi/core/connectors/coinbaseWallet'
import { WalletConnectConnector } from '@wagmi/core/connectors/walletConnect'
import { InjectedConnector } from '@wagmi/core'

const projectId = "624944ddf69f52071b35b4c4aa7f602f";
const alchemyId = 'oKMNBGBp_hvmPNKm1uNcDbqb32FxOGYP';

const { chains, publicClient, webSocketPublicClient } = configureChains(
  [mainnet, optimism, polygon, arbitrumGoerli],
  [alchemyProvider({ apiKey: alchemyId })],
)

export const wagmiConfig = createConfig({
  autoConnect: true,
  connectors: [
    new MetaMaskConnector({ chains }),
    new CoinbaseWalletConnector({
      chains,
      options: {
        appName: 'owlto',
        jsonRpcUrl:
          'https://eth-mainnet.alchemyapi.io/v2/oKMNBGBp_hvmPNKm1uNcDbqb32FxOGYP',
      },
    }),
    new WalletConnectConnector({
      chains,
      options: {
        projectId: projectId,
        showQrModal: true,
        metadata: {
          name: 'Owtlo',
          description: 'Owlto Finance',
          url: 'https://wagmi.sh',
          icons: ['https://wagmi.sh/icon.png'],
        },
      },
    }),
    new InjectedConnector({
      chains,
      options: {
        name: 'Injected',
        shimDisconnect: true,
      },
      explorerRecommendedWalletIds: 'NONE'
    }),
  ],
  publicClient,
  webSocketPublicClient,
})
`
The framework I am using is Vue3，Using the page：
`<template>
  <div>
    <div style="color: red">User ID：{{ userId }}</div>

    <div>User Balance{{ balance }}</div>
    <hr />
    <button
      v-for="item in wagmiConfig.connectors"
      @click="test(item)"
      style="margin: 0 20px"
    >
      {{ item.id }}
    </button>
    <div class="centern_bth">
      <button @click="getBalance">getBalance</button>
      <button @click="sengValue">send</button>
      <button @click="changeNetWork">switchNetwork</button>
    </div>

    <div style="margin-top: 50px">
      <button @click="dis">disconnect</button>
    </div>
  </div>
</template>

<script setup>
import { ref, reactive } from "vue";
import { vagmiConfig } from "./vagmi";
import { wagmiConfig } from "./wagmi";
import {
  connect,
  disconnect,
  getAccount,
  fetchBalance,
  switchNetwork,
  sendTransaction,
  prepareSendTransaction,
  getWalletClient,
} from "@wagmi/core";
import { parseEther } from "viem";
import { useConnect } from "vagmi";

const userId = ref("");
const balance = ref(0);
const test = async (item) => {
  const userid = await connect({
    connector: item,
  });
  const account = getAccount();
  console.log("account", account);
  userId.value = await userid.account;
};

const getBalance = async () => {
  const res = await fetchBalance({
    address: userId.value,
    chainId: 1,
  });
  balance.value = res.formatted;
};

const changeNetWork = async () => {
  const network = await switchNetwork({
    chainId: 1,
  });
  console.log("newtork", network);
};

const newConnectors = async (provider) => {
  const connector = await useConnect({
    connector: provider,
  });

  console.log(connector);
};
const setWalletClient = async () => {
  const account = await getAccount();
  console.log(account.connector);

  await newConnectors(account.connector);
};

const sengValue = async () => {
  const walletClient = await getWalletClient();
  console.log("walletClient", walletClient);
  console.log(window.ethereum);
  // await setWalletClient();
  const config = await prepareSendTransaction({
    to: "0x926022F5862DE2D41D01B8b4e956158F75AebC9C",
    value: parseEther("0.01"),
  });

  console.log(config);
  const { hash } = await sendTransaction(config);
  console.log(hash);
};

const dis = async () => {
  await disconnect();
  userId.value = "";
  balance.value = "";
  const account = getAccount();
  console.log("account", account);
};
console.log(vagmiConfig);
</script>

<style scoped>
.centern_bth button {
  margin: 40px 20px;
}
</style>
`

**Comment by tmm** [comment]
Please make a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) that is runnable ([StackBlitz](https://stackblitz.com) works great for this). Once that is ready, we can look into this issue more.
