### ISSUE TITLE
usePrepareSendTransaction is no longer returning gas price

### ISSUE THREAD

**Issue by johanneskares** [wagmi-dev/wagmi#2325]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

1.0.2

### Current Behavior

I have my wallet connected and the wagmi provider set up. I'm calling this code in a React component:

```
const { data, config, error } = usePrepareSendTransaction({
    to: wallet,
    value: 100n,
});

console.log({ data, config, error });
```

I'm getting this log
<img width="495" alt="Screenshot 2023-05-12 at 11 30 52" src="https://github.com/wagmi-dev/wagmi/assets/1416628/b2a6843b-221b-4d70-9539-b35d15cc6470">

### Expected Behavior

My expectation is, that `gas` is filled with the current gas price for the transaction. (Similar to `gasLimit` in the old wagmi version)

### Steps To Reproduce

1. Setup Wagmi from one of the examples
2. Use the code above

**Comment by jxom** [comment]
This is expected. wagmi no longer populates the `gas` (fka `gasLimit`) as this estimation is performed on the wallet anyway; performing it in wagmi as well will be a redundant (& costly) step. 

That said, you can still pass in your own defined gas limit via the `gas` attribute on `usePrepareSendTransaction`.

**Comment by johanneskares** [comment]
Thanks @jxom

Ok, but how am I expected to display the estimated network fee in my UI? Some of my users use magic.link (whitelabel custodial wallet), where there's no additional UX step (like in Metamask).

So I would like to display the estimated network fee before users submit. Is there any other way of getting `gas` aka `gasLimit` for a transaction?

**Comment by johanneskares** [comment]
Also, this piece of documentation seems outdated then:

```
Eagerly fetches the parameters required for sending a contract write transaction, such as the gas estimate.
```

https://wagmi.sh/core/actions/prepareWriteContract

**Comment by 0xartcro** [comment]
+1

I used to increase estimated gas to make sure some transactions success as casual people do not really know how to increase gas themselves.

A way to force higher gas would be great, multiplier parameter as discussed here would be great
https://github.com/wagmi-dev/wagmi/discussions/2196

**Comment by jxom** [comment]
Hmm yeah fair points. Could be nice to have the Prepare Hook estimate gas for some cases.  Will look at adding it back in tomorrow.

**Comment by johanneskares** [comment]
Awesome, great news! Thanks @jxom

**Comment by jxom** [comment]
Added in `1.0.4`.

**Comment by johanneskares** [comment]
Awesome, thanks, @jxom. Also, the same would apply to `usePrepareContractWrite`. I'm also not getting a gas estimation from the hook

**Comment by jxom** [comment]
Think we might add a `useEstimateContractGas` for that one. We already have an `eth_call` in the Prepare Hook for `usePrepareContractWrite` which does the same validation minus the gas estimation (but contract write result instead), so I don’t want to overload the hook for with a mostly redundant call.

If you want to do this now, you can use the Wallet Client (via `useWalletClient`) with [`estimateContractGas`](https://viem.sh/docs/contract/estimateContractGas.html).

**Comment by jxom** [comment]
Could also have a `useEstimateGas` Hook for parity with send txn too.

**Comment by johanneskares** [comment]
Ahh, thanks, now I know how to create the workaround! 

As an idea, maybe adding a opt-in flag in `usePrepareContractWrite` like. 

```
usePrepareContractWrite({
    ...
    estimateGas: true
})
```

It's still a bit weird to me that this hook returns all these values that are always `undefined`.

**Comment by johanneskares** [comment]
I use lots of Boilerplate Code to generate the fees to display for the user. It would be great to show this. Also, I noticed I need to populate the gasEstimate and gasPrice values when using `Arbitrum` and a `Magic.link` wallet for alle of my contract actions. It would be great to add options for them to be prepopulated.

**Comment by Willyham** [comment]
An optional parameter to the `prepare` hook would massively simplify this 🙏

**Comment by hiromaily** [comment]
[current documentation](https://wagmi.sh/core/actions/prepareWriteContract) must mislead.

```
Eagerly fetches the parameters required for sending a contract write transaction such as the gas estimate.
```

**Comment by geraldinefiser** [comment]
> Added in `1.0.4`.

Hi! 

Trying to understand where the code is at, at this current moment. 

-> The documentation for the prepare hook still mentions the estimation of gas. 
-> You mentioned "adding it back" a little bit above. 
-> But I only see undefined values in the config returned by the prepare hook in my app. 

I am asking because the Time To Open the Wallet on my app is so long that it is becoming a huge UX issue, which I am trying to solve. 
I thought the problem was maybe the gas estimation but now I am not sure if the prepare hook is doing it or not. 

Would appreciate any input :) Thank you!

**Comment by geraldinefiser** [comment]
Just realized the convo here was about usePrepareSendTransaction. I was looking for answers for the usePrepareContractWrite.

I see @jxom, you are mentioning not implementing the gas estimation on this one. FYI, the docs mentions: "Eagerly fetches the parameters required for sending a contract write transaction such as the gas estimate."

Will implement the estimateContractGas from viem. Hopefully this solve my very slow TTOW on mobile. 

Would love to have the option to get the gas estimate directly from the prep hook though.
