### ISSUE TITLE
@wagmi/core's walletconnect connection is abnormal, and the mobile phone scan code flashes back

### ISSUE THREAD

**Issue by youthinn** [wagmi-dev/wagmi#2330]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

1.0.2

### Current Behavior

@wagmi/core's walletconnect connection is abnormal, and the mobile phone scan code flashes back

**Comment by jxom** [comment]
Dupe of #2322. Can you please provide a minimal reproducible example as mentioned here: https://github.com/wagmi-dev/wagmi/issues/2322#issuecomment-1545638456
