### ISSUE TITLE
bug: TypeScript `useContractWrite` requires type casting param to `UseContractWriteConfig`

### ISSUE THREAD

**Issue by hexcowboy** [wagmi-dev/wagmi#2335]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

1.0.2

### Current Behavior

Using documentation's recommendation for hook `usePrepareContractWrite`:

```ts
  const { config } = usePrepareContractWrite({
    address: '0xecb504d39723b0be0e3a9aa33d646642d1051ee1',
    abi: wagmigotchiABI,
    functionName: 'feed',
  })
```

Throws an error on all fields of the param:

<img width="894" alt="image" src="https://github.com/wagmi-dev/wagmi/assets/8162609/93f7fb74-3733-4ff3-a8c8-ace5a0be033a">

Which seems to be fixed by type casting to `UsePrepareContractWriteConfig`:

<img width="701" alt="image" src="https://github.com/wagmi-dev/wagmi/assets/8162609/3f1b521a-b4fd-4fe6-bc22-d3848db6c8c2">

This is also true with the `useContractWrite` hook and resolvable by type casting to `UseContractWriteConfig`.

### Expected Behavior

The type should be inferred.

**Comment by gentle-noah** [comment]
@hexcowboy - I've been having a similar issue. I haven't been able to reproduce in a standalone app. I've been trying to figure out if it has something to do with another package or TS config. Would you mind posting your TS config and package.json?

**Comment by jxom** [comment]
I can't seem to reproduce here either: https://www.typescriptlang.org/play?target=8#code/JYWwDg9gTgLgBAbzgVwM4FMAKV1gIY4DCEAdjFHgMYwDqUwM6ANHOlJQOwBMAjAIIAhAJJwAvnABmUCCDgByAO54A5iGByAUBrRYc+IqXJVa9RgAoEGuNbh4ARsABcrdt37CmVm3gAmPnKioznIADAAecp42ksgk1MCkAHJ4IOjBqHgS6AAqFCSoWVAAYtIgkV7WBMpBcADaoREsDZFwPCQAup6iAJRAA

Can you please provide a minimal reproducible example (via a separate repo or https://new.wagmi.sh)? Will re-open when one is provided!

**Comment by hexcowboy** [comment]
https://github.com/wagmi-dev/wagmi/issues/2328#issuecomment-1546920624
