### ISSUE TITLE
bug: Return field `write` on `useContractWrite` does not take expected params

### ISSUE THREAD

**Issue by hexcowboy** [wagmi-dev/wagmi#2336]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

1.0.2

### Current Behavior

The docs mention using `write` to pass dynamic params.

```ts
  const { data, isLoading, isSuccess, write } = useContractWrite({
    address: '0xecb504d39723b0be0e3a9aa33d646642d1051ee1',
    abi: wagmigotchiABI,
    functionName: 'claim',
  } as UseContractWriteConfig)

  return (
    <div>
      <button
        disabled={!write}
        onClick={() =>
          write({
            args: [69],
            from: '0xA0Cf798816D4b9b9866b5330EEa46a18382f251e',
            value: parseEther('0.01'),
          })
        }
      >
        Claim
      </button>
      {isLoading && <div>Check Wallet</div>}
      {isSuccess && <div>Transaction: {JSON.stringify(data)}</div>}
    </div>
  )
```

However, the type of `write` is `() => void`

<img width="435" alt="image" src="https://github.com/wagmi-dev/wagmi/assets/8162609/52ba35fb-62a3-4a51-9ae2-442a1a414648">

Which doesn't allow the above code to compile.

### Expected Behavior

`write` should be of type `((args?: WriteContractConfig) => void) | undefined` like the docs mention.

https://wagmi.sh/react/hooks/useContractWrite#return-value

**Comment by jxom** [comment]
Can't seem to reproduce this in a minimal environment: https://www.typescriptlang.org/play?target=8#code/JYWwDg9gTgLgBAbzgVwM4FMDCEB2MoCGAxjAOpTAzoA0c6URA7AEwCMAggEICScAvnABmUCCDgByAO4EA5iGDiAUIqK5U8JJIpV+cALwoM2PIRLlK6ABQJFAeltxHTgHoB+RU7gEARsABcdAwsHDzUHk4EACaRUOioqAHiAAwAHuJhnoLIOCTAuAByBCDoiagEgugAKoQ4qBVQAGIiIOnhjgRQMgkoOJHogsA46JFhfACUQA

Do you think you could share a minimal reproducible example (via separate repo or https://new.wagmi.sh) with your tsconfig.json? Will re-open the issue when provided!

**Comment by hexcowboy** [comment]
Related https://github.com/wagmi-dev/wagmi/issues/2328#issuecomment-1546592846
