### ISSUE TITLE
bug: type not inferred with useContractReads

### ISSUE THREAD

**Issue by Max-3-7** [wagmi-dev/wagmi#2342]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

1.0.2

### Current Behavior

Hey guys,

I'm upgrading to wagmi v1 but I'm having issues with type inference when using useContractReads (it works fine with wagmi <v1).

Here's a simple example that is no longer working:

```
import { useContractReads, erc20ABI } from 'wagmi'

// an array of ERC20 addresses on mainnet
const addresses = [
    '0x5A98FcBEA516Cf06857215779Fd812CA3beF1B32',
    '0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2'
]

const contracts = addresses.map((address) => {
    return {
        abi: erc20ABI,
        address: getAddress(address)
    } as const
})

// fetch decimals, symbol and name for all tokens
const { data, isLoading } = useContractReads({
    contracts: [
        ...contracts.map((contract) => ({
        ...contract,
        functionName: 'decimals'
    })),
        ...contracts.map((contract) => ({
        ...contract,
        functionName: 'symbol'
    })),
        ...contracts.map((contract) => ({
        ...contract,
        functionName: 'name'
    }))
  ]
})
```

The result is of type `unknown` :

```
const data: ({
    error: Error;
    result?: undefined;
    status: "failure";
} | {
    error?: undefined;
    result: unknown;
    status: "success";
})[] | undefined
```

Most of the useContractReads no longer inferring the data type correctly, although there is a few of them that still works.

Let me know if you have any clue why this is happening. 

Thank you very much

### Link to Minimal Reproducible Example (StackBlitz, CodeSandbox, GitHub repo etc.)

https://stackblitz.com/edit/new-wagmi-xemvdq?file=src/App.tsx

**Comment by tmm** [comment]
Higher-order functions, like `.map`, don't carry type semantics very well. The best we can do in this case is by helping out the compiler a bit more asserting `const` in a few more places so `result` is now inferred as `string | number`.

[TypeScript Playground](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgVwM4FMDCEB2MoCGAxjAEroEAmqANHOlEQEwAMAggEICScAvnADMoEEHADkAdwIBzEMDEAoUJFiI409DDaVKUdKlR9Bw0WIBuwdCEUKA9LbgEcjqIQCecCALgBRUplZHHT0DfU9nEAJgHBxNBSJcVHgqXX0MQwBeOABtBThxFgAPAFY2AE4ADgAxIg4fNmKARgA2TAEWZorigHYmRp7usqrKCsamTDYAZgAjdCrGjkmmMRo8gsLMFiYCAimy6aYmSaqfCoARdhZ0YswAFiqmbvQ2M7KWCsnMbuLW5hWFAC6jkMCRwSQU8US8FB+GIMEyQVSoVQADpImAABQYlIhVAASjgGQAfIg1noYMgoM4EGt8gRpsAAFz0RisThcVb5OnBNLMjRaHkGbGC-GcowEEFQhS8PEQ+yCTREAAWcEo6CIoAIABtaHBUG4QNMIFrHDhKHAcAQQOhBNBHFqTTAIABrdBgyFg+BISgEGAEIxZNBYXCwkjkKioDE0-LyrkAPQA-GsYYQSKhmbkuXAUTmU3DUeiMbSuRi8yQCcTi1mo1Ws9ncyHUzAxXWuQJkDgSMBcAA5K3oZliNUayI6-6t-L8CVwUFJPEtuDz4s5lFl+FogiY2ulxtwitE2v5GsTrkrtcL1vtzswbs4PvWwf6w3G8cTqeSz1LrNf08NvBNgtNyLVsd3-PdCQPE9jxPetV13EgLzrK8u17ftB0ta1X1bd8ZyhH98h-AFVhlBQgA)

```ts
const data: ({
    error: Error;
    result?: undefined;
    status: "failure";
} | {
    error?: undefined;
    result: string | number;
    status: "success";
})[] | undefined
```

More info https://github.com/microsoft/TypeScript/issues/29841

**Comment by Max-3-7** [comment]
ah got it, thanks for the info!
