### ISSUE TITLE
Coinbase failed to switch chains, except for Goerli and Arbitrum Goreli, other chains failed to switch unsuccessfully with an exception

### ISSUE THREAD

**Issue by youthinn** [wagmi-dev/wagmi#2349]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

1.0.2

### Current Behavior

According to official documents，Coinbase failed to switch chains, except for Goerli and Arbitrum Goreli, other chains failed to switch unsuccessfully with an exception
![image](https://github.com/wagmi-dev/wagmi/assets/96770326/5b34dc7c-12d1-430a-aacb-b6666645ab6d)

### Expected Behavior

Using a switching chain is normal like metamask

**Comment by tmm** [comment]
Are you using the CoinbaseWallet browser extension or Coinbase Wallet mobile app?

**Comment by tmm** [comment]
This issue is temporarily closed due to lack of information. Please provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) and reopen this issue.
