### ISSUE TITLE
bug: Wallet does no longer autoConnect when using the InjectedConnector since Wagmi 1.0

### ISSUE THREAD

**Issue by paintoshi** [wagmi-dev/wagmi#2350]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

1.0.4

### Current Behavior

When connecting using the InjectedConnector, with the autoConnect set to true in the initial config. It does not keep the connection when for example refreshing the app. The setup is in combination with the web3modal and the connection is kept when using the web3modal instead. So I assume it should also be kept using the injected connector. This worked with wagmi 0.12.12.

Using:
"viem": "^0.3.24",
"wagmi": "^1.0.4",
"@web3modal/ethereum": "^2.4.1",
"@web3modal/react": "^2.4.1",

### Expected Behavior

When you have autoConnect set to true and refresh the app, the connection should be kept.

### Steps To Reproduce

```
import { createConfig, configureChains, mainnet } from 'wagmi'
import { publicProvider } from 'wagmi/providers/public'
 
const { publicClient } = configureChains([mainnet], [publicProvider()])
 
const config = createConfig({
  autoConnect: true,
  publicClient,
})

const { connect } = useConnect({
  connector: new InjectedConnector({ chains: [mainnet] }),
})
connect()
```

**DEMO:**

1. Go to https://paintoshi.github.io/wallet-demo-react18/
2. Press Connect Injected (with a wallet such as Metamask or Rabby installed in the browser)
3. Refresh page (connection is lost)
4. Try using "Connect Web3modal" instead and select metamask from the apps
5. Refresh page (connection is kept)

Same issue also seen in the metamask app itself on mobile using the in-app browser.

https://github.com/wagmi-dev/wagmi/assets/88572775/d2f2da6d-aa63-4cac-9881-65eb8e3f1886

### Link to Minimal Reproducible Example (StackBlitz, CodeSandbox, GitHub repo etc.)

https://github.com/paintoshi/wallet-demo-react18

**Comment by jxom** [comment]
Can you reproduce this here: https://new.wagmi.sh?

If you cannot, it might be worth opening this issue on the Web3Modal repository as something might be conflicting there.

**Comment by paintoshi** [comment]
> Can you reproduce this here: https://new.wagmi.sh?
> 
> If you cannot, it might be worth opening this issue on the Web3Modal repository as something might be conflicting there.

It works when using the mapped connectors as done in that example but I can replicate the issue using the button mentioned in my reproduceable steps. It has nothing to do with web3modal in that case. See the "Injected Manual" button I created, it loses connection on refresh.

https://stackblitz.com/edit/new-wagmi-exvpyn?file=src/components/Connect.tsx

```
const { connect: manualConnect } = useConnect({
  connector: new InjectedConnector({
    chains: [mainnet],
    options: {
      shimDisconnect: true,
    },
  }),
});
```

Is that not supposed to work, because it did in earlier version?

**Comment by tmm** [comment]
The issue is that wagmi only reconnects to connectors added to the config (through `createConfig({ connectors })`). Since you are connecting with a connector you passed inline to `useConnect`, the config will not be able to reconnect to it.
