### ISSUE TITLE
bug: useWalletClient returns null despite being connected

### ISSUE THREAD

**Issue by joshlang** [wagmi-dev/wagmi#2351]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

1.0.4

### Current Behavior

```
const { address, isConnected } = useAccount()
const { chain } = useNetwork()
const { data: walletClient, error, isSuccess } = useWalletClient()
```

`address` = 0xsomeaddress
`isConnected` = true
`chain` is a chain

but

`walletClient` is `null`
`error` is `null`
`isSuccess` = false

...F5 refreshing the page will fix it.  It seems to be only after initial (auto?)-connection

### Expected Behavior

`walletClient` is not null

**Comment by joshlang** [comment]
I'll spend time to create a minimal repro if necessary

**Comment by tmm** [comment]
@joshlang minimal reproduction would be great! Won't be able to look into it until then.

**Comment by joshlang** [comment]
https://github.com/joshlang/repro-for-wagmi

I think the problem is actually with `useAccount`, not `useWalletClient`

To reproduce... 
- npm run start
- (a browser window opens)
- Click "Connect" 
- (verify that Account shows, isConnected=true, and Wallet Client provided=true)
- Close browser windows (all of them, so that metamask requests a password again)
- Open another browser window (to localhost:3000)

Account will show the previously loaded account
isConnected will show `true`
Wallet client provided will show `false`

However, you're not *actually* connected, which you can verify by clicking metamask

...

I could *not* reproduce this until I added a second chain.

`configureChains([mainnet], ...)` - Could not reproduce
`configureChains([hardhat, mainnet], ...)` - Reproduces

...

With just `[mainnet]`, upon re-opening the browser window, it would flash a status showing the previously loaded account, but seems to quickly realize "oh wait I'm not connected" and clears it out.  This seems to be the correct behavior, which doesn't seem to happen when both chains are provided.

I suspect the `autoConnect: true` logic may be a good candidate for suspicion

...

Relevant files to look at:  `App.tsx` and `index.tsx`

**Comment by joshlang** [comment]
No longer happens with latest version

**Comment by mqklin** [comment]
I've just got the error: `TypeError: Cannot read properties of undefined (reading 'getProvider')`
My code is: 
```
const {connector, isConnected} = useAccount();
...
useEffect(() => {
    (async () => {
      try {
        if (isConnected) {
          const provider = await connector.getProvider();
        }
      ...
```
My guess was that if `isConnected` is true, then `connector` is not `undefined`

wagmi version 1.0.5

**Comment by naftalimurgor** [comment]
> No longer happens with latest version

what version are you using kindly?
