### ISSUE TITLE
bug: no gas data in prepared write request

### ISSUE THREAD

**Issue by kdembler** [wagmi-dev/wagmi#2367]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

1.0.5

### Current Behavior

Our app used to check simulated gas usage with `writePrepare.data?.request.gasLimit`. In v1, the field was renamed to just `gas` but from my testing so far it's always empty.
```ts
  const { config, error: prepareError } = usePrepareContractWrite({
    address: WETH_ADDRESS,
    abi: WETH9_ABI,
    functionName: 'deposit',
    value: 1n,
  });

  if (config.request) {
    const { gas, gasPrice } = config.request;
    console.log({ gas, gasPrice });
  }
```

### Expected Behavior

gas available on prepared request, or some other way to access the gas

### Link to Minimal Reproducible Example (StackBlitz, CodeSandbox, GitHub repo etc.)

https://stackblitz.com/edit/new-wagmi-acamzv?file=src/App.tsx

**Comment by jxom** [comment]
We do not estimate the gas in Prepare Hooks anymore as the users' wallet will do this anyway, so it's really a redundant request. Instead, we simulate the transaction in the Prepare Hook with an `eth_call` which comes with the benefit of retrieving write function return data & also a lower CU cost.

However, that said, in a future version of wagmi, we will likely support viem's `estimateContractGas` as a first-class Hook. But for now, you may need to use `usePublicClient` with viem's `estimateContractGas` instead.

**Comment by beautyfree** [comment]
Still not time for support of `estimateContractGas`?
