### ISSUE TITLE
bug: cacheTime for hooks doesn't defaults to zero as it's mention in the docs

### ISSUE THREAD

**Issue by guillermoriv** [wagmi-dev/wagmi#2370]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

1.0.5

### Current Behavior

As I am passing the args to the hooks `useContractRead` and `useContractReads` and I don't need the information to be cached (should be the latest information), even if I am not passing the `cacheTime`, there is still some persistent information in the `queryCache` in the `localStorage`, only when I pass a `cacheTime: 0`, the information is not persistent anymore.

I don't if it's a bug in the hooks, or if it's intended, but is not clear if this defaults to zero.

### Expected Behavior

Hooks `useContractRead` and `useContractReads` and others should have cacheTime to zero default and not persist information until is clearly intended in the `cacheTime`.

**Comment by jxom** [comment]
The intended behavior is the persist the data according to the `cacheTime` set on the [global query client](https://github.com/wagmi-dev/wagmi/blob/main/packages/react/src/config.ts#L35) – this is defaulted to 24 hours. You can change this by passing in a [custom `queryClient` to `createConfig`](https://github.com/wagmi-dev/wagmi/blob/main/packages/react/src/config.ts#L32-L44) with your custom `cacheTime`.

**Comment by 3obby** [comment]
Man, I spent so long trying to debug this. I'm gonna come back and add this to the docs.
