### ISSUE TITLE
bug: usePublicClient cannot return the correct publicClient when  specified chianId

### ISSUE THREAD

**Issue by qieman** [wagmi-dev/wagmi#2371]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

1.0.5

### Current Behavior

here is my code :

wagim config
```
import { mainnet, moonbeam, bsc, polygon, avalancheFuji } from 'wagmi/chains
import { configureChains, createConfig, WagmiConfig } from 'wagmi'
import { publicProvider } from 'wagmi/providers/public'

const chainsSupported= [mainnet,  avalancheFuji]

const inject = new InjectedConnector({
    chains: chainsSupported,
})

const { chains, publicClient } = configureChains(
    chainsSupported,
    [publicProvider()],
)

const config = createConfig({
    autoConnect: true,
    connectors:[inject],
    publicClient
})
```

my component
```
import { useEffect } from 'react'
import {usePublicClient } from 'wagmi'

function  MyComponet () {
    // specified ChainId here
    const publicClient = usePublicClient({chainId: 43113})

    useEffect (()=>{
        async function getChainId () {
            const id = await publicClient .getChainId()
           // print current chain id
           console.log('chainId',  id)
         }
        getChainId ()
    },[])

return <div>MyComponet<div>
}
```
It prints out that chainId is 1 but not 43113

### Expected Behavior

It prints out that chainId is 43113

**Comment by jxom** [comment]
They seem to be all synced up on my end at https://stackblitz.com/edit/new-wagmi-xvomgt?file=src%2FApp.tsx,src%2Fwagmi.ts. Can you fork this example and produce the issue there? Will re-open when provided!

**Comment by qieman** [comment]
So sorry to make you spend time on this issue, the issue may be with my code and not wagmi

**Comment by qieman** [comment]
Maybe I know where the problem is, if the network is switched in browser wallet like Metamask. It will return the current chainId of the wallet.
