### ISSUE TITLE
bug: Remove ethersjs as dependecy 

### ISSUE THREAD

**Issue by hammeiam** [wagmi-dev/wagmi#2381]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

1.0.5

### Current Behavior

`wagmi-core` depends on ethersjs

<img width="361" alt="Screen Shot 2023-05-18 at 5 43 36 PM" src="https://github.com/wagmi-dev/wagmi/assets/7607886/42793db0-3f68-4c80-9350-536ed8b3d4f7">

### Expected Behavior

`wagmi-core` should not depend on ethersjs now that it has migrated to `viem`

**Comment by jxom** [comment]
Might be best to re-open this issue in safe-apps-sdk, although, I believe they are already working on their viem migration: https://github.com/safe-global/safe-apps-sdk/pull/478
