### ISSUE TITLE
bug: overrides, onError and useWaitForTransaction doesn't work correctly

### ISSUE THREAD

**Issue by notmhyr** [wagmi-dev/wagmi#2387]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

1.0.5

### Current Behavior

1. I tried to use useContractWrite and use overrides to declare some value but overrides was not working
2. I used onError in useContract wirite and returned error was not the message which transaction reverted with and also error.reason was undifined
3. I used useWaitForTransaction and used onSuccess but onSuccess was getting called after accepting the transaction in the wallet not when it actually went throw in the blockchain

### Steps To Reproduce

 i fixed overrides value  by passing it throw Dynamic Arguments

**Comment by tmm** [comment]
> I tried to use useContractWrite and use overrides to declare some value but overrides was not working

In v1, the `overrides` parameter has been removed in favor of top-level parameters.

```diff
const { config } = useContractWrite({
  ...
- overrides: {
-   gasLimit: BigNumber.from('42069'),
-   value: BigNumber.from('69420'),
- },
+ gasLimit: 42069n,
+ value: 69420n
})
```

Looks like the docs aren't up-to-date so will fix that.

> I used onError in useContract wirite and returned error was not the message which transaction reverted with and also error.reason was undifined

`useContractWrite` `onError` is for handling networking errors sending the transaction through your RPC to the blockchain. It does not handle transaction errors, like reverts. For that, you want to use `useWaitForTransaction`.

> I used useWaitForTransaction and used onSuccess but onSuccess was getting called after accepting the transaction in the wallet not when it actually went throw in the blockchain

I wasn't able to reproduce. Please provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example).
