### ISSUE TITLE
bug: getProvider returns undefined on mobile

### ISSUE THREAD

**Issue by uselesss** [wagmi-dev/wagmi#2399]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

1.0.5

### Current Behavior

I'm using wagmi and web3modal to connect via walletconnect v2

`wagmiConfig.args.connectors[1].getProvider()` works fine on desktop, returning metamask provider (the same as window.ethereum)

doing the same on mobile results in `getProvider()` returning undefined

![image](https://github.com/wagmi-dev/wagmi/assets/47245582/9b59871c-ad84-427c-bf04-3f9501538d45)

**Comment by tmm** [comment]
Thanks for reporting. This issue is temporarily closed due to lack of information. Please provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) and reopen this issue.

**Comment by uselesss** [comment]
@tmm Just made a minimal [repo](https://github.com/uselesss/web3-provider-issue). Again, works fine on desktop and breaks on mobile. I used ngrok for test deployment
