### ISSUE TITLE
bug: signTypedData MetaMask issue

### ISSUE THREAD

**Issue by adjuric-symphony** [wagmi-dev/wagmi#2412]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

1.0.5

### Current Behavior

I'm trying to sign a message with useSignTypedData (signTypedDataAsync) and keep getting the error below even though I click 'Sign' on the MetaMask Signature request pop-up:

```
InternalRpcError: An internal error was received.

Details: MetaMask Typed Message Signature: User denied message signature.
Version: viem@0.3.33
    at withRetry.delay.count.count (buildRequest.ts:74:42)
    at async attemptRetry (withRetry.ts:34:22)
```

**Comment by jxom** [comment]
I cannot seem to reproduce this on my end. Can you please provide us with a minimal reproducible example via https://new.wagmi.sh?

Will re-open when provided.

**Comment by adjuric-symphony** [comment]
Here is the reproducible example:
https://stackblitz.com/edit/new-wagmi-exhjmn?file=src%2Fcomponents%2FSignTest.tsx

The problem is uint64[] type for votesPerOutcome. If I change it to uint256[] it works, but the error message is not suitable for the first case.

I'm looking for a workaround to sign a byte array since it's now removed from `useSignMessage`. I thought that `useSignTypedData` could help but I'm not getting the expected signature and it changes depending on the type (more details are in the example above).

One solution is to cast Uint8Array to a string like this but I'm not sure if that's a good idea (it works tho):
```
      const messageHashBytes = toBytes(messageHash);
      const signature = await signMessageAsync({
        message: messageHashBytes as unknown as string,
      });
```

Is there a better solution?
