### ISSUE TITLE
Function "approve" of "erc20abi" does not work with Trust wallet browser extension

### ISSUE THREAD

**Issue by burasov-artyom** [wagmi-dev/wagmi#2413]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

1.0.5

### Current Behavior

Hello. All functions work except "approve"

My code:
```
const publicClient = usePublicClient({
  chainId: config.chainId,
});
const { data: walletClient } = useWalletClient({
  chainId: config.chainId,
});

const token0 = getContract({
  address: address,
  abi: erc20ABI,
  publicClient,
  walletClient,
});

const approveTx = await token0.write.approve({
  account: address,
  args: [addressRouter, amountInMax]
});
```

![изображение](https://github.com/wagmi-dev/wagmi/assets/47752247/d52eaac2-84c1-41f6-b156-aa068201cb53)

There are no errors in the console. I checked other dapp applications, it works correctly.

Can you please tell me if this could be related to wagmi or viem?

### Anything else?

Node modules:
```
"@web3modal/ethereum": "^2.4.1",
"@web3modal/react": "^2.4.1",
"viem": "^0.3.36",
"wagmi": "^1.0.5"
```

**Comment by tmm** [comment]
The following code is incorrect:

```ts
const approveTx = await token0.write.approve({
  account: address,
  args: [addressRouter, amountInMax]
});
```

And should be:

```ts
const approveTx = await token0.write.approve([addressRouter, amountInMax], {
  account: address,
});
```
