### ISSUE TITLE
Function "approve" of erc20abi is not working for usdt

### ISSUE THREAD

**Issue by Stenor5** [wagmi-dev/wagmi#2419]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

1.0.5

### Current Behavior

I tried to use erc20abi constant from wagmi to call `approve` function of usdt contract.
But it was not working. After I remove outputs data, it was working well.
```
[
  {
    "constant": false,
    "inputs": [
      {
        "name": "_spender",
        "type": "address"
      },
      {
        "name": "_value",
        "type": "uint256"
      }
    ],
    "name": "approve",
    "outputs": [
      {
        "name": "",
        "type": "bool"
      }
    ],
    "payable": false,
    "stateMutability": "nonpayable",
    "type": "function"
  }
]
```

### Expected Behavior

```
[
  {
    "constant": false,
    "inputs": [
      { "name": "_spender", "type": "address" },
      { "name": "_value", "type": "uint256" }
    ],
    "name": "approve",
    "outputs": [],
    "payable": false,
    "stateMutability": "nonpayable",
    "type": "function"
  }
]

```

**Comment by jxom** [comment]
Can you please provide a minimal reproducible example via https://new.wagmi.sh with steps to reproduce the issue? Seems to be working fine for me, and the ERC20 standard has `boolean` as the return value for `approve`.

**Comment by Stenor5** [comment]
> Can you please provide a minimal reproducible example via https://new.wagmi.sh with steps to reproduce the issue? Seems to be working fine for me, and the ERC20 standard has `boolean` as the return value for `approve`.

Yes, But it is not for USDT.
Please check usdt abi. 
![image](https://github.com/wagmi-dev/wagmi/assets/98555031/087c23c7-43be-46e0-871f-e23120acdfb6)
https://etherscan.io/token/0xdac17f958d2ee523a2206206994597c13d831ec7#code

**Comment by Stenor5** [comment]
All approve function call works even if there is no return value in its abi.

**Comment by jxom** [comment]
Right, well that's annoying. 🤣 
Might be best to have a separate ABI for USDT with it omitted then.
