### ISSUE TITLE
bug: wagmi codegen not doing anything on latest version

### ISSUE THREAD

**Issue by nezouse** [wagmi-dev/wagmi#2420]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

1.0.1

### Current Behavior

I tried to use @wagmi/cli after upgrading to wagmi 1.0, but can't make it work right now. Before it was creating output, and now it just doesn't do anything.

### Expected Behavior

Create a file with some output. ERC20, ERC721 and ERC4626 should be generated with provided settings.

### Steps To Reproduce

1. Open provided reproduction
2. Open new terminal window
3. Type `pnpm wagmi codegen`

### Link to Minimal Reproducible Example (StackBlitz, CodeSandbox, GitHub repo etc.)

https://stackblitz.com/edit/new-wagmi-bbpwcg

**Comment by tmm** [comment]
`pnpm wagmi generate` should work. will throw an error if the command doesn't exist (e.g. `codegen`).
