### ISSUE TITLE
bug: usePrepareContractWrite: (property) value?: undefined (Type 'bigint' is not assignable to type 'undefined'.)

### ISSUE THREAD

**Issue by alexanderpehlivanov** [wagmi-dev/wagmi#2423]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

1.0.6

### Current Behavior

(property) value?: undefined

### Expected Behavior

(property) value?: number: undefined

### Steps To Reproduce

  let {
    config,
    error: prepareError,
    isError: isPrepareError,
  } = usePrepareContractWrite({
    address: X,
    abi: contract.abi,
    functionName: "Y",
    value: parseEther(`${price}`)
  });

**Comment by tmm** [comment]
Thanks for reporting. This issue is temporarily closed due to lack of information. Please provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) and reopen this issue. Particularly, we need the ABI in order to help you.

**Comment by j6i** [comment]
I'm getting this when I try to use the `buy` function on the SuperRareBazaar contract
https://etherscan.io/address/0x6d7c44773c52d396f43c2d511b81aa168e9a7a42#code

the function abi
`  {
    "inputs": [
      {
        "internalType": "address",
        "name": "_originContract",
        "type": "address"
      },
      { "internalType": "uint256", "name": "_tokenId", "type": "uint256" },
      {
        "internalType": "address",
        "name": "_currencyAddress",
        "type": "address"
      },
      { "internalType": "uint256", "name": "_amount", "type": "uint256" }
    ],
    "name": "buy",
    "outputs": [],
    "stateMutability": "payable",
    "type": "function"
  },`

**Comment by tmm** [comment]
@j6i working fine in this [TypeScript Playground](https://www.typescriptlang.org/play?target=99#code/JYWwDg9gTgLgBAbzgVwM4FMAKV1gIY4DCEAdjFHgMYwDqUwM6cAvnAGZQQhwDkA7ngDmIYDwBQYyqVTw8AI2BwAvHADaYuIg2a4wEmGQxUALjXadWixb2MoJPABsAKgE8w6UzzwATbzlSoPAA05lb2IB68APrQwIJ6xGQU1MGhFjBukV6+-oEhViz5Vkg26HaOru6eyDYATACsAGzBcOFZUTAQANboJACS3i0ZVbw1ZA3NhWmWBbpkZfbOmZ4+fugBqbOteBGeUZTIUDgklC4AgjnredOaw1mruZtWzEUWJfPlSyM8YzATLW09jsIMgyENlqM6k0eFMLABdV7bXa8OTIFxPTQgmAGIymVQI0IyPCMACyhnkwAcDBcnnwLnkDnQGLgd08bFB1GApCeLzEcLgeFQcCkJBkEhFMjg-mQDngKjQWBw+CIpHIVFo9EYAAoENoHldPAAGAAeTwpRXZJxgXJIADkdpEAESolyOooEQQmNQ8E0tACMtQAzCQgrxfaGA8GCZoAG6OZCRSMh7QAehTcAAegB+MTMACUYmlsrEQA)

**Comment by j6i** [comment]
@tmm It looks like it was how I was importing the abi. I was pulling it from a JSON. When I define it as you do, it works.
