### ISSUE TITLE
bug: `Module not found: Can't resolve 'encoding' in`

### ISSUE THREAD

**Issue by Seranged** [wagmi-dev/wagmi#2425]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.12.13

### Current Behavior

Hey Guys,

I've been having an issue with Trezor-WebConnect over the last few weeks (https://github.com/trezor/trezor-suite/issues/8506) that we've been sorting, they've recently pushed a version (v.9.0.11) that fixed their dependency issues. Now the front end branch dealing with that issue is having a similar issue with WalletConnect and Wagmi.

Re: you guys, I'll update the branch repo to ^v1 in the morning (Euro time) and see if the issue persists

Here is the branch: https://github.com/Seranged/EVM-FE-Bootstrap/tree/trezor-nextjs-issue-reproduction

Issue:

`Module not found: Can't resolve 'encoding' in '/Users/serranged/Documents/GitHub/EVM-bootstrap/node_modules/node-fetch/lib'

Import trace for requested module:
./node_modules/node-fetch/lib/index.js
./node_modules/cross-fetch/dist/node-ponyfill.js
./node_modules/@walletconnect/jsonrpc-http-connection/dist/cjs/http.js
./node_modules/@walletconnect/jsonrpc-http-connection/dist/cjs/index.js
./node_modules/@walletconnect/legacy-provider/dist/cjs/index.js
./node_modules/@wagmi/connectors/dist/walletConnectLegacy.js
./node_modules/@wagmi/core/dist/connectors/walletConnectLegacy.js
./node_modules/wagmi/dist/connectors/walletConnectLegacy.js
./node_modules/@rainbow-me/rainbowkit/dist/index.js
./src/app/layout.tsx`

https://github.com/trezor/trezor-suite/issues/8506

### Expected Behavior

No console error (module imported successfully)

### Steps To Reproduce

https://github.com/Seranged/EVM-FE-Bootstrap/tree/trezor-nextjs-issue-reproduction

**Comment by jxom** [comment]
WalletConnect v1 issue. Add this line to your next config: https://github.com/wagmi-dev/create-wagmi/blob/main/templates/next/rainbowkit/next.config.js#L5

**Comment by Ha2ryZhang** [comment]
> Seems like this is a problem with a few modules:
> 
> 'lokijs' in @WalletConnect, 'pino-pretty' in @WalletConnect, 'encoding' in @safe-global
> 
> Tried your recommendation above & didn't fix it @jxom
> 
> I'm using the non-legacy WalletConnect FYI

same! did you fix it?
