### ISSUE TITLE
Wagmi v. 1 still requires ethers

### ISSUE THREAD

**Issue by monkybrain** [wagmi-dev/wagmi#2436]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

1.0.7

### Current Behavior

Wagmi still installs `ethers` as subdependency to library `@safe-global/safe-apps-sdk`, thereby negating improvements in bundle size.

Output from `yarn why ethers` in project with only `wagmi` and `viem` as dependencies:

```
=> Found "ethers@5.7.2"
info Reasons this module exists
   - "wagmi#@wagmi#core#@wagmi#connectors#@safe-global#safe-apps-sdk" depends on it
   - Hoisted from "wagmi#@wagmi#core#@wagmi#connectors#@safe-global#safe-apps-sdk#ethers"
   - Hoisted from "wagmi#@wagmi#core#@wagmi#connectors#@safe-global#safe-apps-provider#@safe-global#safe-apps-sdk#ethers"
```

### Expected Behavior

Wagmi v. 1.0.0 should have no dependency on `ethers`, just `viem`

### Steps To Reproduce

```
yarn add wagmi viem
yarn why ethers
```

**Comment by jxom** [comment]
Safe SDK should have `viem` fully integrated soon: https://github.com/safe-global/safe-apps-sdk/pull/478

**Comment by monkybrain** [comment]
@jxom Great, thanks!
