### ISSUE TITLE
bug: _wagmi.createConfig is not a function

### ISSUE THREAD

**Issue by milaabl** [wagmi-dev/wagmi#2444]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.12.6

### Current Behavior

https://codesandbox.io/s/sharp-scott-qv4w0b?file=/src/App.js
![image](https://github.com/wagmi-dev/wagmi/assets/86361434/3e1f5ff2-66ae-43f7-a001-3a08fced292f)
Error when importing createConfig from the "wagmi" package.

I have installed the latest versions of wagmi (0.12.6) and viem (0.1.22).

I can see that createConfig is undefined, but have no idea why as I've already worked with Wagmi many times before, and this error is happening to me when I'm using a new scaffolded project.

### Expected Behavior

The wagmi package should export the createConfig function.

### Steps To Reproduce

Please see the CodeSandbox.

### Link to Minimal Reproducible Example (StackBlitz, CodeSandbox, GitHub repo etc.)

https://codesandbox.io/s/sharp-scott-qv4w0b?file=/src/App.js

### Anything else?

Please help! Thanks!

**Comment by jxom** [comment]
`createConfig` was introduced in `wagmi@1.0.0`.

**Comment by milaabl** [comment]
@jxom , hmm, Codesandbox seems to show the 0.12.6 as the latest version. Thanks for your reply!
