### ISSUE TITLE
bug: onReplace/onSpeedUp not working properly

### ISSUE THREAD

**Issue by nfts2me** [wagmi-dev/wagmi#2445]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.12.13

### Current Behavior

When sending a TX with low Base Fee / Priority Fee which is not included (or not reaching the mempool) when replacing with higher gas fees, `onSpeedUp` from `useWaitForTransaction` is never called. Then, the TX seems to be stuck forever.

I'm sending the TX using signer.sendTransaction() directly from ethers. And then `useWaitForTransaction` from the hash received from the "ethers.providers.TransactionResponse" from sendTransaction().

### Expected Behavior

Trigger the `onSpeedUp`.

### Steps To Reproduce

- Create a TX high low fees.
- Increase speed.
- Get the TX stuck.

**Comment by nfts2me** [comment]
I can just confirm that this also happens on `useContractWrite`.

**Comment by jxom** [comment]
Thanks for reporting. Can you please provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) via https://new.wagmi.sh and reopen this issue (as a separate one). 

This issue seems more ethers.js related, but it might be worth upgrading to v1, where transaction replacement is a bit more stable.

**Comment by nfts2me** [comment]
Actually, I can't.
To reproduce it is a matter of doing the replacement on Metamask, something that I can't do as an example.
Any `useWaitForTransaction`suffer from this problem.

**Comment by jxom** [comment]
Does this work on v1?

**Comment by nfts2me** [comment]
> Does this work on v1?

No.
Same issue, well, actually worse :D

You can do this to test on Goerli, set these values when sending the TX:
![image](https://github.com/wagmi-dev/wagmi/assets/109629895/daf56095-be26-4ad4-b7af-8764ceffe2ee)

Then, the TX gets waiting. After that, you'll get the TX hash. 
Go to metamask and increase speed.
The TX will go through but View / Ethers / Wagmi will never realize of that, keeping loading.

Also, while testing on v1 I got these two errors:
1.-
![image](https://github.com/wagmi-dev/wagmi/assets/109629895/7f59664e-abbb-4203-9029-49ee7ff076e8)
2.- 
And with this:
```  const { isLoading, isSuccess, status } = useWaitForTransaction({```
`isSuccess` is always `false`.

**Comment by nfts2me** [comment]
@jxom could you reopen it?

**Comment by atomicDev03** [comment]
I have same problem
@jxom

**Comment by jxom** [comment]
Can you please provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) via https://new.viem.sh or a separate repo? It will save us a lot of time reproducing your config & environment, and trying to reproduce your issue. See [Why reproductions are required](https://antfu.me/posts/why-reproductions-are-required).
