### ISSUE TITLE
next.js MockConnector SyntaxError: Cannot use import statement outside a module

### ISSUE THREAD

**Issue by champseo2017** [wagmi-dev/wagmi#2467]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

^0.10.10

### Current Behavior

When I run my Jest tests, I'm encountering the error message "SyntaxError: Cannot use import statement outside a module" at the module "import { MockConnector } from 'wagmi/connectors/mock';".

### Expected Behavior

It should not be giving the error "SyntaxError: Cannot use import statement outside a module".

### Steps To Reproduce

When I run my Jest tests, I'm encountering the error message "SyntaxError: Cannot use import statement outside a module" at the module "import { MockConnector } from 'wagmi/connectors/mock';".

`import { MockConnector } from "wagmi/connectors/mock";
jest.mock("wagmi", () => {
  const originalModule = jest.requireActual("wagmi");

  return {
    __esModule: true,
    ...originalModule,
    default: jest.fn(),
    useAccount: () => {
      if (typeof window !== "undefined" && window.ethereum) {
        const walletClientInstance = createWalletClient({
          chain: polygonMumbai,
          transport: custom(window.ethereum)
        });

        const connector = new MockConnector({
          options: {
            chainId: polygonMumbai.id,
            // @ts-ignore
            walletClient: walletClientInstance
          }
        });

        return connector.getAccount();
      } else {
        // Handle the case where window.ethereum is undefined
        // You might want to throw an error, return a mock account, etc.
      }
    }
  };
});
`

space
"next": "13.1.6",
  "react": "18.2.0",
  "react-dom": "18.2.0",
"wagmi": "^0.10.10",

**Comment by tmm** [comment]
You need to [configure Jest to support ESM.](https://jestjs.io/docs/ecmascript-modules) ([Vitest](https://vitest.dev) supports ESM by default and has a compatible API with Jest.)

**Comment by SebastienSusini** [comment]
Hello i still have the same issue, only wagmi is blocking me, i did the configuration for jest to support ESM, all my app is in typescript.
