### ISSUE TITLE
bug: <@wagmi/connectors can't load in Android API < 29 Uncaught SyntaxError: Unexpected token . >

### ISSUE THREAD

**Issue by dingcxx** [wagmi-dev/wagmi#2468]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.12.13

### Current Behavior

when load under code will receive error Uncaught SyntaxError: Unexpected token .

```
     if (!targetChainId) {
        const lastUsedChainId = getClient().lastUsedChainId;
        if (lastUsedChainId && !this.isChainUnsupported(lastUsedChainId))
          targetChainId = lastUsedChainId;
        else
          targetChainId = this.chains[0]?.id;
      }
      if (!targetChainId)
        throw new Error("No chains found on connector.");
```

 error line under `chains[0]?.id` 

### Expected Behavior

not receive error 

### Steps To Reproduce

Android API <  29

open https://rns.id in webview or chrome can't load webpage

**Comment by tmm** [comment]
Looks like the browser you mentioned does not support [optional chaining](https://caniuse.com/mdn-javascript_operators_optional_chaining)

**Comment by dingcxx** [comment]
yes, maybe you can change the packaging method

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining

in mobile platform most browser supported in 2020, The number of users is still very large
