### ISSUE TITLE
cant install wagmi with default CRA

### ISSUE THREAD

**Issue by eyooooo** [wagmi-dev/wagmi#2481]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

latest

### Current Behavior

create a default CRA app `npx create-react-app src`
try to install wagmi `npm install wagmi viem`
dont work
```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR! 
npm ERR! While resolving: src@0.1.0
npm ERR! Found: typescript@4.9.5
npm ERR! node_modules/typescript
npm ERR!   peer typescript@">= 2.7" from fork-ts-checker-webpack-plugin@6.5.3
npm ERR!   node_modules/fork-ts-checker-webpack-plugin
npm ERR!     fork-ts-checker-webpack-plugin@"^6.5.0" from react-dev-utils@12.0.1
npm ERR!     node_modules/react-dev-utils
npm ERR!       react-dev-utils@"^12.0.1" from react-scripts@5.0.1
npm ERR!       node_modules/react-scripts
npm ERR!         react-scripts@"5.0.1" from the root project
npm ERR!   peerOptional typescript@"^3.2.1 || ^4" from react-scripts@5.0.1
npm ERR!   node_modules/react-scripts
npm ERR!     react-scripts@"5.0.1" from the root project
npm ERR!   1 more (tsutils)
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! wagmi@"*" from the root project
npm ERR! 
npm ERR! Conflicting peer dependency: typescript@5.0.4
npm ERR! node_modules/typescript
npm ERR!   peerOptional typescript@"^5.0.4" from wagmi@1.0.9
npm ERR!   node_modules/wagmi
npm ERR!     wagmi@"*" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /home/aaa/.npm/eresolve-report.txt for a full report.
```

### Expected Behavior

expect it to install happily

### Steps To Reproduce

see current behavior

### Anything else?

broken with node 14 and 16. npm 9.6.7

**Comment by tmm** [comment]
The latest version of wagmi requires TypeScript v5.0.4 or greater so you'll need to configure CRA to work with that. In general, I'd recommend using something like [Vite](https://vitejs.dev) instead of CRA.

**Comment by eyooooo** [comment]
> The latest version of wagmi requires TypeScript v5.0.4 or greater so you'll need to configure CRA to work with that. In general, I'd recommend using something like [Vite](https://vitejs.dev) instead of CRA.

thanks @tmm  - perhaps add this to the Install page so users dont throw the baby out with the bath water here.
