### ISSUE TITLE
bug: "viem/dist/types/types/eip1193" has no exported member 'Chain' @wagmi/connectors @wagmi/core

### ISSUE THREAD

**Issue by hoangbtmrk** [wagmi-dev/wagmi#2488]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

2.1.0

### Current Behavior

When I install @wagmi/core and viem latest version, catch error when run project

Description: Namespace '".../node_modules/viem/dist/types/types/eip1193"' has no exported member 'Chain'

**Comment by layinka** [comment]
+1 on this

**Comment by jxom** [comment]
Mind providing a minimal reproducible example via a separate repo so we can take a look?

**Comment by hoangbtmrk** [comment]
Hi @jxom, the step to reproduce it is below:
- Create new angular app
- install packages @web3modal/ethereum @web3modal/html @wagmi/core viem
- ng serve -> catch error

I found it cause because Chain is used in @wagmi/connectors/dis/injected.d.ts by import viem_dist_types_types_eip1193, but in this file, there are no export member 'Chain'.
