### ISSUE TITLE
bug: Error: node_modules/@wagmi/connectors/dist/injected.d.ts:540:13 - error TS2413: '`string[${string}]`' index type 'undefined' is no t assignable to 'string' index type 'readonly TypedDataParameter[]'

### ISSUE THREAD

**Issue by layinka** [wagmi-dev/wagmi#2490]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

1.0.8

### Current Behavior

I am getting this error on running my project

```Error: node_modules/@wagmi/connectors/dist/injected.d.ts:540:13 - error TS2413: '`string[${string}]`' index type 'undefined' is no t assignable to 'string' index type 'readonly TypedDataParameter[]'```

### Expected Behavior

No error should be showing up

### Steps To Reproduce

Add wagmi/core to a project and run.

I am currently using typescript 4.8.4

**Comment by jxom** [comment]
You’ll need to upgrade to TypeScript 5.

**Comment by layinka** [comment]
we are using this with Angular 15 which doesnt support Typescript 5

**Comment by jxom** [comment]
Ah damn. Do you know when they’ll support it?

**Comment by layinka** [comment]
I am checking, it seems angular 16 supports it, but i will have preferred nnot to migrate to 16 yet
