### ISSUE TITLE
bug:  ERR_PNPM_WORKSPACE_PKG_NOT_FOUND  when running `pnpm i`

### ISSUE THREAD

**Issue by larskarbo** [wagmi-dev/wagmi#2496]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

1.1.0

### Current Behavior

I am unable to install dependencies and get the local dev environment up and running.

When I run:

```
pnpm i
```

I get:

```
Scope: all 7 workspace projects
/Users/lars/dev/wagmi/packages/cli:
 ERR_PNPM_WORKSPACE_PKG_NOT_FOUND  In packages/cli: "@wagmi/chains@workspace:*" is in the dependencies but no package named "@wagmi/chains" is present in the workspace

This error happened while installing a direct dependency of /Users/lars/dev/wagmi/packages/cli

Packages found in the workspace: docs, example-dev, @wagmi/cli, fixture-hardhat, @wagmi/core, wagmi
```

### Expected Behavior

I expected `pnpm i` to succesfully install dependencies

### Steps To Reproduce

1. Clone the repository
2. Run `pnpm i`

My environment:
- Nodejs: `v16.20.0`
- Pnpm: `8.6.1`
- Macos: Apple M1 Pro

**Comment by tmm** [comment]
Did you clone the references submodule too?

**Comment by MarcusWentz** [comment]
Worked with my fork
```shell
git clone --recurse-submodules git@github.com:MarcusWentz/wagmi.git
```
so the format for other users would be
```shell
git clone --recurse-submodules git@github.com:<your_github_username_fork>/wagmi.git
```
