### ISSUE TITLE
Refresh without reloading the page.

### ISSUE THREAD

**Issue by cesar4design** [wagmi-dev/wagmi#2514]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

Last

### Current Behavior

I have a very simple dapp that I made with hooks.

It is a mint token contract with USDT.

For this I must first approve the tokens and then the mint.

The problem I have is that after approving the tokens, the buy function does not update and shows me the error that I do not have enough allowance. I have to refresh the site to make it work.

### Steps To Reproduce

`
  // Aprove USDT
  const { config: ApproveUSDT } = usePrepareContractWrite({
    ...TokenUSDTAddress,
    functionName: "approve",
    args: ["0x1c103ad0921c35abe1a5e396479922450D38Ad76", 1000000],
  });

  const { write: Approve, isLoading, isSuccess } = useContractWrite(ApproveUSDT);

  // Buy token
  const { config: BuyTokens } = usePrepareContractWrite({
    ...TokenPresaleAddress,
    functionName: "buyTokens",
    args: [BNBSend],
  });

  const { write: Buy} = useContractWrite(BuyTokens);`

### Link to Minimal Reproducible Example (StackBlitz, CodeSandbox, GitHub repo etc.)

https://token-presale-usdt.vercel.app/

### Anything else?

![image](https://github.com/wagmi-dev/wagmi/assets/75784005/3bc87bf8-1012-4214-85b1-ec0ac836bd30)

**Comment by jxom** [comment]
You'll need to wait for the transaction to be confirmed using `useWaitForTransaction`.
