### ISSUE TITLE
bug: <title>

### ISSUE THREAD

**Issue by parshant-1002** [wagmi-dev/wagmi#2519]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

1.1.0

### Current Behavior

note supporting node version above 14 to get install using npm

### Expected Behavior

should install the node version above 14 

### Steps To Reproduce

should provide proper guide to do this

### Anything else?

provide any support or reference to solve this

**Comment by tmm** [comment]
Thanks for reporting. This issue is temporarily closed due to lack of information. Please provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) and reopen this issue.

**Comment by parshant-1002** [comment]
information is that when I use to install this package with npm version above 6 or node version above 15 
it gives conflicts
and If I do the same with lower versions it works properly?
