### ISSUE TITLE
WalletConnect+TrustWallet: Invalid Session Properties requested

### ISSUE THREAD

**Issue by ThakerJayam** [wagmi-dev/wagmi#2525]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.12.13

### Current Behavior

OS: Android 11.
Platform: React
Using wagmi^0.12.13

After connecting to TrustWallet using WalletConnect, If I request a signature using
sign message from wagmi/actions,
following error is raised:
`{context: "client"} 'Invalid Session Properties requested'`.

### Expected Behavior

The sign message should return signature.

**Comment by tmm** [comment]
Can you provide some more info? Are you using WalletConnect v1 or v2? Please attached a minimal reproduction.

**Comment by ThakerJayam** [comment]
I have attached minimal reproduction. I am using WalletConenctv2.
