### ISSUE TITLE
bug: useContractWrite fails when not preparing it first

### ISSUE THREAD

**Issue by sverps** [wagmi-dev/wagmi#2526]
Wasn't entirely sure whether to create this issue on `wagmi` or on `viem`, I checked both repo's and it depends a bit on what the desired expected behavior is.

### Is there an existing issue for this?

- [X] I have searched the existing issues in the `wagmi` project
- [X] I have searched the existing issues in the `viem` project

### Package Version

1.0.2

### Current Behavior

`prepareWriteContract` accepts a `chainId` in order to validate the current client is on the correct chain. This works fine when a user calls the `usePrepareContractWrite`.

However, when the user directly calls `useContractWrite`, the `prepareWriteContract` method is called at https://github.com/wagmi-dev/wagmi/blob/28821d6b4eec38b6065c3eb47d30093f6c677c44/packages/core/src/actions/contracts/writeContract.ts#L80 with an undefined `chainId`. The resulting `request` will thus have `chainId: undefined` (https://github.com/wagmi-dev/wagmi/blob/28821d6b4eec38b6065c3eb47d30093f6c677c44/packages/core/src/actions/contracts/prepareWriteContract.ts#L113).

In the `walletClient.writeContract()` call, this results in the internal use of `sendTransaction` to overwrite the derived `chainId` to `undefined` (https://github.com/wagmi-dev/viem/blob/fe259a0ed6e4f7e264a7c5c761fea3a8ca68efc9/src/actions/wallet/sendTransaction.ts#L151).

The result is a scenario where `useContractWrite` simply fails with error message:
```
Details: Cannot read properties of undefined (reading 'length')
Version: viem@1.0.1
```

### Expected Behavior

Using `useContractWrite` without first preparing it should work as intended.

### Steps To Reproduce

Run scaffold-eth-2 at commit 7845914414b1fc9ccb1df3c90e7c3de2a5cce4d5 and remove the usage of the prepare hook at https://github.com/scaffold-eth/scaffold-eth-2/blob/7845914414b1fc9ccb1df3c90e7c3de2a5cce4d5/packages/nextjs/components/scaffold-eth/Contract/WriteOnlyFunctionForm.tsx#L30 and pass the entire config directly into the write hook.

Then run the project, go to the debug contract page, then try and change the greeting. 

### Anything else?

To fix the issue, the simplest is probably to keep the `chainId` in the `...args` variable to pass into prepareWriteContract (https://github.com/wagmi-dev/wagmi/blob/28821d6b4eec38b6065c3eb47d30093f6c677c44/packages/core/src/actions/contracts/writeContract.ts#L79).

Alternatively, we could ensure that the `request` object gets any `chainId` property removed from it before passing it down to `walletClient.writeContract({ ...request })`

Or, depending on the expected behavior of `viem`'s `writeContract`, we could apply a fix there and not overwrite the internally derived `chainId` if a `transaction` is passed in that has a `chainId: undefined` prop.

**Comment by jxom** [comment]
Fixed in viem @ https://github.com/wagmi-dev/viem/commit/90fd40ba0d5b7e248c7494ca5cbfa46eac281753.
