### ISSUE TITLE
bug: `wagmi generate` with foundry plugin shuffles output, producing large diffs

### ISSUE THREAD

**Issue by dcposch** [wagmi-dev/wagmi#2528]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

1.1.0

### Current Behavior

Running `wagmi generate` outputs contracts in seemingly random order each time it's run.

### Expected Behavior

**Running `wagmi generate` twice on identical inputs should, ideally, generate identical outputs.**

This has two main benefits:
- Concise git diff
- Reproducible builds

### Steps To Reproduce

To reproduce easily

```
git clone https://github.com/daimo-eth/daimo
cd daimo/packages/daimo-api
git checkout 603a172e
npm ci && npm run gen
```

This runs `wagmi generate`. Finally, run

```
git diff
```

**This shows a big diff.** The input contracts have not changed. Output`gen/contracts.ts` is functionally identical but reordered.

### Link to Minimal Reproducible Example (StackBlitz, CodeSandbox, GitHub repo etc.)

https://github.com/daimo-eth/daimo/tree/603a172eb9f902b11446f8d0721956cb338cd47a

### Anything else?

**This might be fixable by sorting the ABI items by name, internally, before generating output.**

Finally, I recommend removing the date from the header line
```
// Generated by @wagmi/cli@1.1.0 on 6/10/2023 at 4:33:44 AM
```

at which point identical inputs = identical generated outputs.

**Comment by tmm** [comment]
Will take a look. Might be faster if you create a minimal example with only the code required to reproduce.

**Comment by dcposch** [comment]
Thanks!

**Comment by Iamshankhadeep** [comment]
@tmm can I work on this issue ?

**Comment by tmm** [comment]
@Iamshankhadeep go for it!

**Comment by llllvvuu** [comment]
PR looks good, doesn't address the header diff but that's trivial to deal with using `sed 1d`. Use-case for this is to run codegen in CI to prevent bugs.

**Comment by gosuto-inzasheru** [comment]
i can confirm we see the same thing happening in two different locals with identical environments: `generated.ts`'s order of contracts differs resulting in big diffs.

**Comment by llllvvuu** [comment]
> Would also like an option to disable the header - there's no need to check in a new timestamp.

Yeah I think this is a reasonable use-case too.

Usually people say not to check in "build outputs". But that assumes wagmi is another thing to add to the dev/watch/build/publish pipeline, and it's easier to just check it into GitHub. I wrote up the proposal here:

https://github.com/wagmi-dev/wagmi/pull/2930

**Comment by dcposch** [comment]
cc @tmm @llllvvuu
