### ISSUE TITLE
bug: waitForTransaction and useWaitForTransaction throw 'block not found' error

### ISSUE THREAD

**Issue by nikakhachi** [wagmi-dev/wagmi#2530]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

^1.1.1

### Current Behavior

`waitForTransaction` and `useWaitForTransaction`  call sometimes throw `BlockNotFoundError`, But the transaction is approved and gets mined successfully.

### Expected Behavior

`waitForTransaction` and `useWaitForTransaction` should return transaction receipt and not throw an error.

### Steps To Reproduce

Just normally use `waitForTransaction` or `useWaitForTransaction`, it should throw an error I mentioned randomly.

### Link to Minimal Reproducible Example (StackBlitz, CodeSandbox, GitHub repo etc.)

https://stackblitz.com/edit/new-wagmi-q5cuif?file=src%2Fcomponents%2FNetworkSwitcher.tsx

### Anything else?

- I'm using a `publicProvider`

- The same issue is opened [here](https://github.com/wagmi-dev/wagmi/issues/2505), but it got closed by an author and my comment hasn't received any replies so I'm opening a new issue.

- I'm not sure if the link I provided in the minimal reproducible example can be counted as `reproducible`, because as I've mentioned this error happens randomly.

- I also got `code.substring is not a function` error sometimes along with the `BlockNotFoundError` error.

![BlockNotFoundError error](https://i.stack.imgur.com/EjTEb.png)
![code.substring error](https://i.stack.imgur.com/xJn3u.png)

**Comment by jxom** [comment]
Can you try upgrade viem to a version post `0.3.30` (we fixed some stability issues with `waitForTransactionReceipt` there, the version in your example is `0.3.21`)?

**Comment by nikakhachi** [comment]
@jxom my viem version is `^0.3.50`.

Its version in the StackBlitz is different there, sorry about that.

I've just changed the `publicProvider` to `alchemyProvider` and I haven't experienced the error anymore.

I guess it's because of the public provider nodes. Request to write in contract was sent  to one node and then `useTransactionWait` tried to find the transaction in another node which wasn't synced yet with the one where we sent request for the contract write. (I'm new to web3, and that's my thought :) ).

Let me know if I'm right or there's other underlying issue for that error.

**Comment by jxom** [comment]
Hmm yeah, it usually occurs most in public/“free” RPC providers as they have some pretty aggressive load-balancing. In this case, viem fetches the current block number, and then tries to fetch for the block using that block number, where the RPC throws an error complaining that it can’t find the block when we just received the block number beforehand.
We could probably try mitigate this in viem though — can investigate more.

**Comment by nikakhachi** [comment]
Thank you for the clarification. All the best!

**Comment by milaabl** [comment]
Having the same error, yes, @nikakhachi your assumption is probably true, probably the public provider nodes. I'm using Sepolia testnet, and sometimes randomly get an error like this.

**Comment by melonges** [comment]
so, how to add custom rpc endpoints when i use web3modal and wagmi?

**Comment by glitch-txs** [comment]
Hi @melonges feel free to open a GitHub discussion in WalletConnect's organization. Happy to help you 🙂

https://github.com/orgs/WalletConnect/discussions

**Comment by azflin** [comment]
Goerli commonly triggers this. Any fix or workaround?

**Comment by jxom** [comment]
Use a different RPC

**Comment by milaabl** [comment]
@azflin, as jxom suggested, you can use a personalized RPC like the ones Alchemy provides
