### ISSUE TITLE
bug: getWalletClient seems to be missing

### ISSUE THREAD

**Issue by onethread** [wagmi-dev/wagmi#2548]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

1.2.0

### Current Behavior

Part of the docs say it should be in the `wagmi` package, but others `@wagmi/core`.

https://wagmi.sh/core/migration-guide#provider--signer-terminology

https://wagmi.sh/core/actions/getWalletClient

I don't think it's just a typescript issue. I tried importing from both sources, and got undefined for both.  

Stackblitz included. If you check the console you'll see that it can't find `getWalletClient` from the `wagmi` package.

### Expected Behavior

`getWalletClient` should be present.

### Steps To Reproduce

Create a new wagmi project.
Import `getWalletClient`

### Link to Minimal Reproducible Example (StackBlitz, CodeSandbox, GitHub repo etc.)

https://stackblitz.com/edit/new-wagmi-1coamy?file=src%2FApp.tsx,src%2Fwagmi.ts

**Comment by glitch-txs** [comment]
core and wagmi are different packages, core is for vanilla js and wagmi is for React.
For wagmi package you can use `useWalletClient` hook

**Comment by tmm** [comment]
@glitch-txs is correct. Also, if you want to access core actions via the wagmi package, you can import from the `wagmi/actions` entrypoint:

```ts
import { getWalletClient } from 'wagmi/actions'
```

**Comment by onethread** [comment]
@tmm Thanks for the clarification. I think the aforementioned documentation page should be updated, though. Now that you all point it out, I see I was in the core docs half the time, but it has import examples for `wagmi`. Maybe I'm missing something, but that seems incorrect?

From https://wagmi.sh/core/migration-guide#provider--signer-terminology:

```
- import { fetchSigner } from 'wagmi'
+ import { getWalletClient } from 'wagmi'

- const signer = await fetchSigner()
+ const walletClient = await getWalletClient()
```

<img width="858" alt="Screenshot 2023-06-20 at 14 04 48" src="https://github.com/wagmi-dev/wagmi/assets/593233/9cc6b68d-2f84-4e7e-9f7d-1ff5f6a688ea">

**Comment by tmm** [comment]
Good catch! Want to submit a PR to fix?
