### ISSUE TITLE
prepare/write contract docs have conflicting/incorrect information

### ISSUE THREAD

**Issue by alex-grover** [wagmi-dev/wagmi#2552]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

1.2.0

### Current Behavior

Docs conflict between the following pages:

### Prepare docs

https://wagmi.sh/core/actions/prepareWriteContract#usage

This works, but the `mode: 'prepared'` returned from `prepareWriteContract` is not passed to `writeContract`. I'm not sure if that's baked into the request as well, but if not I'm assuming it results in the `writeContract` call doing some duplicate work.

```ts
const { request } = await prepareWriteContract({
  address: '0xecb504d39723b0be0e3a9aa33d646642d1051ee1',
  abi: wagmigotchiABI,
  functionName: 'feed',
})
const { hash } = await writeContract(request)
```

### Write docs

https://wagmi.sh/core/actions/writeContract#prepared-usage

This results in a TS error as `writeContract` is expecting `config.request` to be passed, not the whole config object.

```ts
import { prepareWriteContract, writeContract } from '@wagmi/core'
 
const config = await prepareWriteContract({
  address: '0xecb504d39723b0be0e3a9aa33d646642d1051ee1',
  abi: wagmigotchiABI,
  functionName: 'claim',
  args: [69],
})
 
...
 
const { hash } = await writeContract(config)
```

### Workaround

For now, I'm doing the following in my code:

```ts
import { prepareWriteContract, writeContract } from '@wagmi/core'
 
const { request, mode } = await prepareWriteContract({
  address: '0xecb504d39723b0be0e3a9aa33d646642d1051ee1',
  abi: wagmigotchiABI,
  functionName: 'claim',
  args: [69],
})
 
...
 
const { hash } = await writeContract({ ...request, mode })
```

### Expected Behavior

Docs are consistent and `mode: 'prepared'` is passed to `writeContract`

### Steps To Reproduce

See snippets above or linked repo

### Link to Minimal Reproducible Example (StackBlitz, CodeSandbox, GitHub repo etc.)

https://github.com/alex-grover/wagmi-prepared-write-type-errors/blob/main/example.ts

**Comment by deblanco** [comment]
Suffering the same

**Comment by zakopane26** [comment]
Same issue
