### ISSUE TITLE
useContractReads ABI type issue

### ISSUE THREAD

**Issue by berkaycirak** [wagmi-dev/wagmi#2557]
Hi, I can read contract via `useContractRead` but I couldn't read same contract and abi by using `useContractReads` for multiple reading. I am importing abi as a json.

```
...

 const abi = [...hro_abi] as const;

 const hroContract = {
    address: '0x8d553eE8BC386dD7c247B993a142CCc45507e805',
    abi: abi,
  };
  const { data, isError, isLoading } = useContractReads({
    contracts: [
      {
        ...hroContract,
        chainId: 17772,
        functionName: 'tokenURI',
        args: [String(1)],
      },
    ],
  });
  ```
When I pass that abi into useContractReads hook, it gives me an type error but I can use same abi without error on useContractRead hook. Also, if I copy whole abi and paste as an abi value into hroContract, it also works.  Is there anyone who can help that issue?
<img width="786" alt="Screenshot 2023-06-16 at 16 35 42" src="https://github.com/wagmi-dev/wagmi/assets/81809211/5fc70e59-2efe-4b4e-b13c-aeb7c4c595d9">

**Comment by tmm** [comment]
Thanks for reporting. This issue is temporarily closed due to lack of information. Please provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) and reopen this issue. Particularly, what is the ABI?

**Comment by divine-comedian** [comment]
I'm having this same issue! 

Currently my contractABI works fine when using `useContractRead` but the exact same ABI is not accepted and throwing the same error as above when using `useContractReads`.

```
const getSupplyInfo = useContractReads({
    contracts: [
      {
        address: `0x${contractProps.address}`,
        abi: MintingContractJSON.abi,
        functionName: 'maxTokenSupply',
        args: [tokenId],
        chainId: contractProps.chainId,
      },
      {
        address: `0x${contractProps.address}`,
        abi: MintingContractJSON.abi,
        functionName: 'totalSupply',
        args: [tokenId],
        chainId: contractProps.chainId,
      },
    ],
    enabled: false,
  })
  
     const [maxSupplyHex, currentSupplyHex] = getSupplyInfo.data as [bigint, bigint]
  ```

**Comment by tmm** [comment]
Please create a new issue with minimal reproduction (TypeScript version, full ABI, etc.) instead of replying to older issues.
