### ISSUE TITLE
bug: Incorrect blockchain: polygon-mainnet.gateway.pokt.network

### ISSUE THREAD

**Issue by Dellybro** [wagmi-dev/wagmi#2562]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

1.2

### Current Behavior

When attempting to query a contract i get the following error: 

URL: https://rpc.walletconnect.com/v1/?chainId=eip155:137&projectId={id}
Request body: {"method":"eth_getBalance","params":["0x28c75F1bA80b5Cd804FD287c1B426C76B6D32591","latest"]}
Incorrect blockchain: polygon-mainnet.gateway.pokt.network

### Expected Behavior

I would expect the contract to return data

### Steps To Reproduce

Use the polygon network

**Comment by jxom** [comment]
Can you please provide a minimal reproducible example via https://new.wagmi.sh so we can debug further? Will re-open when provided.
