### ISSUE TITLE
bug: value type in usePrepareContractWrite is undefined 

### ISSUE THREAD

**Issue by jamiehewitt15** [wagmi-dev/wagmi#2568]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

1.0.5

### Current Behavior

This code snippet: 

```
  const { config } = usePrepareContractWrite({
    ...wagmiContractConfig,
    functionName: 'createOrganisation',
    args: [orgName, ["Field 1", "Field 2", "Field 3"], [0, 0, 0], ["Value 1", "Value 2", "Value 3"]],
    value: parseEther('0.0001'),
  })
```

Is giving me the following type error: 

```
Type 'bigint' is not assignable to type 'undefined'.ts(2322)
(property) value?: undefined
```

### Expected Behavior

The type of BigInt should be assignable to `value` and the code snippet above should not produce an error. This is according to [the example in the official documentation](https://wagmi.sh/react/hooks/useContractWrite#dynamic-arguments).

**Comment by tmm** [comment]
What version of viem are you using? This was fixed in [viem@1.01](https://github.com/wagmi-dev/viem/releases/tag/viem%401.0.1). If upgrading viem doesn't do it for you, please create a minimal reproduction (can use a [TypeScript Playground](https://www.typescriptlang.org/play)).

**Comment by jamiehewitt15** [comment]
Yeah, you're right turns out I was using an older version. The error has gone now, thank you 👍

**Comment by highnet** [comment]
This issue still persists in viem 1.11.0, any help?

**Comment by tmm** [comment]
@highnet please open a new issue against the latest Viem version with a minimal reproduction.
