### ISSUE TITLE
bug: invalid opcode: INVALID in usePrepareContractWrite

### ISSUE THREAD

**Issue by GeekEdem** [wagmi-dev/wagmi#2586]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

1.2.0

### Current Behavior

When try send USDT tokens receive error:

```
Details: invalid opcode: INVALID
Version: viem@1.1.1

Raw Call Arguments:
  from:  0x...
  to:    0x...
  data:  0xa9059cbb000000000000000000000000...0000000000000000000000000000000000000000000000000000000000000001
  
Contract Call:
  address:   0x...
  function:  transfer(address _to, uint256 _value)
  args:              (0x..., 1)
  sender:    0x...
```

### Expected Behavior

Send USDT tokens :)

### Steps To Reproduce

Go to https://walletconnect-check.chikhrai.xyz/.

1. Select walletconnect version. 
 - 2 for new version Metamask Mobile (v7+), 
 - 1 for Metamask Mobile < v7
 - any when try desktop Metamask extension.
2. Login into Metamask.
3. Click "Check message sign" -> click "sign" in Metamask app/ext -> receive alert in web-page (ok)
4. Click "Check send 10 gwei" -> receive send popup in Metamask app/ext (ok)
5. Click "Check send 0.000001 USDT" -> nothing (receive error in browser console).

Code to check in locale machine: https://github.com/YuriiChikhrai/walletconnect_check

### Link to Minimal Reproducible Example (StackBlitz, CodeSandbox, GitHub repo etc.)

https://walletconnect-check.chikhrai.xyz/

**Comment by jxom** [comment]
Seems like that error is coming from the RPC Provider (it could be not behaving). Can you try using a different one?

**Comment by GeekEdem** [comment]
@jxom Thanks for you response. 
I try change `publicClient` in `createConfig` to 

```
const client = createPublicClient({
  chain: mainnet,
  pollingInterval: 10_000,
  // transport: http(),
  transport: fallback([alchemy]),
});
```
With transport http or alchemy, same issue.

BUT, I find outh that this issue because connected wallet not has enough USDT tokens to create this operation. I try with wallet that has USDT - all works event with `w3mProvider`.
it's not intuitive error...

Thanks for your time and response.
