### ISSUE TITLE
bug: WalletConnectConnector doesn't work on iOS 15.2

### ISSUE THREAD

**Issue by kristiegiles** [wagmi-dev/wagmi#2590]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

1.2.1

### Current Behavior

Using WalletConnectConnector (the v2 one) on an iOS 15.2 device, the connect function fails with the error "Could not generate WalletConnectModal Instance."

<img width="370" alt="Screenshot 2023-06-21 at 5 33 19 PM" src="https://github.com/wagmi-dev/wagmi/assets/25679998/15bd897e-c0e6-4eaf-a3c9-8a7e10eb6dcb">

<img width="399" alt="Screenshot 2023-06-21 at 5 33 03 PM" src="https://github.com/wagmi-dev/wagmi/assets/25679998/ac60dd85-a7cf-433c-a677-8e684d81401b">

### Expected Behavior

It should connect as expected. 

### Steps To Reproduce

Go to [https://wagmi.sh/examples/connect-wallet](https://wagmi.sh/examples/connect-wallet) on an iPhone 13 using Simulator and click the WalletConnect button. It is also happening on my iPhone 11 Pro, which is on iOS 15.2.1.

The legacy (v1) connector works fine, and it seems to work okay on iOS 16.4.

### Link to Minimal Reproducible Example (StackBlitz, CodeSandbox, GitHub repo etc.)

https://wagmi.sh/examples/connect-wallet

**Comment by jxom** [comment]
Seems to be an issue with `@walletconnect/ethereum-provider`. cc. @0xAsimetriq

**Comment by 0xAsimetriq** [comment]
Opened bug ticket in web3modal to investigate.

**Comment by jxom** [comment]
Let's track this issue on web3modal.

**Comment by kristiegiles** [comment]
Thanks! This is fixed now in v1.3.1
