### ISSUE TITLE
bug: <Wagmi document described wrong example>

### ISSUE THREAD

**Issue by mr-new-0509** [wagmi-dev/wagmi#2592]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

1.2.1

### Current Behavior

You can see the following example code of usePrepareSendTransaction hook at https://wagmi.sh/react/prepare-hooks/usePrepareSendTransaction.

`
import { usePrepareSendTransaction, useSendTransaction } from 'wagmi'
 
function App() {
  const { request, error } = usePrepareSendTransaction({
    to: 'moxey.eth',
    value: parseEther('1'),
  })
  const { sendTransaction } = useSendTransaction(request)
 
  return (
    <>
      <button disabled={!sendTransaction} onClick={() => sendTransaction?.()}>
        Send Transaction
      </button>
      {error && (
        <div>An error occurred preparing the transaction: {error.message}</div>
      )}
    </>
  )
}
`

According to the example, the return value of the hook contains `request` property.
But actually, no property named `request`.

Even wagmi team acknowledged the `request` property isn't existed in the return value of the hook in the below of the example.

`
{
  data?: PrepareSendTransactionResult
  error?: Error
  isIdle: boolean
  isLoading: boolean
  isFetching: boolean
  isSuccess: boolean
  isError: boolean
  isFetched: boolean
  isFetchedAfterMount: boolean
  isRefetching: boolean
  refetch: (options: {
    throwOnError: boolean
    cancelRefetch: boolean
  }) => Promise<PrepareSendTransactionResult>
  status: 'idle' | 'error' | 'loading' | 'success'
}
`
![image](https://github.com/wagmi-dev/wagmi/assets/86947718/0ded8d23-738d-446b-b058-0be70fa8235d)
![image](https://github.com/wagmi-dev/wagmi/assets/86947718/6ca59f4b-29a1-4217-ab12-7bab79bff707)

Hope you check the document.

Thank you.

### Expected Behavior

 In my experience, the return value of usePrepareSendTransaction hook contains `config` property instead of `request`.

**Comment by jxom** [comment]
Fixed https://github.com/wagmi-dev/wagmi/commit/f80f493482a216b04d024f038e9eeb3c8d706bcf
