### ISSUE TITLE
bug: InjectedConnector produces different results with Coinbase Wallet after 0.12.x

### ISSUE THREAD

**Issue by tvler** [wagmi-dev/wagmi#2602]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

1.2.1

### Current Behavior

Not sure if this is an issue with wagmi's InjectedConnector or Coinbase Wallet. Apologies for the noise if this is out of your control!

With MetaMask and Coinbase wallet both installed, Coinbase wallet used to show a "Which wallet would you like to use" screen when connecting via an InjectedConnector but now it doesn't post 0.12.x

### Expected Behavior

Coinbase Wallet should show the "Which wallet would you like to use" screen to select between Coinbase and MetaMask

<img width="376" alt="image" src="https://github.com/wagmi-dev/wagmi/assets/4934193/93f10b38-1d4b-4f8f-a508-07b1cfb533b4">

### Steps To Reproduce

Repro:
- Install MetaMask and make sure it's unlocked
- Install Coinbase Wallet  and make sure it's unlocked
- Go to https://wagmi.sh/examples/connect-wallet and click "Injected"
- Coinbase wallet used to show a "Which wallet would you like to use" screen but now it doesn't
- Go to https://0.12.x.wagmi.sh/examples/connect-wallet and click "Injected"
- Coinbase wallet shows the "Which wallet would you like to use" screen

https://github.com/wagmi-dev/wagmi/assets/4934193/60e38eea-b32a-472e-95dd-990f18684edc

**Comment by jxom** [comment]
This would indeed be an issue on the Wallet side. 

Note that [EIP-6963](https://eips.ethereum.org/EIPS/eip-6963) will fix this issue of Wallets overriding each other, and wagmi will support it soon once Wallets have implemented it!

**Comment by tvler** [comment]
Thx for the context! Just curious if you have any idea why CB wallet would be broken in this way post 0.12.x? Like maybe they were relying on a side effect of the old code or something?

**Comment by holic** [comment]
Are there workarounds until EIP-6963?
