### ISSUE TITLE
bug: Type 'string' is not assignable to type 'WriteContractMode'

### ISSUE THREAD

**Issue by meness** [wagmi-dev/wagmi#2622]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

1.2.2

### Current Behavior

TypeScript throws `Type 'string' is not assignable to type 'WriteContractMode'` exception.

### Expected Behavior

It supports string

### Steps To Reproduce

```ts
const hook = useContractWrite({
    // ...
    mode: 'recklesslyUnprepared',
  });
```

**Comment by VsevolodKurochka** [comment]
I had this issue.
But this happens when there is a desynchronization of the frontend application with authorization from WAGMI.

**Comment by jxom** [comment]
You don’t need to pass `mode` anymore.

**Comment by meness** [comment]
@jxom Here it is from the [migration document](https://wagmi.sh/react/migration-guide#usecontractwrite)

> If you are not ready to upgrade to usePrepareContractWrite, it is possible to use useContractWrite without preparing the configuration first by passing mode: 'recklesslyUnprepared'.

```ts
const { data } = useContractWrite({
+ mode: 'recklesslyUnprepared',
  addressOrName: '0x...',
  contractInterface: wagmiAbi,
  functionName: 'mint',
  args: [tokenId],
})
```

**Comment by jxom** [comment]
The migration guide has a - not a +.

**Comment by meness** [comment]
@jxom Sorry, I was reading the `0.6.x Breaking changes`!  You're right, we can remove `mode`

**Comment by jxom** [comment]
🤝
