### ISSUE TITLE
bug: Ethers.js Adapters 'transport' in WalletClient and Public Client is not equivalent to connectionInfo.

### ISSUE THREAD

**Issue by prakhar728** [wagmi-dev/wagmi#2630]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

1.3.0

### Current Behavior

Working with this code snippet to make Ethers.js v5 work with Wagmi
https://wagmi.sh/react/ethers-adapters#reference-implementation-1 

Currently the signer object is not returned due the code line

`const provider = new providers.Web3Provider(transport, network)`

The error thrown is 

> Argument of type 'TransportConfig<string, EIP1193RequestFn> & Record<string, any>' is not assignable to parameter of type 'string | ConnectionInfo'.
  Property 'url' is missing in type 'TransportConfig<string, EIP1193RequestFn> & Record<string, any>' but required in type 'ConnectionInfo'.

That is, **transport** isn't the object(of type 'string | ConnectionInfo') as expected.

### Expected Behavior

Working with Etherjs and Wagmi both I expected the code snippet 
https://wagmi.sh/react/ethers-adapters#reference-implementation-1 to work for ethers.js v5.

Expecting the **useEthersSigner** to return a signer object.
And transport to be accepted as input to JsonRpcProvider

### Steps To Reproduce

1. Create a Rainbowkit-React app.
2. Instantiate Wagmi in it.
3. Create a walletClient using the use **useWalletClient** hook.
4. Create a network `const network = {
    chainId: chain.id,
    name: chain.name,
    ensAddress: chain.contracts?.ensRegistry?.address,
  };`
5.  Run the following code `const provider = new providers.JsonRpcProvider(transport, network);
  const signer = provider.getSigner(account.address);
  return signer;`
6. The error will be visible on **transport** object.

### Link to Minimal Reproducible Example (StackBlitz, CodeSandbox, GitHub repo etc.)

https://wagmi.sh/react/ethers-adapters#reference-implementation-1

**Comment by tmm** [comment]
See https://github.com/wagmi-dev/viem/discussions/792
