### ISSUE TITLE
bug: connectAsync with walletconnect 2

### ISSUE THREAD

**Issue by imornar** [wagmi-dev/wagmi#2631]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

1.3.0

### Current Behavior

awaiting connectAsync with walletconnect resolves prematurely, I'm not able to sign message right after
```
 async function connectAndSign({ connector }) {
    await connectAsync({ connector });
    //sleep for e.g. 1000ms here solves issue
    const signature = await signMessageAsync({ message: 'some message' }); //throws
    }
  }
  ```
  
  using same logic with metamask injected wallet seems to work fine, also same code was working with walletconnect 1.
  maybe I'm doing something wrong, but seems like it resolves before signer is set up or something like that

### Expected Behavior

when connectAsync resolves all hooks should work properly

### Steps To Reproduce

click `Wallectconnect+sign` button, login with walletconnect, it will throw right after since signMessage fails
![image](https://github.com/wagmi-dev/wagmi/assets/9463015/36a69e59-7c5e-4e1d-9fb7-347b279f9c5b)

### Link to Minimal Reproducible Example (StackBlitz, CodeSandbox, GitHub repo etc.)

https://stackblitz.com/edit/stackblitz-starters-xvs7pj?file=pages%2Findex.js

**Comment by imornar** [comment]
Thanks for response. Gotcha, so fix for this will be probably in next release? If so any estimate on when that should be.

**Comment by jxom** [comment]
WalletConnect update should be released now.

**Comment by imornar** [comment]
Thank you guys. 
I just tested it with new version and issue still persist.

**Comment by vkuts** [comment]
Thanks for the quick patch to include the newest WC dependencies. I'm also continuing to experience the chain switching issue. Wondering if the bug originates in WC libs or on MM's end, sigh.
