### ISSUE TITLE
bug: switchNetwork from wagmi core does not work on mobile

### ISSUE THREAD

**Issue by HT-Moh** [wagmi-dev/wagmi#2632]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

1.3.0

### Current Behavior

If the network does not exist on wallets (tested wallets: metamask + trust wallet), `switchNetwork` does not add the network on mobile (iPhone), on desktop simply works.

### Expected Behavior

`switchNetwork` should simply work on mobile and desktop
![image](https://github.com/wagmi-dev/wagmi/assets/34759569/50d07997-1fc1-482c-91ee-c7a5cd3628fb)

### Link to minimal reproducible example

below

### Summary

Description:
The switchNetwork function should add the network if it does not exist and switch to it. This behavior works correctly on desktops, but when using an iPhone with MetaMask installed, the network is not added.

Steps to Reproduce:

Open the index.html file.

1. create `index.html` and add the following code snippet: <w3m-core-button icon='hide'></w3m-core-button> inside the body of 
2. Add `<script type="module" src="'web3modal.js"/>` inside the head tag of `index.html`
3. create `web3modal.js` file and add the code below inside 
4. host the page somewhere and open it on the mobile (iPhone).

```javascript
import {
  EthereumClient,
  w3mConnectors,
  w3mProvider,
  WagmiCore,
  WagmiCoreChains,
  WagmiCoreConnectors,
} from "https://unpkg.com/@web3modal/ethereum";
import {
  EthereumClient,
  w3mConnectors,
  w3mProvider,
  WagmiCore,
  WagmiCoreChains,
  WagmiCoreConnectors,
} from "https://unpkg.com/@web3modal/ethereum";

// import UniversalProvider from "https://unpkg.com/@walletconnect/universal-provider";

import { Web3Modal } from "https://unpkg.com/@web3modal/html";

const { mainnet, polygon, polygonMumbai, avalanche, arbitrum } =
  WagmiCoreChains;
const {
  configureChains,
  createConfig,
  switchNetwork,
} = WagmiCore;

// 1. Define chains
const chains = [mainnet, polygon, polygonMumbai, avalanche, arbitrum];

const projectId = "your_project_id";

const { publicClient } = configureChains(chains, [w3mProvider({ projectId })]);
const wagmiConfig = createConfig({
  autoConnect: true,
  connectors: w3mConnectors({ projectId, version: 1, chains }),
  publicClient,
});
const ethereumClient = new EthereumClient(wagmiConfig, chains);
const web3modal = new Web3Modal(
  { projectId, walletConnectVersion: 2 },
  ethereumClient
);
web3modal.subscribeModal((newState) => {
  console.log(newState);
});
web3modal.subscribeEvents((newState) => {
  const { name } = newState;
  if (name === "ACCOUNT_CONNECTED") {
    switchNetwork({
      chainId: 80001,
    })
      .then((chain) => {
        console.log(chain);
      })
      .catch((e) => {
       console.error(addError);
      });
  }
  console.log(newState);
});
```

### List of related npm package versions

I am using just html and vanilla javascript and importing the libraries inside the file  `web3modal.js` which is imported on head of index.html as script type module

```javascript
import {
  EthereumClient,
  w3mConnectors,
  w3mProvider,
  WagmiCore,
  WagmiCoreChains,
  WagmiCoreConnectors,
} from "https://unpkg.com/@web3modal/ethereum";
import {
  EthereumClient,
  w3mConnectors,
  w3mProvider,
  WagmiCore,
  WagmiCoreChains,
  WagmiCoreConnectors,
} from "https://unpkg.com/@web3modal/ethereum";

// import UniversalProvider from "https://unpkg.com/@walletconnect/universal-provider";

import { Web3Modal } from "https://unpkg.com/@web3modal/html";
```

### Anything else?

Note: 
https://github.com/WalletConnect
[web3modal](https://github.com/WalletConnect/web3modal) is using  @wagmi/core": "1.3.0"
posted the same issue on https://github.com/WalletConnect/web3modal/issues/1098

**Comment by jxom** [comment]
Let's track this in Web3Modal.
