### ISSUE TITLE
bug: readContract return "can't convert BigInt to number"

### ISSUE THREAD

**Issue by samyan** [wagmi-dev/wagmi#2637]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Package Version

1.1.8

### Current Behavior

```typescript
const { data: contractReadData } = useContractRead({
		address: contractAddress,
		abi: JSON.parse(contractAbi),
		functionName: 'balanceOf',
		args: [address],
		onError(error) {
			console.log('Error ', error);
		}
	});

```

Error
```
ContractFunctionExecutionError: An unknown error occurred while executing the contract function "balanceOf".

Raw Call Arguments:
  to:    0x7D4650aa313b8061178aeae5bee5b8dA2f655729
  data:  0x70a0823100000000000000000000000049c10e40bc9a7571da9b4f24f0affda112d6559b
 
Contract Call:
  address:   0x7D4650aa313b8061178aeae5bee5b8dA2f655729
  function:  balanceOf(address account)
  args:               (0x49C10E40bC9A7571Da9B4f24f0afFDA112d6559b)

Docs: https://viem.sh/docs/contract/readContract.html
Details: can't convert BigInt to number
Version: viem@1.1.7
```

### Expected Behavior

The balance amount

### Steps To Reproduce

I created my project via CRA (Create React App). In debug mode is ok but after build the project I get the mentioned error.

Packages:

```json
"react-scripts": "5.0.1",
"viem": "^1.1.8",
"wagmi": "^1.3.2",
"typescript": "^4.9.5"
```

### Anything else?

It doesn't make sense to attach a stackblitz link because as I said in debug mode it works and only fails in generated build.

**Comment by jxom** [comment]
You'll need to modify the `browserslist` to target bigints. 

https://github.com/hirosystems/stacks.js/issues/1096#issuecomment-946350299

**Comment by samyan** [comment]
> You'll need to modify the `browserslist` to target bigints.
> 
> [hirosystems/stacks.js#1096 (comment)](https://github.com/hirosystems/stacks.js/issues/1096#issuecomment-946350299)

This is my current config:

```json
{
"browserslist": {
		"production": [
			">0.2%",
			"not dead",
			"not op_mini all"
		],
		"development": [
			"last 1 chrome version",
			"last 1 firefox version",
			"last 1 safari version"
		]
	}
}
```

Is not ok?

**Comment by samyan** [comment]
> You'll need to modify the `browserslist` to target bigints.
> 
> [hirosystems/stacks.js#1096 (comment)](https://github.com/hirosystems/stacks.js/issues/1096#issuecomment-946350299)

Solved, thank you!
