### ISSUE TITLE
bug:  Cannot use import statement outside a module

### ISSUE THREAD

**Issue by ghost** [wagmi-dev/wagmi#2640]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

1.2.1

### Current Behavior

The test failed.

`
 Details:

    /home/runner/work/makeweb3-boilerplate/makeweb3-boilerplate/node_modules/@wagmi/connectors/dist/metaMask.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,jest){import {
                                                                                      ^^^^^^

    SyntaxError: Cannot use import statement outside a module
`
https://github.com/MakeWeb3/makeweb3-boilerplate/actions/runs/5398039191/jobs/9803378896

### Expected Behavior

Test don't failed

### Link to Minimal Reproducible Example (StackBlitz, CodeSandbox, GitHub repo etc.)

https://github.com/MakeWeb3/makeweb3-boilerplate

**Comment by tmm** [comment]
Looks like a Jest configuration error.
