### ISSUE TITLE
bug: Issue with WAGMI app deployment and contract function execution in development environment

### ISSUE THREAD

**Issue by Rohitbaghel** [wagmi-dev/wagmi#2642]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

1.3.2

### Current Behavior

After successful deployment in the development environment, calling or executing transaction contract functions does not work as expected.

### Expected Behavior

The WAGMI app should deploy successfully in the development environment and allow the execution of transaction contract functions.

### Steps To Reproduce

Set up the development environment.
Deploy the WAGMI app in the development environment.
Attempt to call or execute a transaction contract function.

### Anything else?

Issue Overview:
When attempting to run the WAGMI app in the development environment, the deployment process completes successfully. However, upon attempting to call or execute a transaction contract function, the function is not executable. This issue does not occur when running the app locally.

**Comment by tmm** [comment]
Thanks for reporting. This issue is temporarily closed due to lack of information. Please provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) and reopen this issue.
