### ISSUE TITLE
bug: switching networks

### ISSUE THREAD

**Issue by 0xvidejk** [wagmi-dev/wagmi#2643]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

1.3.2

### Current Behavior

Chain doesn't change in mobile metamask

I try to change chain using `switchNetwork` which coming from hook `useSwitchNetwork()`. Some time it just makes wagmi think that network has been changed ( `useNetwork()` returns new chainId, but in metamask still the previous one), some time it redirect to metamask and nothing happens. 

**If it is the correct behaviour, then how can I handle this, because when user tries to send a transaction using chain, that is not selected in metamask mobile - there is no approve transaction pop up.**

### Expected Behavior

Pop-up request to change the chain in mobile metamask or pop-up to approve tx

### Link to Minimal Reproducible Example (StackBlitz, CodeSandbox, GitHub repo etc.)

https://fpcmd7.csb.app/

### Anything else?

In addition I use rainbowkit 1.0.4, viem 1.2.1

**Comment by 0xvidejk** [comment]
Also it is switching, but metamask doesn’t have selected chain at all :)

https://github.com/wagmi-dev/wagmi/assets/119004906/19c8b83f-381d-4188-af2e-743fa5d57b32

**Comment by tmm** [comment]
Let's track here: https://github.com/wagmi-dev/wagmi/issues/2639
