### ISSUE TITLE
bug: Documentation for useContract is incorrect.

### ISSUE THREAD

**Issue by scotthconner** [wagmi-dev/wagmi#2657]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.12.8

### Current Behavior

The documentation for useContract() is no longer correct for the latest version of wagmi: 

https://0.3.x.wagmi.sh/docs/hooks/useContract

The attributes are considered as "addressOrName" and "contractInterface", but in the latest versions they are "address" and "abi". If someone uses the latest version of wagmi, but looks at the documentation, useContract() will return null and it will confuse people.

### Expected Behavior

I would expect the wagmi documentation to be properly versioned, or make it clear which version each documentation supports.

### Steps To Reproduce

Try to use any of the code samples in the documentation as a basis for useContract() using the latest public version of wagmi.

### Link to Minimal Reproducible Example (StackBlitz, CodeSandbox, GitHub repo etc.)

unneeded

### Anything else?

All you need to do is update the documentation.

**Comment by tmm** [comment]
`useContract` no longer exists in v1 of wagmi. You should [use `getContract` instead](https://wagmi.sh/react/migration-guide#usecontract). (`useContract` was removed because it doesn't have any hook behavior.)
