### ISSUE TITLE
bug: get error message "Cannot read properties of undefined (reading 'init')"

### ISSUE THREAD

**Issue by EdenHwang** [wagmi-dev/wagmi#2659]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

1.3.3

### Current Behavior

After WalletConnect v1 was shut down, I upgraded wagmi to version 1.3.3 (previously using version 0.11) to accommodate the use of v2. However, suddenly I'm getting the "Cannot read properties of undefined (reading 'init')" error, and the app is not running. can you gays help me with this?

there is my connector config
<img width="438" alt="스크린샷 2023-06-30 오후 2 48 15" src="https://github.com/wagmi-dev/wagmi/assets/112357934/cdd296db-78ce-43d5-baf2-4d9425622b5c">
<img width="1008" alt="스크린샷 2023-06-30 오후 3 36 21" src="https://github.com/wagmi-dev/wagmi/assets/112357934/34528a4f-8bd3-45dd-807b-06a90c4bd8fc">

**Comment by tmm** [comment]
Thanks for reporting. This issue is temporarily closed due to lack of information. Please provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) (e.g. what bundler are you using? ) and reopen this issue.
