### ISSUE TITLE
bug: MetaMask Connect Button Intermittently Missing or Non-Responsive in Chrome

### ISSUE THREAD

**Issue by avalan4e57** [wagmi-dev/wagmi#2660]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

1.3.3

### Current Behavior

I'm facing an intermittent issue with MetaMask when using Wagmi's web3 interface in Chrome:

1. Sometimes, the button to connect MetaMask is not visible, as though MetaMask is not installed.
2. At other times, the button is visible but unresponsive. Nothing happens upon clicking (except changing the loading state), and the MetaMask extension does not open.

This issue is not specific to Wagmi, as I can reproduce it across different web3 apps and while using the basic MetaMask API call `window.ethereum.request({ method: 'eth_requestAccounts' })`.

The issues do not always occur and it's unpredictable which of the two scenarios will occur. I have not encountered these issues in Firefox or Brave.

### Expected Behavior

The button to connect MetaMask should always be visible and responsive. Clicking it should always open the MetaMask browser extension.

### Steps To Reproduce

1. Open a new tab in Chrome (Version 114.0.5735.133 (Official Build) (arm64)).
2. Navigate to https://wagmi.sh/examples/connect-wallet.
3. Check if the button to connect MetaMask is present and note what happens upon clicking it.

Refreshing the page usually fixes the issue. However, the issue frequently occurs when a web3 app is initially loaded in a new tab.

### Link to Minimal Reproducible Example (StackBlitz, CodeSandbox, GitHub repo etc.)

https://wagmi.sh/examples/connect-wallet

### Anything else?

I have reported the same issue to the MetaMask team on their GitHub repository [here](https://github.com/MetaMask/metamask-extension/issues/19839). This report is for awareness, and to see if there are any known workarounds or fixes from the Wagmi side.

**Comment by sergiycheck** [comment]
I have faced the same issue with **"wagmi": "^1.3.3"**. The metamask connector is not ready for the first page load and becomes ready for the second page load. Workaround is to reload the page every time on the first load. This behaviour is also reproduced on earlier versions of wagmi for examle **^0.12.8**
