### ISSUE TITLE
i can't pass payable to args when writeContract like in version 0.12.9 , how can i pass payable to args.

### ISSUE THREAD

**Issue by chungit201** [wagmi-dev/wagmi#2683]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

1.9.0

### Current Behavior

i can't pass payable to args when writeContract like in version 0.12.9 , how can i pass payable to args.

### Expected Behavior

can pass a payable parameter to args

### Steps To Reproduce

version 1.9.0 working and new version not working.
```
 const { data: res } = await write({
      address: data.contract,
      abi: RouterAbi,
      functionName: 'swapExactETHForTokens',
      args: [
        data.amountOut,
        data.routers,
        address,
        deadline,
        {
          value:data.amountIn
        }
      ],
    } as any);
```

### Anything else?

ko

**Comment by jxom** [comment]
https://wagmi.sh/react/hooks/useContractWrite#value-optional
