### ISSUE TITLE
Doc: The doc is not updated on Wagmi Core no longer returning wait after migrating to viem

### ISSUE THREAD

**Issue by ong-appxplore** [wagmi-dev/wagmi#2684]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

1.3.5

### Current Behavior

The return value from `writeContract` used to have wait function but was removed after migrating to viem. It's still there in the [doc](https://wagmi.sh/core/actions/writeContract#return-value)

My code as below
```js
const { hash, wait } = await writeContract(config);
```

It returns `TypeError: wait is not a function`

### Expected Behavior

To update the return value of the function `writeContract` as it's misleading.

### Anything else?
Is there anything similar to the previous `wait` function from `ethers` that I can use to wait for the receipt? If not, how do I know when the transaction receipt is done?

**Comment by saintmaxi** [comment]
I believe you're looking for viem's [waitForTransactionReceipt](https://viem.sh/docs/actions/public/waitForTransactionReceipt.html#waitfortransactionreceipt). You pass it the hash returned from [writeContract](https://viem.sh/docs/contract/writeContract.html). It will return 'success' in the status of the returned object if it completed successfully.

**Comment by ong-appxplore** [comment]
Yes. You're right. Thanks @saintmaxi.
