### ISSUE TITLE
bug: Module not found: Can't resolve 'ethers'

### ISSUE THREAD

**Issue by ryuji-orca** [wagmi-dev/wagmi#2689]
### Package Version

1.3.6

### Current Behavior

I get the following error when trying to SIWE with the latest version of wagmi.

```
./node_modules/siwe/dist/ethersCompat.js:5:0
Module not found: Can't resolve 'ethers'

https://nextjs.org/docs/messages/module-not-found

Import trace for requested module:
./node_modules/siwe/dist/client.js
./node_modules/siwe/dist/siwe.js
./src/pages/closet/index.page.tsx
```

When I set the wagmi version to 1.1.0, the error no longer occurs.

Other versions

```
"next": "^13.4.8",
"viem": "^1.2.9",
"siwe": "^2.1.4",
```

**Comment by jxom** [comment]
Might be worth raising this issue on the siwe repo? Seems like it's coming from there.
