### ISSUE TITLE
bug: SendTransaction example - sendTransaction when connecting WalletConnect via mobile qr

### ISSUE THREAD

**Issue by meri-maki** [wagmi-dev/wagmi#2694]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

the one that's used in doc examples

### Current Behavior

I'm currently writing logic on my react website based on the examples in the docs
Connect wallet example works perfectly fine
However, in send transaction example (https://wagmi.sh/examples/send-transaction) I connected my zerion wallet via qr code (and mobile app for zerion). Then I tried sending transaction and got this error:

```
Error: An unknown RPC error occurred. Request Arguments: from: 0x568A33aA237fFc284FF584A3BAB17A44FAeF4054 to: 0xe8078b5198e572be8d8d412511d48b7d0f5e9a1c value: 0.0001 ETH gas: 104799 Version: viem@1.0.0
```

![Снимок экрана 2023-07-05 в 20 16 16](https://github.com/wagmi-dev/wagmi/assets/97887955/a5ff51b3-d079-45e7-b022-57cc36bd2ba2)

I got the same behavior when connecting trust wallet (through walletconnect mobile qr)

When doing the same in Incognito chrome, with zerion wallet (through walletconnect mobile qr) I got infinite Check wallet with no transaction appearing in my zerion mobile app
![Снимок экрана 2023-07-05 в 20 16 33](https://github.com/wagmi-dev/wagmi/assets/97887955/a32450d3-8158-438c-a8a2-63e19162fe36)

### Expected Behavior

When connecting with Wallet Connect mobile qr, transaction should automatically appear in the mobile app of connected wallet

### Steps To Reproduce

Can be reproduced on this page https://wagmi.sh/examples/send-transaction

**Comment by meri-maki** [comment]
When connecting to Metamask via WalletConnect (mobile qr)- transactions successfully appear on my mobile metamask app

**Comment by meri-maki** [comment]
Opened https://wagmi.sh/examples/send-transaction on my phone (ios 16.3.1)
successfully connected to my zerion wallet via WalletConnect

However, when sending transaction - got redirected to zerion wallet app, but nothing showed up
When going back to wagmi site - error appeared:
![image](https://github.com/wagmi-dev/wagmi/assets/97887955/64a837df-eb57-47b3-8b61-61ffa198bd4b)

**Comment by tmm** [comment]
Thanks for reporting. This issue is temporarily closed due to lack of information. Please provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) and reopen this issue.

**Comment by meri-maki** [comment]
Well, this error appeared on wagmi docs page, but here is the build with same error @tmm 

https://github.com/meri-maki/wagmi-issue

To reproduce: 
1. Connect to any wallet via WalletConnect (except for metamask)
2. Try sending transaction
2. Get 
```
Error: An unknown RPC error occurred. Request Arguments: from: 0x568A33aA237fFc284FF584A3BAB17A44FAeF4054 to: 0xe8078b5198e572be8d8d412511d48b7d0f5e9a1c value: 0.0001 ETH gas: 104799 Version: viem@1.0.0
```
