### ISSUE TITLE
bug: Updating wagmi form 1.3.4 to 1.3.8 caused ERROR`useConfig` must be used within `WagmiConfig`.

### ISSUE THREAD

**Issue by meri-maki** [wagmi-dev/wagmi#2707]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

1.3.8

### Current Behavior

Updated wagmi form 1.3.4 to 1.3.8 and app started with 
```
ERROR
`useConfig` must be used within `WagmiConfig`.

Read more: https://wagmi.sh/react/WagmiConfig
Error: `useConfig` must be used within `WagmiConfig`.

Read more: https://wagmi.sh/react/WagmiConfig
    at useConfig (http://localhost:3000/js/purchase.31a97e17.js:86526:11)
    at useAccount 

```

However, couldn't find in documentation how useConfig must be used in this case

```
const { chains, publicClient, webSocketPublicClient } = configureChains([mainnet, polygon, optimism, arbitrum, zora], [infuraProvider({ apiKey: mainconfig.services.infura.key }), publicProvider()])

const config = createConfig({
	autoConnect: true,
	connectors: [
		new MetaMaskConnector({ chains }),
		new WalletConnectConnector({
			chains,
			options: {
				projectId: mainconfig.services.walletconnect.key,
				qrcode: true,
				themeVariables: {
					"--wcm-font-family": "Inter, sans-serif",
					"--wcm-accent-color": "var(--primary-200)",
					"--wcm-overlay-background-color": "rgba(0, 0, 0, 0.6)",
				},
			},
		}),
	],
	publicClient,
	webSocketPublicClient,
})
```

### Anything else?

Couldn't find any answer in releases too

**Comment by meri-maki** [comment]
The error remains when downgrading back to 1.3.4

**Comment by meri-maki** [comment]
Fixed by placing WagmiConfig one component up the tree

**Comment by DramaCrypto** [comment]
@meri-maki Hi
Sorry, but I am having the same issue as you.
Can you please explain more details how you fixed this issue?

**Comment by meri-maki** [comment]
@DramaCrypto hi! unfortunately, i'm not using wagmi in my project anymore so i cannot provide code
But I will try to explain how I fixed it

I had WagmiConfig in my component ```<Purchase> ```  in file Purchase.jsx like this
```
<WagmiConfig ....>
...content....
<WagmiConfig/>
```
This component was placed inside root (react.createRoot) like this
```
root.render(
	<ErrorBoundary>
			<Purchase />
	</ErrorBoundary>
)
```

Your error should be fixed by doing this (placing wagmi config in ROOT file)

```
root.render(
	<ErrorBoundary>
		<WagmiConfig /*somthing*/>
			<Purchase />
		</WagmiConfig >
	</ErrorBoundary>
)
````

**Comment by DramaCrypto** [comment]
I got it. Thanks!
