### ISSUE TITLE
bug: can't connect my wallet with rabby

### ISSUE THREAD

**Issue by imtipi** [wagmi-dev/wagmi#2708]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Package Version

idk

### Current Behavior

when i try to connect my wallet on mirrorxyz or mintfun or venus,i can't connect my rabby wallet,it shows this:
`ConnectorNotFoundError: Connector not found`

### Expected Behavior

successful connect

### Steps To Reproduce

go to mirrorxyz or mintfun and try connect with rabby

### Link to Minimal Reproducible Example (StackBlitz, CodeSandbox, GitHub repo etc.)

https://mirror.xyz/

### Anything else?

![image](https://github.com/wagmi-dev/wagmi/assets/27230181/b9c3c89b-141d-46ad-ba2d-9630a724c169)

**Comment by tmm** [comment]
Thanks for reporting. This issue is temporarily closed due to lack of information. Please provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) and reopen this issue.

**Comment by sherrbss** [comment]
@tmm  if Rabby is installed, it seems to always inject `true` as the value for the `isRabby` property within the window.ethereum object. As a result, the MetaMask connector will always return false when calling `getReady` in the constructor. 

From my understanding, Rabby is somewhat of a drop-in replacement for MetaMask. When applying a patch to comment out the checks against isRabby, all works as intended. Can see a gist of the patch [here](https://gist.github.com/sherrbss/a55b462c91e2faa716327d1dc12606d5).

To reproduce, you can log the window.ethereum object out in the constructor of the MetaMask connector. When doing this, you'll notice that you won't see the isRabby property. If you then log ethereum.isRabby, you'll see that it is indeed present and evaluates to true.
