### ISSUE TITLE
Wrong chainid when use getChainId

### ISSUE THREAD

**Issue by cungns** [wagmi-dev/wagmi#2709]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

1.3.4

### Current Behavior

useAccount({
    async onConnect({ address, connector, isReconnected }) {
      const provider = await connector?.getProvider();
      const chainId = await connector?.getChainId();
      console.log("chainId", chainId); // wrong value first time scan QR code , try again it work well .  Issue only when scan QR code 
    },
  });
  
- I connect wallet by scan QR code but on first time I use function getChainId return wrong value and I'm try scan again it return right value .

**Comment by tmm** [comment]
Thanks for reporting. This issue is temporarily closed due to lack of information. Please provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) and reopen this issue.
