### ISSUE TITLE
bug: MetaMask or Injected Connector doesn't response anything

### ISSUE THREAD

**Issue by DongwooSohn** [wagmi-dev/wagmi#2716]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

latest

### Current Behavior

1. Open a new tab on PC Chrome
2. Go to "https://wagmi.sh/examples/connect-wallet"
3. click "Injected"

### Expected Behavior

It's supposed to be connected to MetaMask.
I have only MetaMask extension, no any other wallets.

I tried several times, it was ok like first 3~4 times, after that it is not working.

After refreshing page, it works fine.
The issue only happens when open a new tab.

### Steps To Reproduce

1. Open a new tab on PC Chrome
2. Go to "https://wagmi.sh/examples/connect-wallet"
3. click "Injected"

repeat 3 or 4 times

### Anything else?

![스크린샷 2023-07-10 오후 5 10 33](https://github.com/wagmi-dev/wagmi/assets/110084028/c3433fb9-df84-4e25-bbda-5b0bf1517b49)

Loading spinner rotate infinitely.

Furthermore, I tried MetaMask Connector by myself. It response nothing too.
I tried with Rainbowkit and web3modal

**Comment by ennioVisco** [comment]
I can't reproduce, to me it works fine
<img width="809" alt="image" src="https://github.com/wagmi-dev/wagmi/assets/740025/9503764e-a791-4186-a3e1-c742185c5e19">

Try maybe with another browser/ in incognito mode/ by disabling some extensions
