### ISSUE TITLE
@wagmi/core's InjectedConnector configuration option did not take effect, I want to return the provider of the okxwallet wallet, but I see that the name and provider return metamsk

### ISSUE THREAD

**Issue by youthinn** [wagmi-dev/wagmi#2722]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

1.0.4

### Current Behavior

I want to define the connection of the Okx Wallet wallet. I see that the official document says that the mapped wallet can be extended using the injectedConnector. I also see the okx wallet from the extension. After configuring the injectedConnector according to the document, the meta mask is called up. I found that the configuration of the injectedConnector did not take effect from the content printed from the console.

### Expected Behavior

The configuration of the InjectedConnector takes effect, and okx wallet will not be metamasked

**Comment by youthinn** [comment]
![image](https://github.com/wagmi-dev/wagmi/assets/96770326/1fc185a2-e94f-48c8-8396-727feb6ecb26)
![image](https://github.com/wagmi-dev/wagmi/assets/96770326/680dd232-ef63-44bf-9b8d-de6c3ad93aa9)
This is my configuration code and console printing results

**Comment by youthinn** [comment]
This is my configuration code and console printing results
![image](https://github.com/wagmi-dev/wagmi/assets/96770326/150f3b58-9758-4768-9ed3-fb8e5bb3fd7f)
![image](https://github.com/wagmi-dev/wagmi/assets/96770326/0c7f5234-fc02-41a4-9d08-78fd2292edec)

**Comment by milaabl** [comment]
@youthinn, **_did you find a way to solve that?_** If yes, could you please share it? I really appreciate it. Please help me figure that thing out!
