### ISSUE TITLE
bug: Wagmi CLI unable to handle multiple methods with different casing but same name

### ISSUE THREAD

**Issue by roninjin10** [wagmi-dev/wagmi#2724]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

 "@wagmi/cli": "^1.3.0",

### Current Behavior

If a contract has multiple methods with same name such as `messenger` and `MESSENGER` the wagmi cli will fail with an error `Hook name "useL1Erc721BridgeMessenger" must be unique for contract "L1ERC721Bridge".`

### Expected Behavior

Should be able to handle this corner case gracefully.

### Steps To Reproduce

Use the ERC721Bridge.sol contract from optimism repo via etherscan plugin or any other method.

### Link to Minimal Reproducible Example (StackBlitz, CodeSandbox, GitHub repo etc.)

https://github.com/ethereum-optimism/optimism/pull/6260

### Anything else?

<img width="667" alt="image" src="https://github.com/wagmi-dev/wagmi/assets/35039927/a8a540e2-b390-41a9-bb8c-b69d1d5b8e56">

**Comment by tmm** [comment]
duplicate https://github.com/wagmi-dev/wagmi/issues/2297
