### ISSUE TITLE
bug: <title>

### ISSUE THREAD

**Issue by Pszz** [wagmi-dev/wagmi#2725]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

 "wagmi": "^0.12.10",

### Current Behavior

I'm currently in chain `421613` but useChainId shows `1`

```typescript
import { useCallback } from 'react'
import { BigNumber } from 'bignumber.js'
import { fetchBalance } from '@wagmi/core'
import { Address, useAccount, useChainId, useNetwork } from 'wagmi'

export const useBalanceOf = () => {
  const chainId = useChainId()
  const { chain } = useNetwork()
  const { address } = useAccount()
  const getBalance = useCallback(
    async (token: Address, native?: boolean): Promise<BigNumber> => {
      console.log('chainId:', chain, chainId)
      const _balance = await fetchBalance({
        chainId,
        address: address,
        token: native ? undefined : token,
      })
      return new BigNumber(_balance.value.toString())
    },
    [address, chain, chainId],
  )

  return {
    getBalance,
  }
}

```

<img width="1237" alt="image" src="https://github.com/wagmi-dev/wagmi/assets/12093551/45580dbf-322c-42de-8de4-2a26d83cc0be">

### Expected Behavior

Hopefully, `useChainId` and `useNetwork` behave consistently.

**Comment by tmm** [comment]
`useChainId` reflects the current chain the config is using, `useNetwork` reflects the current chain the connected account is using. It looks like you don't have Chain 421613 configured. Please share you `createConfig` set up and a complete minimal reproduction.
