### ISSUE TITLE
bug: `value` property of the parameters of usePrepareContractWrite() is undefined

### ISSUE THREAD

**Issue by mr-new-0509** [wagmi-dev/wagmi#2735]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

1.1.0

### Current Behavior

![image](https://github.com/wagmi-dev/wagmi/assets/86947718/030d47ac-ebf3-4fff-beb9-ba5d91668213)

I know `value` property is used when a payable function is called.
However, its type is undefined so any value can't be inserted in that property but only `undefined`.

### Expected Behavior

The type of `value` property should be `bigint` or `undefined`.

**Comment by tmm** [comment]
Thanks for reporting. This issue is temporarily closed due to lack of information. Please provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) and reopen this issue.

**Comment by hskang9** [comment]
@tmm minimal reproducible example is not even needed, just look at your `index.d.ts`. the property `value` is literally missing
```
declare function usePrepareContractWrite<TAbi extends Abi | readonly unknown[], TFunctionName extends string, TChainId extends number>({ address, abi, functionName, chainId, args, overrides, cacheTime, enabled, scopeKey, staleTime, suspense, onError, onSettled, onSuccess, }?: UsePrepareContractWriteConfig<TAbi, TFunctionName, TChainId>): Pick<_tanstack_react_query.QueryObserverResult<PrepareWriteContractResult<TAbi, TFunctionName, TChainId>, Error>, "data" | "error" | "isError" | "isLoading" | "isSuccess" | "isFetched" | "isFetchedAfterMount" | "isFetching" | "isRefetching" | "refetch" | "fetchStatus"> & {
  isIdle: boolean;
  status: "error" | "success" | "loading" | "idle";
  internal: Pick<_tanstack_react_query.QueryObserverResult<unknown, unknown>, "isLoadingError" | "isRefetchError" | "dataUpdatedAt" | "errorUpdatedAt" | "failureCount" | "isPaused" | "isPlaceholderData" | "isPreviousData" | "isStale" | "remove">;
} & {
  config: PrepareWriteContractResult<TAbi, TFunctionName, TChainId>;
};
```

**Comment by backseats** [comment]
@hskang9 Going at @tmm in two different issues doesn't seem like the best way to get this issue solved. Let's try to be civil here, yeah?

**Comment by hskang9** [comment]
@backseats @tmm deserves it. These two issues has been alarming two months, and this guy just ignored when this is what Typescript is for. Now I face both v0 and v1 unable to handle payable contract method. V1 breaking features from v0, while v0 in javascript still remains as useless for amm projects.

**Comment by hskang9** [comment]
This is for v0.

**Comment by jxom** [comment]
It works for me: https://www.typescriptlang.org/play?target=99#code/JYWwDg9gTgLgBAbzgVwM4FMAKV1gIY4DCEAdjFHgMYwDqUwM6cAvnAGZQQhwBEA7ngDmIYDwDcAKAlosOfEVLkqteowAUCCXDh4ARsABccANpbtiM+bjASYZDFRHjAXQA0l8yTwh0RnvgBPHncrbQh7OwcnNw9tVBg8RgBZez1gABsGAL9AvXT0YNi4GACwX142ZBJqYFJCq2YQuGcdVDhKUnimvAATHpxURzgAcgAGAA9hpsrqmFqSADlvcuHAqbMAeg24AEl4PmgAa1QAOjMANzx05HKARhIJZgBKSWkMbFwCdGIyCmo6BjoDRmNJODyaULWWz2IYuJpWLw+PwkCCYPBBeHmcIwSKwmKQ+KJdApBL6TIlZGkXK6fL1UIlMp+GY1OqYxpmFp4NodEhdEF9AZDMaTaZVFmLZZGYYotEBdbaLZwAACDgAtOhxmVqOqoJwoBcrjcjPdHi8pEA

There are no type errors in the above minimal reproducible example.

**Comment by hskang9** [comment]
@jxom what you really need to do imo is to include value key in the hook and add test you just wrote in branch 0.12.x then publish new version for v0.

https://github.com/wagmi-dev/wagmi/blob/0.12.x/packages/react/src/hooks/contracts/usePrepareContractWrite.ts

**Comment by backseats** [comment]
Instead of yelling at someone to do free labor for you, you can fork the repo and make the changes you desire… it’s open source

**Comment by hskang9** [comment]
I am doing both. I have my changes []() right now. I don’t expect they will fix the code, so I yell at them.

**Comment by backseats** [comment]
Change your code to suit you. Don’t be a dick.

Have a good day

**Comment by hskang9** [comment]
I will, and I will yell at them for other v0 projects who cannot use payable contract method. 

Thank you.

**Comment by hskang9** [comment]
here are the issues that they have been ignoring.

https://github.com/wagmi-dev/wagmi/issues/2568

https://github.com/wagmi-dev/wagmi/issues/2423

https://github.com/wagmi-dev/wagmi/issues/2311

https://github.com/wagmi-dev/wagmi/issues/1326

Now who is doing a free labor?

**Comment by tmm** [comment]
@hskang9 all of those issues ended up with the OP resolving their issue.

I understand it can be frustrating when things come up when coding, but that's not an excuse to act without respect. Hope you learn from this experience!
