### ISSUE TITLE
bug: `AddressType` error when using wagmi and viem

### ISSUE THREAD

**Issue by technophile-04** [wagmi-dev/wagmi#2736]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

1.3.8

### Current Behavior

It seems that #2421 has again appeared in the latest version 

There is a version mismatch of `abitype` in `wagmi` and `viem`

PS : We have overrided `AddressType : string` 

### Steps To Reproduce

Please check the below issue for easy reproduction 🙏: 

https://github.com/scaffold-eth/scaffold-eth-2/issues/419

### Link to Minimal Reproducible Example (StackBlitz, CodeSandbox, GitHub repo etc.)

https://github.com/scaffold-eth/scaffold-eth-2/issues/419

### Anything else?

Just pasting SS from https://github.com/scaffold-eth/scaffold-eth-2/issues/419

![Screenshot 2023-07-14 at 12 16 18 AM](https://github.com/wagmi-dev/wagmi/assets/80153681/d3df1281-26d0-4313-aba3-bc13cf091f15)

--- 
![Screenshot 2023-07-14 at 12 16 18 AM](https://user-images.githubusercontent.com/80153681/253390109-c1ef1a49-ae53-47f1-bafc-ff83ad6f2784.jpg)

Tysm Guys !! 🙌

**Comment by tmm** [comment]
Let's track this https://github.com/wagmi-dev/wagmi/issues/2898
