### ISSUE TITLE
SendTransaction is not working with Trustwallet connection

### ISSUE THREAD

**Issue by cryptonexum** [wagmi-dev/wagmi#2746]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Package Version

1.3.8

### Current Behavior

calling send transaction not opens popup in trustwallet and getting some "unknown RPC error not in console but after debug source in console I found that"
However with  metamask its working

### Expected Behavior

it should open popup to confirm transaction on trustwallet

### Steps To Reproduce

try to use @wagmi/core ->{ sendTransaction }
here is my code
`  let tx = {
    to: '0x0000000000000000000000000000000000000000',
    gasLimit: '300000',
    nonce: 1,
    chainId: 1,
    value: "1"
  };
  const result = await sendTransaction(tx);
  console.log(result);`

**Comment by tmm** [comment]
See https://github.com/wagmi-dev/wagmi/issues/2161 or add a minimal reproduction
