### ISSUE TITLE
bug: USDT transfer - The contract function "transfer" returned no data ("0x")

### ISSUE THREAD

**Issue by DarioSiroki** [wagmi-dev/wagmi#2749]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

1.3.9

### Current Behavior

I'm implementing the token transfers in my app and USDT is being the only token which is not working. The contract returns no data when trying to initiate the contract write. I'm not 100% sure this is a wagmi issue... could be me or viem too

### Expected Behavior

USDT contract calls should work

### Steps To Reproduce

1. Connect the wallet
2. Try to send some USDT (you'll need some USDT balance, I'm ready to send some over to maintainers if they wanna take a look)

### Link to Minimal Reproducible Example (StackBlitz, CodeSandbox, GitHub repo etc.)

https://github.com/DarioSiroki/usdt-please

### Anything else?

The error I get is:

```
App.jsx:51 ContractFunctionExecutionError: The contract function "transfer" returned no data ("0x").

This could be due to any of the following:

- The contract does not have the function "transfer",
- The parameters passed to the contract function may be invalid, or
- The address is not a contract.

Contract Call:
address: 0xdAC17F958D2ee523a2206206994597C13D831ec7
function: transfer(address recipient, uint256 amount)
args: (0x04dAb01aA15Dc4e57910420f7464bFC68579b2d2, 10000000)
sender: 0x00d2ADa3365e40C05E8772e58B9aAcf356F3E474

Docs: https://viem.sh/docs/contract/simulateContract.html
Version: viem@1.2.15
at getContractError (getContractError.ts:55:10)
at simulateContract (simulateContract.ts:159:11)
at async prepareWriteContract (chunk-LAFZBYO7.js:2078:31)
at async writeContract (chunk-LAFZBYO7.js:2354:17)
```

**Comment by tmm** [comment]
USDTs ABI does not exactly follow the `erc20ABI` (see below). Make sure you either use the correct ABI.

```diff
[
    {
        "constant": false,
        "inputs": [
            {
                "name": "_to",
                "type": "address"
            },
            {
                "name": "_value",
                "type": "uint256"
            }
        ],
        "name": "transfer",
        "outputs": [
-            {
-                "name": "",
-                "type": "bool"
-            }
        ],
        "payable": false,
        "stateMutability": "nonpayable",
        "type": "function"
    },
]
```

**Comment by DarioSiroki** [comment]
That fixed it indeed! Thank you so much for the help 🙂

**Comment by memoryInject** [comment]
@DarioSiroki can you please explain how did you fix it? I am facing the same issue

**Comment by DarioSiroki** [comment]
> @DarioSiroki can you please explain how did you fix it? I am facing the same issue

Sure, I copied over erc20ABI from wagmi and removed the lines of code that @tmm decribed. You end up with a variable like this:

```ts
export const usdtAbi = [
    {
        type: 'event',
        name: 'Approval',
        inputs: [
            {
                indexed: true,
                name: 'owner',
                type: 'address',
            },
            {
                indexed: true,
                name: 'spender',
                type: 'address',
            },
            {
                indexed: false,
                name: 'value',
                type: 'uint256',
            },
        ],
    },
    {
        type: 'event',
        name: 'Transfer',
        inputs: [
            {
                indexed: true,
                name: 'from',
                type: 'address',
            },
            {
                indexed: true,
                name: 'to',
                type: 'address',
            },
            {
                indexed: false,
                name: 'value',
                type: 'uint256',
            },
        ],
    },
    {
        type: 'function',
        name: 'allowance',
        stateMutability: 'view',
        inputs: [
            {
                name: 'owner',
                type: 'address',
            },
            {
                name: 'spender',
                type: 'address',
            },
        ],
        outputs: [
            {
                name: '',
                type: 'uint256',
            },
        ],
    },
    {
        type: 'function',
        name: 'approve',
        stateMutability: 'nonpayable',
        inputs: [
            {
                name: 'spender',
                type: 'address',
            },
            {
                name: 'amount',
                type: 'uint256',
            },
        ],
        outputs: [
            {
                name: '',
                type: 'bool',
            },
        ],
    },
    {
        type: 'function',
        name: 'balanceOf',
        stateMutability: 'view',
        inputs: [
            {
                name: 'account',
                type: 'address',
            },
        ],
        outputs: [
            {
                name: '',
                type: 'uint256',
            },
        ],
    },
    {
        type: 'function',
        name: 'decimals',
        stateMutability: 'view',
        inputs: [],
        outputs: [
            {
                name: '',
                type: 'uint8',
            },
        ],
    },
    {
        type: 'function',
        name: 'name',
        stateMutability: 'view',
        inputs: [],
        outputs: [
            {
                name: '',
                type: 'string',
            },
        ],
    },
    {
        type: 'function',
        name: 'symbol',
        stateMutability: 'view',
        inputs: [],
        outputs: [
            {
                name: '',
                type: 'string',
            },
        ],
    },
    {
        type: 'function',
        name: 'totalSupply',
        stateMutability: 'view',
        inputs: [],
        outputs: [
            {
                name: '',
                type: 'uint256',
            },
        ],
    },
    {
        type: 'function',
        name: 'transfer',
        stateMutability: 'nonpayable',
        inputs: [
            {
                name: 'recipient',
                type: 'address',
            },
            {
                name: 'amount',
                type: 'uint256',
            },
        ],
        outputs: [],
    },
    {
        type: 'function',
        name: 'transferFrom',
        stateMutability: 'nonpayable',
        inputs: [
            {
                name: 'sender',
                type: 'address',
            },
            {
                name: 'recipient',
                type: 'address',
            },
            {
                name: 'amount',
                type: 'uint256',
            },
        ],
        outputs: [
            {
                name: '',
                type: 'bool',
            },
        ],
    },
] as const
```

which you can then pass to 

```ts
    const { config } = usePrepareContractWrite({
        address: contractAddress,
        abi: selectedAsset.asset_id === 'USDT' ? usdtAbi : erc20ABI,
        functionName: 'transfer',
        args: [receiverAddress, parseUnits(`${debouncedAmount}`, token.data?.decimals ?? 0),
        ],
    })
```

**Comment by memoryInject** [comment]
@DarioSiroki thank you so much

**Comment by denvradiy** [comment]
what should be in ```token.data?.decimals``` ? where do you get it from?

**Comment by denvradiy** [comment]
what should be in ```token.data?.decimals``` ? where do you get it from?  @DarioSiroki

**Comment by DarioSiroki** [comment]
> what should be in `token.data?.decimals` ? where do you get it from? @DarioSiroki

Each token uses different amount of decimals, so you have to know the amount of decimals for each token that you want to work with. The way I handled it is I seeded the database with a list of tokens that my project supports and their contract addresses (selectedAsset corresponds to a row in database with contract address and some more stuff which is irrelevant here).

And then this:

```ts
const contractAddress = selectedAsset.contract_address
    ? (selectedAsset.contract_address as `0x${string}`)
    : undefined

const token = useToken({
    address: contractAddress,
})
```

There are lists of erc20 token addresses on github, example:
https://gist.github.com/tayvano/7f8373a290a21568f2666929677daf54

You can also find the contract addresses on etherscan, for example:
https://etherscan.io/token/0xdac17f958d2ee523a2206206994597c13d831ec7

**Comment by denvradiy** [comment]
@DarioSiroki  Thank you so much for your answer! 

Could you please help me with following issue: 

I just have a simple SendTransaction component:
<img width="1155" alt="Screenshot 2023-09-06 at 02 46 51" src="https://github.com/wagmi-dev/wagmi/assets/49561056/9e4b5897-6275-45f7-934d-c328f91b1c20">

I want to transfer USDT from address that is connected to my app via Metamask to another eth user address. I copied usdtAbi you provided above.

I always getting this error when I'm connected to eth mainnet:
<img width="1728" alt="Screenshot 2023-09-06 at 02 51 40" src="https://github.com/wagmi-dev/wagmi/assets/49561056/36eb9d56-e398-45fd-bb42-b29b307cd45f">
And "Transfer" button which calls write() not working at all.

But if I change the network to Goerli for example then if I click "Transfer" I'll see metamask window opened but it will says that I'm sending GoerliEth with 0 value but not USDT as I want: 
<img width="371" alt="image" src="https://github.com/wagmi-dev/wagmi/assets/49561056/3c684846-2dc5-4752-a83c-b70bd610b4ac">

The same thing if I choose Polygon for example: 
<img width="512" alt="Screenshot 2023-09-06 at 02 57 50" src="https://github.com/wagmi-dev/wagmi/assets/49561056/a4bc496c-1173-4b38-bd7b-5268724685ce">
<img width="514" alt="Screenshot 2023-09-06 at 02 58 42" src="https://github.com/wagmi-dev/wagmi/assets/49561056/3068097c-f798-40a1-8577-cbbc0882784a">

It says that I'm sending MATIC but not USDT and value is 0 again.

What I'm doing wrong? I'm pretty new to these things and tried many ways to make this work but didn't find any solution. 
Could you please help me? 

Let me know if you need an MRE repo to reproduce this

**Comment by ajrahul09** [comment]
For me when I call the **_write()_** function on AVAX network, it initiates a smart contract call but it's displaying to transfer 0 AVAX instead of 5 USDT which I inputted. Thus no USDT is transferred and I'm charged with just gas fee. Below is the code I'm working with. 

```
const { config: writeConfig } = usePrepareContractWrite({
    address: '0xdac17f958d2ee523a2206206994597c13d831ec7' // USDT contract address,
    abi: token === 'USDT' ? usdtAbi : erc20ABI,
    functionName: 'transfer',
    args: [
      receivingAddress,
      parseUnits(`${amount}`, 6),
    ],
  });
  
const { write } = useContractWrite(writeConfig);
```

@DarioSiroki can you assist me if you were able to transfer USDT from one address to another? Thanks in advance.
