### ISSUE TITLE
switchNetwork does not wake up the wallet

### ISSUE THREAD

**Issue by vic-x** [wagmi-dev/wagmi#2756]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

2.7.0

### Current Behavior

Operation steps: 1. Open the website and connect to the wallet
2. Switch the chain once (can wake up the wallet normally)
3. Switching back to the chain connected for the first time will not wake up the wallet, there is no error, and the chain is switched successfully, but the chain in the wallet APP is not switched, which leads to no result for any subsequent calls to the wallet

### Expected Behavior

Hope to wake up the wallet APP to switch again when switching to a chain that is not used for the first time

### Steps To Reproduce

Operation steps: 1. Open the website and connect to the wallet
2. Switch the chain once (can wake up the wallet normally)
3. Switching back to the chain connected for the first time will not wake up the wallet, there is no error, and the chain is switched successfully, but the chain in the wallet APP is not switched, which leads to no result for any subsequent calls to the wallet

### Link to Minimal Reproducible Example (StackBlitz, CodeSandbox, GitHub repo etc.)

https://web3modal.com/

**Comment by tmm** [comment]
Looks like you should follow up upstream with web3modal.

**Comment by vic-x** [comment]
### **At the beginning, you must use the QR code to scan and log in to reproduce this problem**

I use web3modal and @wagmi/core, switchNetwork in @wagmi/core is called separately when switching chains

> Operation steps: 
> 1. Open the website and connect to the wallet, you must log in by scanning the QR code
> 2. Switch the chain once (can wake up the wallet normally)
> 3. Switching back to the chain connected for the first time will not wake up the wallet, there is no error, and the chain is switched successfully, but the chain in the wallet APP is not switched, which leads to no result for any subsequent calls to the wallet


import {
   switchNetwork
} from '@wagmi/core'

const changeNetWork = async (chainId) => {
      try {
         const network = await switchNetwork({ chainId: chainId })
         console. log(network)
       } catch (error) {
         console. log(error)
        console. log(error)
       }
}
