### ISSUE TITLE
bug: useBalance hook doesn't update balance after an address change

### ISSUE THREAD

**Issue by rin-st** [wagmi-dev/wagmi#2764]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

1.3.2

### Current Behavior

`watch: true` doesn't work after changing the address in `useBalance` hook. It always shows the first returned balance of updated address

### Expected Behavior

new address balance updates works correctly

### Steps To Reproduce

use 
```
const { data } = useBalance({
    address,
    watch: true
  });
```
-> change address -> check returned balance (works) -> update balance of the new address -> check returned balance again (it doesn't change, but it should)

After the page reload it shows correct balance and works correctly.

### Anything else?

Video of the bug and reproducible example: https://github.com/scaffold-eth/scaffold-eth-2/issues/433

**Comment by tmm** [comment]
What do you mean "update balance of the new address"? Can you attach a minimal reproduction so we can look into this.
