### ISSUE TITLE
bug: Documentation for useEnsAvatar uses "address"

### ISSUE THREAD

**Issue by MidnightLightning** [wagmi-dev/wagmi#2765]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

1.3

### Current Behavior

I copy/paste the examples from the `useEnsAvatar` documentation page.

### Expected Behavior

I expect them to compile and run successfully

### Steps To Reproduce

Example from documentation:

```
import { useEnsAvatar } from 'wagmi'

function App() {
  const ensAvatar = useEnsAvatar({
    address: '0xA0Cf798816D4b9b9866b5330EEa46a18382f251e',
    chainId: 1,
  })
}
```

### Anything else?

The issue is the documentation gives incorrect examples. The documentation at https://wagmi.sh/react/hooks/useEnsAvatar indicates that function needs to have a `name` supplied to it as the key determining thing to look up, but then other examples go on to use `address` as an option for what to look up. The underlying viem `getEnsAvatar` function doesn't take `address`, and the Typescript compilation fails if `address` is used.

**Comment by tmm** [comment]
Feel free to update the documentation! Usually takes less time to do that than create a bug.

**Comment by MidnightLightning** [comment]
> Feel free to update the documentation! Usually takes less time to do that than create a bug.

I know I can submit a pull request for the documentation update. However, it's unclear to me whether this was a mistake in the implementation (a bug that the intended method of using it doesn't work) or documentation (the feature's not going to change, and the documentation needs to change), so hence filing an issue so it could be discussed and properly acted upon.
