### ISSUE TITLE
bug: Unable to run wagmi generate: Dynamic require of "child_process" is not supported

### ISSUE THREAD

**Issue by SaulDope** [wagmi-dev/wagmi#2766]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

1.3.0 (cli)

### Current Behavior

I'm trying to run `yarn wagmi generate` using the foundry plugin.

```
import { defineConfig } from '@wagmi/cli'
import { foundry } from '@wagmi/cli/plugins'

export default defineConfig({
  out: 'src/generated.ts',
  contracts: [],
  plugins: [
    foundry({
      project: './contracts/duel',
    }),
  ],
})
```

I'm using yarn 3.6.1 .

I've tried to do some research on the issue and it seems like a greater bundling + building issue.  This is way out of my expertise so I was wondering what some may suggest to try.

A side note is that a verbose flag would probably be useful.

```
$ yarn wagmi generate

Dynamic require of "child_process" is not supported 
```

### Expected Behavior

Wagmi generate runs as expected, links abis + deployed addresses from foundry

**Comment by tmm** [comment]
Thanks for reporting. This issue is temporarily closed due to lack of information. Please provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) and reopen this issue.
