### ISSUE TITLE
bug: Chain data change is delayed using WalletConnect v2

### ISSUE THREAD

**Issue by buildtheui** [wagmi-dev/wagmi#2767]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

1.3.9

### Current Behavior

When I connect my wallet through WalletConnect V2 using the Android MetaMask app, the chain data, whether I use useNetwork or getNetwork, delays the chain change for several seconds after the wallet is connected. This issue has been reported and discussed in detail on GitHub at https://github.com/MetaMask/metamask-mobile/issues/6835#issuecomment-1642542716.

when using the const `{ chain } = useNetwork();` happens the following using a chain different than main net:
1. before connecting WalletConnect V2 `chain.id` is equal to `undefined`
2. right after connecting the wallet using WalletConnect V2 QR code, `chain.id` is changed to `1`
3. a few seconds later `chain.id` is changed to the actual selected chain in the wallet e.g. 1155511

### Expected Behavior

When connecting with `WalletConnect V2`, chain data should be equal to the connected wallet, meaning:
1. before connecting WalletConnect V2 `chain.id` is equal to `undefined`
2. right after connecting the wallet using WalletConnect V2 QR code, `chain.id` is changed to the actual selected chain in the wallet e.g. `1155511`

This is essential to prevent any issues with operations such as signing requests after connecting the wallet, which could otherwise be sent with the wrong chain ID.

### Steps To Reproduce

1. Set up a wagmi client using WalletConnectConnector and the following chains on configureChains in the same order `[mainnet, sepolia, goerli]`
4. observe with a useEffect the chain data from useNetwork(); and validate chain data is `undefined`
5. connect your wallet using the metamask app with sepolia or goerli chain ids (Not main net) through scanning the QR code from WalletConnect v2, and observe how first `chain.id` is 1 and a few seconds later is the real `chain.id` (5 or 1155511 for this case)

### Link to Minimal Reproducible Example (StackBlitz, CodeSandbox, GitHub repo etc.)

https://stackblitz.com/edit/new-wagmi-y9mxwp?file=src%2Fmain.tsx,src%2FApp.tsx

### Anything else?

More context in this filed issue in metamask repository https://github.com/MetaMask/metamask-mobile/issues/6835

**Comment by tmm** [comment]
Not sure there's much we can do about this one as it's outside of our system.
