### ISSUE TITLE
bug: The useWalletClient() hook returns undefined after opening the application in a new tab while using MetaMask.

### ISSUE THREAD

**Issue by kuji2336** [wagmi-dev/wagmi#2778]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

1.3.4

### Current Behavior

After connecting to the application with the MetaMask wallet using the browser and attempting to open the app in a different tab multiple times, the `useWalletClient()` hook randomly returns `undefined`.  but MetaMask shows that wallet is connected, it's even possible to retrieve connected account address.
However, after refreshing the page, the `useWalletClient()` hook starts behaving correctly.

### Expected Behavior

Every time when user opens tab `useWalletClient()` should return data when wallet is connected.

Expected behavior is correct for "WalletConnect" provider.

### Steps To Reproduce

1. Connect your MetaMask Wallet to application (Link Below)
2. You can see `useWalletClient()` data been printed.
3. Try to open application in different tab multiple time (As it described in below video)
4. Randomly `useWalletClient()` data is undefined, and wallet is still connected

### Link to Minimal Reproducible Example (StackBlitz, CodeSandbox, GitHub repo etc.)

https://rainbow-test-gules.vercel.app/

### Anything else?

CodeSandBox: [url](https://codesandbox.io/p/sandbox/competent-frog-wmnsr6?file=%2Fpages%2F_app.tsx%3A55%2C29)

https://github.com/wagmi-dev/wagmi/assets/58769030/47c0e8d3-fedd-4d48-98c2-da532871c180

**Comment by tmm** [comment]
Please add a minimal reproduction that just uses wagmi (and doesn't use RainbowKit).

**Comment by Oz4** [comment]
I'm facing the same issue as well, its not related to rainbowkit wallet as it happens with walletConnect's web3modal too.
