### ISSUE TITLE
bug: wagmi-cli generate functions with no argument type

### ISSUE THREAD

**Issue by estarossa0** [wagmi-dev/wagmi#2783]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

1.3.9

### Current Behavior

When running `wagmi generate`, I get all the function and hooks with no types like:
```ts
export function useErc20Allowance(config = {}) {
  return useContractRead({ abi: erc20ABI, functionName: 'allowance', ...config })
}
export function useErc20BalanceOf(config = {}) {
  return useContractRead({ abi: erc20ABI, functionName: 'balanceOf', ...config })
}
``` 
with the config file from the docs.

### Expected Behavior

the functions argument type should not be `config = {}` but instead be typed correctly.

### Anything else?

node: v19.9.0
tsconfig.json:
```json
{
  "compileOnSave": false,
  "compilerOptions": {
    "strict": true,
    "rootDir": ".",
    "sourceMap": true,
    "declaration": false,
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "importHelpers": true,
    "target": "es2015",
    "module": "esnext",
    "lib": ["es2020", "dom"],
    "skipLibCheck": true,
    "skipDefaultLibCheck": true,
}
```
project is using a monorepo using nx and nextjs apps.

**Comment by tmm** [comment]
Thanks for reporting. This issue is temporarily closed due to lack of information. Please provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) and reopen this issue.

**Comment by estarossa0** [comment]
The issue here was that on root folder, I hade a `tsconfig.base.josn` and other apps in the monorepo were `extend`ing it in their own `tsconfig.json`, I don't know what `tsconfig` wagmi-cli was using maybe one of from the subfolders, but once I changed `tscofig.base.json` to `tsconfig.json` it worked fine.

@tmm sorry I couldn't reproduce this with a minimal example, like I said I was using default config example and it was working fine in a new project, the issue was withing my project setup.
