### ISSUE TITLE
Shardeum supported chain Id

### ISSUE THREAD

**Issue by dats-mesutdede** [wagmi-dev/wagmi#2796]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

1.3.7

### Current Behavior

Hi!

Supported chains include shardeumSphinx with 8082 chains. However, the shardeum network accepts new projects on the chain with the 8081 chain id. Would it be possible for you to do some work on supporting 8081 chain id?

### Expected Behavior

Supporting 8081 chain id

**Comment by dats-mesutdede** [comment]
Below I share the network information that we have deployed contracts and want to interact with metamask.

Name: Shardeum Dapp Sphinx 1.X
RPC: https://dapps.shardeum.org/
Chain ID: 8081
You can see all activity here: https://explorer-dapps.shardeum.org/
Get free tokens here: https://faucet-dapps.shardeum.org/

**Comment by tmm** [comment]
Feel free to open a PR in https://github.com/wagmi-dev/references
