### ISSUE TITLE
`readContract` function from @wagmi/core is not working properly.

### ISSUE THREAD

**Issue by Stenor5** [wagmi-dev/wagmi#2802]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

1.3.9

### Current Behavior

I am on sepolia testnet.
And approved 0.2 WETH to a contract.
WETH address: `0x7b79995e5f793A07Bc00c21412e50Ecae098E7f9`
Wallet address: `0x13af3C337A0d9B54E71C7Fd663Fe5bAb9E341b6E`
Contract address: `0x0402430ceF28BC0C53db2B0CcdeD92fE5F156D96`

When I tried to read allowance using readContract function, it says 0.
But If I try to get allowance on sepolia etherscan, it says below.
![image](https://github.com/wagmi-dev/wagmi/assets/98555031/8d605207-38c9-45ff-bf6f-0ead9e7ab471)

### Expected Behavior

```js
const data = await readContract({
    address: WETHAddress,
    abi: erc20ABI,
    functionName: "allowance",
    args: [WalletAddress, ContractAddress],
  });
```
the value of data should not be 0 but it is 0.

**Comment by tmm** [comment]
Thanks for reporting. This issue is temporarily closed due to lack of information. Please provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) and reopen this issue.

**Comment by prometx11** [comment]
I found the same issue. 
I get different result from etherscan and when using wagmi on Sepolia!

**Comment by tmm** [comment]
@prometx11 have a reproducible example?

**Comment by Stenor5** [comment]
@prometx11 
Please try to change RPC url with Alchemy or other things. The public RPC from wagmi is not working now.
I was able to solve this issue changing the rpc.

**Comment by tmm** [comment]
Thanks for sharing. In general, it is discouraged to use public resources.
