### ISSUE TITLE
bug: Uncaught SyntaxError: The requested module '<User>/<project>/node_modules/eventemitter3/index.js?v=59e72198' does not provide an export named 'default'

### ISSUE THREAD

**Issue by ccali11** [wagmi-dev/wagmi#2811]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

^1.3.8

### Current Behavior

Perhaps I should cross-post this to the WalletConnect repo, but posting here in case there is a known issue with my setup or fix I haven't considered. I am following the WalletConnect migration guide [found here](https://docs.walletconnect.com/2.0/advanced/migration-from-v1.x/dapps#ethereum-provider) to upgrade from v1 to v2. To use `@walletconnect/modal`, I must install `@wagmi/core` as well. The following is the code I am using (again, per the WalletConnect docs):

```typescript
import { EthereumClient, w3mConnectors, w3mProvider } from '@web3modal/ethereum'
import { Web3Modal } from '@web3modal/html'
import { configureChains, createConfig } from '@wagmi/core'
import { createPublicClient, http } from 'viem'
import { mainnet, goerli } from '@wagmi/core/chains'

const chains = [mainnet, goerli]
const projectId = import.meta.env.WALLET_CONNECT_PROJECT_ID || '8e6877b49198d7a9f9561b8712805726'

const { publicClient } = configureChains(chains, [w3mProvider({ projectId })])
// const wagmiConfig = createConfig({
//   autoConnect: true,
//   connectors: w3mConnectors({ projectId, chains }),
//   publicClient
// })
// const ethereumClient = new EthereumClient(wagmiConfig, chains)
// const web3modal = new Web3Modal({ projectId }, ethereumClient)
```

The line of code that is not commented out throws the error mentioned in the subject line of this post. (`const { publicClient } = configureChains(chains, [w3mProvider({ projectId })])`).

The issue appears only after resolving a previous issue (seemingly having to do with Big integer literals are not being available/compatible with my setup), which required me to add the following to my vite config:
```typescript
optimizeDeps: {
    exclude: ['@wagmi/core', 'viem']
  }
```

Any feedback would be much appreciated. 🙏 

Machine: Mac M1
Processor: x86 via Rosetta
OS: MacOS Ventura 13.4
Browser: Chrome Version 114.0.5735.198 
Front-End: Vue
Build Tool: Vite

**Comment by tmm** [comment]
Thanks for reporting. This issue is temporarily closed due to lack of information. Please provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) and reopen this issue.
