### ISSUE TITLE
bug: useBalance data not refreshing

### ISSUE THREAD

**Issue by Jam516** [wagmi-dev/wagmi#2818]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

1.3.9

### Current Behavior

- **useBalance** hook is used to pull the Sepolia ETH balance of the connected wallet and show it on the UI

- When the connected wallet performs a transaction that changes the SEP balance, the balance does not update even though the 'watch' parameter is set to true

### Expected Behavior

- User connects wallet

- The Sepolia ETH balance returned by **useBalance** is correct

- User performs a transaction that changes the SEP balance

- **useBalance** refreshes data and returns the latest balance when there is a new block

### Steps To Reproduce

(1) Fork this CodeSandbox that has a basic example of displaying SEP balance using **useBalance**: https://codesandbox.io/p/sandbox/starter-template-forked-gl6wpp?file=%2Fpages%2Findex.tsx%3A41%2C36

(2) Connect wallet and view balance

(3) Send or receive Sepolia ETH to change your balance

(4) Check to see if your balance updates

### Link to Minimal Reproducible Example (StackBlitz, CodeSandbox, GitHub repo etc.)

https://codesandbox.io/p/sandbox/starter-template-forked-gl6wpp?file=%2Fpages%2Findex.tsx%3A41%2C36

**Comment by tmm** [comment]
Please put together a minimal reproduction that only uses wagmi (doesn't use ConnectKit). You can use [new.wagmi.sh](https://new.wagmi.sh) to get started.
