### ISSUE TITLE
bug: Wagmi causing "Property 'TextEncoder' doesn't exist" error in React Native Expo. Is Wagmi compatible with React Native?

### ISSUE THREAD

**Issue by ElliotWood13** [wagmi-dev/wagmi#2825]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

1.3.9

### Current Behavior

Has anyone come across the problem whereby once you've installed Wagmi in a React Native app and wrapped your app in the provider it causes an error "Property 'TextEncoder' doesn't exist"? Any help would be much appreciated.

App is wrapped in:

<WagmiConfig config={config}>...</WagmiConfig>

Config is:

import { configureChains, createConfig } from 'wagmi';
import { publicProvider } from '@wagmi/core/providers/public';

export const { chains, publicClient, webSocketPublicClient } = configureChains([polygonMumbai], [publicProvider()]);
export const config = createConfig({
  autoConnect: true,
  publicClient,
  webSocketPublicClient,
});

### Expected Behavior

Not sure if Wagmi and it's dependencies rely on web browser features which we don't have access to in React Native.

### Steps To Reproduce

Install latest wagmi viem in React Native Expo project.

### Link to Minimal Reproducible Example (StackBlitz, CodeSandbox, GitHub repo etc.)

n/a

**Comment by tmm** [comment]
See [Platform Compatibility](https://viem.sh/docs/compatibility.html). You may have to polyfill.
