### ISSUE TITLE
bug: No matching key. keychain:

### ISSUE THREAD

**Issue by MickaelNeves** [wagmi-dev/wagmi#2847]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

^1.3.9

### Current Behavior

I can't verify my account. I'm using RainbowKit v^1.0.6 + WalletConnect + Argent Wallet and when the signature modal pops up to send a message, I accept it in Argent wallet, but in the modal I get the message "Error verifying signature, please retry!". After debugging using breakpoints (cause the try/catch error is not handled) I found that im getting the error "No matching key. keychain"

### Expected Behavior

Excepted to sign the message and connect my wallet

### Steps To Reproduce

1 - visit [www.botto.com](http://www.botto.com/)
2 - connect wallet
3 - choose walletconnect or argent wallet
4 - follow the steps until reaching the sign modal

### Anything else?

![Screenshot 2023-08-02 at 11 04 31](https://github.com/wagmi-dev/wagmi/assets/20476271/4e393f57-fd77-4916-8d81-ea660a3fe113)

**Comment by tmm** [comment]
Thanks for reporting. This issue is temporarily closed due to lack of information. Please provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) and reopen this issue.

**Comment by naviocean** [comment]
Got the same issue

**Comment by drquinn** [comment]
same issue

**Comment by tmm** [comment]
Waiting for minimal reproduction.
