### ISSUE TITLE
bug: useContractRead does nothing

### ISSUE THREAD

**Issue by sayhicoelho** [wagmi-dev/wagmi#2850]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

^1.3.9

### Current Behavior

When I try to run a function named "balanceOf", nothing happens.

### Expected Behavior

I want to get the user's balanceOf result.

### Steps To Reproduce

```jsx
const { data: balanceOfData, isError, isLoading } = useContractRead({
    address: process.env.REACT_APP_ERC20_TOKEN_CONTRACT_ADDRESS,
    abi: erc20TokenAbi,
    functionName: 'balanceOf',
    args: ['0x00000123'],
  })

return (
  <div>{balanceOfData}</div>
)
```

The balanceOfData is always empty. No errors. No loadings.

**Comment by tmm** [comment]
Check that `REACT_APP_ERC20_TOKEN_CONTRACT_ADDRESS` is defined. If `address` is not defined, the hook will not run.

**Comment by sayhicoelho** [comment]
@tmm The env var is already defined. The hook doesn't work as expected. Also, the docs is messy.

**Comment by tmm** [comment]
@sayhicoelho I understand it can be frustrating when things don't work they way you want them to. If you put together a minimal reproduction, I'm happy to look into it.

**Comment by jxom** [comment]
`args` needs to be an address.
