### ISSUE TITLE
bug: usePrepareContractWrite not using custom wallet client

### ISSUE THREAD

**Issue by Max-3-7** [wagmi-dev/wagmi#2853]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

1.3.9

### Current Behavior

Hello,

I'm trying to send a write transaction with another wallet client than the connected one but it's still using the connected wallet anyway:

```
const { config } = usePrepareContractWrite({
    walletClient: customWalletClient,
    ...
});

const { write } = useContractWrite(config)

// ...
```

https://github.com/wagmi-dev/wagmi/blob/main/packages/react/src/hooks/contracts/usePrepareContractWrite.ts#L172

Let me know if that's still a supported use case or not, thanks!

**Comment by tmm** [comment]
This isn't supported at the moment.

**Comment by liho00** [comment]
I think this is a bug, for some specific function we want to use local wallet client instead of calling rpc...
