### ISSUE TITLE
bug: Not receiving prompt for approval/accept connection

### ISSUE THREAD

**Issue by nfts2me** [wagmi-dev/wagmi#2854]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.12.x

### Current Behavior

No prompt is shown when trying to connect to dApps using Chrome mobile after Metamask mobile update to 7.3.0. With dApps that were already connected, all actions that should prompt the user for approval have no effect.

This happens on multiple dApps; 
Here full description from the Metamask repo:
https://github.com/MetaMask/metamask-mobile/issues/6943

However, I've seen that some apps like OpenSea circumvent this issue using this kind of links that are opened by Metamask mobile. https://metamask.app.link/dapp/opensea.io
Which open the Metamask mobile browser. 

### Expected Behavior

Work using Chrome mobile. 

### Steps To Reproduce

See above.

**Comment by tmm** [comment]
This isn't something wagmi has control over unfortunately.
