### ISSUE TITLE
bug: actions can't be imported via "@wagmi/core"

### ISSUE THREAD

**Issue by norswap** [wagmi-dev/wagmi#2861]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

1.3.9

### Current Behavior

The documentation for wagmi core actions instruct to import them from "@wagmi/core". At least for me, that doesn't work, and I need to import them from "wagmi/actions" instead.

### Expected Behavior

Either ability to import from "@wagmi/core" or documentation pointing to "wagmi/actions" as the import path.

### Steps To Reproduce

Simply try the import, see attached stackblitz.

### Link to Minimal Reproducible Example (StackBlitz, CodeSandbox, GitHub repo etc.)

https://stackblitz.com/edit/new-wagmi-asmjjp?file=src%2Fmain.tsx

**Comment by tmm** [comment]
You can only import from `'@wagmi/core'` if you have it installed.

**Comment by norswap** [comment]
Two points there:
- if it's included in `wagmi` anyway, why not allow installation from there (or document that)?
- Doesn't installing `@wagmi/core` along `wagmi` cause pretty dire breakage when pnpm is used? That's what I seem to recall.

**Comment by tmm** [comment]
- The `'wagmi/actions'` entrypoint is documented here: https://wagmi.sh/react/actions
- Depends how what versions you are using and how your project is set up. The next major version should iron out some of the edge cases.

**Comment by norswap** [comment]
Sounds reasonable, missed that!
