### ISSUE TITLE
bug: args stripped from [[1n]] to [] in usePrepareContractWrite

### ISSUE THREAD

**Issue by 0xartcro** [wagmi-dev/wagmi#2872]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

1.3.9

### Current Behavior

```
ContractFunctionExecutionError: The contract function "stake" reverted with the following reason:
Must stake at least 1

Contract Call:
  address:   0x88e...
  function:  stake(uint256[] tokens)
  args:           ([])
  sender:    0x93...
```

### Expected Behavior

usePrepareContractWrite preparing write properly for a single argument

### Steps To Reproduce

```
const prepareStake = usePrepareContractWrite({
        ...contractConfig,
        functionName: 'stake',
        args: [[1n]],
        value: 1n,
    })
```

ABI:
```
  {
    "inputs": [
      {
        "internalType": "uint256[]",
        "name": "tokens",
        "type": "uint256[]"
      }
    ],
    "name": "stake",
    "outputs": [],
    "stateMutability": "payable",
    "type": "function"
  },
```

Setting an array with a single `1n` element (weirdly it works fine with any other number, 1n seems to be the only problematic one) incorrectly triggers an error thinking the array was empty. Works fine when there is 2 or more elements.

### Link to Minimal Reproducible Example (StackBlitz, CodeSandbox, GitHub repo etc.)

https://stackblitz.com/edit/new-wagmi-2t5etm

### Anything else?

Been reported here but ignored: https://github.com/wagmi-dev/viem/issues/939

Adding video from the **Minimal Reproducible Example**.
The issue occurs while selecting number 1 but works fine for number 2.

https://github.com/wagmi-dev/wagmi/assets/108104261/b3470317-b744-412b-b2cf-0a905a1d0c5f

Can use https://cronos.org/faucet to get some funds on Cronos Testnet

**Comment by tmm** [comment]
See https://github.com/wagmi-dev/viem/issues/939#issuecomment-1670456602. We aren't ignoring this, rather waiting for you to provide more info.
