### ISSUE TITLE
bug: Metamask Connector triggering other injected wallets instead of metamask

### ISSUE THREAD

**Issue by chiragpay3** [wagmi-dev/wagmi#2874]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.12.16

### Current Behavior

I am using `new MetaMaskConnector({ chains })` to connect the user to MetaMask wallet. But after installing other wallets browser extension such as Trust Wallet/ Rainbow Wallet, the user is triggered to connect to these wallets instead of metamask.

### Expected Behavior

I want the Metamask connect to only trigger metamask connect and not other wallets.

### Steps To Reproduce

1. Have only Metamask wallet in the extension.
2. Install Trust Wallet extension
3. Triggering connect through `new MetaMaskConnector({ chains })` but the Trust pop-up comes up.

### Anything else?

![Screenshot 2023-08-09 at 12 59 59 PM](https://github.com/wagmi-dev/wagmi/assets/121009923/8e04759a-2e61-4397-bcc0-99e39fac16d4)

The wagmiClient is defined like this

```
const wagmiClient = createClient({
  autoConnect: true,
  connectors: [
    new MetaMaskConnector({ chains }),
    new CoinbaseWalletConnector({
      chains,
      options: {
        appName: config?.coinbaseConnector?.appName,
      },
    }),
    new WalletConnectConnector({
      chains,
      options: {
        projectId: config?.walletConnectConnector?.projectId,
        showQrModal: config?.walletConnectConnector?.qrcode,
      },
    })
  ],
  provider,
  webSocketProvider,
})

**Comment by tmm** [comment]
Unfortunately, this is the nature of EIP-1193 injected wallets at the moment. The MetaMask connector attempts to only interface with MetaMask, but when there are multiple injected wallet, they can clash over `window.ethereum` (the underlying 1193 provider) and hijack the behavior. [EIP-6963](https://eips.ethereum.org/EIPS/eip-6963) attempts to solve this and we are excited about rolling out support in wagmi in the future.
