### ISSUE TITLE
bug: <title>为什么useContractRead  返回的数据为0n，实际上是有数据的，而且是18位

### ISSUE THREAD

**Issue by voledy** [wagmi-dev/wagmi#2875]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

1.2.0

### Current Behavior

当我使用useContractRead 通过合约接口获取余额时，返回值data为0n，实际上是有值的，不知道是不是值太长了，有19位。我猜测是值太大了，BigInt溢出导致的

### Expected Behavior

以字符串返回正常的数值过来

**Comment by tmm** [comment]
Thanks for reporting. This issue is temporarily closed due to lack of information. Please provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) and reopen this issue.
