### ISSUE TITLE
bug: Can't submit transaction to Safe Apps SDK (invalid BigNumber value)

### ISSUE THREAD

**Issue by LilaRest** [wagmi-dev/wagmi#2887]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

1.3.9

### Current Behavior

Hi, it's me again ^^

We are in the process of launching our DApp in prod and so were starting to interact with it from the Safe interface to test multisig workflow.

However, when trying to submit any transaction, the Safe Apps SDK reverts with the following error:
`Code 901: Error processing Safe Apps SDK request (invalid BigNumber value (argument="value", value=undefined, code=INVALID_ARGUMENT, version=bignumber/5.7.0))`

Note that trying to send the exact same transaction from Metamask wallet works fine.

After some investigations I figured that setting the `value` field of transactions' configs to `0n` solves this issue.

Hopefully we are using a single component `TxButton` to handle all transactions of the app.
This component accepts a preparation object as prop, so we just had to add those lines to fix the issue globally:
```ts
// @ts-ignore
if (preparation.config.request && !preparation.config.request.value) {
  // @ts-ignore
  preparation.config.request.value = 0n;
}
```

### Expected Behavior

I would expect Wagmi to default transactions values to `0n` when the used wallet is Safe.

### Anything else?

Someone opened a post on Stack Exchange about that issue 9 days ago: https://ethereum.stackexchange.com/questions/152988/problem-on-wagmi-safe-connector-sdk

**Comment by tmm** [comment]
Thanks for reporting. This issue is temporarily closed due to lack of information. Please provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) and reopen this issue.

**Comment by LilaRest** [comment]
@tmm Of course, I will. However, I'm a bit swamped at the moment. I'll try next week

**Comment by kasparkallas** [comment]
Ran into this issue as well and setting `value: 0n` was the workaround. Thanks, @LilaRest!

**Comment by stas** [comment]
Looks like a Safe issue:
https://github.com/safe-global/safe-apps-sdk/issues/480
