### ISSUE TITLE
bug: Can't use react-query devtools

### ISSUE THREAD

**Issue by amirhhashemi** [wagmi-dev/wagmi#2888]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Package Version

1.3.10

### Current Behavior

When I want to use `@tanstack/react-query-devtools` with `wagmi` I get this error in the console:
```
No QueryClient set, use QueryClientProvider to set one
```

### Expected Behavior

The devtools should work without any errors because `WagmiConfig` renders `QueryClientProvider` and `ReactQueryDevtools` should be able to access the query client.

### Steps To Reproduce

I just followed the instructions in your home page ([The overview section](https://wagmi.sh/#overview)) to setup wagmi and then added the devtools by following the react-query docs: https://tanstack.com/query/v4/docs/react/devtools

### Link to Minimal Reproducible Example (StackBlitz, CodeSandbox, GitHub repo etc.)

https://stackblitz.com/edit/vitejs-vite-eafyhb?file=package.json

### Anything else?

- I'm using `vite`

- Here is the full error:
```
QueryClientProvider.tsx:49 Uncaught Error: No QueryClient set, use QueryClientProvider to set one
    at useQueryClient (QueryClientProvider.tsx:49:5)
    at ReactQueryDevtoolsPanel2 (devtools.tsx:464:9)
    at renderWithHooks (react-dom.development.js:16305:18)
    at updateForwardRef (react-dom.development.js:19226:20)
    at beginWork (react-dom.development.js:21636:16)
    at HTMLUnknownElement.callCallback2 (react-dom.development.js:4164:14)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:4213:16)
    at invokeGuardedCallback (react-dom.development.js:4277:31)
    at beginWork$1 (react-dom.development.js:27451:7)
    at performUnitOfWork (react-dom.development.js:26557:12)
```
- Relevant dependencies:
```json
    "@tanstack/react-query": "^4.32.6",
    "@tanstack/react-query-devtools": "^4.32.6",
    "@wagmi/core": "^1.3.9",
    "react": "^18.2.0",
    "viem": "^1.6.0",
    "wagmi": "^1.3.10"
```

**Comment by StanleyDing** [comment]
The `queryClient` lives in the [context](https://github.com/wagmi-dev/wagmi/blob/main/packages/react/src/context.ts#L12) created by wagmi. `ReactQueryDevtools` uses a default context created by `react-query` themself, so the devtools can't access the `queryClient`. To fix it, wrap `<ReactQueryDevtools />` like so:

```ts
<QueryClientProvider client={queryClient} >
  <ReactQueryDevtools />
</QueryClientProvider>
```
