### ISSUE TITLE
bug: Ethers.js Adapters error

### ISSUE THREAD

**Issue by LXVC** [wagmi-dev/wagmi#2891]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

1.3.9

### Current Behavior

<img width="1066" alt="image" src="https://github.com/wagmi-dev/wagmi/assets/12185175/04cd886f-a288-4d4a-9dd6-a6dfdb97c644">
I used it according to the document https://wagmi.sh/core/ethers-adapters ,Ethers.js version is 5.7.2, but there was an error, the `transport` could not be passed to `providers.Web3Provider`

### Expected Behavior

`transport` can be passed to `providers.Web3Provider`

**Comment by tmm** [comment]
What's the error? Please attach a minimal reproduction using a [TypeScript Playground](https://www.typescriptlang.org/play).
