### ISSUE TITLE
bug: account stays logged in after refresh

### ISSUE THREAD

**Issue by fred-dinari** [wagmi-dev/wagmi#2903]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

^0.12.12

### Current Behavior

Steps to reproduce:
1. log into wagmi using a coinbase wallet
2. log out using useDisconnect.disconnect
3. refresh the page

The account is still logged in

### Expected Behavior

upon refresh, no accounts should be logged in

**Comment by tmm** [comment]
Thanks for reporting. This issue is temporarily closed due to lack of information. Please provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) and reopen this issue.
