### ISSUE TITLE
Connector Not Found 

### ISSUE THREAD

**Issue by developersubbareddy** [wagmi-dev/wagmi#2906]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

1.3.10

### Current Behavior

I am trying to switchNetwork From other network to Polygon mumbai 
  switchNetwork method throwing an issue , Connector not found 
Sample Code :
import { switchNetwork } from 'wagmi/actions'
 async function swtchNetwrk(){
    await switchNetwork({ chainId:80001 });
}
swtchNetwrk()
Error : Connector  not found

Please Help me to solve this issue

### Expected Behavior

switchNetwork Method should ask user to change network from other network to Polygon mumbai network

**Comment by jxom** [comment]
Thanks for reporting. This issue is temporarily closed due to lack of information. Please provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) via https://new.wagmi.sh and create a new issue. 

Is your wallet connected?
