### ISSUE TITLE
bug: useProvider not existed

### ISSUE THREAD

**Issue by silivex** [wagmi-dev/wagmi#2907]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

1.3.10

**Comment by jxom** [comment]
It was renamed in v1: https://wagmi.sh/react/migration-guide#useprovider

**Comment by silivex** [comment]
Okay, thank you.

**Comment by Jairwin-L** [comment]
> It was renamed in v1: https://wagmi.sh/react/migration-guide#useprovider

@jxom but it seems that no specific provider method is provided.
@silivex can you provide a sample reference?

**Comment by jxom** [comment]
Yes, that is because it was renamed to `usePublicClient`

**Comment by Jairwin-L** [comment]
> Yes, that is because it was renamed to `usePublicClient`

But when I use usePublicClient() directly, when the provider processes it, the error in the screenshot will be reported.

```ts
const publicClient = usePublicClient();
const swapPrice = new SwapPrice(publicClient);
```

<img width="361" alt="image" src="https://github.com/wagmi-dev/wagmi/assets/32570960/294a560f-e2b6-48e1-a8ee-c71d5d1caf26">
