### ISSUE TITLE
bug: usePrepareContractWrite TypeError: x.replace is not a function

### ISSUE THREAD

**Issue by DeveloperTheExplorer** [wagmi-dev/wagmi#2909]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

1.3.10

### Current Behavior

When the `enabled` boolean for `usePrepareContractWrite` is flipped to true, I get the following error from the `usePrepareContractWrite` and in the browser logs:
```
TypeError: x.replace is not a function
    at concat.ts:30:25
    at Array.reduce (<anonymous>)
    at concatHex (concat.ts:29:33)
    at concat (concat.ts:10:12)
    at encodeBytes (encodeAbiParameters.ts:210:16)
    at prepareParam (encodeAbiParameters.ts:101:12)
    at prepareParams (encodeAbiParameters.ts:68:25)
    at encodeAbiParameters (encodeAbiParameters.ts:43:26)
    at encodeFunctionData (encodeFunctionData.ts:58:9)
    at simulateContract (simulateContract.ts:124:20)
```

### Expected Behavior

Before upgrading to wagmi `1.x.x` this contract write was working properly without issues, It would trigger the wallet prompt to approve the transaction.

### Steps To Reproduce

I'm unsure what exactly is causing this error since none of our app's contract write hooks work anymore. They all result into the same error. But I suspect something in our `args` is wrong, possibly how we pass empty `bytes`.

1. Create a vite React project with **Polygon Mumbai** Network.
2. Add the following code within any component:
```ts
const [count, setCount] = useState(0);
const { config } = usePrepareContractWrite({
  address: '0x1Fd4Dc2027C1Cfae1D5a09073809f3f3F97d93dd',
  abi: [
    {
      inputs: [
        {
          internalType: "address",
          name: "from",
          type: "address",
        },
        {
          internalType: "address",
          name: "recipient",
          type: "address",
        },
        {
          internalType: "uint256",
          name: "amount",
          type: "uint256",
        },
        {
          internalType: "bytes",
          name: "data",
          type: "bytes",
        },
      ],
      name: "withdrawFrom",
      outputs: [
        {
          internalType: "uint256[]",
          name: "tokenIds",
          type: "uint256[]",
        },
        {
          internalType: "uint256[]",
          name: "amounts",
          type: "uint256[]",
        },
      ],
      stateMutability: "nonpayable",
      type: "function",
    },
  ],
  functionName: 'mint',
  args: [
    "0x77f774c6632B1CA6BD248068fBaA952355eAE2b5", // <-- you can also put your own wallet address
    "0x77f774c6632B1CA6BD248068fBaA952355eAE2b5", // <-- you can also put your own wallet address
    count,
    [] // <-- I suspect this is causing the issue, not sure what to replace it with...
  ],
  enabled: Boolean(count),
})
const { write } = useContractWrite(config)
```
3. Create an input to modify `count`.
4. As soon as `count` is bigger than 0, you should get the same error.

Ideally, this should throw a different error, saying the user has insufficient balance.

> Note: I have tried this with other contracts that should result in successful transactions, however, the outcome is still the error mentioned in this issue.

**Comment by DeveloperTheExplorer** [comment]
As I suspected the error was the formatting of `bytes`. If empty they needed be provided as an empty string.

In this case the args should be: 
```js
args: [
  "0x77f774c6632B1CA6BD248068fBaA952355eAE2b5",
  "0x77f774c6632B1CA6BD248068fBaA952355eAE2b5", 
  count,
  '' // <-- '' instead of []
]
```

**Comment by jeraldgan** [comment]
@DeveloperTheExplorer thank you, this helped me a lot 👍
