### ISSUE TITLE
bug: Type error: Type parameter declaration expected

### ISSUE THREAD

**Issue by sasuke0601** [wagmi-dev/wagmi#2915]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

1.3.10

### Current Behavior

I got an error at building my **Next.js** app.
```sh
./node_modules/viem/dist/types/cliets/createClient.d.ts:37:14
Type error: Type parameter declaration expected.
```

![Screenshot_5](https://github.com/wagmi-dev/wagmi/assets/99005797/0956ac5f-df88-469d-a066-2781b9b91fed)

- Node Version: ``v16.15.1``
- Next.js: ``13.2.4``

Please help me. 🙏
Thanks.

**Comment by tmm** [comment]
Thanks for reporting. This issue is temporarily closed due to lack of information. Please provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) and reopen this issue.
