### ISSUE TITLE
bug: wagmi doesn't work when I'm building

### ISSUE THREAD

**Issue by JacopoNeroni** [wagmi-dev/wagmi#2916]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

1.3.9

### Current Behavior

I developed a dapp using create-react-app, and when I launch it with 'npm start', everything works perfectly. However, when I go to 'npm run build' and deploy it on the server, it no longer communicates with the blockchain.

The dapp utilizes the following dependencies: 
    "@testing-library/jest-dom": "^5.17.0",
    "@testing-library/react": "^13.4.0",
    "@testing-library/user-event": "^13.5.0",
    "@web3modal/ethereum": "^2.7.1",
    "@web3modal/react": "^2.7.1",
    "axios": "^1.4.0",
    "bignumber.js": "^9.1.1",
    "bootstrap": "^5.3.1",
    "ethers": "^5.7.2",
    "react": "^18.2.0",
    "react-bootstrap": "^2.8.0",
    "react-dom": "^18.2.0",
    "react-scripts": "5.0.1",
    "viem": "^1.5.3",
    "wagmi": "^1.3.9",
    "web-vitals": "^2.1.4"

### Expected Behavior

I expect that once the dapp is built, it communicates with the contract on the blockchain, just like it does when using 'npm start'.

### Link to Minimal Reproducible Example (StackBlitz, CodeSandbox, GitHub repo etc.)

https://www.busdrace.com

### Anything else?

![Screenshot 2023-08-18 alle 10 56 51](https://github.com/wagmi-dev/wagmi/assets/95048349/e7e42212-1250-4c31-ac84-32c849b84f9a)

**Comment by tmm** [comment]
Thanks for reporting. This issue is temporarily closed due to lack of information. Please provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) and reopen this issue.

**Comment by JacopoNeroni** [comment]
this is a full example https://www.busdrace.com/

**Comment by tmm** [comment]
It must be a minimal reproduction:

- Minimal: Use as little code as possible that still produces the same problem
- Complete: Provide all parts someone else needs to reproduce your problem in the question itself
- Reproducible: Test the code you're about to provide to make sure it reproduces the problem

You should also include some info about the error you are running into and instructions on how to reproduce.

**Comment by 0xvidejk** [comment]
seems like you need to specify browser list which are compatible with native JS bigint


if you are using Create React App
_replace browsersList property with this one_

 "browserslist": {
    "production": [
      "chrome >= 67",
      "edge >= 79",
      "firefox >= 68",
      "opera >= 54",
      "safari >= 14"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  }

**Comment by ikaz-jem** [comment]
> seems like you need to specify browser list which are compatible with native JS bigint
> 
> if you are using Create React App _replace browsersList property with this one_
> 
> ```
> 
> "browserslist": {
>     "production": [
>       "chrome >= 67",
>       "edge >= 79",
>       "firefox >= 68",
>       "opera >= 54",
>       "safari >= 14"
>     ],
>     "development": [
>       "last 1 chrome version",
>       "last 1 firefox version",
>       "last 1 safari version"
>     ]
>   }
> ```
> 
> hope it helps.

i had the same issue cannot read or write contract but this helped me thanks a lot
