### ISSUE TITLE
Incompatible transport object

### ISSUE THREAD

**Issue by emiridbest** [wagmi-dev/wagmi#2923]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

v2

### Current Behavior

Argument of type 'TransportConfig<string, { (args: { method: "web3_clientVersion"; params?: undefined; }): Promise<string>; (args: { method: "web3_sha3"; params: [data: `0x${string}`]; }): Promise<string>; (args: { ...; }): Promise<...>; (args: { ...; }): Promise<...>; (args: { ...; }): Promise<...>; (args: { ...; }): Promise<...>; (...' is not assignable to parameter of type 'ExternalProvider | 

### Steps To Reproduce

import * as React from 'react'
import { type PublicClient, usePublicClient, type WalletClient, useWalletClient } from 'wagmi'
import { providers } from 'ethers'
import { type HttpTransport } from 'viem'

function publicClientToProvider(publicClient: PublicClient) {
   const { chain, transport } = publicClient
   const network = {
   	chainId: chain.id,
   	name: chain.name,
   	ensAddress: chain.contracts?.ensRegistry?.address,
   }
   if (transport.type === 'fallback')
   	return new providers.FallbackProvider(
       	(transport.transports as ReturnType<HttpTransport>[]).map(
           	({ value }) => new providers.JsonRpcProvider(value?.url, network),
       	),
   	)
   return new providers.JsonRpcProvider(transport.url, network)
}

/** Hook to convert a viem Public Client to an ethers.js Provider. */
export function useEthersProvider({ chainId }: { chainId?: number } = {}) {
   const publicClient = usePublicClient({ chainId })
   return React.useMemo(() => publicClientToProvider(publicClient), [publicClient])
}

function walletClientToSigner(walletClient: WalletClient) {
   const { account, chain, transport } = walletClient
   const network = {
   	chainId: chain.id,
   	name: chain.name,
   	ensAddress: chain.contracts?.ensRegistry?.address,
   }
   const provider = new providers.Web3Provider(transport, network)
   const signer = provider.getSigner(account.address)
   return signer
}

/** Hook to convert a viem Wallet Client to an ethers.js Signer. */
export function useEthersSigner({ chainId }: { chainId?: number } = {}) {
   const { data: walletClient } = useWalletClient({ chainId })
   return React.useMemo(
   	() => (walletClient ? walletClientToSigner(walletClient) : undefined),
   	[walletClient],
   )
}

### Link to Minimal Reproducible Example (StackBlitz, CodeSandbox, GitHub repo etc.)

https://github.com/emiridbest/celoPets

### Anything else?

The error is preventing DApps from deploying on vercel

**Comment by tmm** [comment]
Thanks for reporting. This issue is temporarily closed due to lack of information. Please provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) and reopen this issue.
