### ISSUE TITLE
bug: Create React App: Conflicting peer dependency: typescript@5.1.6

### ISSUE THREAD

**Issue by DudleDev** [wagmi-dev/wagmi#2925]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

last

### Current Behavior

```
npm ERR! Conflicting peer dependency: typescript@5.1.6
npm ERR! node_modules/typescript
npm ERR!   peerOptional typescript@">=5.0.4" from @wagmi/core@1.3.9
npm ERR!   node_modules/@wagmi/core
```

### Expected Behavior

installation without errors

### Steps To Reproduce

npm install -g create-react-app
npx create-react-app .
npm install @web3modal/ethereum @web3modal/react wagmi viem

**Comment by tmm** [comment]
Create React App is deprecated so we don't support it anymore. I would look into using [Vite](https://vitejs.dev/guide/#scaffolding-your-first-vite-project) instead. Wagmi's version range [supports TypeScript 5.1.6](https://github.com/wagmi-dev/wagmi/blob/main/packages/react/package.json#L112) so not sure what's going on here.
