### ISSUE TITLE
bug: Base chain missing from wagmi.chains v0.12.x

### ISSUE THREAD

**Issue by jtardioli** [wagmi-dev/wagmi#2927]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.12.18

### Current Behavior

on versions 0.12.18 (latest of 0.12.x) we are missing the base chain from the wagmi/chains file

![Screenshot 2023-08-23 at 12 18 47 PM](https://github.com/wagmi-dev/wagmi/assets/85530348/01613611-840d-441d-aac7-9f21ecc722e7)

### Expected Behavior

Should be a chain called `base` exported from the file

### Steps To Reproduce

download wagmi at version 0.12.18 and go to the wagmi/chains file

### Link to Minimal Reproducible Example (StackBlitz, CodeSandbox, GitHub repo etc.)

https://stackblitz.com/edit/new-wagmi-hl2xru?file=src%2Fmain.tsx

**Comment by tmm** [comment]
`0.12.x` versions only receive security or important updates (e.g. WalletConnect v2). You can install `@wagmi/chains` directly to get the latest chains.
