### ISSUE TITLE
bug: Getting this in sentry c(...).then(...).catch(...).finally is not a function from walletconnect

### ISSUE THREAD

**Issue by bigint** [wagmi-dev/wagmi#2948]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

latest

### Current Behavior

Getting this in sentry c(...).then(...).catch(...).finally is not a function from walletconnect

### Expected Behavior

The error should be handled

### Steps To Reproduce

https://sentry.lenster.xyz/share/issue/0d4aa6d9ee8f403e816f0a873aa3483e/

### Anything else?

Walletconnect team told that wagmi is using 2.9.2 but those errors are fixed in WC 2.10.0 🙇🏼

**Comment by bigint** [comment]
cc @jxom 🙇🏼

**Comment by tmm** [comment]
You can use the latest `@wagmi/connectors` package for WalletConnect updates.
