### ISSUE TITLE
Documentation uses undefined variable

### ISSUE THREAD

**Issue by fulldecent** [wagmi-dev/wagmi#2968]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

website

### Current Behavior

On the page https://wagmi.sh/core/actions/writeContract reference is made to a variable `wagmigotchiABI`.

And a mention is made to the Etherscan like for some contract.

But instead, I was looking to see the actual contents of the `wagmigotchiABI`. Is it using Ethers.js style ABI definition like 

```
[ "function getValue() returns uint256" ]
```

or is it using the web3js version that is like 50 lines long?

This could please be specified in the documentation.

### Expected Behavior

Docs are more clear

**Comment by tmm** [comment]
JSON ABI. If you want to use human-readable ABIs, check out `parseAbi` from Viem.

**Comment by fulldecent** [comment]
Thank you for the explanation. I am hoping that this can please be in the docs.

I am learning a lot about WalletConnect Web3Modal and WAGMI, but learning currently requires reading docs and getting answers in the issues. I hope this issue can stay open to improve the docs so it is no longer necessary to interact on issues to get the full picture.

**Comment by tmm** [comment]
Working on new docs currently and this is included.

**Comment by fulldecent** [comment]
Cool thank you. Looking forward to it
