### ISSUE TITLE
bug: `wagmi/cli` uses local `prettier` config and plugins, even if the local `prettier` version doesn't match the one from `wagmi/cli`

### ISSUE THREAD

**Issue by allezxandre** [wagmi-dev/wagmi#2971]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

1.5.0

### Current Behavior

On a project with `prettier` v3, `wagmi/cli` will run its own bundled `prettier` v2, but will still load the local prettier configuration and plugins, potentially breaking the `generate` command if anything works with `prettier` v3 but not v2.

One such example is the `prettier-plugin-tailwindcss` plugin that was updated to v3 recently:

```bash
$ wagmi generate
✔ Validating plugins
✔ Resolving contracts
✔ Running plugins
⠋ Writing to [...]/generated/index.ts
require() of ES Module ./node_modules/.pnpm/prettier-plugin-tailwindcss@0.5.4_prettier-plugin-svelte@3.0.3_prettier@3.0.3/node_modules/prettier-plugin-tailwindcss/dist/index.mjs not supported.
Instead change the require of ./node_modules/.pnpm/prettier-plugin-tailwindcss@0.5.4_prettier-plugin-svelte@3.0.3_prettier@3.0.3/node_modules/prettier-plugin-tailwindcss/dist/index.mjs to a dynamic import() which is available in all CommonJS modules.
```

### Expected Behavior

The culprit appears to be the following `format` method: 
https://github.com/wagmi-dev/wagmi/blob/c14c41651c4e90342ad22ca0cbbc1e1780cb47a1/packages/cli/src/utils/format.ts#L3-L20 

I'm not sure what would be the better course of action here. The responsibility of formatting code could be left to the end user to prevent this issue from happening in the future, or the CLI could be upgraded to accept `prettier` v3.

**Comment by oxSaturn** [comment]
Just ran into the same problem.

Currently I'm working around it with `resolutions` in `package.json` if you're using `yarn` or `pnpm`:

```
"resolutions": {
    "prettier": "^3.0.3"
  }
```

**Comment by tmm** [comment]
If someone wants to open a PR, overriding plugins to an empty array [here](https://github.com/wagmi-dev/wagmi/blob/main/packages/cli/src/utils/format.ts#L18) should work:
