### ISSUE TITLE
bug:  wagmi/cli generate Invalid ABI for contract: Invalid at `[2].outputs[0].type`

### ISSUE THREAD

**Issue by sherpya** [wagmi-dev/wagmi#2974]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

1.3.10

### Current Behavior

I'm trying to generate abi using an hardhat project, it worked find but broken when I added SafeTransfer.sol library,
but generate fails with:

```
Invalid ABI for contract "SafeTransfer"
- Invalid at `[2].outputs[0].type`
```

the error (from zod)
```
ZodError: [
  {
    "validation": "regex",
    "code": "invalid_string",
    "message": "Invalid",
    "path": [
      2,
      "outputs",
      0,
      "type"
    ]
  }
]
    at get error [as error] (/home/sherpya/workspace/web3/chainraise-web/node_modules/zod/lib/index.mjs:537:31)
    at ZodArray.parseAsync (/home/sherpya/workspace/web3/chainraise-web/node_modules/zod/lib/index.mjs:659:22)
    at async getContract (/home/sherpya/workspace/web3/chainraise-web/node_modules/@wagmi/cli/dist/commands-IGLZ47TT.js:265:11)
    at async generate (/home/sherpya/workspace/web3/chainraise-web/node_modules/@wagmi/cli/dist/commands-IGLZ47TT.js:103:24)
    at async CAC.<anonymous> (/home/sherpya/workspace/web3/chainraise-web/node_modules/@wagmi/cli/dist/cli.js:15:3)
    at async file:///home/sherpya/workspace/web3/chainraise-web/node_modules/@wagmi/cli/dist/cli.js:32:5 {issues: Array(1), addIssue: ƒ, addIssues: ƒ, name: 'ZodError', stack: 'ZodError: [
  {
    "validation": "regex",
  …-web/node_modules/@wagmi/cli/dist/cli.js:32:5'}
  ```

### Expected Behavior

generate the abi file

### Steps To Reproduce

create any wagmi project:

```typescript
import { defineConfig } from '@wagmi/cli';
import { hardhat } from '@wagmi/cli/plugins';

export default defineConfig({
    out: 'gen/abi.ts',
    plugins: [
        hardhat({
            project: '../chainraise'
        }),
    ]
});
```

### Link to Minimal Reproducible Example (StackBlitz, CodeSandbox, GitHub repo etc.)

https://github.com/sherpya/chainraise
https://github.com/sherpya/chainraise-web

**Comment by tmm** [comment]
Can you share what the `SafeTransfer` ABI? Once I have that I can look into it.

**Comment by sherpya** [comment]
[SafeTransfer.zip](https://github.com/wagmi-dev/wagmi/files/12525194/SafeTransfer.zip)

**Comment by sherpya** [comment]
[SafeTransfer.json.txt](https://github.com/wagmi-dev/wagmi/files/12525392/SafeTransfer.json.txt)

renamed .txt, github does not allow json

**Comment by tmm** [comment]
In the ABI, `"type": "IERC20"` is not a valid [elementary type](https://docs.soliditylang.org/en/latest/abi-spec.html#types).

```json
{
  "inputs": [],
  "name": "NATIVE_TOKEN",
  "outputs": [
    {
      "internalType": "contract IERC20",
      "name": "",
      "type": "IERC20"
    }
  ],
  "stateMutability": "view",
  "type": "function"
}
```

**Comment by sherpya** [comment]
> 

isn't the abi generated by solc?

**Comment by sherpya** [comment]
so do I need to bugreport somewhere else?

**Comment by tmm** [comment]
I'd gather some info about why solc or another tool is generating that ABI, then come back here with the info.

**Comment by gte620v** [comment]
@sherpya you can fix this by not having any public functions on the library.  you have `IERC20 public constant NATIVE_TOKEN = IERC20(address(0));`. public functions on a library imply that the library will be deployed to its own contract and thus gets its own abi.  

You probably dont need `SafeTransfer` be an external library and you don't need a trivial value like `address(0)` to be a public.  Or, if you do, put that value on a contract instead of in a library.

If a library only has internal functions, then no abi file will be created and you will not have this wagmi problem.
