### ISSUE TITLE
Error in docs for watchBlockNumber

### ISSUE THREAD

**Issue by sunmer** [wagmi-dev/wagmi#2981]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

1.3.9

### Current Behavior

Property `listen` is not an optional argument - contrary to what the docs say
https://github.com/wagmi-dev/wagmi/blob/5e4bc8e26aa9bfc28f654c2d01a38c8d1d7ecc4e/docs/pages/core/actions/watchBlockNumber.en-US.mdx#L52

**Comment by tmm** [comment]
Easy fix if you want credit! PR welcome.

**Comment by SrijanShovit** [comment]
Hey @sunmer and @tmm Can I work on this issue?

**Comment by tmm** [comment]
Go got it!

**Comment by SrijanShovit** [comment]
Hi @tmm when I try to run a react app after installing wagmi, it gives No wagmi config found. Ensure you have set up a config: https://wagmi.sh/react/config.
Could you please help me?

**Comment by glitch-txs** [comment]
@SrijanShovit you need to wrap you app with this https://wagmi.sh/react/WagmiConfig

**Comment by SrijanShovit** [comment]
Thanks @glitch-txs

**Comment by SrijanShovit** [comment]
Hey @tmm , I have made a pull request for this issue as PR #2990 . Kindly review. Thanks!!

**Comment by SrijanShovit** [comment]
thanks @tmm 😊
