### ISSUE TITLE
Cannot read properties of undefined (reading 'forEach')

### ISSUE THREAD

**Issue by liu-xin-xin** [wagmi-dev/wagmi#2983]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

^1.4.1

### Current Behavior

react项目本地编译的时候 突然控制台出错 Cannot read properties of undefined (reading 'forEach')
这是一个偶发性的错误 不是一直出现

### Expected Behavior

希望不出错

### Steps To Reproduce

![微信图片_20230908011604](https://github.com/wagmi-dev/wagmi/assets/71886858/f86f2c4c-72f0-42b2-b7a6-c6bb91706c82)

### Anything else?

![微信图片_20230908011604](https://github.com/wagmi-dev/wagmi/assets/71886858/6466505f-2e54-49fc-92c8-4e36768ae3d4)
![微信图片_20230908011613](https://github.com/wagmi-dev/wagmi/assets/71886858/76446dce-06b8-436c-bbee-eed3196f90de)

**Comment by tmm** [comment]
Thanks for reporting. This issue is temporarily closed due to lack of information. Please provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) and reopen this issue.
