### ISSUE TITLE
bug: passing `blockNumber` to `useContractRead` does not have any effect

### ISSUE THREAD

**Issue by hfa0** [wagmi-dev/wagmi#2984]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

1.3.11

### Current Behavior

Passing `blockNumber` to `useContractRead` doesn't have any effect.
Error in console
![image](https://github.com/wagmi-dev/wagmi/assets/46442988/c8443065-c983-4f74-a7b7-927271e88745)

### Expected Behavior

`blockNumber` is considered in the query

### Steps To Reproduce

```ts
call `useContractRead` passing any past blocknumber 

```

### Link to Minimal Reproducible Example (StackBlitz, CodeSandbox, GitHub repo etc.)
https://codesandbox.io/s/react-wagmi-example-k23ctx?file=/src/App.js

**Comment by tmm** [comment]
Thanks for reporting. This issue is temporarily closed due to lack of information. Please provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) and reopen this issue.

**Comment by hfa0** [comment]
added minimal example. please reopen

**Comment by jxom** [comment]
`blockNumber` needs to be a bigint, and not a string.

**Comment by hfa0** [comment]
already tried `BigInt`. still not working.
