### ISSUE TITLE
bug: Wagmi's `usePrepareContractWrite` does not include value property when the documentation says it includes

### ISSUE THREAD

**Issue by hskang9** [wagmi-dev/wagmi#2986]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.12.19

### Current Behavior

https://wagmi.sh/react/prepare-hooks/usePrepareContractWrite includes value(Optional) property where it includes eth value to be sent with contract interaction. However, the wagmi version 0.12.19 does not do that.

### Expected Behavior

the hook must include value property on its returned data variable from the hook.

### Steps To Reproduce

1. install wagmi 0.12.19

2. declare the hook
```
import { usePrepareContractWrite } from "wagmi";
 // limit order native variables
  const { config: limitBuyETHConfig, error: limitBuyETHError } =
    usePrepareContractWrite({
      abi: MatchingEngineABI,
      address: matchingEngine,
      chainId: chainId,
      functionName: "limitBuyETH",
      value: ethers.utils.parseEther(roundToThirdDecimal(qAmount).toString()),
      args: [
        base.contract_address,
        ethers.utils.parseUnits(roundToThirdDecimal(limitPrice).toString(), 8),
        true,
        5,
        0,
      ],
    });
 ```
    
   3. Watch value property missing after console.log(limitBuyETHConfig)
   
  Or just watch the codebase which is missing value property in index.d.ts
  ```
  declare function usePrepareContractWrite<TAbi extends Abi | readonly unknown[], TFunctionName extends string, TChainId extends number>({ address, abi, functionName, chainId, args, overrides, cacheTime, enabled, scopeKey, staleTime, suspense, onError, onSettled, onSuccess, }?: UsePrepareContractWriteConfig<TAbi, TFunctionName, TChainId>): Pick<_tanstack_react_query.QueryObserverResult<PrepareWriteContractResult<TAbi, TFunctionName, TChainId>, Error>, "data" | "error" | "isError" | "isLoading" | "isSuccess" | "isFetched" | "isFetchedAfterMount" | "isFetching" | "isRefetching" | "refetch" | "fetchStatus"> & {
    isIdle: boolean;
    status: "error" | "success" | "loading" | "idle";
    internal: Pick<_tanstack_react_query.QueryObserverResult<unknown, unknown>, "isLoadingError" | "isRefetchError" | "dataUpdatedAt" | "errorUpdatedAt" | "failureCount" | "isPaused" | "isPlaceholderData" | "isPreviousData" | "isStale" | "remove">;
} & {
    config: PrepareWriteContractResult<TAbi, TFunctionName, TChainId>;
};
```
  

### Anything else?

**Why would you use Typescript when you cannot even add existing functions you declared in the documentation nor strongly define types that are used in library functions?**
Current v1 even misses out the features v0 provided.

**Comment by tmm** [comment]
Thanks for reporting. This issue is temporarily closed due to lack of information. Please provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) and reopen this issue.

**Comment by hskang9** [comment]
no, I am not providing minimal reproducible example, it is what Typescript was built for, and you do not understand it.

**Comment by hskang9** [comment]
This code has never tested a payable function, and it does not properly populate contract methods without any native arguments.

**Comment by tmm** [comment]
@hskang9 Providing a minimal reproduction helps us help you. We generally don't pick up issues without them. See [Why Reproductions are Required](https://antfu.me/posts/why-reproductions-are-required) for more info.

**Comment by backseats** [comment]
I'm also experiencing this in `wagmi@0.11.7`

```
  const { config, error, isError } = usePrepareContractWrite({
    address: airdropContractAddress,
    abi,
    functionName: 'airdropERC721',
    args: [
      tokenAddress,
      recipients.map(({ address }) => address),
      recipients.map(({ amount }) => amount),
    ],
    enabled: true, //!!address && enabled,
    chainId,
    value: BigNumber.from('0')
  });
  ```

> Object literal may only specify known properties, and 'value' does not exist in type 'UsePrepareContractWriteConfig

**Comment by hskang9** [comment]
@tmm  using Typescript means it has strongly typed compiler to check undefined property from existing types in Ethers.js, not making another confusing client library with useless type gymnastics like Viem. See [Why Typescript was made](https://www.typescriptlang.org/why-create-typescript).

**Comment by hskang9** [comment]
> @hskang9 Providing a minimal reproduction helps us help you. We generally don't pick up issues without them. See [Why Reproductions are Required](https://antfu.me/posts/why-reproductions-are-required) for more info.

I would rather fork this library and start a new with covering tests in existing Ethers.js type first, then wrap up with Typescript. This library will always be not available for executing payable contract method as you can't even find what's wrong, and I just do not want to work with these dishonest, useless people who focuses on type gymnastics over real use cases.

**Comment by hskang9** [comment]
I genuinely hope this typescript code becomes obsolete and don't see useless ppl anymore in rooftop saying that they use Typescript hence they are better without even knowing why it exists.

**Comment by hskang9** [comment]
> I'm also experiencing this in `wagmi@0.11.7`
> 
> ```
>   const { config, error, isError } = usePrepareContractWrite({
>     address: airdropContractAddress,
>     abi,
>     functionName: 'airdropERC721',
>     args: [
>       tokenAddress,
>       recipients.map(({ address }) => address),
>       recipients.map(({ amount }) => amount),
>     ],
>     enabled: true, //!!address && enabled,
>     chainId,
>     value: BigNumber.from('0')
>   });
> ```
> 
> > Object literal may only specify known properties, and 'value' does not exist in type 'UsePrepareContractWriteConfig

Thanks for speaking up! this is the minimal example we should need with editor picture with red line on `value`.

**Comment by jxom** [comment]
You are using 0.12.x. Please refer to those docs, not the v1 docs: https://0.12.x.wagmi.sh/react/prepare-hooks/usePrepareContractWrite#overrides-optional

**Comment by jxom** [comment]
> Also, Viem is not testing payable contract method too

We do test that actually: https://github.com/wagmi-dev/viem/blob/main/src/actions/wallet/writeContract.test.ts#L149

**Comment by hskang9** [comment]
> You are using 0.12.x. Please refer to those docs, not the v1 docs: https://0.12.x.wagmi.sh/react/prepare-hooks/usePrepareContractWrite#overrides-optional

ah what? jesus christ my time. ok I am a dick.
