### ISSUE TITLE
{context: 'core'} {context: 'core/verify-api'} 'Verify iframe failed to load: https://verify.walletconnect.org'

### ISSUE THREAD

**Issue by liu-xin-xin** [wagmi-dev/wagmi#2998]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

"viem": "^1.10.9",     "wagmi": "^1.4.1",

### Current Behavior

添加WalletConnectConnector连接器的时候 浏览器控制台报错   {context: 'core'} {context: 'core/verify-api'} 'Verify iframe failed to load: https://verify.walletconnect.org'

### Anything else?

![微信图片_20230912112701](https://github.com/wagmi-dev/wagmi/assets/71886858/00bab1a9-f772-4077-a232-20a8eaf7301a)

**Comment by glitch-txs** [comment]
Hi, this issue is related to WalletConnect and not Wagmi, please refer to [issue](https://github.com/WalletConnect/walletconnect-monorepo/issues/3500#issuecomment-1714905385)

**Comment by liu-xin-xin** [comment]
> 



> 您好，此问题与 WalletConnect 相关，与 Wagmi 关联，请参阅[问题](https://github.com/WalletConnect/walletconnect-monorepo/issues/3500#issuecomment-1714905385)
您好，这个与WalletConnect 相关的问题 现在有解决吗  我是在开发环境(http://localhost:3000/)遇到的
