### ISSUE TITLE
bug: switchNetwork request sent twice to MetaMask

### ISSUE THREAD

**Issue by thomasvalera** [wagmi-dev/wagmi#2999]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

1.4.1

### Current Behavior

Hey all!

I have a weird issue using `switchNetwork` from the `useSwitchNetwork` hook where the switch request popup is shown twice instead of once! 

At first I thought it might have to do with the modal library I used but it happens on both RainbowKit and Web3Modal from WalletConnect.

So, the bug goes as follows:

When MetaMask is locked and the user unlocks/connects using WalletConnect's modal I need to ensure the right chain is connected. So once `useAccount.onConnect` is triggered I call `switchNetwork`.

The call is made only once but MetaMask shows 2 popups to switch chain. Which is weird and confusing to the users.

Here is the code I use:

```JavaScript
const { open } = useWeb3Modal();

const { address } = useAccount({
  onConnect: async ({ address, connector }) => {
    if (state === ConnectionState.OPENING_MODAL && address) {
      const newChainId = await connector?.getChainId();

      if (newChainId === BLOCKCHAIN_ID) {
        props.continue()
      } else {
        connectToNetwork();
      }
    }
  },
});

const { switchNetwork } = useSwitchNetwork({
  onSuccess: (data, args) => {
    props.onConnected()
  },
  onError: (error) => {
    props.onConnectionError?.(error);
  },
});

// Entry point, this is the function that is called from component
function connect() {
  // If not connected
  if (!address) {
    setState(ConnectionState.OPENING_MODAL);
    open();

    // If chain not connected
  } else if (!chain || chain.id !== BLOCKCHAIN_ID) {
    connectToNetwork();

    // If connected
  } else {
    props.onConnected()
  }
}


function connectToNetwork() {
  setState(ConnectionState.SWITCHING_CHAIN);
  switchNetwork?.(BLOCKCHAIN_ID);
}
```

Any ideas how this happens?

EDIT:

I've noticed that if I add a delay before calling `switchNetwork` it only shows once!!
But that doesn't really solve the core of the problem which I'd still like to do.

The delay looks like this:
```
setTimeout(() => {
      switchNetwork?.(BLOCKCHAIN_ID);
    }, 1000);
```

### Expected Behavior

When `switchNetwork` is called right after unlocking MetaMask, the popup to switch network in MetaMask should only show once.

### Steps To Reproduce

1. In MetaMask, switch to another network that is not the one you want.
2. Lock MetaMask
3. Connect to MetaMask using modal
4. Enter the MetaMask password
5. Two popups to switch network are displayed!

**Comment by tmm** [comment]
Thanks for reporting. This issue is temporarily closed due to lack of information. Please provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) and reopen this issue.
