### ISSUE TITLE
bug: When the sign message is called in the combination of walletconnect + metamask-mobile + mobile device, it is called to unconditionally switch the chain to the ethereum mainnet.

### ISSUE THREAD

**Issue by siosio34** [wagmi-dev/wagmi#3002]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

1.3.9 / viem: 1.10.8

### Current Behavior

When the sign message is called in the combination of walletconnect + metamask-mobile + mobile device, it is called to unconditionally switch the chain to the ethereum mainnet.

### Expected Behavior

I want to call only signMessage without the chain conversion modal appearing on the Ethereum mainnet.

### Steps To Reproduce

https://wagmi.sh/examples/sign-message

0. Click the link above on your mobile device to open it. 
1. Connect to any chain except the Ethereum mainnet.
2.  click sign message button
3.  Then, the signing modal should appear, but then the network switching modal will appear.

### Link to Minimal Reproducible Example (StackBlitz, CodeSandbox, GitHub repo etc.)

https://wagmi.sh/examples/sign-message

**Comment by glitch-txs** [comment]
Hi this is related to MetaMask's WalletConnect implementation. See https://github.com/MetaMask/metamask-mobile/issues/7138

**Comment by siosio34** [comment]
@glitch-txs @tmm 

Hello, even after reading the issue, I still don't understand why the issue I posted is closed.

Can I understand that the modal popping up asking me to switch to the Ethereum chain when doing signMessage is because MetamaskMobile does not handle WalletConnect?

What should I do to prevent unnecessary chain switch modal from appearing when calling signMessage on mobile?

**Comment by glitch-txs** [comment]
hi @siosio34, I think the reason this issue was closed is because Wagmi has no power over MetaMask implementation of WalletConnect, I think this should be opened in MetaMask repo instead

**Comment by siosio34** [comment]
@glitch-txs thanks  !!
