### ISSUE TITLE
bug: Unsupported method "eth_signtypeddata_v4" with WalletConnect & Trust Wallet

### ISSUE THREAD

**Issue by niratodev** [wagmi-dev/wagmi#3012]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

1.4.2

### Current Behavior

When signing typed data connected via WalletConnect (Trust Wallet) an error is thrown.
```
Unsupported method "eth_signtypeddata_v4" 
```

### Expected Behavior

You can use `eth_signtypeddata_v4`

### Steps To Reproduce

Try to use `useSignTypedData`

### Link to Minimal Reproducible Example (StackBlitz, CodeSandbox, GitHub repo etc.)

https://github.com/niratodev/wagmi-walletconnect-trust-wallet-no-method

### Anything else?

Apologies if Wagmi is not the source of the issue. I have searched and cannot pinpoint the source, so I am starting here. All indications point to: 
1. `eth_signtypeddata_v4` is supported
2. Wagmi creates the provider and includes the optional methods

**Comment by glitch-txs** [comment]
Hi, this issue is related to WalletConnect namespaces, this happens when you use only one chain, in the configuration you can try as workaround something like

```ts
const chains = [mainnet, mainnet]

const connector = new WalletConnectConnector({
  chains,
  options: {
    projectId: import.meta.env.VITE_WC_PROJECT_ID,
  },
});
```

Placing it directly in the `WallletConnectConnector` and not through the `configureChains` function.

This will be fixed once we go full optional namespaces.

**Comment by niratodev** [comment]
No freakin way. How did you figure that out?

**Comment by TheJuze** [comment]
Hi, i'm having same issue but multiple chains already passed (`[mainnet, bsc, okc, polygon, fantom]`). So any other ideas how to fix that?
"@wagmi/core": "^1.4.12"

**Comment by glitch-txs** [comment]
@TheJuze with which wallet? Can you share repro steps?

**Comment by TheJuze** [comment]
> @TheJuze with which wallet? Can you share repro steps?

Trust wallet. Repro steps:
1. Connect to WC with TrustWallet
2. Change network to mainnet
3. call signTypedData
4. get error `Unsupported method "eth_signtypeddata_v4" `
