### ISSUE TITLE
bug: Wagmi v2 Alpha

### ISSUE THREAD

**Issue by glitch-txs** [wagmi-dev/wagmi#3016]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

2

### Current Behavior

loving it so far!

Some small issues I ran into:

- `useSyncExternalStore` seems to be lacking the `getServerSnapshot` param so I'm getting the following error on Next.js when using some hooks:

`Error: Missing getServerSnapshot, which is required for server-rendered content. Will revert to client rendering.`

- WalletConnectConnector gets initialized on server side on Next.js which causes this error on console

`Error: To use WalletConnect server side, you'll need to install the "lokijs" dependency. If you are seeing this error during a build / in an SSR environment, you can add "lokijs" as a devDependency to make this error go away.`

Maybe init function can be conditinated to only run on client side?

Thanks!

### Link to Minimal Reproducible Example (StackBlitz, CodeSandbox, GitHub repo etc.)

https://github.com/glitch-txs/wagmi-v2-alpha-test

**Comment by tmm** [comment]
Thanks for checking the alpha out! `wagmi@2.0.0-alpha.3` is released and fixes both these things. (I tested it out with your repo.)

**Comment by glitch-txs** [comment]
Cool! Just one small thing, connectors type seems to be `Evaluate<any>` which gives an error
![image](https://github.com/wagmi-dev/wagmi/assets/66949816/70aa33be-8e3d-4889-991c-db14231665d7)

**Comment by tmm** [comment]
Interesting! Will check that out.
