### ISSUE TITLE
bug: ABI encoding params/values length mismatch usePrepareContractWrite

### ISSUE THREAD

**Issue by sagaratalatti** [wagmi-dev/wagmi#3026]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

1.4.1

### Current Behavior

Using `usePrepareContractWrite` function with `useContractWrite` to write data to the contract throws error 

❌ **Error: ABI encoding params/values length mismatch. Expected length (params): 2 Given length (values): 0**

I am using default OpenZeppelin ERC721 contract and importing erc721ABI from wagmi. 

### Expected Behavior

Following the wagmi documentation for usePrepareContractWrite should've worked as intended.

### Steps To Reproduce

```
const { config } = usePrepareContractWrite({
        ...testContractConfig,
        functionName: 'setApprovalForAll',
    });

const { data, write } = useContractWrite(config);

const getPermission = async () => {
        if (write) {
            write({
                args: [BatchTransferAddress, true],
                from: address
            })
        }
    }    
```
**TestContractConfig** 

```
import { erc721ABI } from "wagmi";

export const testContractConfig = {
    address: '0x07a06AD39f940a505B306b294b29390e792C3869', 
    abi: erc721ABI
}
```

And the 

### Anything else?

When I only implement `useContractWrite` with the same ABI everything works fine.

**Comment by tmm** [comment]
Thanks for reporting. This issue is temporarily closed due to lack of information. Please provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) and reopen this issue.

**Comment by sagaratalatti** [comment]
Here's the code published: https://github.com/sagaratalatti/drainz/tree/main/frontend
