### ISSUE TITLE
bug: `useContractEvent`: event listeners never fire

### ISSUE THREAD

**Issue by firnprotocol** [wagmi-dev/wagmi#3033]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

1.4.2

### Current Behavior

on the chain Base, `useContractEvent` is completely silent; `onLogs` refuses to fire even when events are emitted. all other chains I've tried work fine.

runnable MWE: https://github.com/firnprotocol/wagmi-v1-example: observe that no USDC transfers get fired. (`npm install`; `npm run dev`)

### Expected Behavior

should trigger listener.

### Steps To Reproduce

run my MWE; observe that "Watch Contract Events" stays permanently at "0 USDC `Transfers logged".

### Link to Minimal Reproducible Example (StackBlitz, CodeSandbox, GitHub repo etc.)

https://github.com/firnprotocol/wagmi-v1-example

**Comment by theshadowagent** [comment]
I have the same issue with zkSync Era chain

**Comment by BLOCKCHAINDEVWEB** [comment]
The event is listened to and I get the event data in console.log but no script works afterwards:
```js
listener(log) {
   console.log(log)
   // script not interpreted
}
```

**Comment by niffyord** [comment]
any solution to this

**Comment by jxom** [comment]
Using `publicProvider` as a sole RPC provider is not recommended as it has brittle filter & logs support. Please use `alchemyProvider` along with `publicProvider`.
