### ISSUE TITLE
bug: multicall does not return proper type inference

### ISSUE THREAD

**Issue by MidnightLightning** [wagmi-dev/wagmi#3053]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

1.3

### Current Behavior

When using `multicall`, the documentation indicates the [return type](https://wagmi.sh/core/actions/multicall#return-value) should be inferred from the ABI/method-name used as input.

But in practice it's being set to `unknown[]` even when `allowFailure` is set to `false`

### Expected Behavior

The array of objects returned should be typed as an object with specific keys/values, and not `unknown[]`

### Steps To Reproduce

```ts
import { multicall } from 'wagmi/actions'

const ACCESSORIES = {
  address: '0x8d33303023723dE93b213da4EB53bE890e747C63',
  abi: parseAbi([
    'function totalAccessories() external view returns (uint256)',
    'function balanceOf(uint256 rescueOrder) external view returns (uint256)',
    'function ownedAccessoryByIndex(uint256 rescueOrder, uint256 ownedAccessoryIndex) external view returns ((uint232 accessoryId, uint8 paletteIndex, uint16 zIndex))',
    'function accessoryInfo(uint256 accessoryId) external view returns ((uint16 totalSupply, uint16 availableSupply, bytes28 name, address manager, uint8 metabyte, uint8 availablePalettes, bytes2[4] positions, bool availableForPurchase, uint256 price))',
  ])

let rs = await multicall({
  contracts: [
    {
      ...ACCESSORIES,
      functionName: 'ownedAccessoryByIndex',
      args: [1289n, 0n]
    }
  ],
  allowFailure: false 
})
```

The type of the return variable `rs` should be `{accessoryId: bigint, paletteIndex: number, zIndex number}[]`, but it is being set as `unknown[]`

Within the same code context, using `readContract` with the same inputs works as expected:
```ts
const testRs = await readContract({
  ...ACCESSORIES,
  functionName: 'ownedAccessoryByIndex',
  args: [1289n, 0n]
})
```

Here `testRs` has an inferred type of `{accessoryId: bigint, paletteIndex: number, zIndex number}`, which shows the ABI parameter is being set up properly and `readContract` is able to use it, but `multicall` isn't.

### Anything else?

Using Typescript 5.1 and inspecting types inside Visual Studio Code IDE

**Comment by tmm** [comment]
Can you put together a complete minimal reproducible example? Works fine in [this TypeScript Playground](https://www.typescriptlang.org/play?target=99#code/JYWwDg9gTgLgBAbziArgGxsAxgQzWuAXzgDMoIQ4ByAAQHccBzEYAei2gFMqAoUSWIjhgcUAM6cAggCNgRUuUpUAbsE4hePDgDsx8SQGEDAUQDKpgPIAlAJJm4AXkQ84cHABN3UTmLEAuagAGAA8ADncAZijAiMCAJgiAdgT3YwBOCOk4gEYI9xwAFmMAIQBWTONQtMDORILEgwA2CKoAGhc3WQCRcSlZAAoAbQ7XKhIUbSxMCG04GAgYPEksLB8xaDUxfoBKOE5gmE4obTw4VU46OG8YFGOxOH6UYG0YONLG7baR6nHJ6dnpHgcJNOBYSI9nq93lcfFgUKCoO4jrt9odjqdzpdrrddA8ni83h8vq5Rr8psAZnAIHRtJx3MtVr5oABPYrMmzaJHBCEE6HeMRwhFIqCtOD4qGNKk0ukMtYsjlclEHI4nAiYmE3O4PHmvCJxNwrOVQdnuUXi0LCPCcGCHBX7M2Q7KSgBeduC20+7RJPwm5MpOENTONHJIEB1hINjPWwfcSrRqrOaix1px936OqdcwWeFMKDAYDQzIdL0zOGUOGAaBw0jQnFz+cLoukzMOYjiFpOIE4oo8XjWyGBTCOxZgFq7i2bhxHFrLFarNc4AAUrTafE2Wz44oMCgBdYQQMTAf5iJsQCAEWeV6u1gBi0EXtywAAscBIRxGwFBsJwPcS4DvtnaYhXzgHQ9B4LQZj0GF7icHAGCPZB0EwXB8H6BAOjwNBqRvOdbk4AISDwN8Oh0GAoADGB-DgYZvQw71XAAOmYwwTHMaw7FML0GLJf4ADkcC7AIqGpWl6UDaNWXZTl9j-b1REYajBmyds0m0UVAm0HduNcQhuO0nhCG2Hh+R4VhWDgAA9AB+HggA). You should add a const assertion to `ACCESSORIES` (see below).

```ts
import { multicall } from '@wagmi/core'
import { parseAbi } from 'viem'

const ACCESSORIES = {
  address: '0x8d33303023723dE93b213da4EB53bE890e747C63',
  abi: parseAbi([
    'function totalAccessories() external view returns (uint256)',
    'function balanceOf(uint256 rescueOrder) external view returns (uint256)',
    'function ownedAccessoryByIndex(uint256 rescueOrder, uint256 ownedAccessoryIndex) external view returns ((uint232 accessoryId, uint8 paletteIndex, uint16 zIndex))',
    'function accessoryInfo(uint256 accessoryId) external view returns ((uint16 totalSupply, uint16 availableSupply, bytes28 name, address manager, uint8 metabyte, uint8 availablePalettes, bytes2[4] positions, bool availableForPurchase, uint256 price))',
  ]),
} as const // <----- need this

const res = await multicall({
  allowFailure: false,
  contracts: [
    {
      ...ACCESSORIES,
      functionName: 'ownedAccessoryByIndex',
      args: [1289n, 0n],
    },
  ],
})
res
// ^? const res: [{ accessoryId: bigint; paletteIndex: number; zIndex: number; }]
```

**Comment by MidnightLightning** [comment]
I fiddled with this some more and found for my use-case there were actually two factors at play:

- Object literals not being declared "as const"
- Variables being passed as arguments to the function that were `number` types instead of `bigint`

Here's an example of my use-case with the types broken: [Typescript playground](https://www.typescriptlang.org/play?target=99&ts=5.2.2#code/JYWwDg9gTgLgBAbzmAhlAzgUwIICNhwC+cAZlBCHAOQBuwmIVAUKJLInCAK4A2MwAYxQ8eRUuUpUAAgHcUAcxDAA9AOiZmTNQDt08bAGEDAUQDKpgPIAlAJJm4AXkRM4cFABN3UTOnQAuagAGAA8ADncAZijAiMCAJgiAdgT3YwBOCNw4gEYI9xQAFmMAIQBWTONQtMDMRILEgwA2CKoAGhc3fADUDBx8AAoAbQ7XKhIubQF+CG04GAgYYWwBAR90aHp0foBKOExgmEwobWE4OkwZOG8YLmP0OH6uYG0YONLG7baR6nHJ6dncMIUJNMBYSI9nq93lcfAIuKCoO4jrt9odjqdzpdrrddA8ni83h8vq5Rr8psAZnAIDJtJh3MtVr5oABPYrMmzaJHBCEE6HedBwhFIqCtOD4qGNKk0ukMtYsjlclEHI4nUSYmE3O4PHmvCJxNwrOVQdnuUXi0LIYSYGCHBX7M2Q7KSgBeduC20+7RJPwm5MpKENTONHJIEB1hINjPWwfcSrRqrO9Cx1px936OqdcwWwlMXDAYB4zIdL0zKBoKGAPBQuB4mFz+cLotwzMO6DiFpOIEwoo8XjWnGBCiOxZgFq7i2bhxHFrLFarNcwAAUrTafE2Wz44oMCgBdZAQdDAf7oJsQCCiWeV6u1gBi0EXtwEAAsUFgRxGwFBBJgPcS4DvtiYYhXzgHQ9DgZRlDgAAeABaWC4AAFSfYB7lQuBaTpOkmCYV9mUmUhfX+UhrWfWUg02fp+UFCxESOAJtC4EBcGRZxXDA+BuD4QRhB4e4nGGb0EG+VwADpxMMExzGsOxTC9b1CL+CltAAORQLsAioalaXpQNo1ZdlOX2P9vTQeR-DgQZqPhWjhVFbJtB3UVIJg+C4BsEg9iPJ8jipTyYB8rA3G8S1fDpNx7kY5ijnuYF3AwhY4HweRIRPK57hYtQu3uCYAGttG075gPuDiIKguCEOQ9D0MwpF3A6HcOlreAMEcNw5CPTheH4IQRH6JAdBgKAAxgCyuJ63i0t46kbznW5MACEhhCCwhANcFyAD0AH4gKAA)

```ts
import { parseAbi } from 'viem'
import { multicall } from '@wagmi/core'

const ACCESSORIES = {
  address: '0x8d33303023723dE93b213da4EB53bE890e747C63',
  abi: parseAbi([
    'function totalAccessories() external view returns (uint256)',
    'function balanceOf(uint256 rescueOrder) external view returns (uint256)',
    'function ownedAccessoryByIndex(uint256 rescueOrder, uint256 ownedAccessoryIndex) external view returns ((uint232 accessoryId, uint8 paletteIndex, uint16 zIndex))',
    'function accessoryInfo(uint256 accessoryId) external view returns ((uint16 totalSupply, uint16 availableSupply, bytes28 name, address manager, uint8 metabyte, uint8 availablePalettes, bytes2[4] positions, bool availableForPurchase, uint256 price))',
  ])
} as const // <-- This is needed

async function fetchAccessories(rescueOrder: number) {
  const multicalls = [
    {
      ...ACCESSORIES,
      functionName: 'ownedAccessoryByIndex',
      args: [rescueOrder, 1n], // <-- If either of these are passed as numbers and not bigints, rs becomes unknown
    } as const // <-- This is needed
  ]
  let rs = await multicall({ contracts: multicalls, allowFailure: false })
  // ^?
}
```

The issue is that `rescueOrder` is coming into the function as a `number` and is passed as an argument that way, when it's supposed to be a `bigint`. When used in this way, there doesn't seem to be any alerting that the wrong type of `args` are being passed in (you just have to infer that from the inferred type being `unknown`?)?

Is there a better way to structure this such that the mismatch in types becomes more evident?

**Comment by tmm** [comment]
Add a const assertion to `multicalls` and you should be good.

```diff
import { parseAbi } from 'viem'
import { multicall } from '@wagmi/core'

const ACCESSORIES = {
  address: '0x8d33303023723dE93b213da4EB53bE890e747C63',
  abi: parseAbi([
    'function totalAccessories() external view returns (uint256)',
    'function balanceOf(uint256 rescueOrder) external view returns (uint256)',
    'function ownedAccessoryByIndex(uint256 rescueOrder, uint256 ownedAccessoryIndex) external view returns ((uint232 accessoryId, uint8 paletteIndex, uint16 zIndex))',
    'function accessoryInfo(uint256 accessoryId) external view returns ((uint16 totalSupply, uint16 availableSupply, bytes28 name, address manager, uint8 metabyte, uint8 availablePalettes, bytes2[4] positions, bool availableForPurchase, uint256 price))',
  ])
} as const // <-- This is needed

async function fetchAccessories(rescueOrder: number) {
  const multicalls = [
    {
      ...ACCESSORIES,
      functionName: 'ownedAccessoryByIndex',
      args: [rescueOrder, 1n], // <-- If either of these are passed as numbers and not bigints, rs becomes unknown
    } as const // <-- This is needed
- ]
+ ] as const
  let rs = await multicall({ contracts: multicalls, allowFailure: false })
  // ^?
}
```

**Comment by MidnightLightning** [comment]
Oh, of course; for that simplified example that makes sense, as the array is being declared as a literal. Thanks! Making it one step more complicated (would this be best as a "discussion" item or a guide page in the docs to cover these sort of stumbling blocks?): if the array is assembled piecemeal (either from a loop or as the result of different function calls), then the array cannot be declared "as const" after its assembled: [Playground example](https://www.typescriptlang.org/play?target=99&ts=5.2.2#code/JYWwDg9gTgLgBAbzmAhlAzgUwIICNhwC+cAZlBCHAOQBuwmIVAUKJLInCAK4A2MwAYxQ8eRUuUpUAAgHcUAcxDAA9AOiZmTNQDt08bAGEDAUQDKpgPIAlAJJm4AXkRM4cFABN3UTOnQAuagAGAA8ADncAZijAiMCAJgiAdgT3YwBOCNw4gEYI9xQAFmMAIQBWTONQtMDMRILEgwA2CKoAGhc3fADUDBx8AAoAbQ7XKhIubQF+CG04GAgYYWwBAR90aHp0foBKOExgmEwobWE4OkwZOG8YLmP0OH6uYG0YONLG7baR6nHJ6dncMIUJNMBYSI9nq93lcfAIuKCoO4jrt9odjqdzpdrrddA8ni83h8vq5Rr8psAZnAIDJtJh3MtVr5oABPYrMmzaJHBCEE6HedBwhFIqCtOD4qGNKk0ukMtYsjlclEHI4nUSYmE3O4PHmvCJxNwrOVQdnuUXi0LIYSYGCHBX7M2Q7KSgBeduC20+7RJPwm5MpKENTONHJIEB1hINjPWwfcSrRqrO9Cx1px936OqdcwWwlMXDAYB4zIdL0zKBoKGAPBQuB4mFz+cLotwzMO6DiFpOIEwoo8XjWnGBCiOxZgFq7i2bhxHFrLFarNcwAAUrTafE2Wz44oMCgBdZAQdDAf7oJsQCCiWeV6u1gBi0EXtwEAAsUFgRxGwFBBJgPcS4DvtiYYhXzgHQ9DgZRlDgAAeABaWC4AAFSfYB7lQuBaTpOkmCYV9mUmUhfX+UhrWfWUg02fp+UFCxESOAJtC4EBcGHSMjWZAwIAmGAGKYlioF2BAOjA+BuD4QRhB4e4nEGHcOlDKAHlreACCcQJtAAbjgAhoLYoMOK4l4tOAABqEzBO+MT+CEER0AAOjALh0CffohO9Vw7M8wwTHMaw7FML13LJf4ADkUC7AIqGpWl6UDaNWXZTl9j-b00Hkfw4EGaj4Vo4VRWAHdRUgmD4LgGwSD2I8nyOKkKpgaqsDcbxLV8Ok3HuRjmKOe5gXcDCFjgfB5EhE8rnuFi1C7e4JgAa20aLvmA+4RN2Yq4IQ5D0PQzCkXcDpCA6ZSxscNw5CPTheGsyTXNAmYYCgAMYAyqyJNsnsRGpG851uTAAhIYRGsIQDXGKgA9AB+ICgA)

```ts
import { parseAbi } from 'viem'
import { multicall } from '@wagmi/core'

const ACCESSORIES = {
  address: '0x8d33303023723dE93b213da4EB53bE890e747C63',
  abi: parseAbi([
    'function totalAccessories() external view returns (uint256)',
    'function balanceOf(uint256 rescueOrder) external view returns (uint256)',
    'function ownedAccessoryByIndex(uint256 rescueOrder, uint256 ownedAccessoryIndex) external view returns ((uint232 accessoryId, uint8 paletteIndex, uint16 zIndex))',
    'function accessoryInfo(uint256 accessoryId) external view returns ((uint16 totalSupply, uint16 availableSupply, bytes28 name, address manager, uint8 metabyte, uint8 availablePalettes, bytes2[4] positions, bool availableForPurchase, uint256 price))',
  ])
} as const // <-- This is needed

async function fetchAccessories(rescueOrder: number, accessoryCount: number) {
  const multicalls = []
  for (let i = 0n; i < accessoryCount; i++) {
    multicalls.push({
      ...ACCESSORIES,
      functionName: 'ownedAccessoryByIndex',
      args: [rescueOrder, 1n], // <-- If either of these are passed as numbers and not bigints, rs becomes unknown
    } as const) // <-- This is needed
  }
  let rs = await multicall({ contracts: multicalls, allowFailure: false })
  // ^?
}
```

The "bug" here is the value passed into the `args` isn't exactly right (passing in a number when it should be a bigint). In this situation is there a better way to make it obvious there's a bigint/number mismatch, or convert and ignore the discrepancy?
