### ISSUE TITLE
bug: useContractEvent not getting triggered

### ISSUE THREAD

**Issue by carloscip** [wagmi-dev/wagmi#3054]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

1.4.2

### Current Behavior

The listener never gets triggered.

### Expected Behavior

To log when event gets triggered

### Steps To Reproduce

```
export function EventListener() {
  const abi = "./abi.json"
  const address = "0xCORRECT_ADDRESS"

  // 3. wait for event logs
  useContractEvent({
    address: address,
    abi: abi,
    eventName: "CorrectListenerName",
    listener(log) {
      console.log("listener triggered", log);
    },
  });

  return <></>;
}
```

The address and eventName are correct. And I use this component inside the main wagmi component:

```
<WagmiConfig config={wagmiConfig}>
  < EventListener />
</WagmiConfig>
```

**Comment by carloscip** [comment]
@tmm It is not duplicate, since I am trying it in goerli network. Not in base.

**Comment by tmm** [comment]
Someone else [commented](https://github.com/wagmi-dev/wagmi/issues/3033#issuecomment-1732592439) on this issue saying the same thing happens with zkSync Era so I'm inclined to say it's the same issue across any chain.

**Comment by 1337-ishaan** [comment]
Leaving a solution for people coming here from Rainbow Wallet, try 
```
[...<your-previous-providers>,
 jsonRpcProvider({
        rpc: (chain) => ({
          http: `https://${chain.id}.example.com`,
        }),
      }),
    ]
 ]
```
