### ISSUE TITLE
bug:  useContractRead hook with an array of tokens without breaking the rules of hooks ? 

### ISSUE THREAD

**Issue by Subham-Maity** [wagmi-dev/wagmi#3063]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

"wagmi": "^1.3.9"

### Current Behavior

I am trying to get the `name`, `symbol` and `decimal` properties of each token in an array of tokens using the useContractRead hook. However, I am getting errors when I use the map method to iterate over the token array and call the hook inside the callback function. The errors are:

- Error: Rendered more hooks than during the previous render
- Error: Rendered fewer hooks than expected. This may be caused by an accidental early return statement

These errors only appear before reloading the page or disconnecting the wallet. After that, they disappear and the results are shown in the frontend. I think this is because the map method violates the rules of hooks, which state that hooks should only be called at the top level and not inside loops, conditions or nested functions.

Is there a better way to get the name, symbol and decimal properties of each token without using the map method or breaking the rules of hooks? Here is my code:

```jsx
const names = tokenArray.map((token: string, index: number) => {
    // eslint-disable-next-line react-hooks/rules-of-hooks
    const { data: name } = useContractRead({
      //@ts-ignore
      address: token,
      abi: ERC20Abi,
      functionName: "name",
    });
    // return an object with the data property
    return { data: name };
  });

  const name = names.map((item: any, index: number) => item.data);

  const symbols = tokenArray.map((token: string, index: number) => {
    // eslint-disable-next-line react-hooks/rules-of-hooks
    const { data: symbol } = useContractRead({
      //@ts-ignore
      address: token,
      abi: ERC20Abi,
      functionName: "symbol",
    });
    // return an object with the data property
    return { data: symbol };
  });

  const symbol = symbols.map((item: any, index: number) => item.data);

  console.log(symbol, "symbol");

  const decimals = tokenArray.map((token: string, index: number) => {
    // eslint-disable-next-line react-hooks/rules-of-hooks
    const { data: decimals } = useContractRead({
      //@ts-ignore
      address: token,
      abi: ERC20Abi,
      functionName: "decimals",
    });
    // return an object with the data property
    return { data: decimals };
  });

  const decimal = decimals.map((item: any, index: number) => item.data);
  console.log(decimal, "decimal");
  ```

### Expected Behavior

To achieve my goal of obtaining separate arrays for the name, symbol, and decimal properties from the token array, I am seeking an alternative method to replace the current use of the map function.

**Comment by jxom** [comment]
I think you are after [`useContractReads`](https://wagmi.sh/react/hooks/useContractReads)
