### ISSUE TITLE
bug: Connectors in package even if not needed

### ISSUE THREAD

**Issue by ennioVisco** [wagmi-dev/wagmi#3073]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

1.4.2

### Current Behavior

<img width="325" alt="image" src="https://github.com/wagmi-dev/wagmi/assets/740025/09ae15fc-2f9e-43ad-87e9-0d5f56055819">

### Expected Behavior

I was expecting to install connectors as an extra dependency, not automatically when installing `core`

**Comment by tmm** [comment]
Intentional so you don't need to worry about bumping versions.

**Comment by ennioVisco** [comment]
> Intentional so you don't need to worry about bumping versions.

Ok, but is there a way to exclude them?
This makes my `node_modules`explode, which is a problem for some running environments where the size of this folder is limited...
