### ISSUE TITLE
bug: Type definition for `BaseError` missing 'cause' property

### ISSUE THREAD

**Issue by Mahdi-HF** [wagmi-dev/wagmi#3077]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

1.14

### Current Behavior

The `BaseError` class in the `viem` module sets a `cause` property dynamically, but this property is not defined in the type definition.
TypeScript throws an error saying "Property 'cause' does not exist on type 'BaseError'."

### Expected Behavior

TypeScript should recognize the `cause` property on `BaseError` without any type errors.

### Steps To Reproduce

1. Import `BaseError` from `viem`.
2. Try to access the `cause` property on an instance of `BaseError`.

### Anything else?

**Possible Solution**:
Augment the type definition for `BaseError` to include the `cause` property.

**Comment by tmm** [comment]
What does your `tsconfig.json` look like? What version of TypeScript are you using?

**Comment by Mahdi-HF** [comment]
"typescript": "~5.0.4"

```json
{
  "compilerOptions": {
    "module": "commonjs",
    "target": "ES6",
    "strict": true,
    "skipLibCheck": true,
    "esModuleInterop": true,
    "types": [],
    "jsx": "react",
    "allowJs": true,
    "forceConsistentCasingInFileNames": true,
    "noEmit": true,
    "allowSyntheticDefaultImports": true,
    "useUnknownInCatchVariables": false,
    "noImplicitAny": false,
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    // "jsx": "preserve",
    "downlevelIteration": true,
    "incremental": true
  },
  "exclude": ["node_modules", "dist"]
}

**Comment by tmm** [comment]
Set `"target"` to `"es2022"` or later.

**Comment by Mahdi-HF** [comment]
Thank you! This solved my problem.
