### ISSUE TITLE
bug: MetaMask not detected

### ISSUE THREAD

**Issue by motechFR** [wagmi-dev/wagmi#3080]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

1.4.1

### Current Behavior

When entering my site with Metamask locked, and then unlocking metamask, the account value from useAccount does not change.

If I enter the site and Metamask was unlocked, then it is picked up. I can lock it and re-unlock it. The changes will be picked up.

_Note: The wallet is authorised on the site. I also only have 1 wallet in my browser._

### Expected Behavior

Metamask changes should always be detected, whatever the initial state of metamask was on navigating to the site (locked / unlocked).

I should not need to manually call **connectAsync** for the wallet to come through via useAccount, if the wallet is already authorised on this site.

### Steps To Reproduce

Get account from useAccount hook.

Enter website with metamask wallet locked.

Unlock the wallet manually.

Change is not detected.

### Anything else?

Attached the fix I used. Here, I hook directly into window.ethereum, and trigger connectAsync to reactivate Metamask within Wagmi.

https://github.com/charmverse/app.charmverse.io/pull/2872/files#diff-904ced01550bfc35f0ac424af15ddff4366afdffabc45c87e87c23366801cb5cR269-R291

**Comment by tmm** [comment]
This is fixed in Wagmi v2 (see #3068).
