### ISSUE TITLE
bug: SafeConnector doesn't connect, gets stuck on "connecting".

### ISSUE THREAD

**Issue by 0xfps** [wagmi-dev/wagmi#3082]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

1.4.1

### Current Behavior

SafeConnect connector button when clicked doesn't connect with Safe.

### Expected Behavior

It should connect with Safe.

### Steps To Reproduce

I have a simple frontend page, and I intend to add a wallet connect feature using Safe. Below is the necessary code to setup a SafeConnector in Wagmi.

```js
// Import all packages necessary.
import { SafeConnector } from 'wagmi/connectors/safe';

const { chains, publicClient, webSocketPublicClient } = configureChains(
  [goerli],
  [publicProvider()]
)

// Set up wagmi config
const config = createConfig({
  autoConnect: false,
  connectors: [
    new SafeConnector({ chains: [goerli] })
  ],
  publicClient,
  webSocketPublicClient
})
```

Over here, is the code to allow the connection.

```js
const { connect, connectors, error, pendingConnector } = useConnect();
{
  connectors
  .map((x) => (
      <button key={x.id} onClick={() => { console.log(x); connect({ connector: x }) }}>
          {x.name}
          {isConnecting && x.id === pendingConnector?.id && ' (connecting)'}
      </button>
  ))
}
```

This doesn't work, rather, it gets the button stuck in this state.
![image](https://github.com/wagmi-dev/wagmi/assets/74331706/689105ca-de18-41ee-b687-8509ac553a3b)

What can be done to fix this?
Recreatable code @ https://github.com/0xfps/safe-demo.

### Link to Minimal Reproducible Example (StackBlitz, CodeSandbox, GitHub repo etc.)

https://github.com/0xfps/safe-demo

### Anything else?

![image](https://github.com/wagmi-dev/wagmi/assets/74331706/8221ccdd-199d-452c-bcaf-e53c4b32ff15)

**Comment by tmm** [comment]
The Safe connector only works on [app.safe.global](https://app.safe.global). Are you using that?
