### ISSUE TITLE
bug: Network request failed error in usePrepareContractWrite on iOS（Chrome, Safari）

### ISSUE THREAD

**Issue by cg-yamada** [wagmi-dev/wagmi#3087]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.12.19

### Current Behavior

nextjs: 13.2.3
@web3modal/ethereum: 2.7.1

I am implementing a process to mint the Polygon (Mumbai) chain.
Parameters are used with appropriate values.

```
  const authorAddress = '0x...123456789'
  const tokenID = 12345678
  const res = {
    chainId: 80001,
    contractAddress:'0x...123456789',
    mintFromAddress: '0x...123456789',
    mintToAddress: '0x...123456789',
    tokenId: 200000000,
    minterAddress: '0x123456789...',
    idempotencyHash:  '0x123456789...',
    signature:  '0x123456789...',
    uid: 123456,
    deadline: 1696579781,
    mintStatus: 0,
    createdAt: 1696234543,
  }
  
  const { config, error, isSuccess } = usePrepareContractWrite({
    abi: Minter__factory.abi,
    address: res.minterAddress,
    functionName: 'transfer',
    args: [
      res.contractAddress,
      authorAddress,
      tokenID,
      res.deadline,
      res.idempotencyHash,
      res.signature,
    ],
  })
```

In this code, in the MacOS environment, the config response is returned successfully and the error response is returned undefined. However, in the iOS environment, the response `error="Network request failed"` is returned.

### Expected Behavior

I would like to be able to get the value of config parameter on iOS as well as MacOS.
However, it seems possible that there is something wrong at the OS level in iOS that has not been resolved on the wagmi side.

### Steps To Reproduce

Write at Current Behavior.

**Comment by tmm** [comment]
Thanks for reporting. This issue is temporarily closed due to lack of information. Please provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) and reopen this issue.
