### ISSUE TITLE
bug: Different Wallet Client object between Wagmi and Viem

### ISSUE THREAD

**Issue by 70nyIT** [wagmi-dev/wagmi#3094]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

1.4.2

### Current Behavior

If I get a WalletClient using wagmi hook `useWalletClient` and I pass it to a function, maybe from an SDK that uses `viem`, I get the error that WalletClient (from wagmi) is not assignable to WalletClient (from viem). Specifically, the value `account` in wagmi is always of type `Account`, while in viem is `Account | undefined`.

```
const {data: walletClient} = useWalletClient();
const myHook = useHook(walletClient, otherData);
```

### Expected Behavior

That two types, with the same name, between `wagmi` and `viem` are fully compatible, to avoid confusion.

### Steps To Reproduce

This is the Wagmi definition (where `account` is always `Account`): 
https://github.com/wagmi-dev/wagmi/blob/1fb735b3ada01eff6944073ff8406d5b0d74fc04/packages/core/src/types/index.ts#L33

This is the Viem definition (where `account` can be `Account | undefined`): 
https://github.com/wagmi-dev/viem/blob/1385d14ccdcc2df1ac76a6de9a9d2476c7ddb7f8/src/clients/createWalletClient.ts#L32

### Anything else?

I think that if we want to keep the same behavior, there's the need for a new type name. Or a hook to retrieve a `viem` compatible `WalletClient` is required. I still believe that calling `WalletClient` two different types in two close libraries such as `wagmi` and `viem` is confusing.

I've also opened a Discussion - ref: https://github.com/wagmi-dev/wagmi/discussions/3042

**Comment by tmm** [comment]
`WalletClient` in Wagmi always has an `Account` attached to it (for the connected connector), otherwise `data` is `undefined`. This is the intended behavior.
