### ISSUE TITLE
bug: @wagmi/cli (React plugin) watch<Name>Event might generate typescript errors

### ISSUE THREAD

**Issue by SuPuL** [wagmi-dev/wagmi#3098]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

1.5.2

### Current Behavior

Generate contracts will result in such `watchContractEvent` functions per contract

```
export function watchSomeContractEvent<
  TAbi extends readonly unknown[] = typeof someAbi,
  TEventName extends string = string
>(
  config: Omit<WatchContractEventConfig<TAbi, TEventName>, 'abi' | 'address'> & {
    chainId?: keyof typeof someAddress;
  },
  callback: WatchContractEventCallback<TAbi, TEventName>
) {
  return watchContractEvent(
    {
      abi: someAbi,
      address: someAddress[config.chainId as keyof typeof someAddress],
      ...config
    } as WatchContractEventConfig<TAbi, TEventName>,
    callback
  );
}
```

But this might produce typescript errors while compiling. E.g. integrate the generated data in a package und run `tsc --build` to publish it. I tried a lot of config mit the result ist always. 

> Conversion of type {insert someAbi here} may be a mistake because neither type sufficiently overlaps. If this was intentional, convert the expression to 'unknown' first.

The solution would be similar to the other generated methods

```
export function watchSomeEvent<
  TAbi extends readonly unknown[] = typeof someABI,
  TEventName extends string = string
>(
  config: Omit<WatchContractEventConfig<TAbi, TEventName>, 'abi' | 'address'> & {
    chainId?: keyof typeof oracleAddress;
  },
  callback: WatchContractEventCallback<TAbi, TEventName>
) {
  return watchContractEvent(
    {
      abi: someABI,
      address: someAddress[config.chainId as keyof typeof someAddress],
      ...config
    } as unknown as WatchContractEventConfig<TAbi, TEventName>,
    callback
  );
}
```

So just add the `as unknown as WatchContra` like it is done in other generated methods.

### Expected Behavior

No compile errors

### Steps To Reproduce

1. Create a Typescript project.
2. Generate some contracts in it
3. Run `tsc --build`

**Comment by tmm** [comment]
What version of TypeScript are you using? Please attach a minimal reproduction. Issue will be re-opened once that is provided.

**Comment by DorianWilhelm** [comment]
Stumbled upon this today myself.
It's rather related to the actions plugin
created a quick repro:
https://stackblitz.com/edit/stackblitz-starters-vt97ap?file=src%2Fgenerated.ts
