### ISSUE TITLE
Event change wallet is not working with Coinbase and Wagmi

### ISSUE THREAD

**Issue by frantrick** [wagmi-dev/wagmi#3107]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

1.0.14

### Current Behavior

from official site change your wallet and is not detecting the change

https://wagmi.sh/examples/connect-wallet

### Expected Behavior

detect the address selected when change

### Steps To Reproduce

1- go to the page https://wagmi.sh/examples/connect-wallet
2- connect your wallet with coinbase
3- change your wallet and you wont see the new address selected

### Link to Minimal Reproducible Example (StackBlitz, CodeSandbox, GitHub repo etc.)

https://wagmi.sh/examples/connect-wallet

### Anything else?

official site https://wagmi.sh/examples/connect-wallet

**Comment by jxom** [comment]
This is likely a bug on Coinbase Wallet. Best to get in touch with them!
