### ISSUE TITLE
bug: `useBalance` with token reads cache of `useBalance` without token

### ISSUE THREAD

**Issue by krzkaczor** [wagmi-dev/wagmi#3116]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

1.4.3

### Current Behavior

When `useBalance` is being used with `token` argument that is being loaded and is temporarily `undefined`, eth balance will be loaded instead.
```ts
useBalance({address: "...", token: undefined})
```
To add to the confusion, even setting `enabled` flag to `false` doesn't help in a case when eth balance is already in cache.

### Expected Behavior

There are no pitfalls when providing `token` argument and similarly to a case when `address` is temporary undefined, it works as expected.

### Steps To Reproduce

Have a look at stackblitz. WETH balance is equal to ETH balance until `token` gets set.

### Link to Minimal Reproducible Example (StackBlitz, CodeSandbox, GitHub repo etc.)

https://stackblitz.com/edit/new-wagmi-9v6vky?file=src%2FApp.tsx,src%2Fwagmi.ts,src%2Fmain.tsx

### Anything else?

I see two solutions:
1. Split `useBalance` into `useBalance` and `useTokenBalance`. The latter would automatically be disabled unless both address and token are defined.
2. Introduce yet another flag to `useBalance` to explicitly state that token balance should be loaded: `loadTokenBalance: true`.

I am more than happy to contribute a fix but first, we need to agree what is the correct solution.

**Comment by tmm** [comment]
Appreciate the feedback! `useBalance`'s [`token` parameter is deprecated](https://alpha.wagmi.sh/react/guides/migrate-from-v1-to-v2#deprecated-usebalance-token-parameter) so not going to make changes to this now.
