### ISSUE TITLE
Failure to Add New Ethereum Chains using Wallet Connect

### ISSUE THREAD

**Issue by camolezi** [wagmi-dev/wagmi#3119]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

1.4.3

### Current Behavior

When utilizing Wallet Connect with wallets supporting the `wallet_addEthereumChain` method (e.g., MetaMask Mobile), there's an unexpected behavior: the new chain is not automatically added to the wallet when using `connect({chainId}.` This issue persists even when manually invoking the switchNetwork(chain) function post-connection.

**Initial Connection:** When initially connecting to a network (that isn't already in the wallet) via Wallet Connect, seems like no request is made to add the new Ethereum chain to the wallet.
**Manual Switch:** After the connection is established, invoking switchNetwork(chain) does not add the missing chain to the wallet. However, the useNetwork hook is updated to reflect the new chain.

### Expected Behavior

On the first connection, the user should automatically be prompt to add the new chain if it is not already in the wallet. Invoking switchNetwork(chain) should not only update the useNetwork hook but should also add the new chain to the wallet if it is not already present.

### Steps To Reproduce

https://stackblitz.com/edit/vitejs-vite-xdrtyy?file=src%2Fcomponents%2FProfile.tsx

The example is using Arbitrum but I'm able to reproduce with any other non-default chain.
Connect using MetaMask Mobile (using wallet connect) ensuring that Arbitrum is not already added to the wallet. The user is not requested to add Arbitrum to the wallet. 
Invoke switchNetwork to Arbitrum. Although the useNetwork hook updates, the new chain is not added to the wallet. Any transaction attempt will fail.

### Link to Minimal Reproducible Example (StackBlitz, CodeSandbox, GitHub repo etc.)

https://stackblitz.com/edit/vitejs-vite-xdrtyy?file=src%2Fcomponents%2FProfile.tsx

**Comment by tmm** [comment]
Not all wallets support `wallet_addEthereumChain` via WalletConnect.

**Comment by camolezi** [comment]
Hey @tmm 

I've done my testing with a wallet that supports the `wallet_addEthereumChain` method, specifically using MetaMask Mobile via WalletConnect. Given this setup, I would expect that the library would behave the same as for injected wallets, which is to add a new chain if it doesn't already exist in the wallet. Is that correct? Or is the expected behavior to never add new chains on all WalletConnect wallets?

**Comment by glitch-txs** [comment]
MetaMask mobile requires a different error handling for `wallet_addEthereumChain` not sure if this is the case
I was handling it like this: `er.code === 4902 || er?.data?.originalError?.code == 4902`

**Comment by camolezi** [comment]
hey @tmm, wondering if you had the change to take a look at my response. thanks
