### ISSUE TITLE
MethodNotFoundRpcError: The method does not exist / is not available.  Details: the method eth_signTypedData_v4 does not exist/is not available Version: viem@1.16.5

### ISSUE THREAD

**Issue by Madeindreams** [wagmi-dev/wagmi#3130]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

1.4.3

### Current Behavior

I'm using the walletClient.signTypedData and it is working fine on my desktop and was also working fine on mobile.
I'm using the publicClient.

I have not touched that part of the code and for a reason I still ignore, It stopped working on mobile.

When clicking the sign button, I get this error.

buildRequest.ts:143 Uncaught (in promise) MethodNotFoundRpcError: The method does not exist / is not available.

```
Details: the method eth_signTypedData_v4 does not exist/is not available
Version: viem@1.16.5
    at xa.delay.count (buildRequest.ts:143:21)
    at async a (withRetry.ts:37:15)
```
    
    
I have tried on Brave and Chrome and I get that same error. It was working on both an hour or so ago.
 

### Expected Behavior

Metamask should pop up and ask me to sign the message

### Steps To Reproduce

```
 const handleSubmit = async (event) => {
        event.preventDefault();
        
        const address = await walletClient.requestAddresses()
        console.log("Account: ",address[0])
        // retrieve typedData
        const typedData = createTypedData(props)


        const signature = await walletClient.signTypedData(typedData)
```

### Anything else?

![image](https://github.com/wagmi-dev/wagmi/assets/17243647/3e8c938d-3df9-425c-9539-8eb79d9ae7e2)

**Comment by Madeindreams** [comment]
upgrading to 1.4.4 do not resolve it.

**Comment by Madeindreams** [comment]
Turns out that if mainnet is not in the list of chain to load, it can't find the signTypedData_v4 method.

**Comment by glitch-txs** [comment]
Mobile wallet via WalletConnect?

**Comment by cg-yamada** [comment]
@jxom 
Hello!
It worked fine for me in the MacOS, but the same error occurred in the iOS.
I have tried several patterns and it seems to work with "mainnet".

```
[polygonMumbai, mainnet] → OK
[polygonMumbai] → NG
[polygonMumbai, sepolia] → NG
```

In the future, we would like to implement the following.
Is this a bug?
And if so, is there a plan to fix it?

```
[polygonMumbai]　→ development
[polygon] → production
```
