### ISSUE TITLE
bug: `prepareWriteContract` chainId parameter is ignored. 

### ISSUE THREAD

**Issue by atanasbozhkov** [wagmi-dev/wagmi#3135]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

1.4.4

### Current Behavior

Originally opened on viem's side ([Original Issue](https://github.com/wagmi-dev/viem/issues/1365)) but it seems that the problem actually lies with the wagmi implementation. 

I'm using a `prepareWriteContract` followed by a `writeContract` call. 
The `prepareWriteContract` documentation allows passing in a chainId to bind the contract call - [prepareWriteContract docs](https://wagmi.sh/core/actions/prepareWriteContract#chainid-optional)

However the underlying call to `writeContract` ignores the chainId on the prepared request ([code link](https://github.com/wagmi-dev/wagmi/blob/main/packages/core/src/actions/contracts/writeContract.ts#L77-L92))

```typescript
 if (config.mode === 'prepared') {
    request = config.request
  } else {
    const { chainId: _, mode: __, ...args } = config
    const res = await prepareWriteContract(args as PrepareWriteContractConfig)
    request = res.request as unknown as WriteContractParameters<
      TAbi,
      TFunctionName,
      Chain,
      Account
    >
  }

  const hash = await walletClient.writeContract({
    ...request,
    chain: config.chainId ? { id: config.chainId } : null,
  } as WriteContractParameters<TAbi, TFunctionName, Chain, Account>)

```

Since the chainId will be on the `config.request.chainId` the writeWriteContract call will ignore it and pass a `null` chain down to viem. 
Using `writeContract` directly - does not have this issue.

At the moment this issue can be bypassed by doing the following: 

```typescript
        const config = await prepareWriteContract({
          address,
          account,
          abi: ERC20ABi,
          functionName: "someFunc",
          value,
        });
        const { hash } = await writeContract({ ...config, chainId: chainId }); // Put the chainId on the writeContract instead of the request
```

But this is counterintuitive and not obvious at all.

### Expected Behavior

`prepareWriteContract` should check the chainId pass it down

```typescript

 if (config.mode === 'prepared') {
    request = config.request
  } else {
    const { chainId: _, mode: __, ...args } = config
    const res = await prepareWriteContract(args as PrepareWriteContractConfig)
    request = res.request as unknown as WriteContractParameters<
      TAbi,
      TFunctionName,
      Chain,
      Account
    >
  }
  const chainId = config.mode === 'prepared' ? config.request.chainId : config.chainId;
  const hash = await walletClient.writeContract({
    ...request,
    chain: chainId? { id: chainId } : null,
  } as WriteContractParameters<TAbi, TFunctionName, Chain, Account>)

```

### Steps To Reproduce

Read the wagmi code for prepareWriteContract and writeContract

**Comment by jxom** [comment]
Thanks for reporting. I can't seem to reproduce this. How are you consuming `prepareWriteContract` and `writeContract`? 

Something like the following should pass through `chain` to viem correctly:

```tsx
const { request } = await prepareWriteContract({
  abi,
  address: '0x...',
  functionName: 'mint',
  chainId: mainnet.id,
})
const { hash } = await writeContract(request)
```

Can you please provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) via https://new.wagmi.sh or a separate repo? It will save us a lot of time reproducing your config & environment, and trying to reproduce your issue. See [Why reproductions are required](https://antfu.me/posts/why-reproductions-are-required).

Will reopen when a reproduction is provided.

**Comment by atanasbozhkov** [comment]
The test is looking at the `request.chainId`. Which in turn is ignored by [this line](https://github.com/wagmi-dev/wagmi/blob/main/packages/core/src/actions/contracts/writeContract.ts#L92C10-L92C10).

I'll see if I can setup a repro.

**Comment by jxom** [comment]
It shouldn't be – `request` is passed as the first parameter to `writeContract` (which is `config`).

**Comment by atanasbozhkov** [comment]
If the config is prepared - then it would be under `config.request` - which you set on the `request` payload. 
But you never check the `config.request.chainid` on the [chain param line](https://github.com/wagmi-dev/wagmi/blob/main/packages/core/src/actions/contracts/writeContract.ts#L92). 
Hence the call to `writeContract` ends up having a `chainId` param and not a `chain` param. 

Will try to setup a repro if you insist.

**Comment by jxom** [comment]
Can you please provide usage?

Correct usage is like the below:

```tsx
const { request } = await prepareWriteContract({
  abi,
  address: '0x...',
  functionName: 'mint',
  chainId: mainnet.id,
})
const { hash } = await writeContract(request)
```

**Comment by atanasbozhkov** [comment]
That's the exact usage in my code.

**Comment by jxom** [comment]
That's the usage I am using, and I cannot seem to reproduce it. So, a minimal reproducible example will help a lot. 😄
