### ISSUE TITLE
error handling inconstancy

### ISSUE THREAD

**Issue by Madeindreams** [wagmi-dev/wagmi#3144]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

1.4.4

### Current Behavior

When a signature request is made using ` walletClient.signTypedData` and that an error occurs, the proper error code is thrown allowing us to catch the error as a code 4001.

When using write from useContractWrite, We are not able to catch any error on the write call and have to rely on the error that is returned from the hook.

`const { data: transaction,  error, write } = useContractWrite({...}}`

This error is returned as plain text and does not contain the error code that, for instance Metamask would return.

```
TransactionExecutionError: User rejected the request.
Request Arguments:
  from:   0x...
  to:     0x...
  value: ...
  data:  ...
Details: MetaMask Tx Signature: User denied transaction signature.
Version: viem@1.16.5
    at getTransactionError (getTransactionError.js:14:1)
    at sendTransaction (sendTransaction.js:135:1)
    at async writeContract (writeContract.js:67:1)
    at async writeContract (chunk-TSH6VVF4.js:2142:1)
```
    
  

### Expected Behavior

I'm expecting an error to be thrown with an error object that allow us to efficiently handle the error.

### Steps To Reproduce

Reject a transaction signature

**Comment by meri-maki** [comment]
Have and had this issue too for a long time. It's also an issue with different wallets (especially mobile) since they are all sending different errors in different formats

I'm currently fixing it by filtering ```error.message.includes()``` to display certain UI
But hope it'll get better at some point

**Comment by glitch-txs** [comment]
I wonder if this is a Wagmi related or wallet related issue.

As for EIP-1193 protocol wallets should respect this interface when throwing errors.

```ts
interface ProviderRpcError extends Error {
  code: number;
  data?: unknown;
}

<html>
<body>
<!--StartFragment-->

Status code | Name | Description
-- | -- | --
4001 | User Rejected Request | The user rejected the request.
4100 | Unauthorized | The requested method and/or account has not been authorized by the user.
4200 | Unsupported Method | The Provider does not support the requested method.
4900 | Disconnected | The Provider is disconnected from all chains.
4901 | Chain Disconnected | The Provider is not connected to the requested chain.

<!--EndFragment-->
</body>
</html>
```

@meri-maki I saw your issue on WalletConnect org, could you share which wallets have this problem?

**Comment by Madeindreams** [comment]
Metamask does return the error code when a signature transaction is rejected. But it is not being propagated upstream.

**Comment by glitch-txs** [comment]
is this desktop or mobile? I think it would be better to open the issue on MetaMask repository instead if that's the case.

**Comment by Madeindreams** [comment]
> is this desktop or mobile? I think it would be better to open the issue on MetaMask repository instead if that's the case.

There is no issue with Metamask. They do return the appropriate error.

**Comment by glitch-txs** [comment]
I see, have you tried this with Viem alone?

**Comment by Madeindreams** [comment]
> I see, have you tried this with Viem alone?

I have not yet. Will look at it when I have a chance

**Comment by jxom** [comment]
Thanks for reporting. Error propagation with the Contract Hooks should work correctly in wagmi. Can you please provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) via https://new.wagmi.sh or a separate repo? It will save us a lot of time reproducing your config & environment, and trying to reproduce your issue. See [Why reproductions are required](https://antfu.me/posts/why-reproductions-are-required).

Please reopen this issue when a reproduction is added.

**Comment by meri-maki** [comment]
@glitch-txs I currently cannot tell which wallets exactly have the issue with returning errors in proper format
However I had this issue with ```web3js``` [here](https://github.com/web3/web3.js/issues/6300)

And with this repo https://github.com/meri-maki/useSwitchNetwork
When I conect to metamask and reject transaction I get this (first error on screenshot)
And when I connect to Zerion via WalletConnect qr and reject transaction I get second error which I cannot access (no proper message, code etc)

![Снимок экрана 2023-10-24 в 17 49 18](https://github.com/wagmi-dev/wagmi/assets/97887955/7197f82e-d42e-4838-af93-6d50fbe8235c)

**Comment by Madeindreams** [comment]
I don't understand why this issue got closed so rapidly. We should be able to retrieve the correct error and code.

**Comment by glitch-txs** [comment]
This issue was reopened and solved [here](https://github.com/wagmi-dev/wagmi/issues/3146)

**Comment by Madeindreams** [comment]
It's is not solved. It's allowing us to catch the error but still does not contain the error object we are looking for.

**Comment by jxom** [comment]
I am happy to look into this issue if you provide a minimal reproducible example. See https://github.com/wagmi-dev/wagmi/issues/3144#issuecomment-1773930005

**Comment by meri-maki** [comment]
@Madeindreams you can fork the repo I mentioned above and see if your issue is there too
then you can share it here
