### ISSUE TITLE
bug: useSwitchNetwork doesn't detect chain switch via Web3Modal v3

### ISSUE THREAD

**Issue by meri-maki** [wagmi-dev/wagmi#3145]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

1.4.3

### Current Behavior

I'm using Web3Modal along with wagmi
I'm using default web3modal button to display anf change chain if needed
```
function Chain() {
	return <w3m-network-button />
}
```

I wanted to detect network switch and fire some action, however ```onSuccess``` never fired

```
const network = useSwitchNetwork({
		onSuccess(data) {
			console.log("Success", data)
		},
	})
	
```

I can detect network switch via ```useNetwork``` though but I expected wagmi to detect network switch via Modal

### Expected Behavior

```
const network = useSwitchNetwork({
		onSuccess(data) {
			console.log("Success", data)
		},
	})
```

OnSuccess should fire when you change network via Web3Modal default button (and since they included wagmi hooks in their official docs it should work perfectly)

I'm pretty new to wagmi so I might have done something wrong, I've provided link to github with my minimal build	

### Steps To Reproduce

fork repo or download it - works fine on localhost

npm i
npm start
Connect Wallet  ==> Click on Chain button ==> Switch Chain ===> see nothing log into console

### Link to Minimal Reproducible Example (StackBlitz, CodeSandbox, GitHub repo etc.)

https://github.com/meri-maki/useSwitchNetwork

**Comment by tmm** [comment]
`onSuccess` only fires if you call `switchNetwork` from that specific instance of the hook. It doesn't listen for global changes from other hooks (e.g. from Web3Modal).
