### ISSUE TITLE
Unable to handle transaction error

### ISSUE THREAD

**Issue by Madeindreams** [wagmi-dev/wagmi#3146]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

1.4.4

### Current Behavior

As requested, a code sample to reproduce the behaviour. It is not possible to correctly handle errors on transactions. 

[stackblitz](https://stackblitz.com/edit/new-wagmi-ynhwv8?file=src%2FApp.tsx)

The error we want upstream is the one that is logged by inpage.js

I assume it somehow get lost in wagmi.js.

I am logging the error and also created an error boundary
The console is logging plain text and the error boundary is logging null.

### Expected Behavior

I'm expecting an error object.

Instead i'm getting a plain text message and there is no error code present.

### Steps To Reproduce

Connect your wallet,

Click the Send Transaction button but do not confirm it, instead hit cancel.

This will trigger the 4001 error. And it does. You will see it correctly logged but does not make it upstream.

### Link to Minimal Reproducible Example (StackBlitz, CodeSandbox, GitHub repo etc.)

https://stackblitz.com/edit/new-wagmi-ynhwv8?file=src%2Fcomponents%2FErrorBoundary.tsx

### Anything else?

https://github.com/wagmi-dev/wagmi/blob/b12248167636e413ec2b6f477e3961b190468c04/packages/connectors/src/metaMask.ts#L119

**Comment by jxom** [comment]
Here you go: https://stackblitz.com/edit/new-wagmi-raedjd?file=src%2FApp.tsx,src%2Fcomponents%2FErrorBoundary.tsx,src%2Fmain.tsx

**Comment by Madeindreams** [comment]
Still no error code from the wallet

![image](https://github.com/wagmi-dev/wagmi/assets/17243647/fe5f5bb4-ed42-4778-b48e-56f98bf7b0a6)

But it does catch the error

**Comment by jxom** [comment]
The code is in the error object: 
<img width="124" alt="Screenshot 2023-10-25 at 6 58 15 am" src="https://github.com/wagmi-dev/wagmi/assets/7336481/d6fae564-695c-49d3-8d12-51949b3f8cd2">

**Comment by Madeindreams** [comment]
Yes but this is the log from inpage. It logs it but this is not what we catch in the react app.

**Comment by jxom** [comment]
That is the error I get from logging the object in the ErrorBoundary.

**Comment by Madeindreams** [comment]
OMG Your right. I do get it now.. Did not go far enough in the stack. Thanks for clarifying this.
