### ISSUE TITLE
frequent "transactionNotFoundError"

### ISSUE THREAD

**Issue by dcsan** [wagmi-dev/wagmi#3152]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

1.4.1

### Current Behavior

about 10% of the time I get a `TransactionNotFoundError` when sending on polygon mainnet.
I saw one similar issue with `block not found` and have made sure that we're using a paid alchemy API key and provider.

I'm using `usePrepareContractWrite` and `useWaitForTransaction`

I never see the problem with testnets/ mumbai, only in production polygon mainnet.
and again, it's only about 1 in 10 TXs - but still very frequent.

the transactions DO exist, I can see them on polygonscan.

![image](https://github.com/wagmi-dev/wagmi/assets/514002/dc040c2e-d528-49c7-aa05-c94dae5fb33d)

which exists here:
https://polygonscan.com/tx/0x354c004bf1e6c4759958a29ad7e8d346a3f8de1f46d33869eb355d425b558fa6

the major problem here is that this is *after* metamask has confirmed and the payment is taken out of the user's account.

The app is also using wallet connect to allow a wallet login
I'm in the US on a good network connection.

are there any other params I could play with on the connection? 

I did try messing with some of the params but these settings didn't seem to affect:

```
    useWaitForTransaction({
      hash: contractData?.hash,
      // staleTime: 5000,
      // timeout: 60000,  // 1 minute
      // confirmations: 1,
```

anything else that can be investigated? 

At this point the only reliable solution seems to be to listen for TXs server side and implement my own socket connection to the client.

### Expected Behavior

transactions should not fail locally after taking people's money

### Steps To Reproduce

```
/// config code

export const { chains, publicClient } = configureChains(
  // mainnet, optimism, arbitrum, base, zora
  // [polygon, polygonMumbai],
  AppConfig.chains,
  [
    alchemyProvider({ apiKey: AppConfig.VITE_ALCHEMY_API_KEY }),
  ]
);

const { connectors } = getDefaultWallets({
  appName: "battle-traits",
  projectId: import.meta.env.VITE_WALLET_PROJECT_ID,
  chains,
});

export const wagmiConfig = createConfig({
  connectors,
  publicClient,
  autoConnect: true, // to last connection
});

//// --- calling code

  const { config, error: prepError, isError: isPrepError } = usePrepareContractWrite({
    address: contractAddress,
    abi: abiList,
    functionName: 'battle',
    value: ethers.parseEther(AppConfig.BATTLE_COST),
    // args,
    // chainId: // TODO - enforce correct chain
    // cacheTime: 2_000,
  });
  const contractSetup = useContractWrite(config);
  // execute write function uncontracted
  const contractData = contractSetup?.data;
  const contractWriteFn = contractSetup?.write;
  console.log('contractSetup', { contractSetup, contractData, contractWriteFn });

  // wait until transaction is processed
  const {
    isLoading: isTxLoading,
    isSuccess: isTxSuccess,
    isError: isTxError,
    error: txError } =
    useWaitForTransaction({
      hash: contractData?.hash,
      staleTime: 5000,
      timeout: 60000,  // 1 minute
      confirmations: 1,
      onSuccess(data) {
        // todo - decide if we'll handle here or via useEffect
        handlePaymentSuccess(data);
        console.log('txSuccess', data)
      },
      onError(error) {
        // TODO handle error to client - modal?
        // log
        console.warn('txError', error)
        // throw new Error('payment error')
      },
      onSettled(data, error) {
        console.log('Settled', { data, error })
      },
      onReplaced(data) {
        console.log('Transaction has been sped up', data)
      },
    });
```

**Comment by dcsan** [comment]
related issues / topics:
- https://github.com/wagmi-dev/wagmi/issues/2505
- https://ethereum.stackexchange.com/questions/151125/randomly-getting-errors-on-wagmi-usewaitfortransaction-and-usecontractwrite-hook

**Comment by jxom** [comment]
Thanks for reporting. I cannot seem to reproduce this on my end. Can you please provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) via https://new.wagmi.sh or a separate repo? It will save us a lot of time reproducing your config & environment, and trying to reproduce your issue. See [Why reproductions are required](https://antfu.me/posts/why-reproductions-are-required).

Please reopen this issue when a reproduction is added.

**Comment by jxom** [comment]
Might be worth trying a different RPC Provider for Polygon. Usually, this error occurs due to an RPC Provider's brittle load balancing and caching strategies.

**Comment by dcsan** [comment]
I've found alchemy more stable than infura, what other providers would you recommend? 

for server side we're using openzep's relayers but I don't know a more robust alternative client side.

this is very serious as the failed TXs still take the user's money - as they're not really failing.
