### ISSUE TITLE
bug: Coinbase connector refreshes the page when disconnect

### ISSUE THREAD

**Issue by GFialho** [wagmi-dev/wagmi#3157]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

1.4.5

### Current Behavior

When I use the disconnect hook for coinbase wallet the page gets refreshed.
I searched the code and found that what causes that is the `provider.close()` on the `disconnect` function in `coinbaseWallet.js`
If I comment this code, everything works as supposed

### Expected Behavior

The page should not refresh

**Comment by glitch-txs** [comment]
you can use `reloadOnDisconnect` option in the connector configuration

**Comment by GFialho** [comment]
It is already set to false but the problem still persists

**Comment by tmm** [comment]
Upstream issue https://github.com/coinbase/coinbase-wallet-sdk/issues/1012
