### ISSUE TITLE
bug: after npm run build got viem problem e.walk is not a function

### ISSUE THREAD

**Issue by facilty** [wagmi-dev/wagmi#3158]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

web3modal wagmi"^3.1.0" - wagmi 1.4.5 - viem 1.17.1

### Current Behavior

Error ContractFunctionExecutionError: An unknown error occurred while executing the contract function "totalSupply".

Contract Call:
  address:   0x18A560e4a6dE7476450b05ca871DE2eAE65159c7
  function:  totalSupply()

Docs: https://viem.sh/docs/contract/readContract.html
Details: e.walk is not a function
Version: viem@1.17.1
    at u (main.6596abd5.js:2:735415)
    at main.6596abd5.js:2:664206
    at p (main.6596abd5.js:2:335425)
    at Generator.<anonymous> (main.6596abd5.js:2:336777)
    at Generator.throw (main.6596abd5.js:2:335854)
    at r (main.6596abd5.js:2:329492)
    at u (main.6596abd5.js:2:329731)

### Expected Behavior

with npm start, no one problem detected and all work perfectly

### Steps To Reproduce

//readfunction.js
import { useEffect, useState } from 'react';
import { useContractRead, useBalance } from 'wagmi';

export function TotalSupply() {
    const [totalsupply, settotalsupply] = useState("");
    const contractfacil = Connectiontocontract.facil
    const { data } = useContractRead({
        address: contractfacil.address,
        abi: contractfacil.abi,
        functionName: 'totalSupply',
        watch: true,
        onError(error) {
            console.log('Error', error)
        },
        onSuccess(data) {
            console.log('Success', data)
        },
    });

    useEffect(() => {
        settotalsupply(Number(data) / 10 ** 18)
    }, [data, settotalsupply]);

    return (
        <>
            <p className="supplyfacilfi">Total Supply:</p>
            <p id="supplyfacilfitoken">{totalsupply} FACILFI</p>
            <p id="totalcirculate">CIRCULATE SUPPLY: </p>
            <p id="totalcirculatetoken">{totalsupply}</p>
        </>
    );
}

### Link to Minimal Reproducible Example (StackBlitz, CodeSandbox, GitHub repo etc.)

https://aidogecoin.com/FacilToken

### Anything else?

I am currently attempting to deploy my React app to a website I already have set up, in order to test its functionality. However, upon building and uploading the app to the site, I encounter an issue when trying to interact with the blockchain functions. This issue is unique to the deployed version, as the app functions perfectly when running through 'npm start' in my development environment."

{
  "name": "facildex",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "@web3modal/wagmi": "^3.1.0",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "react-router-dom": "^6.17.0",
    "wagmi": "^1.4.5",
    "web-vitals": "^3.5.0"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject"
  },
  "eslintConfig": {
    "extends": [
      "react-app",
      "react-app/jest"
    ]
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  },
  "devDependencies": {
    "@babel/plugin-proposal-private-property-in-object": "^7.21.11"
  }
}

**Comment by tmm** [comment]
Can you re-open this on the [Viem repo](https://github.com/wagmi-dev/viem) with a minimal reproduction attached? The link you shared does not work.

**Comment by facilty** [comment]
sure! this is a website that im using only for test it. the link is working for me.
