### ISSUE TITLE
bug: not able to switch to Polygon Mumbai using useSwitchNetwork() due to invalid public RPC

### ISSUE THREAD

**Issue by bavzy** [wagmi-dev/wagmi#3164]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.12.12

### Current Behavior

I'm utilizing the "useSwitchNetwork()" function to switch over to the Polygon Mumbai network. Typically, this operation is carried out by users who haven't previously added the Polygon Mumbai network to their MetaMask wallet, necessitating the addition of a new network. However, because the hook consistently relies on the Public RPC, and configuring the chain using the jsonRpcProvider doesn't have any impact (as it alters the default RPC, which isn't suitable in this scenario), it appears that there's no direct and uncomplicated method to accomplish this.

Here's my code to configure the Polygon Mumbai RPC:
```
const { chains } = configureChains(
  [polygonMumbai],
  [
    jsonRpcProvider({
      rpc: (chain) => ({
        http: 'https://rpc-mumbai.maticvigil.com'
      })
    }),
    infuraProvider({ apiKey: XXX })
  ]
)
```

```
const { isLoading, switchNetwork } = useSwitchNetwork({
    chainId: 80001
  })
```

### Expected Behavior

Users should have the ability to use the "useSwitchNetwork()" function to transition to the Polygon Mumbai network, even if it isn't already present in their MetaMask network configurations.

### Steps To Reproduce

1. Set up a custom RPC provider in the configureChains function specifically for the Mumbai network. This sets the default RPC URL as the custom URL.
2. Delete the Mumbai network from your MetaMask wallet networks.
3. Finally, invoke the "switchNetwork" function from the "useSwitchNetwork" React hook. This action should trigger a "Allow this site to add a network?" dialog in your MetaMask extension, displaying the RPC URL as "https://matic-mumbai.chainstacklabs.com/." It will also show an error message stating, "According to our records the submitted RPC URL value does not match a known provider for this chain ID."

**Comment by tmm** [comment]
Seems more related to how MetaMask handles this. Chains are managed in [Viem](https://github.com/wagmi-dev/viem) if you think changes are required there.

**Comment by danilo-89** [comment]
@bavzy , Polygon Mumbai has been experiencing recurring issues with RPCs lately, notably, issues with the MetaMask extension arise when an invalid RPC is provided. To resolve this problem in wagmi, you should define a custom chain.

```
const preferredChain = defineChain({
    ...polygonMumbai,
    rpcUrls: {
        ...polygonMumbai.rpcUrls,
        default: {
            http: [RPC_PUBLIC],
        },
        public: {
            http: [RPC_PUBLIC],
        },
    },
})

const { chains, publicClient, webSocketPublicClient } = configureChains(
    [preferredChain],
    [
        publicProvider(),
        alchemyProvider({ apiKey: process.env.NEXT_PUBLIC_ALCHEMY || '' }),
    ]
)
```

because you are using older version of wagmi, you can probably define custom chain in this way
```
const preferredChain = {
    ...polygonMumbai,
    rpcUrls: {
        ...polygonMumbai.rpcUrls,
        default: {
            http: [RPC_PUBLIC],
        },
        public: {
            http: [RPC_PUBLIC],
        },
    },
}
```
