### ISSUE TITLE
bug: Value ignored (usePrepareContractWrite)

### ISSUE THREAD

**Issue by tjelz** [wagmi-dev/wagmi#3168]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

1.4.2

### Current Behavior

const { config } = usePrepareContractWrite({
address: "...",
abi: ...,
functionName: "...",
args: [args],
value: parseEther("0.1"),
})

Using this code, the value property is being ignored, so when trying to call a payable function, no value is being passed up to it.

### Expected Behavior

I would expect the value in ETH to be send to the payable contract function

### Steps To Reproduce

Using the following code, I should expect to be able to pass a value to the payable contract function:

const { config } = usePrepareContractWrite({
address: "...",
abi: ...,
functionName: "...",
args: [args],
value: parseEther("0.1"),
})

const { write } = useContractWrite(config)

write?.()

**Comment by tmm** [comment]
Thanks for reporting. This issue is temporarily closed due to lack of information. Please provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) and reopen this issue.
