### ISSUE TITLE
bug: Wrong chain name for Polygon Mainnet

### ISSUE THREAD

**Issue by ennioVisco** [wagmi-dev/wagmi#3171]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

1.4.3 (core)

### Current Behavior

Wagmi chain has the wrong name for the Polygon Mainnet.

Current:
![image](https://github.com/wagmi-dev/wagmi/assets/740025/80b46494-68d0-4dce-ad8e-8e12c3268d6f)

### Expected Behavior

The correct one should be `Polygon Mainnet`:
![image](https://github.com/wagmi-dev/wagmi/assets/740025/0bd34609-dd5a-48be-bcb2-6f8b9f42feb3)

### Steps To Reproduce

- Correct name: add the chain via https://chainlist.wtf/
- Wrong name: add the chain via wagmi

**Comment by tmm** [comment]
Feel free to create a PR on the [Viem repo](https://github.com/wagmi-dev/viem).
