### ISSUE TITLE
bug: Fail to compile with nextjs 14

### ISSUE THREAD

**Issue by marcolivierbouch** [wagmi-dev/wagmi#3178]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

1.4.5

### Current Behavior

When I use wagmi in a new nextjs 14 project I get this error. Is there anything I can do to fix this?

```
./node_modules/wagmi/dist/chains.js
Error: It's currently unsupported to use "export *" in a client boundary. Please use named exports instead.
```

### Expected Behavior

The project to build correctly

### Steps To Reproduce

1. Create a nextjs project
2. `npm install @web3modal/wagmi wagmi viem`
3. Do basic implementation step

**Comment by glitch-txs** [comment]
Hi, how are you exporting chains?

**Comment by lesser-P** [comment]
I also encountered this issue in next14 when using Rainbowkit. Have you resolved it

**Comment by hangleang** [comment]
I also encountered the same issue in nextjs 14 (14.0.3 to be specific)

**Comment by alihassan18** [comment]
webpack: (config) => {
  config.externals.push("pino-pretty", "lokijs", "encoding");
  return config;
};

Add this code in the next.config.js file it will fix your issue.
