### ISSUE TITLE
bug: `stallTimeout` property missing in `JsonRpcProviderConfig`

### ISSUE THREAD

**Issue by toniocodo** [wagmi-dev/wagmi#3179]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

1.4.5

### Current Behavior

The `stallTimeout` property  appears to be missing in a `JsonRpcProviderConfig` as explained [here](https://wagmi.sh/react/providers/jsonRpc#stalltimeout-optional) in the documentation. 

![image](https://github.com/wagmi-dev/wagmi/assets/13216617/83902028-44d1-4b34-bca5-08b576329735)

### Expected Behavior

If this feature is still supported, the types should allow passing this configuration property

### Steps To Reproduce

Reproduce the [documentation example](https://wagmi.sh/react/providers/jsonRpc#stalltimeout-optional)

```
import { chain, configureChains } from 'wagmi'
import { jsonRpcProvider } from 'wagmi/providers/jsonRpc'
 
const { chains, publicClient } = configureChains(
  [chain.mainnet, chain.polygon],
  [
    jsonRpcProvider({
      rpc: (chain) => ({
        http: `https://${chain.id}.example.com`,
        webSocket: `wss://${chain.id}.example.com`,
      }),
      stallTimeout: 1000,
    }),
    alchemyProvider({ stallTimeout: 1000 }),
  ],
)
```

**Comment by tmm** [comment]
Docs are incorrect. This is a third parameter on `configureChains`.

```ts
const { chains, publicClient, webSocketPublicClient } = configureChains(
  [mainnet, goerli, optimism, avalanche],
  [
    alchemyProvider({ apiKey: process.env.NEXT_PUBLIC_ALCHEMY_API_KEY! }),
    infuraProvider({ apiKey: process.env.NEXT_PUBLIC_INFURA_API_KEY! }),
    publicProvider(),
  ],
  {
    stallTimeout: 1_000, // <----------------
  }
)
```
