### ISSUE TITLE
bug: Error: (0 , wagmi_providers_public__WEBPACK_IMPORTED_MODULE_3__.publicProvider) is not a function

### ISSUE THREAD

**Issue by ereynier** [wagmi-dev/wagmi#3182]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

1.4.5

### Current Behavior

With NextJS 14.0.1, I followed the "getting started" guide and I have the following error
```
Server Error

Error: (0 , wagmi_providers_public__WEBPACK_IMPORTED_MODULE_3__.publicProvider) is not a function

  16 | const { chains, publicClient, webSocketPublicClient } = configureChains(
  17 |   [mainnet],
> 18 |   [publicProvider()],
     |                 ^
  19 | )
  20 |  
  21 | const config = createConfig({
  ```

### Expected Behavior

No error

### Steps To Reproduce

- `pnpx create-next-app`
- follow the "getting started" guide https://wagmi.sh/react/getting-started and place it in layout.tsx like that
```
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { WagmiConfig, createConfig, configureChains, mainnet } from 'wagmi'
import { publicProvider } from 'wagmi/providers/public'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const { chains, publicClient, webSocketPublicClient } = configureChains(
  [mainnet],
  [publicProvider()],
)

const config = createConfig({
  autoConnect: true,
  publicClient,
  webSocketPublicClient,
})

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <WagmiConfig config={config}>
          {children}
        </WagmiConfig>
      </body>
    </html>
  )
}

```
- `pnpm next dev`

**Comment by glitch-txs** [comment]
are you using "use client" directive?

**Comment by tmm** [comment]
Bundler issue

**Comment by ombayoeco11** [comment]
> Bundler issue

is there any fixes? or how to solve this?

**Comment by dodocie** [comment]
got same problem, tried next-app version 13.1.6, and old wagmi@1.3.10 & viem@1.5.4, not work.

**Comment by ombayoeco11** [comment]
> got same problem, tried next-app version 13.1.6, and old wagmi@1.3.10 & viem@1.5.4, not work.

On my case is first issue is in wagmi/chain so i created the Chain myself. Another problem is this one 

Server Error
Error: (0 , wagmi_providers_public__WEBPACK_IMPORTED_MODULE_2__.publicProvider) is not a function

This error happened while generating the page. Any console logs will be displayed in the terminal window.
Source
app\wagmiConfig.js (13:17) @ publicProvider

  11 | const { chains, publicClient, webSocketPublicClient } = configureChains(
  12 | [bsc],
> 13 | [publicProvider()],
     |               ^
  14 | )
  
is there anyone can solve this problem?

**Comment by DiasNabil** [comment]
for my case a import from '@wagmi/core' the functions that returned that error

**Comment by alihassan18** [comment]
webpack: (config) => {
  config.externals.push("pino-pretty", "lokijs", "encoding");
  return config;
};

Add this code in the next.config.js file it will fix your issue.
