### ISSUE TITLE
bug: Socket stalled when trying to connect to wss://relay.walletconnect.org

### ISSUE THREAD

**Issue by dsldsl** [wagmi-dev/wagmi#3183]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

1.4.5

### Current Behavior

I get an unhandled runtime error after page loading.

Seems to be this issue: https://github.com/wagmi-dev/references/issues/427

Is there a certain version number I need to be over?  I was using 1.3.11 and just upgraded to 1.4.5 and issue seems to still be present.

I do have project id set.  Any other suggestions?

**Comment by tmm** [comment]
Wagmi doesn't control this. Check with WalletConnect.
