### ISSUE TITLE
ContractFunctionExecutionError: The contract function "reverse" reverted with the following reason: Internal errorbug: <title>

### ISSUE THREAD

**Issue by fhrryDeveloper** [wagmi-dev/wagmi#3184]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

1.3.9

### Current Behavior

I am using web3modal and wagmi on my react project (wallet connect v2)
But I have the following error. It doesn't happen before. Help me!
![image](https://github.com/wagmi-dev/wagmi/assets/72539001/99227c33-a66e-4dd4-b0fc-56fb3594217a)

**Comment by tmm** [comment]
Thanks for reporting. This issue is temporarily closed due to lack of information. Please provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) and reopen this issue.

**Comment by jxom** [comment]
Most likely because https://cloudflare-eth.com RPC is down at the moment. Best to use a non-public RPC provider.

**Comment by fhrryDeveloper** [comment]
OK thanks

**Comment by fhrryDeveloper** [comment]
Please let me know non-rpc provider
