### ISSUE TITLE
Unable to fetch balance using Ethereum main network, but working with other networks.

### ISSUE THREAD

**Issue by amandeep-coolplugin** [wagmi-dev/wagmi#3189]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

1.4.3

### Current Behavior

Using this function to fetch the ethererum network balance
import { fetchBalance } from '@wagmi/core'

const balance = await fetchBalance({
  address: '0xA0Cf798816D4b9b9866b5330EEa46a18382f251e',
})

https://prnt.sc/CGxrRKo7LA3R

### Expected Behavior

Should fetch the balance.

### Steps To Reproduce

Using this function to fetch the ethererum network balance
import { fetchBalance } from '@wagmi/core'

const balance = await fetchBalance({
  address: '0xA0Cf798816D4b9b9866b5330EEa46a18382f251e',
})

https://prnt.sc/CGxrRKo7LA3R

**Comment by jxom** [comment]
Thanks for reporting. This issue is temporarily closed due to lack of information. Please provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) and reopen this issue.
