### ISSUE TITLE
bug: useContractReads doesn't read all contracts (different chains) at once 

### ISSUE THREAD

**Issue by meri-maki** [wagmi-dev/wagmi#3203]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Package Version

1.4.3

### Current Behavior

I'm calling ```useContractReads``` to check if user has any NFT on ANY contract (on 4 different chains)
The contracts are exactly the same (abi) except for the ```address``` and are on Ethereum, Polygon, BNB Smart Chain and Arbitrum One

```
const abi = [
		{
			inputs: [{ internalType: "address", name: "owner", type: "address" }],
			name: "tokensOfOwner",
			outputs: [{ internalType: "uint256[]", name: "", type: "uint256[]" }],
			stateMutability: "view",
			type: "function",
		},
	]

	const read = useContractReads({
		suspense: true,
		enabled: enableRead,
		contracts: [
			{
				address: "0x49cC7de889C1e4bDc1b4156B882cA5c76C668987",
				abi: abi,
				functionName: "tokensOfOwner",
				args: [address],
			},
			{
				address: "0xA42ccA468fd07491824Ab121CB559f1B3791e92C",
				abi: abi,
				functionName: "tokensOfOwner",
				args: [address],
			},
			{
				address: "0x6f2C97dB74D4d3E8A31e628325A39bbef928dd59",
				abi: abi,
				functionName: "tokensOfOwner",
				args: [address],
			},
			{
				address: "0xFA17c9e4f5Ec1A62d032731fE0a9529D7B851BE6",
				abi: abi,
				functionName: "tokensOfOwner",
				args: [address],
			},
		],
		onSuccess(data) {
			console.log(data)
			const successArray = data.filter((item) => item.status === "success")
			setSuccessCount(successArray.length)
		},
	})
```

I'm also using web3modal and set default chain to Ethereum
When user connects, they get switched to Eth and the hook runs with **only** checking contracts on ETH and ARBITRUM

![Снимок экрана 2023-11-08 в 17 04 31](https://github.com/wagmi-dev/wagmi/assets/97887955/09e0d5bf-68ed-4eaa-9801-91cc3037a6b2)

If you switch chain to Polygon, the hook will only check contract on Polygon while others would have this error:

![Снимок экрана 2023-11-08 в 17 04 15](https://github.com/wagmi-dev/wagmi/assets/97887955/9a12a430-1c97-489b-810a-7ca827a521c8)

```
"The contract function "tokensOfOwner" returned no data ("0x").

This could be due to any of the following:
  - The contract does not have the function "tokensOfOwner",
  - The parameters passed to the contract function may be invalid, or
  - The address is not a contract.
 
Contract Call:
  address:   0x6f2C97dB74D4d3E8A31e628325A39bbef928dd59
  function:  tokensOfOwner(address owner)
  args:                   (0x3AcF77a2A3bFC198D5343e420B53AbE0a5f79e9C)

Docs: https://viem.sh/docs/contract/multicall.html
Version: viem@1.16.5"
```

I think this is also a related issue: https://github.com/wagmi-dev/wagmi/issues/3201

### Expected Behavior

The hook should check all contracts despite user being connected to specific chain

### Steps To Reproduce

minimal reproduction: https://github.com/meri-maki/useSwitchNetwork/blob/main/src/ConnectButton.jsx
demo: https://wagmi-read.vercel.app/

You can open demo, connect wallet
you will be switched/connected to ETH
You will see how many contracts have been checked

![Снимок экрана 2023-11-08 в 16 58 32](https://github.com/wagmi-dev/wagmi/assets/97887955/88b10959-4f09-48d2-9543-56ffb001628e)

Switch to Polygon
See that only 1 contract has been checked
![Снимок экрана 2023-11-08 в 17 00 20](https://github.com/wagmi-dev/wagmi/assets/97887955/f8f3d78f-7593-45c1-a5de-7cfaa36034cd)

### Link to Minimal Reproducible Example (StackBlitz, CodeSandbox, GitHub repo etc.)

https://github.com/meri-maki/useSwitchNetwork/blob/main/src/ConnectButton.jsx

### Anything else?

		"viem": "^1.16.2",
		"wagmi": "^1.4.3"
		
		Latest versions of packages didn't help
		
		Using useContractRead didn't help
		Using only alchemy or infura didn't help

**Comment by tura11541** [comment]
Ok listen I am the owner creater .
Why are you guys helping this girl my ex to hack and still everything my
life means .. she couldn't even tell you the meaning of my art and it's
purpose ..
Stop helping these people still from me or I will do the best I can to sue
you and your organization...

**Comment by tura11541** [comment]
Please scan the questions she's asking you and be a better judge of her
questions in her intent you f****** are wrong

**Comment by meri-maki** [comment]
What😆😆😆

**Comment by tmm** [comment]
You need to add [`chainId`](https://wagmi.sh/react/hooks/useContractReads#chainid-optional) to each `contracts` item if you want to target a specific chain.
