### ISSUE TITLE
useChainId returning the wrong chainId after switching networks with useSwitchNetwork

### ISSUE THREAD

**Issue by tommaay** [wagmi-dev/wagmi#3205]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

1.4.6

### Current Behavior

// Before switching networks
const chainId = useChainId(); // value is 1
const { switchNetwork } = useSwitchNetwork();
await switchNetwork(10);

// After network switch is successful
const chainId = useChainId(); // value is 137

### Expected Behavior

The value of chainId using the usChainId() hook should be 10.

**Comment by tmm** [comment]
Thanks for reporting. This issue is temporarily closed due to lack of information. Please provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) and reopen this issue.
