### ISSUE TITLE
bug: usePrepareContractWrite doesn't resolve; perpetually stuck in status loading

### ISSUE THREAD

**Issue by drew-w** [wagmi-dev/wagmi#3206]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

1.4.6

### Current Behavior

When calling generated hook `usePrepareRewardNftSafeMint`, the query never resolves to neither success or error, it is stuck in a loading state without giving any information as to why. The process to get approval works just fine, I will post approval and minting steps below.

### Expected Behavior

I expect the query to resolve to either a success or error state.

### Steps To Reproduce

```
  const approvePrep = usePrepareRewardTokenApprove({
    enabled: true
    address: "0x799563961b124B98a1Dd5C882CBDAe930f841792",
    args: ["0x799563961b124B98a1Dd5C882CBDAe930f841792", 250000000000n]
  })

  const approveMutation = useRewardTokenApprove(approvePrep.config)
  const { isSuccess: approveSuccess } = useWaitForTransaction({
    hash: approveMutation.data?.hash
  })

  const safeMintPrep = usePrepareRewardNftSafeMint({
    enabled: true,
    address: "0x799563961b124B98a1Dd5C882CBDAe930f841792",
    args:  [
    "0x4921dE5bA3d015BF73623533170827b6dc14d3b3", //my staging wallet
    "0755f70c-0d09-4484-881c-92fd1f22f485",
    "0xc1C39Cf2303AA340f2ac7404E831b2d19fB6a860"
  ]
  })
```
[rewardNftABI.json](https://github.com/wagmi-dev/wagmi/files/13314139/rewardNft.json)
[rewardsTokenABI(erc20).json](https://github.com/wagmi-dev/wagmi/files/13314178/rewardsTokenABI.erc20.json)

### Anything else?

We have no issue approving or staking NFTs so far using the same setup as listed above.

**Comment by tmm** [comment]
Can you create a minimal reproducible example with what you provided above? [new.wagmi.sh](https://new.wagmi.sh) is fine. Then you can re-open this issue.
