### ISSUE TITLE
bug: <useChainId> The value of useChainId does not change when the chain id changes.

### ISSUE THREAD

**Issue by unicape** [wagmi-dev/wagmi#3215]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

2.0.0.beta.3

### Current Behavior

The value of useChainId does not change when the chain id changes.

### Expected Behavior

When the chain is modified in the wallet, the result returned by useChainId changes accordingly.

**Comment by tmm** [comment]
Works fine for me. Mind sharing some more info on how to reproduce (what wallet are you using, config, etc.)?

**Comment by tmm** [comment]
Closing for now. Feel free to share some more details/minimal reproduction and I'm happy to look into it more.

**Comment by unicape** [comment]
https://github.com/wagmi-dev/wagmi/blob/beta/playgrounds/vite-react/src/App.tsx

@tmm  You are using the official playground. If you use the return value of useChainId, you can reproduce this problem.

**Comment by tmm** [comment]
It changes for me when I connect a wallet and switch chains. What wallet are you using?

**Comment by unicape** [comment]
> 当我连接钱包并切换链时，它对我来说发生了变化。你用什么钱包？

metamask

**Comment by unicape** [comment]
> It changes for me when I connect a wallet and switch chains. What wallet are you using?

![image](https://github.com/wagmi-dev/wagmi/assets/31918458/40e6ded7-24c3-4a75-90ae-8de1ad44f39c)
<img width="472" alt="image" src="https://github.com/wagmi-dev/wagmi/assets/31918458/27e7bb08-a263-4378-8d17-5b910a7950e5">

**Comment by tmm** [comment]
Have you configured chain `280` via `createConfig`? Otherwise, `useChainId` falls back to the first chain in `createConfig#chains`.
