### ISSUE TITLE
bug: useWaitForTransaction gives `isError:true` and stop waiting while transaction is finally added to block.

### ISSUE THREAD

**Issue by pociej** [wagmi-dev/wagmi#3228]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

1.4.3

### Current Behavior

It happens already 3 times `useWaitForTransaction` and, kill me but i didnt record the exact error that was throw to the console but here what happens 

```
  const { isSuccess, isError } = useWaitForTransaction({
    hash: hash,
  })
```

it sometimes happen that isError comes to true and then it stops waiting while it is possible that transaction anyway is added to the block after initial troubles. I didn't find exact problematic code but 99% its somewhwere in viem ( so maybe i should post issue also there? )

To monitor things beside useWaitForTransaction i used brutal poling 

```
const publicClient = usePublicClient()
const interval = setInterval(() => {
  publicClient
    .getTransactionReceipt({ hash })
    .then((receipt) => {
      if (receipt.status === 'success') {
        setStatus(TxStatus.SUCCESS)
        clearInterval(interval)
      }
    })
    .catch((err) => {
      log('transaction not ready yet')
    })
}, 1000)

```

this works because it keep polling. However, probably there are errors that should make code sure that there is no point in waiting anymore. From other hand there are error that cause `useWaitForTransaction` to resolve into `isError : true` and stop working. 

### Expected Behavior

`useWaitForTransaction` properly keep waiting if there is still chance to attach transaction to the block. 

### Steps To Reproduce

This happens to me only on polygon. On mumbai everything works fine so Im working  now creating some solution that will allow me mock error responses on test net and I will be able to reproduce without bankrupting on gas fees.

**Comment by tmm** [comment]
Thanks for reporting. This issue is temporarily closed due to lack of information. Please provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) and reopen this issue.
