### ISSUE TITLE
[bug] jsonRpcProvider polls for both current network and previous network

### ISSUE THREAD

**Issue by mihoward21** [wagmi-dev/wagmi#651]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.5.5

### Current Behavior

As I switch between networks while connected to my dapp, I see the polling requests being sent for both the current chain and the previous chain.

### Expected Behavior

Requests should only be sent for the currently selected chain.

### Steps To Reproduce

1. Load up dapp with wallet connected on mainnet. See polling requests being sent to the mainnet rpc url.
2. Switch network from mainnet to goerli. See polling requests being sent to both the goerli rpc url and the mainnet rpc url.
3. Switch network from goerli to mumbai. See polling requests being sent to both the mumbai rpc url and the goerli rpc url (the polling requests to mainnet stop).

Here's my json rpc provider config:
```
jsonRpcProvider({
  rpc: (chain) => {
    const rpcUrl = CHAIN_INFO[chain.id].rpcUrl
    const websocketUrl = CHAIN_INFO[chain.id].websocketUrl

    return {
      http: rpcUrl,
      webSocket: websocketUrl ? websocketUrl : undefined,
    }
  },
  pollingInterval: RPC_POLLING_RATE_MS,
  priority: 1,
  static: false,
})
```

I'm using the `switchNetworkAsync` function from `useSwitchNetwork` to change networks. And not sure if it matters, but for my testing I was connected to coinbase wallet.

**Comment by jxom** [comment]
I'm having trouble reproducing this one! Could you create a reproducible example on CodeSandbox and then re-open the issue? Thanks!
