### ISSUE TITLE
[bug] Wallet connect signer doesn't support signTransaction

### ISSUE THREAD

**Issue by cattingcat** [wagmi-dev/wagmi#731]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

^0.5.9

### Current Behavior

```
  const provider = await connector.getProvider();
  const signer = await connector.getSigner();

  // this way to sign doesn't work at all, just returns 'UNSUPPORTED_OPERATION' or something like this
  const s = await signer.signTransaction({
    to: addr,
    from: userAddress,
    gasLimit: gasLimit,
    data: swapDescription,
  });

  // This one sends notification to my mobile, but doesn't work too for another reason (screenshot below)
  const r = await provider.request({
    method: 'eth_signTransaction',
    params: {
      to: addr,
      from: userAddress,
      gas: gasLimit,
      data: swapDescription,
      gasPrice: '0x9999'
    },
  });
  ```
![2022-07-19 16 12 21](https://user-images.githubusercontent.com/5341725/179758589-91c42bd0-a3c4-4127-9119-a79666188429.jpg)

### Expected Behavior

signTransaction for wallet connect should work fine (example apps: 1inch, it has WC integration and it is possible to send tx via flashbots)

### Link to Minimal Reproducible Example (CodeSandbox, StackBlitz, etc.)

[repo](https://github.com/cattingcat/template-react-crypto-app)

**Comment by cattingcat** [comment]
useSigner hook works the same way as first example

**Comment by tmm** [comment]
Please add a minimal reproducible example and re-open.

**Comment by jxom** [comment]
Yeah `UNSUPPORTED_OPERATION` on `signer.signTransaction` is expected as the ethers `JsonRpcSigner` doesn't support the method.

However, it should still work via a vanilla `request`.

Can you try this:

```tsx
const r = await signer.provider.request({
  method: 'eth_signTransaction',
  params: {
    to: addr,
    from: userAddress,
    gas: gasLimit,
    data: swapDescription,
    gasPrice: '0x9999'
  },
});
```

Note: try `signer.provider` instead of `provider`. 

Re-open if it still doesn't work!

**Comment by cattingcat** [comment]
Hi @jxom 

I tried your example. But there are those problems:
- signer.provider doesn't have request function in types (because there is base provider class) and there is no such function in runtime in JS console
- Also I tried 
```
    const provider = (signer!.provider! as any).provider;
    const r = await provider!.request({ ... });
```
and it produce error modal from op-post (Ethereum is different with Ethereum)


And it seems quite strange that `signer` doesn't support `sign` :)

**Comment by cattingcat** [comment]
https://github.com/cattingcat/template-react-crypto-app/blob/master/src/App.tsx#L69 
Added example here

**Comment by cattingcat** [comment]
@jxom  I think I can't reopen issues closed by collaborators or something like this

**Comment by jxom** [comment]
Hey @cattingcat,

Sorry I only just got the time to have a look into this. For now, you may have to try hook into the `WalletConnectProvider` instance on the Wallet Connect connector.

Example:

```tsx
const { connector } = useAccount()

// ...

const provider = await connector?.getProvider()
const test = await provider.request({
  method: 'eth_signTransaction', 
  params: [{
    to: '0xA0Cf798816D4b9b9866b5330EEa46a18382f251e',
    from: '0xa5cc3c03994DB5b0d9A5eEdD10CabaB0813678AC',
    value: '0x0'
  }]
})
```

**Comment by cattingcat** [comment]
Yep, it works thanks :) 
Just in case if somebody will have the same issue as here:
all tx values even gas should be in HEX format (I spent some time debugging issue with it)

Also Is it possible to migrate to signTransaction function sometime?
