### ISSUE TITLE
[bug] ConnectorNotFoundError: Connector not found

### ISSUE THREAD

**Issue by carlomigueldy** [wagmi-dev/wagmi#741]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.5.11

### Current Behavior

Migrated from `^0.4.1` to `^0.5.11` recently and have all in the codebase update its hooks, then right now our authentication flow is to connect to wallet and call `signMessage`, by the time it does that it throws the error. And so we couldn't let our users login into our dApp.

### Expected Behavior

To call the `signMessage` mutation function without throwing exception then a MetaMask prompt to confirm singing the message

### Steps To Reproduce

Use the hook `useSignMessage()` and setup wagmiClient using `InjectedConnector` as first index pass along supported chains (any chains) then just sign any random message string

We can't share our codebase to Sandbox as we got it in a private repository

### Anything else?

<img width="526" alt="Screen Shot 2022-07-21 at 10 43 12 AM" src="https://user-images.githubusercontent.com/45052332/180118688-c15120ec-7b9e-4907-a64e-677fd4ac32ee.png">

<img width="373" alt="Screen Shot 2022-07-21 at 10 43 06 AM" src="https://user-images.githubusercontent.com/45052332/180118683-d8d79830-bc97-4b6e-bfec-7f8fd0a7224a.png">

<img width="1287" alt="Screen Shot 2022-07-21 at 10 42 45 AM" src="https://user-images.githubusercontent.com/45052332/180118596-3a8d3178-8bc6-480c-8ce7-d5163646e573.png">

**Comment by carlomigueldy** [comment]
issue resolved, dumb logical mistake on my end due to rushing things :)

**Comment by sivaram-undefy** [comment]
> issue resolved, dumb logical mistake on my end due to rushing things :)

@carlomigueldy How did you fix this issue?. I am also facing the same.

**Comment by supriyaamisshra** [comment]
what was the logical mistake? - i am facing this and maybe your experience will help

**Comment by youthinn** [comment]
> 问题已解决，由于匆忙的事情，我最后犯了愚蠢的逻辑错误:)

![image](https://github.com/wagmi-dev/wagmi/assets/96770326/c47fe43c-0e54-4a31-b2a0-0e2f9bb8907a)
How did it work? I currently report this bug when sending transactions on the web

**Comment by Kais3rP** [comment]
I suggest you to use the async version of connect `asyncConnect` and only after call any other method that relias on the connector to be properly initialized like `signMessageAsync`.
