### ISSUE TITLE
[bug] `useContractReads` does not run on initial (not-connected) load while `useContractRead` does.

### ISSUE THREAD

**Issue by akshatmittal** [wagmi-dev/wagmi#756]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.5.11

### Current Behavior

`useContractRead` runs on the initial load (correctly) when the user wallet is not connected while `useContractReads` does not.

### Expected Behavior

`useContractReads` should also read contract values and return appropriate values like `useContractRead` does.

### Steps To Reproduce

Try using `useContractRead` and `useContractReads` _without_ connecting a wallet. Only `useContractRead` will return the data.

**Comment by tmm** [comment]
Thanks for reporting. This issue is temporarily closed due to lack of information. Please provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) and reopen this issue.

**Comment by akshatmittal** [comment]
Minimal Reproducible Example: https://codesandbox.io/s/rainbowkit-nextjs-forked-63n2rs?file=/pages/day/index.js

This is possibly a parsing issue actually, since it returns `null` instead of `undefined`. Also, in this minimal example `useContractReads` works while `useContractRead` doesn't, which is the opposite of what happens when I try locally.

**Comment by jxom** [comment]
Good spot! This is fixed on `0.5.12`.
