### ISSUE TITLE
[bug] `sendTransaction` is not working with `recklesslySetUnpreparedRequest`

### ISSUE THREAD

**Issue by bigint** [wagmi-dev/wagmi#768]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.6.0

### Current Behavior

When clicking the button that is bind with `sendTransaction` with `recklesslySetUnpreparedRequest` is not opening the wallet transaction

```ts
sendTransaction?.({
  recklesslySetUnpreparedRequest: {
    from: data?.from,
    to: data?.to,
    data: data?.data
  }
})
```

### Expected Behavior

It should open the wallet for txn

**Comment by sasicodes** [comment]
+1

**Comment by tmm** [comment]
Can you attach a minimal reproducible example?

**Comment by bigint** [comment]
@tmm If we add mode it's working, but it is not mentioned in the changelog or docs 🙈
