### ISSUE TITLE
[bug] "crypo" not found for React Native expo

### ISSUE THREAD

**Issue by kdong007** [wagmi-dev/wagmi#772]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.6

### Current Behavior

```
  node_modules
  ../node_modules
   5 | Object.defineProperty(exports, "__esModule", { value: true });
   6 | exports.randomBytes = void 0;
>  7 | const crypto_1 = __importDefault(require("crypto"));
     |                                           ^
   8 | const encoding_1 = require("@walletconnect/encoding");
   9 | function randomBytes(length) {
  10 |     const buf = crypto_1.default.randomBytes(length);
```

### Steps To Reproduce

1. ReactNative + expo
2. setup wagami with noopstorage
3. run and crash..

**Comment by tmm** [comment]
Looks related to this https://github.com/WalletConnect/walletconnect-monorepo/issues/595 on the WalletConnect side.
