### ISSUE TITLE
[bug] No Optimism Goerli support

### ISSUE THREAD

**Issue by wmn-at-strands** [wagmi-dev/wagmi#786]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

latest

### Current Behavior

No network details Optimism Goerli in custom npm package (`wagmi-chains.cjs.js` or `wagmi-chains.esm.js`) used to get chain information

### Expected Behavior

Network details Optimism Goerli in custom npm package so Optimism Goerli is listed as an available chain in `@wagmi` package

### Steps To Reproduce

n/a

### Link to Minimal Reproducible Example (CodeSandbox, StackBlitz, etc.)

n/a

### Anything else?

n/a

**Comment by tmm** [comment]
Will be available once #785 is merged in.
