### ISSUE TITLE
[bug] `useAccount` causes an Hydration Error when using with next.js

### ISSUE THREAD

**Issue by ottodevs** [wagmi-dev/wagmi#792]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.6.0

### Current Behavior

When conditionally rendering a component depending on `isConnected` value
![image](https://user-images.githubusercontent.com/5030059/182103977-663d12d7-e0f7-4145-a1e8-19f3265daa3f.png)

The component is conditionally rendered this way:
![image](https://user-images.githubusercontent.com/5030059/182103822-d792f655-eb79-446d-b539-cff85cc4a740.png)

As soon as the user refreshes the page after connecting, next.js shows an Hydration Error, like this one:
![image](https://user-images.githubusercontent.com/5030059/182103215-c57c3fc0-ecd8-49ee-a8a6-9bcd4ea1c3f3.png)

Temporary fix:
Wrapping the `isConnected` value in a `useEffect` solves the issue, like this way:
![image](https://user-images.githubusercontent.com/5030059/182103501-8ca94c78-85c3-40e1-b35f-2a7fcbdfdea2.png)

Then depending on `connected` to conditionally render the component, instead of directly `isConnected` from `useAccount`:
![image](https://user-images.githubusercontent.com/5030059/182103692-c437c71f-cbc7-4680-ac4e-07ee178b757b.png)

### Expected Behavior

It should not be any Hydration issue.

### Steps To Reproduce

I used the example from `https://github.com/rainbow-me/rainbowkit/tree/main/examples/with-next-mint-nft` to reproduce the error.

I uploaded to codesandbox, [here](https://codesandbox.io/s/wagmi-repro-lfjezh?file=/pages/index.tsx:632-672)

Steps:
1. Open the codesandbox example link or download the rainbowkit example from their repo and run.
2. Click "Connect Wallet"
3. Once connected with a wallet, try to refresh the page, the error will happen.

https://user-images.githubusercontent.com/5030059/182113193-42e0cc57-33f4-4625-a29a-6292a2b36396.mov

### Link to Minimal Reproducible Example (CodeSandbox, StackBlitz, etc.)

https://codesandbox.io/s/wagmi-repro-lfjezh?file=/pages/index.tsx:632-672

**Comment by jxom** [comment]
Hey, check out https://github.com/wagmi-dev/wagmi/issues/542#issuecomment-1144178142 for a solution.
