### ISSUE TITLE
[bug] infinite re-render / fetching with preact and vite

### ISSUE THREAD

**Issue by filoozom** [wagmi-dev/wagmi#797]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.6.0

### Current Behavior

Using hooks causes the component to re-render infinitely, and `wagmi` continuously keeps re-fetching the data from the RPC, with the most basic component:
```tsx
const Component = () => {
  const balance = useBalance({
    addressOrName: constants.AddressZero,
    cacheTime: 30_000, // same without this
  });
  console.log(balance);
  return null;
};
```
This prints the `useBalance` constantly and also fetches data from the RPC continuously.

### Expected Behavior

The `useBalance` hook should fetch data once and then stop re-rendering and polling the RPC.

### Steps To Reproduce

```sh
git clone https://github.com/filoozom/wagmi-bug
cd wagmi-bug
npm i
npm run dev
```
then open the browser console.

The code is mostly in https://github.com/filoozom/wagmi-bug/blob/main/src/app.tsx.

### Link to Minimal Reproducible Example (CodeSandbox, StackBlitz, etc.)

https://github.com/filoozom/wagmi-bug

### Anything else?

The browser is Google Chrome version 103.0.5060.134 on Windows 11.

Screenshot of the network tab showing all the requests:
![image](https://user-images.githubusercontent.com/6319092/182572935-5a4e104d-d293-4cca-b445-2d3ffd1568f3.png)

**Comment by filoozom** [comment]
Might be this and not on `wagmi`'s side actually: https://github.com/TanStack/query/issues/3966

**Comment by jxom** [comment]
Going to close this as it is not directly an issue w/ `wagmi`.

**Comment by eip-achilles** [comment]
@filoozom did you manage to find the fix for this?

**Comment by filoozom** [comment]
> @filoozom did you manage to find the fix for this?

Yes: https://github.com/TanStack/query/issues/3966#issuecomment-1216453780

**Comment by Amirjab21** [comment]
Wait so Wagmis hooks have this infinite re-render problem?

Is there a solution to this?
