### ISSUE TITLE
bug: useWaitForTransaction returns IsSuccess true even if transaction fails after pending

### ISSUE THREAD

**Issue by jasan-s** [wagmi-dev/wagmi#819]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.6.0

### Current Behavior

im using `usePrepareContractWrite` --> `useContractWrite` and then `useWaitForTransaction`. 

I am able to submit a transaction using metamask and explorer show pending. Im intentionally sending a transaction i know will fail. thus after a while the explorer reports transaction failed with status showing why. However `useWaitForTransaction` returns `isSuccess`  and the callback `OnSucess` fires  for the failed transaction hash. 

### Expected Behavior

I expected the `useWaitForTransaction` to return an error with the status of the error i can display to the user. I'm I using this hook incorrectly?

**Comment by jxom** [comment]
This is more of an Ethereum RPC constraint than a wagmi bug.

See more here:
https://github.com/ethers-io/ethers.js/discussions/2819

**Comment by tmm** [comment]
See https://github.com/wagmi-dev/wagmi/discussions/428#discussioncomment-2730175
