### ISSUE TITLE
bug: websocket connection failed: Insufficient resources using useContractEvent

### ISSUE THREAD

**Issue by jasan-s** [wagmi-dev/wagmi#820]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.6.0

### Current Behavior

currently im subscribing to multiple events from contract like so 
```
events.forEach((event_name) => {
  useContractEvent({
    addressOrName: `${CONTRACT_ADDRESS}`,
    contractInterface: SmartContract.abi,
     chainId: CHAIN_ID,
     eventName: event_name,
     listener: (event) => {
	console.log('event:', event)
     },
  })
})
```

however i see multiple errors in the console(seems for each event im listening to) 
>WebSocket connection to 'wss://xxxxxxxxxxxxxxxxxxx' failed: Insufficient resources

is it possible to stop listening on component dismount i.e useEffect return function? if so how? 

### Expected Behavior

No see any errors.

**Comment by tmm** [comment]
Thanks for reporting. This issue is temporarily closed due to lack of information. Please provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) and reopen this issue.
