### ISSUE TITLE
bug: switching chains breaks usePrepareContractWrite

### ISSUE THREAD

**Issue by ivelin** [wagmi-dev/wagmi#827]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.6

### Current Behavior

When `chainId` is used as a guard in `usePrepareContractWrite` and the user switches to the network that is required for the transaction, the `usePrepareContractWrite` react hook does not update and `useContractWrite` stalls.

### Expected Behavior

When `chainId` is used as a guard in `usePrepareContractWrite` and the user switches to the network that is required for the transaction, the `usePrepareContractWrite` react hook should update and `useContractWrite` should execute.

### Steps To Reproduce

1. Create a write transaction that is guarded by a `chainId` parameter.
2. `usePrepareWriteContract`
3. `usePrepareContract`
4. Go to the page with use connected to a different chain.
5. Switch chains.
6. Notice error in dev console.

### Link to Minimal Reproducible Example (CodeSandbox, StackBlitz, etc.)

https://gitpod.io/start/#ivelin-sweattoken-35c7js9fpzw

### Anything else?

![Screen Shot 2022-08-09 at 8 17 28 PM](https://user-images.githubusercontent.com/2234901/183789409-e9b2184d-444a-4cf9-be28-4e40ea720f4c.png)

The bug can be reproduced by opening this branch in gitpod:
https://github.com/ivelin/sweat-token/tree/wagmi-switch-bug

Create a DAO, navigate to Projects, create a Project, click on Tribute, click Submit.

![Screen Shot 2022-08-09 at 8 23 36 PM](https://user-images.githubusercontent.com/2234901/183789975-f8d7b1bc-f4b9-47c9-a46f-fc89f305155d.png)

**Comment by jxom** [comment]
Sorry, I am unsure of where to look in that code workspace. Can you please provide a **minimal reproducible example**? I will re-open when one is provided. Thank you!

**Comment by wuichen** [comment]
I can confirm this error exists. switching chain when using usePrepareContractWrite breaks the code. something like this breaks.
```

import {
  useContractWrite,
  usePrepareContractWrite,
  useSwitchNetwork,

} from 'wagmi';

const TestSwitch = () => {
  const {chain} = useNetwork()
  const { config: mainnetConfig } = usePrepareContractWrite({
    addressOrName: ADDRESS_MAINNET,
    contractInterface: abi.abi,
    functionName: 'create',
    enabled: chain.name === 'Ethereum',
    args: [
    ],
    onSettled(data, error) {
      console.log('Settled', { data, error });
    },
  });
  const { config: rinkebyConfig } = usePrepareContractWrite({
    addressOrName: ADDRESS_RINKEBT,
    contractInterface: abi.abi,
    functionName: 'create',
    enabled: chain.name === 'Rinkeby',
    args: [
    ],
    onSettled(data, error) {
      console.log('Settled', { data, error });
    },
  });

  const { data: rinkebyChainData, switchNetworkAsync: switchToRinkeby } = useSwitchNetwork({
    chainId: 4,
    onSuccess(rinkebyChainData) {
      console.log('Success', rinkebyChainData);
    },
  });

  const { data: mainnetChainData, switchNetworkAsync: switchToMainnet } = useSwitchNetwork({
    chainId: 1,
    onSuccess(mainnetChainData) {
      console.log('Success', mainnetChainData);
    },
  });



  return <div><button onClick={()=>switchToMainnet()}>mainnet</button><button onClick={()=>switchToRinkeby()>rinkeby</button></div>
}

```
