### ISSUE TITLE
bug: Error: No wagmi client found. 

### ISSUE THREAD

**Issue by Geczy** [wagmi-dev/wagmi#841]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.6.2

### Current Behavior

Error: No wagmi client found. Ensure you have set up a client: https://wagmi.sh/docs/client
    at getClient (getProvider-e3d84eba.esm.js?dc91:1000:1)
    at MetaMaskConnector.connect (wagmi-core-connectors-metaMask.esm.js?6ab8:102:147)
    at async connect (wagmi-core.esm.js?2d30:257:1)
window.console.error @ next-dev.js?4cd6:20

### Expected Behavior

No error	

### Steps To Reproduce

Login with metamask

<img width="831" alt="image" src="https://user-images.githubusercontent.com/1036968/184369431-9678ed20-200a-4a19-9c65-f74fa7c8eb49.png">

**Comment by tmm** [comment]
Thanks for reporting. This issue is temporarily closed due to lack of information. Please provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) and reopen this issue. Other information is also helpful, like framework (e.g. Next.js), browser, etc.

**Comment by ian** [comment]
@Geczy are you using pnpm by chance?

**Comment by Geczy** [comment]
> @Geczy are you using pnpm by chance?

i am

**Comment by ian** [comment]
I've been chasing this issue as well, it has to do with version resolution in pnpm repos. Pnpm can get into a scenario where it will resolve to the same version number and install twice or more. 

Still trying to come up with minimal reproducible repo but it's really elusive.

Can you check your node_modules repo and see what directories exist for `wagmi` and `@wagmi/core` repositories, how many of each exist?

**Comment by ian** [comment]
For instance, here's my node_modules repo:

<img width="389" alt="CleanShot 2022-08-29 at 05 44 22@2x" src="https://user-images.githubusercontent.com/19853/187203945-690cdf5d-5a15-4492-b9e6-c6f5a94d4ede.png">

**Comment by ian** [comment]
@tmm I think the way to solve this is to stop relying on per-package global var definition.

Is there a reason the package is using a local `client` var instead of using React's createContext inside of `<WagmiConfig />` ?

See here:

```
let client;
function createClient(config) {
  const client_ = new Client(config);
  client = client_;
  return client_;
}
function getClient() {
  if (!client) {
    throw new Error('No wagmi client found. Ensure you have set up a client: https://wagmi.sh/docs/client');
  }

  return client;
}
```

**Comment by ian** [comment]
@Geczy yeah - that works sometimes, but not always. Glad it worked in your case.

**Comment by rafinskipg** [comment]
@ian  you make a really good points, how did you make it work?
