### ISSUE TITLE
bug: WalletConnect search bar styling in CRA

### ISSUE THREAD

**Issue by awj5** [wagmi-dev/wagmi#846]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.6.2

### Current Behavior

When installing CRA demo the WalletConnect modal search bar appears too wide (see screenshot).

<img width="539" alt="Screen Shot 2022-08-14 at 8 49 36 pm" src="https://user-images.githubusercontent.com/1964695/184533945-b722b190-1619-4419-ba48-23f927eeb3f5.png">

### Expected Behavior

Expecting the search bar to look the same as the example https://wagmi.sh/examples/connect-wallet

### Steps To Reproduce

Download and run CRA example here https://github.com/wagmi-dev/wagmi/tree/main/examples/cra

**Comment by tmm** [comment]
wagmi does not control the styling of the default WalletConnect modal. My guess is global styles are overriding the modal's styles.

**Comment by awj5** [comment]
If anyone else runs into this issue it's happening because the WalletConnect modal expects that all elements in your app have `box-sizing: border-box;`
