### ISSUE TITLE
bug: Cryptic error when not passing args to `prepareContractWrite`

### ISSUE THREAD

**Issue by RafaelVidaurre** [wagmi-dev/wagmi#858]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.6.3

### Current Behavior

When calling `usePrepareContractWrite` without the `args` property.

```js
const { config, error } = usePrepareContractWrite({
    addressOrName: '<some address>',
    contractInterface: someAbi,
    functionName: 'someTxn',
  });
```

This returns an error:

```
TypeError: contract.interface.encodeFunctionData is not a function
```

Afters spending close to 2 hours, we realized the fix was:

```js
const { config, error } = usePrepareContractWrite({
    addressOrName: '<some address>',
    contractInterface: someAbi,
    functionName: 'someTxn',
    args: [] // Adding this line
  });
```

Is there a reason why `args` is not the default? If there's some technical limitation, then it would be good to at least catch this error and return instead something more informative

### Expected Behavior

I expected `args` to default to an empty array

### Steps To Reproduce

Steps explained previously

**Comment by jxom** [comment]
Thanks for reporting. I couldn't seem to reproduce this though. Can you please provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example)? I can reopen the issue when so!
