### ISSUE TITLE
bug: useSignTypedData signTypeData transaction reject error

### ISSUE THREAD

**Issue by jeff0723** [wagmi-dev/wagmi#868]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

^0.6.0

### Current Behavior

Whenever you sign a transaction, with signTypedData function, if you reject the transaction, there will be a bug and make the entire website crash.

```
 const signature = await signTypedDataAsync({
                        domain: omit(typedData?.domain, '__typename'),
                        types: omit(typedData?.types, '__typename'),
                        value: omit(typedData?.value, '__typename')
                    })
```

Error
![Screenshot 2022-08-20 at 18 22 00](https://user-images.githubusercontent.com/38219877/185741668-4eff2775-a73e-49a1-802a-5658cfa981b7.png)

### Steps To Reproduce

1. Create a sign transaction with signTypeDataAsync
2. Reject it.

**Comment by jxom** [comment]
This is probably because you are trying to render an object as a child, which is not valid.

https://www.g2i.co/blog/understanding-the-objects-are-not-valid-as-a-react-child-error-in-react

**Comment by jeff0723** [comment]
I have checked my code entirely. I didn't render anything besides just using `signTypedDayaAsync`. But errors still happened. Is there any chance that the library have failed to do the error handling?

**Comment by jxom** [comment]
Can you upload a minimal reproducible example? Then I will be able to see what's going on. :)

**Comment by jeff0723** [comment]
Hello, I solved this issue. However, I think it might be a bit misleading that the `error.message` of `signTypedAsnc` is an object.
![Screenshot 2022-08-23 at 16 34 02](https://user-images.githubusercontent.com/38219877/186112007-eaa81899-f206-4776-8fe6-9e18e6d5b5d1.png)
I was using `error.message `as my toast message, that's why I got the error.
