### ISSUE TITLE
UsePrePareContractWrite will stuck with Phaser to cooperate with PHASER task and get stuck in the interface

### ISSUE THREAD

**Issue by aLIEzsss4** [wagmi-dev/wagmi#874]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.6.4

**Comment by jxom** [comment]
Thanks for reporting. This issue is temporarily closed due to lack of information. Please provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) and reopen this issue. Other information is also helpful, like framework (e.g. Next.js), browser, etc.
