### ISSUE TITLE
useSignMessage leads to deep link issue on mobile

### ISSUE THREAD

**Issue by melissafzhang** [wagmi-dev/wagmi#877]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.6.2

### Current Behavior

In our web application, we requires users to sign a message in order to log in. On mobile, we're seeing that prompting users to sign a message leads to the deep link issue described [here](https://wagmi.sh/docs/prepare-hooks/intro#ios-app-link-constraints) where the browser will fail to deep link into the app. It would be great to have a similar hook to `usePrepareSendTransaction` for signing messages so that we can prepare any async work before users are prompted to sign. 

### Expected Behavior

A hook like `usePrepareSignMessage` that does any async work ahead of time

### Steps To Reproduce

1. Prompt user to connect any mobile wallet using WalletConnect
2. Prompt user to sign message
3. User gets redirected to a new web page rather than deep linked into the app

**Comment by jxom** [comment]
Hey @melissafzhang – do you think you can provide a minimal reproducible example? I can't seem to reproduce this.

**Comment by melissafzhang** [comment]
@jxom do you have a default project I can play with? I've been trying to get WalletConnect working on codepen but I keep getting `No wagmi client found. Ensure you have set up a client: https://wagmi.sh/docs/client` https://codesandbox.io/s/stoic-brattain-jjvrlz?file=/src/App.js

**Comment by jxom** [comment]
Interesting about the error. I tried to pull down the repository but struggled to get it to run (ran into some framer-motion dependency issues). 

I created a minimal sandbox here: https://codesandbox.io/s/crimson-meadow-idpb05?file=/pages/index.tsx

However, I don't get these deep linking issues on this sandbox.

**Comment by melissafzhang** [comment]
@jxom With your example, I'm not able to connect my wallet at all. After I click "Wallet Connect" and choose Rainbow, it automatically redirects me to the Rainbow web page.

https://user-images.githubusercontent.com/38673112/186278036-d8751d4a-9463-4bfd-875f-6764a7f7c90b.mov

**Comment by jxom** [comment]
Interesting. I get a different outcome :\ 

https://user-images.githubusercontent.com/7336481/186279411-0d3514e9-5c7e-401e-b545-2fa6f1097b93.mp4

**Comment by jxom** [comment]
Is your internet connection a bottleneck?

**Comment by melissafzhang** [comment]
:/ wow totally different haha... My wifi is pretty fast but my phone is kind of old. Just to confirm, are you using Safari?

**Comment by jxom** [comment]
Yep! Safari on iOS 16.0

**Comment by jxom** [comment]
I am going to close this issue as it's now becoming stale and we are unable to reproduce. If a clear minimal reproducible example is provided, we can reopen this issue.

**Comment by melissafzhang** [comment]
Yup no problem! I figured out that the issue was specific to my device. Thanks!
