### ISSUE TITLE
bug: missing argument: passed to contract (count=0, expectedCount=1, code=MISSING_ARGUMENT, version=contracts/5.7.0)

### ISSUE THREAD

**Issue by NishantPacharne** [wagmi-dev/wagmi#879]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Package Version

0.6.4

### Current Behavior

I get this error :- missing argument: passed to contract (count=0, expectedCount=1, code=MISSING_ARGUMENT, version=contracts/5.7.0)

### Expected Behavior

The write contract should have worked as Iam passing the argument.

### Steps To Reproduce

My code :- 

`const { writeAsync: mint, error: mintError } = useContractWrite({ ...contractConfig, functionName: 'mint', });`

`const tx = await mint({args: [{_quantity: 1}]});`

### Anything else?

My mint function of the smart contract 
![image](https://user-images.githubusercontent.com/71060551/186405551-d8339a88-963d-49fe-b029-579386ebf374.png)

**Comment by tmm** [comment]
Closing in favor of #878.
