### ISSUE TITLE
bug: useContractRead fetching data automatically with enabled set to false

### ISSUE THREAD

**Issue by danilo-89** [wagmi-dev/wagmi#888]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.6.4

### Current Behavior

**useContractRead** is fetching data automatically with **enabled** set to false and isLoading and isFetching are showing false.

```
const {
    data: readData,
    isLoading: isReadLoading,
    isFetching: isReadFetching,
    refetch
  } = useContractRead({
    addressOrName: "0xecb504d39723b0be0e3a9aa33d646642d1051ee1",
    contractInterface: wagmigotchiABI,
    functionName: "getBoredom",
    enabled: false
  });

  console.log({ isReadFetching });
  console.log({ isReadLoading });
  console.log("Result from read:", readData);
```

### Expected Behavior

Fetching contract data on load shouldn't happen if enabled is set to false. Also, when fetching data, isFetching (possibly isLoading too) should have true value.

### Steps To Reproduce

Open codesandbox link and watch the Console.

### Link to Minimal Reproducible Example (CodeSandbox, StackBlitz, etc.)

https://codesandbox.io/s/condescending-allen-ek1ion?file=/pages/index.tsx

**Comment by sumicet** [comment]
Having the same issue with `useBalance`

**Comment by jxom** [comment]
I can't reproduce this bug with a clear local storage on the CodeSandbox. If there is data cached in local storage, then the hook will return that data regardless of the `enabled` value, however, **it will never perform a contract read if `enabled` is falsy**. If you wish to not show the cached data, you may need to utilise a flag like so:

E.g.

```tsx
function Example() {
  const [enabled, setEnabled] = useState(false)

  const {
    data,
    isLoading,
    isFetching,
    fetchStatus
  } = useContractRead({
    addressOrName: '0xecb504d39723b0be0e3a9aa33d646642d1051ee1',
    contractInterface: wagmigotchiABI,
    functionName: "getBoredom",
    enabled
  });
  
  return (
    <div>
      {enabled ? `Boredom: ${data}` : null}
    </div>
  )
}
```

**Comment by apecollector** [comment]
This happens to me, only way to solve is setting `persister: null` in the `createClient`:

```js
const wagmiClient = createClient({
  persister: null,
  connectors,
  provider,
  webSocketProvider
});
```

**Comment by rsodre** [comment]
I'm having a similar issue, I know data is cached, chain block did not change (using local Ganache), then `useContractRead` returns `status:success`, but `isFetching:true`. It takes a couple of seconds before `isFetching` is released (the same time my function takes to complete). Is it calling the function even when the cache is ok, 'just in case'?

I usually consider `(isLoading || isFetching)` to block UI until data is available. In this case, if I just ignore `isFetching`, cached data comes quickly. So, can I just completely ignore `isFetching`?

I just ported my dapp from Moralis to wagmi, in favour of a completely open source, and to benefit from caching, but some concepts should be explained better on the docs, like what's the difference between **loading** and **fetching**? Also, how exactly does **caching** work? What is **stale** data?

**Comment by tmm** [comment]
@rsodre for some quick hints check out [React Query's definition of network states](https://tanstack.com/query/v4/docs/guides/queries). There are a [couple nuances](https://github.com/wagmi-dev/wagmi/blob/main/packages/react/src/hooks/utils/query/useBaseQuery.ts#L140-L145) with wagmi's set up, but overall it's pretty much the same.

The `watch` configuration option listens for new blocks (via polling or websockets) and refetches the data. `cacheOnBlock` is similar. It also listens for new blocks, but also uses current block number as part of the cache key.

Agree that we need to improve the docs and appreciate the feedback!
