### ISSUE TITLE
bug: Uncaught Error: No QueryClient set, use QueryClientProvider to set one

### ISSUE THREAD

**Issue by alxkzmn** [wagmi-dev/wagmi#890]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.6.4

### Current Behavior

Uncaught Error: No QueryClient set, use QueryClientProvider to set one

### Steps To Reproduce

Create react app and follow official docs to send a transaction.

### Link to Minimal Reproducible Example (CodeSandbox, StackBlitz, etc.)

https://codesandbox.io/s/wagmi-errors-3z3etc

**Comment by jxom** [comment]
You must wrap `WagmiConfig` around any components that consume wagmi hooks. I have fixed it for you in the CodeSandbox. :)

https://codesandbox.io/s/hardcore-torvalds-lbcg6m?file=/src/App.js

**Comment by ajsharp** [comment]
Especially when trying to use `useSigner` hook, it would be helpful if this were more clear in the docs.
