### ISSUE TITLE
bug: Crash when using usePrepareContractWrite

### ISSUE THREAD

**Issue by phumaster** [wagmi-dev/wagmi#891]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.6.4

### Current Behavior

Hi there ! I just want to use `usePrepareContractWrite` to approve erc20 token. But my page is keeping crash. This is my code.
```js
const { config } = usePrepareContractWrite({
    addressOrName: address,
    contractInterface: erc20ABI,
    functionName: 'approve',
    args: [spender, ethers.constants.MaxUint256.toString()],
  });

  const { write, isLoading: isApproving, isError: isApprovingError, data: approveData } = useContractWrite(config);
```

=> this page was crashed

<img width="658" alt="Screen Shot 2022-08-26 at 16 46 12" src="https://user-images.githubusercontent.com/13518558/186878110-502e98fd-c754-4a90-b134-5e0fae6f733e.png">

When I delete 2 hooks above, my page is working fine. So, I use `useContractWrite` with mode `recklesslyUnprepared` instead.

```js
const {
    write,
    isLoading: isApproving,
    isError: isApprovingError,
    data: approveData,
  } = useContractWrite({
    mode: 'recklesslyUnprepared',
    addressOrName: address,
    contractInterface: erc20ABI,
    functionName: 'approve',
    args: [spender, ethers.constants.MaxUint256.toString()],
  });
```

=> this page is working fine.

Can you guys tell me some reasons for this.

### Expected Behavior

Page is not crash

### Steps To Reproduce

```js
const { config } = usePrepareContractWrite({
    addressOrName: address,
    contractInterface: erc20ABI,
    functionName: 'approve',
    args: [spender, ethers.constants.MaxUint256.toString()],
  });

  const { write, isLoading: isApproving, isError: isApprovingError, data: approveData } = useContractWrite(config);
```

**Comment by jxom** [comment]
Thanks for reporting! I could not seem to reproduce this issue. Can you please provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example)? 

Here is a template CodeSandbox you can use: https://codesandbox.io/s/serene-morse-frzh0w

I will reopen this issue when a minimal reproducible example is provided. :)
