### ISSUE TITLE
v 0.6.1 breaks react-query-devtools

### ISSUE THREAD

**Issue by octavioamu** [wagmi-dev/wagmi#900]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.6.4

### Current Behavior

on a project using @tanstack/react-query-devtools (tested with 4.0.10 and 4.0.11-beta.0) if you bump wagmi version to 0.6.4 react-query-devtools stop showing any query

### Expected Behavior

Wagmi shouldn't break react-query-devtools

### Steps To Reproduce

- Create a project using both wagmi@0.6.4 and @tanstack/react-query-devtools
- open react-query-devtools 
- no queries showing

If you downgrade to 0.6.1 all works fine with any of the 2 react-query-devtools versions

**Comment by tmm** [comment]
Thanks for reporting. This issue is temporarily closed due to lack of information. Please provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) and reopen this issue.
