### ISSUE TITLE
Expose `getProvider`

### ISSUE THREAD

**Issue by wottpal** [wagmi-dev/wagmi#901]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.6.1

### Current Behavior

Neither [`getProvider`](https://github.com/wagmi-dev/wagmi/blob/7c657fbbec39353b82ad30f7975690856fb0930d/packages/core/src/actions/providers/getProvider.ts) nor [`getWebsocketProvider`](https://github.com/wagmi-dev/wagmi/blob/7c657fbbec39353b82ad30f7975690856fb0930d/packages/core/src/actions/providers/getWebSocketProvider.ts) can be imported at the moment as they are not publicly exposed. Only via hooks (i.e. `useProvider`).

### Expected Behavior

That I can also use wagmis `getProvider` function where I don't want to use a hook.

**Comment by tmm** [comment]
You can import actions from the entrypoint.

```ts
import {
  getProvider,
  getWebSocketProvider,
} from 'wagmi/actions'
```
