### ISSUE TITLE
bug: usePrepareContractWrite has incorrect typings

### ISSUE THREAD

**Issue by JDansercoer** [wagmi-dev/wagmi#903]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.6.4

### Current Behavior

When working with `usePrepareContractWrite`, the returned `error` key is incorrectly typed. When inspecting the object, we see that there is a more human readable property called `reason`, however this does not appear to be present on the type, causing TS errors.

### Expected Behavior

To have correct typings on the error property to remove the TS errors

### Steps To Reproduce

Just some example setup:  

```tsx
const { config, error: prepareError } = usePrepareContractWrite({
    addressOrName: 'address',
    contractInterface: abi,
    functionName: 'mint',
    args: [merkleProof],
  });

  useEffect(() => {
    if (prepareError && prepareError.reason) {
      toast({
        description: prepareError.reason,
        status: 'warning',
      });
    }
  }, [prepareError]);
```

The code above works and displays the correct `execution reverted: You already claimed an NFT.` toast to the end-user. However, TS is complaining:
![image](https://user-images.githubusercontent.com/11869830/187829751-86ab3ea2-46bc-47d6-9c86-c866e905777a.png)

**Comment by tmm** [comment]
Thanks for reporting. This issue is temporarily closed due to lack of information. Please provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) and reopen this issue.
