### ISSUE TITLE
Bug: Half-screen website looks impossible to read

### ISSUE THREAD

**Issue by woojiq** [wagmi-dev/wagmi#918]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

https://wagmi.sh/docs/getting-started

### Current Behavior

I use Windows 11. When I split my screen (the text editor is half the screen and the browser is half the screen) documentation on [wagmi.sh](https://wagmi.sh/docs/getting-started) is unreadable, everything overlaps each other. 
Also, when I scroll down, the sidebar scrolls, not the documentation. If you make the window a few centimeters wider, everything becomes normal.

**Exactly half the screen**

![Exactly half the screen](https://user-images.githubusercontent.com/97038258/188445777-d6a66a55-54e3-4e99-aca8-4990dfe22771.png)

**Few cm wider**

![Few cm wider](https://user-images.githubusercontent.com/97038258/188446926-9b1a710f-1e2a-430b-b9e6-7df330a52205.png)

### Expected Behavior

Only main article is visible and side panel is hidden.

### Steps To Reproduce

Windows -> open browser with wagmi.sh and any other window for example vscode -> split screen `window_Key + arrow_left`

### Anything else?

For example, for a small window, make the side panels collapsible.

**Comment by tmm** [comment]
Will create an issue over at [nextra](https://github.com/shuding/nextra/issues) for this
