### ISSUE TITLE
bug: useSigner hook causing multiple rerenders

### ISSUE THREAD

**Issue by jtlacci** [wagmi-dev/wagmi#919]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.6.4

### Current Behavior

calling the `useSigner()` hook within the context of component causes looping re-renders

### Steps To Reproduce

calling `useSigner` hook within the context of a component will cause component to continually re-render

**Comment by tmm** [comment]
Thanks for reporting. This issue is temporarily closed due to lack of information. Please provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) and reopen this issue.
