### ISSUE TITLE
bug: useNetwork hooks shows following error "TypeError: Cannot read properties of undefined (reading 'chains')"

### ISSUE THREAD

**Issue by KrishEnacton** [wagmi-dev/wagmi#956]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.6.6

### Anything else?

![2022-09-16_16-02](https://user-images.githubusercontent.com/77377186/190620142-f11c3068-2c3d-49a3-a7b7-c779416fd3ce.png)

**Comment by tmm** [comment]
Thanks for reporting. This issue is temporarily closed due to lack of information. Please provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) and reopen this issue.

**Comment by KrishEnacton** [comment]
It gives me an error of undefined when I import the useNetwork from wagmi.
I am currently downgrading to version 0.4.12 because it works fine in wagmi v0.4.12.
