### ISSUE TITLE
bug: CoinbaseWalletConnector resets to mainnet on refresh

### ISSUE THREAD

**Issue by markdalgleish** [wagmi-dev/wagmi#966]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.6.6

### Current Behavior

After connecting with Coinbase Wallet and switching networks, if I refresh the page the network is reset to mainnet.

If I open the Coinbase Wallet extension, it still thinks I'm connected to the network I originally switched to.

### Expected Behavior

After refreshing the page, I expect to be on the same network.

### Steps To Reproduce

I've shared a link to a repro below.

1) Start dev server.
2) Connect with Coinbase.
3) Switch to Polygon.
4) Refresh the page.

### Link to Minimal Reproducible Example (CodeSandbox, StackBlitz, etc.)

https://github.com/markdalgleish/wagmi-coinbase-chain-issue

### Anything else?

I've dug into the logic a bit, and I can manually pass in a `chainId` to the Coinbase connector, but internally it falls back to the first chain if a chain ID wasn't passed in.

Instead, this logic might need to fall back to the chain the Coinbase Wallet extension is already connected to. When using the extension, I found that the `CoinbaseWalletSDK` instance has a `walletExtension` property with a `getChainId` method that returns the expected chain ID on load. If I hard code this value as the 2nd arg to `makeWeb3Provider`, it seems to resolve the issue.

**Comment by jxom** [comment]
Fixed on `0.6.7`
