### ISSUE TITLE
bug: <title>

### ISSUE THREAD

**Issue by soccerarenadev** [wagmi-dev/wagmi#973]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.6.6

### Current Behavior

When changing the current network in Metamask (directly from Metamask or through wagmi) I get this error using usePrepareContractWrite:

- Message: 
`underlying network changed (event="changed", network={"name":"goerli","chainId":5,"ensAddress":"0x00000000000C2E074eC69A0dFb2997BA6C7d2e1e"}, detectedNetwork={"name":"maticmum","chainId":80001,"ensAddress":null,"_defaultProvider":null}, code=NETWORK_ERROR, version=providers/5.7.1)
`
- Stack: 
`Error: underlying network changed (event="changed", network={"name":"goerli","chainId":5,"ensAddress":"0x00000000000C2E074eC69A0dFb2997BA6C7d2e1e"}, detectedNetwork={"name":"maticmum","chainId":80001,"ensAddress":null,"_defaultProvider":null}, code=NETWORK_ERROR, version=providers/5.7.1) at Logger.makeError (webpack-internal:///./node_modules/@ethersproject/logger/lib.esm/index.js:231:23) at Web3Provider.eval (webpack-internal:///./node_modules/@ethersproject/providers/lib.esm/base-provider.js:1021:38) at Generator.next (<anonymous>) at fulfilled (webpack-internal:///./node_modules/@ethersproject/providers/lib.esm/base-provider.js:28:58)`

### Expected Behavior

Just reload with the new network information.

### Steps To Reproduce

Change network using a usePrepareContractWrite

**Comment by tmm** [comment]
Thanks for reporting. This issue is temporarily closed due to lack of information. Please provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) and reopen this issue.
