### ISSUE TITLE
bug: Can't find variable: getProvider - React Native using wagmi 0.64.0 and 0.66.0. Re-opening #911

### ISSUE THREAD

**Issue by thegitparticle** [wagmi-dev/wagmi#982]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.66.0

### Current Behavior

While trying to setup WalletConnect Setup using wagmi 0.64.0 - It does not work and throws this error up - Can't find variable: getProvider.
![188272376-f35e5cbb-b9fd-449c-86d4-8a0c9c877d01](https://user-images.githubusercontent.com/12975157/191562939-aa77ab66-8fff-44b5-b60b-63b53360a863.jpeg)

### Steps To Reproduce

Expo app repo to reproduce - https://github.com/thegitparticle/wagmi-rn-setup

### Link to Minimal Reproducible Example (CodeSandbox, StackBlitz, etc.)

https://github.com/thegitparticle/wagmi-rn-setup

**Comment by jxom** [comment]
The WalletConnect connector is only compatible for the web. You may want to look into [WalletConnect's React Native client](https://docs.walletconnect.com/quick-start/dapps/react-native) instead.
