### ISSUE TITLE
bug: connection to unsupported chains

### ISSUE THREAD

**Issue by kodjunkie** [wagmi-dev/wagmi#990]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.6.7

### Current Behavior

The library allows connection to chains not specified in the supported chains list.

### Expected Behavior

I expect an `UnsupportedChainIdError` to be thrown when connected to a different network, so it can be properly handled in the `onError` function.

### Steps To Reproduce

```javascript
const supportedChains = [chain.mainnet, chain.ropsten, chain.rinkeby];

const { chains, provider, webSocketProvider } = configureChains(
  supportedChains,
  [ publicProvider() ]
);

const client = createClient({
  autoConnect: true,
  connectors: [
    new InjectedConnector({ chains, options: { shimDisconnect: true } }),
  ],
  provider,
  webSocketProvider,
});
```

```javascript
const { disconnect } = useDisconnect();
  const { connect, connectors, isLoading } = useConnect({
    onError(error) {
      if (error instanceof UserRejectedRequestError) {
        console.error(
          "Please authorize this app to access your Ethereum account."
        );
      } else {
        console.error(
          "An unknown error occurred."
        );
      }
    },
    onSuccess(data) {
      // Here's my temp fix with `data.chain`
      if (data.chain.unsupported) {
        console.error("You're connected to an unsupported network.");
        disconnect();
      } else {
        navigate("/home");
      }
    },
  });
```

### Anything else?

For now, the temp fix works as expected but I think it'd be a nice addition. 
I can send a PR if you don't mind, cheers

**Comment by jxom** [comment]
Hi. I'm not sure this should be the UX we should be aiming for by default. You may want to look into prompting the user to switch network upon connection via [supplying `chainId` to `useConnect`](https://wagmi.sh/docs/hooks/useConnect#chainid-optional). Otherwise, you can just roll with the workaround you noted here.

**Comment by kodjunkie** [comment]
Cool! If more users request this feature then we can add a config option that lets users decide if they want an error thrown for such case or not.
